package com.galexis.alloga2mysql.model;

// Generated Mar 4, 2013 4:41:13 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Bizpconaut generated by hbm2java
 */
@Entity
@Table(name = "BIZPCONAUT")
public class Bizpconaut implements java.io.Serializable {

	private long pk;

	private long bizpmasterpk;

	private long contrdefpk;

	private String isactiveflag;

	private String programname;

	private String filename;

	private Date recordlastchangetime;

	private Date recordcreationtime;

	public Bizpconaut() {
	}

	public Bizpconaut(long pk, long bizpmasterpk, long contrdefpk, Date recordcreationtime) {
		this.pk = pk;
		this.bizpmasterpk = bizpmasterpk;
		this.contrdefpk = contrdefpk;
		this.recordcreationtime = recordcreationtime;
	}

	public Bizpconaut(long pk, long bizpmasterpk, long contrdefpk, String isactiveflag, String programname, String filename, Date recordlastchangetime, Date recordcreationtime) {
		this.pk = pk;
		this.bizpmasterpk = bizpmasterpk;
		this.contrdefpk = contrdefpk;
		this.isactiveflag = isactiveflag;
		this.programname = programname;
		this.filename = filename;
		this.recordlastchangetime = recordlastchangetime;
		this.recordcreationtime = recordcreationtime;
	}

	@Id
	@Column(name = "PK", unique = true, nullable = false, precision = 12, scale = 0)
	public long getPk() {
		return this.pk;
	}

	public void setPk(long pk) {
		this.pk = pk;
	}

	@Column(name = "BIZPMASTERPK", nullable = false, precision = 12, scale = 0)
	public long getBizpmasterpk() {
		return this.bizpmasterpk;
	}

	public void setBizpmasterpk(long bizpmasterpk) {
		this.bizpmasterpk = bizpmasterpk;
	}

	@Column(name = "CONTRDEFPK", nullable = false, precision = 12, scale = 0)
	public long getContrdefpk() {
		return this.contrdefpk;
	}

	public void setContrdefpk(long contrdefpk) {
		this.contrdefpk = contrdefpk;
	}

	@Column(name = "ISACTIVEFLAG", length = 1)
	public String getIsactiveflag() {
		return this.isactiveflag;
	}

	public void setIsactiveflag(String isactiveflag) {
		this.isactiveflag = isactiveflag;
	}

	@Column(name = "PROGRAMNAME", length = 10)
	public String getProgramname() {
		return this.programname;
	}

	public void setProgramname(String programname) {
		this.programname = programname;
	}

	@Column(name = "FILENAME", length = 10)
	public String getFilename() {
		return this.filename;
	}

	public void setFilename(String filename) {
		this.filename = filename;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "RECORDLASTCHANGETIME", length = 19)
	public Date getRecordlastchangetime() {
		return this.recordlastchangetime;
	}

	public void setRecordlastchangetime(Date recordlastchangetime) {
		this.recordlastchangetime = recordlastchangetime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "RECORDCREATIONTIME", nullable = false, length = 19)
	public Date getRecordcreationtime() {
		return this.recordcreationtime;
	}

	public void setRecordcreationtime(Date recordcreationtime) {
		this.recordcreationtime = recordcreationtime;
	}

}
