package com.galexis.alloga2mysql.model;

// Generated Mar 4, 2013 4:41:13 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Bizparaddr generated by hbm2java
 */
@Entity
@Table(name = "BIZPARADDR")
public class Bizparaddr implements java.io.Serializable {

	private long pk;

	private String partnernr;

	private Long bizpmasterpk;

	private String manualmodifiedflag;

	private String name1;

	private String address1;

	private String address2;

	private String address3;

	private String address4;

	private String town;

	private String zip;

	private String country;

	private String state;

	private String language;

	private String contractordeliverycustomernr;

	private Date recordlastchangetime;

	private Date recordcreationtime;

	public Bizparaddr() {
	}

	public Bizparaddr(long pk, String partnernr, String manualmodifiedflag, Date recordcreationtime) {
		this.pk = pk;
		this.partnernr = partnernr;
		this.manualmodifiedflag = manualmodifiedflag;
		this.recordcreationtime = recordcreationtime;
	}

	public Bizparaddr(long pk, String partnernr, Long bizpmasterpk, String manualmodifiedflag, String name1, String address1, String address2, String address3, String address4,
	        String town, String zip, String country, String state, String language, String contractordeliverycustomernr, Date recordlastchangetime, Date recordcreationtime) {
		this.pk = pk;
		this.partnernr = partnernr;
		this.bizpmasterpk = bizpmasterpk;
		this.manualmodifiedflag = manualmodifiedflag;
		this.name1 = name1;
		this.address1 = address1;
		this.address2 = address2;
		this.address3 = address3;
		this.address4 = address4;
		this.town = town;
		this.zip = zip;
		this.country = country;
		this.state = state;
		this.language = language;
		this.contractordeliverycustomernr = contractordeliverycustomernr;
		this.recordlastchangetime = recordlastchangetime;
		this.recordcreationtime = recordcreationtime;
	}

	@Id
	@Column(name = "PK", unique = true, nullable = false, precision = 12, scale = 0)
	public long getPk() {
		return this.pk;
	}

	public void setPk(long pk) {
		this.pk = pk;
	}

	@Column(name = "PARTNERNR", nullable = false, length = 20)
	public String getPartnernr() {
		return this.partnernr;
	}

	public void setPartnernr(String partnernr) {
		this.partnernr = partnernr;
	}

	@Column(name = "BIZPMASTERPK", precision = 12, scale = 0)
	public Long getBizpmasterpk() {
		return this.bizpmasterpk;
	}

	public void setBizpmasterpk(Long bizpmasterpk) {
		this.bizpmasterpk = bizpmasterpk;
	}

	@Column(name = "MANUALMODIFIEDFLAG", nullable = false, length = 1)
	public String getManualmodifiedflag() {
		return this.manualmodifiedflag;
	}

	public void setManualmodifiedflag(String manualmodifiedflag) {
		this.manualmodifiedflag = manualmodifiedflag;
	}

	@Column(name = "NAME1", length = 50)
	public String getName1() {
		return this.name1;
	}

	public void setName1(String name1) {
		this.name1 = name1;
	}

	@Column(name = "ADDRESS1", length = 50)
	public String getAddress1() {
		return this.address1;
	}

	public void setAddress1(String address1) {
		this.address1 = address1;
	}

	@Column(name = "ADDRESS2", length = 50)
	public String getAddress2() {
		return this.address2;
	}

	public void setAddress2(String address2) {
		this.address2 = address2;
	}

	@Column(name = "ADDRESS3", length = 50)
	public String getAddress3() {
		return this.address3;
	}

	public void setAddress3(String address3) {
		this.address3 = address3;
	}

	@Column(name = "ADDRESS4", length = 50)
	public String getAddress4() {
		return this.address4;
	}

	public void setAddress4(String address4) {
		this.address4 = address4;
	}

	@Column(name = "TOWN", length = 35)
	public String getTown() {
		return this.town;
	}

	public void setTown(String town) {
		this.town = town;
	}

	@Column(name = "ZIP", length = 16)
	public String getZip() {
		return this.zip;
	}

	public void setZip(String zip) {
		this.zip = zip;
	}

	@Column(name = "COUNTRY", length = 4)
	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	@Column(name = "STATE", length = 2)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "LANGUAGE", length = 3)
	public String getLanguage() {
		return this.language;
	}

	public void setLanguage(String language) {
		this.language = language;
	}

	@Column(name = "CONTRACTORDELIVERYCUSTOMERNR", length = 30)
	public String getContractordeliverycustomernr() {
		return this.contractordeliverycustomernr;
	}

	public void setContractordeliverycustomernr(String contractordeliverycustomernr) {
		this.contractordeliverycustomernr = contractordeliverycustomernr;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "RECORDLASTCHANGETIME", length = 19)
	public Date getRecordlastchangetime() {
		return this.recordlastchangetime;
	}

	public void setRecordlastchangetime(Date recordlastchangetime) {
		this.recordlastchangetime = recordlastchangetime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "RECORDCREATIONTIME", nullable = false, length = 19)
	public Date getRecordcreationtime() {
		return this.recordcreationtime;
	}

	public void setRecordcreationtime(Date recordcreationtime) {
		this.recordcreationtime = recordcreationtime;
	}

}
