package com.galexis.alloga2mysql.model;

// Generated Mar 4, 2013 4:41:13 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Bizparmail generated by hbm2java
 */
@Entity
@Table(name = "BIZPARMAIL")
public class Bizparmail implements java.io.Serializable {

	private long pk;

	private Long bizpmasterpk;

	private String function;

	private String mailaddress;

	private Date recordlastchangetime;

	private String userlastchange;

	private Date recordcreationtime;

	public Bizparmail() {
	}

	public Bizparmail(long pk, String function, String mailaddress, Date recordcreationtime) {
		this.pk = pk;
		this.function = function;
		this.mailaddress = mailaddress;
		this.recordcreationtime = recordcreationtime;
	}

	public Bizparmail(long pk, Long bizpmasterpk, String function, String mailaddress, Date recordlastchangetime, String userlastchange, Date recordcreationtime) {
		this.pk = pk;
		this.bizpmasterpk = bizpmasterpk;
		this.function = function;
		this.mailaddress = mailaddress;
		this.recordlastchangetime = recordlastchangetime;
		this.userlastchange = userlastchange;
		this.recordcreationtime = recordcreationtime;
	}

	@Id
	@Column(name = "PK", unique = true, nullable = false, precision = 12, scale = 0)
	public long getPk() {
		return this.pk;
	}

	public void setPk(long pk) {
		this.pk = pk;
	}

	@Column(name = "BIZPMASTERPK", precision = 12, scale = 0)
	public Long getBizpmasterpk() {
		return this.bizpmasterpk;
	}

	public void setBizpmasterpk(Long bizpmasterpk) {
		this.bizpmasterpk = bizpmasterpk;
	}

	@Column(name = "FUNCTION", nullable = false, length = 50)
	public String getFunction() {
		return this.function;
	}

	public void setFunction(String function) {
		this.function = function;
	}

	@Column(name = "MAILADDRESS", nullable = false, length = 1000)
	public String getMailaddress() {
		return this.mailaddress;
	}

	public void setMailaddress(String mailaddress) {
		this.mailaddress = mailaddress;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "RECORDLASTCHANGETIME", length = 19)
	public Date getRecordlastchangetime() {
		return this.recordlastchangetime;
	}

	public void setRecordlastchangetime(Date recordlastchangetime) {
		this.recordlastchangetime = recordlastchangetime;
	}

	@Column(name = "USERLASTCHANGE", length = 20)
	public String getUserlastchange() {
		return this.userlastchange;
	}

	public void setUserlastchange(String userlastchange) {
		this.userlastchange = userlastchange;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "RECORDCREATIONTIME", nullable = false, length = 19)
	public Date getRecordcreationtime() {
		return this.recordcreationtime;
	}

	public void setRecordcreationtime(Date recordcreationtime) {
		this.recordcreationtime = recordcreationtime;
	}

}
