package com.galexis.alloga2mysql.model;

// Generated Mar 4, 2013 4:41:13 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Contrpgrp generated by hbm2java
 */
@Entity
@Table(name = "CONTRPGRP", uniqueConstraints = @UniqueConstraint(columnNames = "PRODUCTGROUP"))
public class Contrpgrp implements java.io.Serializable {

	private long pk;

	private long contrdefpk;

	private String productgroup;

	private String isactiveflag;

	private Date recordcreationtime;

	private Date recordlastchangetime;

	private String userlastchange;

	public Contrpgrp() {
	}

	public Contrpgrp(long pk, long contrdefpk, String productgroup, String isactiveflag, Date recordcreationtime) {
		this.pk = pk;
		this.contrdefpk = contrdefpk;
		this.productgroup = productgroup;
		this.isactiveflag = isactiveflag;
		this.recordcreationtime = recordcreationtime;
	}

	public Contrpgrp(long pk, long contrdefpk, String productgroup, String isactiveflag, Date recordcreationtime, Date recordlastchangetime, String userlastchange) {
		this.pk = pk;
		this.contrdefpk = contrdefpk;
		this.productgroup = productgroup;
		this.isactiveflag = isactiveflag;
		this.recordcreationtime = recordcreationtime;
		this.recordlastchangetime = recordlastchangetime;
		this.userlastchange = userlastchange;
	}

	@Id
	@Column(name = "PK", unique = true, nullable = false, precision = 12, scale = 0)
	public long getPk() {
		return this.pk;
	}

	public void setPk(long pk) {
		this.pk = pk;
	}

	@Column(name = "CONTRDEFPK", nullable = false, precision = 12, scale = 0)
	public long getContrdefpk() {
		return this.contrdefpk;
	}

	public void setContrdefpk(long contrdefpk) {
		this.contrdefpk = contrdefpk;
	}

	@Column(name = "PRODUCTGROUP", unique = true, nullable = false, length = 5)
	public String getProductgroup() {
		return this.productgroup;
	}

	public void setProductgroup(String productgroup) {
		this.productgroup = productgroup;
	}

	@Column(name = "ISACTIVEFLAG", nullable = false, length = 1)
	public String getIsactiveflag() {
		return this.isactiveflag;
	}

	public void setIsactiveflag(String isactiveflag) {
		this.isactiveflag = isactiveflag;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "RECORDCREATIONTIME", nullable = false, length = 19)
	public Date getRecordcreationtime() {
		return this.recordcreationtime;
	}

	public void setRecordcreationtime(Date recordcreationtime) {
		this.recordcreationtime = recordcreationtime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "RECORDLASTCHANGETIME", length = 19)
	public Date getRecordlastchangetime() {
		return this.recordlastchangetime;
	}

	public void setRecordlastchangetime(Date recordlastchangetime) {
		this.recordlastchangetime = recordlastchangetime;
	}

	@Column(name = "USERLASTCHANGE", length = 20)
	public String getUserlastchange() {
		return this.userlastchange;
	}

	public void setUserlastchange(String userlastchange) {
		this.userlastchange = userlastchange;
	}

}
