package com.galexis.alloga2mysql.model;

// Generated Mar 4, 2013 4:41:13 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Ctrbizpcls generated by hbm2java
 */
@Entity
@Table(name = "CTRBIZPCLS", uniqueConstraints = @UniqueConstraint(columnNames = { "CONTRDEFPK", "BIZPMASTERPK", "CONTRACTORCLASS" }))
public class Ctrbizpcls implements java.io.Serializable {

	private long pk;

	private long contrdefpk;

	private long bizpmasterpk;

	private String contractorclass;

	private String contractorclassgroup;

	private Character isactiveflag;

	private Date recordlastchangetime;

	private Date recordcreationtime;

	public Ctrbizpcls() {
	}

	public Ctrbizpcls(long pk, long contrdefpk, long bizpmasterpk, String contractorclass, String contractorclassgroup, Date recordcreationtime) {
		this.pk = pk;
		this.contrdefpk = contrdefpk;
		this.bizpmasterpk = bizpmasterpk;
		this.contractorclass = contractorclass;
		this.contractorclassgroup = contractorclassgroup;
		this.recordcreationtime = recordcreationtime;
	}

	public Ctrbizpcls(long pk, long contrdefpk, long bizpmasterpk, String contractorclass, String contractorclassgroup, Character isactiveflag, Date recordlastchangetime,
	        Date recordcreationtime) {
		this.pk = pk;
		this.contrdefpk = contrdefpk;
		this.bizpmasterpk = bizpmasterpk;
		this.contractorclass = contractorclass;
		this.contractorclassgroup = contractorclassgroup;
		this.isactiveflag = isactiveflag;
		this.recordlastchangetime = recordlastchangetime;
		this.recordcreationtime = recordcreationtime;
	}

	@Id
	@Column(name = "PK", unique = true, nullable = false, precision = 12, scale = 0)
	public long getPk() {
		return this.pk;
	}

	public void setPk(long pk) {
		this.pk = pk;
	}

	@Column(name = "CONTRDEFPK", nullable = false, precision = 12, scale = 0)
	public long getContrdefpk() {
		return this.contrdefpk;
	}

	public void setContrdefpk(long contrdefpk) {
		this.contrdefpk = contrdefpk;
	}

	@Column(name = "BIZPMASTERPK", nullable = false, precision = 12, scale = 0)
	public long getBizpmasterpk() {
		return this.bizpmasterpk;
	}

	public void setBizpmasterpk(long bizpmasterpk) {
		this.bizpmasterpk = bizpmasterpk;
	}

	@Column(name = "CONTRACTORCLASS", nullable = false, length = 30)
	public String getContractorclass() {
		return this.contractorclass;
	}

	public void setContractorclass(String contractorclass) {
		this.contractorclass = contractorclass;
	}

	@Column(name = "CONTRACTORCLASSGROUP", nullable = false, length = 30)
	public String getContractorclassgroup() {
		return this.contractorclassgroup;
	}

	public void setContractorclassgroup(String contractorclassgroup) {
		this.contractorclassgroup = contractorclassgroup;
	}

	@Column(name = "ISACTIVEFLAG", length = 1)
	public Character getIsactiveflag() {
		return this.isactiveflag;
	}

	public void setIsactiveflag(Character isactiveflag) {
		this.isactiveflag = isactiveflag;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "RECORDLASTCHANGETIME", length = 19)
	public Date getRecordlastchangetime() {
		return this.recordlastchangetime;
	}

	public void setRecordlastchangetime(Date recordlastchangetime) {
		this.recordlastchangetime = recordlastchangetime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "RECORDCREATIONTIME", nullable = false, length = 19)
	public Date getRecordcreationtime() {
		return this.recordcreationtime;
	}

	public void setRecordcreationtime(Date recordcreationtime) {
		this.recordcreationtime = recordcreationtime;
	}

}
