package com.galexis.alloga2mysql.model;

// Generated Mar 4, 2013 4:41:13 PM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Custordlin generated by hbm2java
 */
@Entity
@Table(name = "CUSTORDLIN")
public class Custordlin implements java.io.Serializable {

	private long pk;

	private long custordhdrpk;

	private int deliverylinenr;

	private String itemcategory;

	private String storagelocation;

	private String contractoritemnr;

	private String contractoritemnr2;

	private String itemnr;

	private String itemdescription;

	private String batchnr;

	private BigDecimal requesteddeliveryqty;

	private String unit;

	private Date deliverydate;

	private String batchsplitallowedflag;

	private BigDecimal ssoInvoiceqty;

	private BigDecimal ssoNettopriceunit;

	private BigDecimal ssoDiscount;

	private Date timestampreceived;

	private Integer filesequencenr;

	private String transactionid;

	private Long backendordernr;

	private Integer backendorderlinenr;

	private Byte backendorderstatus;

	private Date timestampconfirmation;

	private String programname;

	private String processingflag1;

	private String processingflag2;

	private String processingflag3;

	private String processingflag4;

	private String processingflag5;

	private String processingflag6;

	private String processingflag7;

	private String processingflag8;

	private String processingflag9;

	private String processingflag10;

	private String recordprocessedflag;

	private Date recordprocessingtime;

	private Date recordlastchangetime;

	private Date recordcreationtime;

	private String orderingpartypurchordnumber;

	private String orderingpartypurchordline;

	private String customerorderreference;

	private String customerorderreferenceline;

	private String customerreference1;

	private String customerreference2;

	private String customerreference3;

	private String customerreference4;

	private String customerreference5;

	private Integer superiorpositionlinenr;

	public Custordlin() {
	}

	public Custordlin(long pk, long custordhdrpk, int deliverylinenr, String contractoritemnr, Date recordcreationtime) {
		this.pk = pk;
		this.custordhdrpk = custordhdrpk;
		this.deliverylinenr = deliverylinenr;
		this.contractoritemnr = contractoritemnr;
		this.recordcreationtime = recordcreationtime;
	}

	public Custordlin(long pk, long custordhdrpk, int deliverylinenr, String itemcategory, String storagelocation, String contractoritemnr, String contractoritemnr2,
	        String itemnr, String itemdescription, String batchnr, BigDecimal requesteddeliveryqty, String unit, Date deliverydate, String batchsplitallowedflag,
	        BigDecimal ssoInvoiceqty, BigDecimal ssoNettopriceunit, BigDecimal ssoDiscount, Date timestampreceived, Integer filesequencenr, String transactionid,
	        Long backendordernr, Integer backendorderlinenr, Byte backendorderstatus, Date timestampconfirmation, String programname, String processingflag1,
	        String processingflag2, String processingflag3, String processingflag4, String processingflag5, String processingflag6, String processingflag7, String processingflag8,
	        String processingflag9, String processingflag10, String recordprocessedflag, Date recordprocessingtime, Date recordlastchangetime, Date recordcreationtime,
	        String orderingpartypurchordnumber, String orderingpartypurchordline, String customerorderreference, String customerorderreferenceline, String customerreference1,
	        String customerreference2, String customerreference3, String customerreference4, String customerreference5, Integer superiorpositionlinenr) {
		this.pk = pk;
		this.custordhdrpk = custordhdrpk;
		this.deliverylinenr = deliverylinenr;
		this.itemcategory = itemcategory;
		this.storagelocation = storagelocation;
		this.contractoritemnr = contractoritemnr;
		this.contractoritemnr2 = contractoritemnr2;
		this.itemnr = itemnr;
		this.itemdescription = itemdescription;
		this.batchnr = batchnr;
		this.requesteddeliveryqty = requesteddeliveryqty;
		this.unit = unit;
		this.deliverydate = deliverydate;
		this.batchsplitallowedflag = batchsplitallowedflag;
		this.ssoInvoiceqty = ssoInvoiceqty;
		this.ssoNettopriceunit = ssoNettopriceunit;
		this.ssoDiscount = ssoDiscount;
		this.timestampreceived = timestampreceived;
		this.filesequencenr = filesequencenr;
		this.transactionid = transactionid;
		this.backendordernr = backendordernr;
		this.backendorderlinenr = backendorderlinenr;
		this.backendorderstatus = backendorderstatus;
		this.timestampconfirmation = timestampconfirmation;
		this.programname = programname;
		this.processingflag1 = processingflag1;
		this.processingflag2 = processingflag2;
		this.processingflag3 = processingflag3;
		this.processingflag4 = processingflag4;
		this.processingflag5 = processingflag5;
		this.processingflag6 = processingflag6;
		this.processingflag7 = processingflag7;
		this.processingflag8 = processingflag8;
		this.processingflag9 = processingflag9;
		this.processingflag10 = processingflag10;
		this.recordprocessedflag = recordprocessedflag;
		this.recordprocessingtime = recordprocessingtime;
		this.recordlastchangetime = recordlastchangetime;
		this.recordcreationtime = recordcreationtime;
		this.orderingpartypurchordnumber = orderingpartypurchordnumber;
		this.orderingpartypurchordline = orderingpartypurchordline;
		this.customerorderreference = customerorderreference;
		this.customerorderreferenceline = customerorderreferenceline;
		this.customerreference1 = customerreference1;
		this.customerreference2 = customerreference2;
		this.customerreference3 = customerreference3;
		this.customerreference4 = customerreference4;
		this.customerreference5 = customerreference5;
		this.superiorpositionlinenr = superiorpositionlinenr;
	}

	@Id
	@Column(name = "PK", unique = true, nullable = false, precision = 12, scale = 0)
	public long getPk() {
		return this.pk;
	}

	public void setPk(long pk) {
		this.pk = pk;
	}

	@Column(name = "CUSTORDHDRPK", nullable = false, precision = 12, scale = 0)
	public long getCustordhdrpk() {
		return this.custordhdrpk;
	}

	public void setCustordhdrpk(long custordhdrpk) {
		this.custordhdrpk = custordhdrpk;
	}

	@Column(name = "DELIVERYLINENR", nullable = false, precision = 6, scale = 0)
	public int getDeliverylinenr() {
		return this.deliverylinenr;
	}

	public void setDeliverylinenr(int deliverylinenr) {
		this.deliverylinenr = deliverylinenr;
	}

	@Column(name = "ITEMCATEGORY", length = 10)
	public String getItemcategory() {
		return this.itemcategory;
	}

	public void setItemcategory(String itemcategory) {
		this.itemcategory = itemcategory;
	}

	@Column(name = "STORAGELOCATION", length = 10)
	public String getStoragelocation() {
		return this.storagelocation;
	}

	public void setStoragelocation(String storagelocation) {
		this.storagelocation = storagelocation;
	}

	@Column(name = "CONTRACTORITEMNR", nullable = false, length = 35)
	public String getContractoritemnr() {
		return this.contractoritemnr;
	}

	public void setContractoritemnr(String contractoritemnr) {
		this.contractoritemnr = contractoritemnr;
	}

	@Column(name = "CONTRACTORITEMNR2", length = 35)
	public String getContractoritemnr2() {
		return this.contractoritemnr2;
	}

	public void setContractoritemnr2(String contractoritemnr2) {
		this.contractoritemnr2 = contractoritemnr2;
	}

	@Column(name = "ITEMNR", length = 35)
	public String getItemnr() {
		return this.itemnr;
	}

	public void setItemnr(String itemnr) {
		this.itemnr = itemnr;
	}

	@Column(name = "ITEMDESCRIPTION", length = 50)
	public String getItemdescription() {
		return this.itemdescription;
	}

	public void setItemdescription(String itemdescription) {
		this.itemdescription = itemdescription;
	}

	@Column(name = "BATCHNR", length = 20)
	public String getBatchnr() {
		return this.batchnr;
	}

	public void setBatchnr(String batchnr) {
		this.batchnr = batchnr;
	}

	@Column(name = "REQUESTEDDELIVERYQTY", precision = 15, scale = 3)
	public BigDecimal getRequesteddeliveryqty() {
		return this.requesteddeliveryqty;
	}

	public void setRequesteddeliveryqty(BigDecimal requesteddeliveryqty) {
		this.requesteddeliveryqty = requesteddeliveryqty;
	}

	@Column(name = "UNIT", length = 10)
	public String getUnit() {
		return this.unit;
	}

	public void setUnit(String unit) {
		this.unit = unit;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DELIVERYDATE", length = 19)
	public Date getDeliverydate() {
		return this.deliverydate;
	}

	public void setDeliverydate(Date deliverydate) {
		this.deliverydate = deliverydate;
	}

	@Column(name = "BATCHSPLITALLOWEDFLAG", length = 1)
	public String getBatchsplitallowedflag() {
		return this.batchsplitallowedflag;
	}

	public void setBatchsplitallowedflag(String batchsplitallowedflag) {
		this.batchsplitallowedflag = batchsplitallowedflag;
	}

	@Column(name = "SSO_INVOICEQTY", precision = 15, scale = 3)
	public BigDecimal getSsoInvoiceqty() {
		return this.ssoInvoiceqty;
	}

	public void setSsoInvoiceqty(BigDecimal ssoInvoiceqty) {
		this.ssoInvoiceqty = ssoInvoiceqty;
	}

	@Column(name = "SSO_NETTOPRICEUNIT", precision = 17, scale = 4)
	public BigDecimal getSsoNettopriceunit() {
		return this.ssoNettopriceunit;
	}

	public void setSsoNettopriceunit(BigDecimal ssoNettopriceunit) {
		this.ssoNettopriceunit = ssoNettopriceunit;
	}

	@Column(name = "SSO_DISCOUNT", precision = 5)
	public BigDecimal getSsoDiscount() {
		return this.ssoDiscount;
	}

	public void setSsoDiscount(BigDecimal ssoDiscount) {
		this.ssoDiscount = ssoDiscount;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "TIMESTAMPRECEIVED", length = 19)
	public Date getTimestampreceived() {
		return this.timestampreceived;
	}

	public void setTimestampreceived(Date timestampreceived) {
		this.timestampreceived = timestampreceived;
	}

	@Column(name = "FILESEQUENCENR", precision = 7, scale = 0)
	public Integer getFilesequencenr() {
		return this.filesequencenr;
	}

	public void setFilesequencenr(Integer filesequencenr) {
		this.filesequencenr = filesequencenr;
	}

	@Column(name = "TRANSACTIONID", length = 50)
	public String getTransactionid() {
		return this.transactionid;
	}

	public void setTransactionid(String transactionid) {
		this.transactionid = transactionid;
	}

	@Column(name = "BACKENDORDERNR", precision = 12, scale = 0)
	public Long getBackendordernr() {
		return this.backendordernr;
	}

	public void setBackendordernr(Long backendordernr) {
		this.backendordernr = backendordernr;
	}

	@Column(name = "BACKENDORDERLINENR", precision = 5, scale = 0)
	public Integer getBackendorderlinenr() {
		return this.backendorderlinenr;
	}

	public void setBackendorderlinenr(Integer backendorderlinenr) {
		this.backendorderlinenr = backendorderlinenr;
	}

	@Column(name = "BACKENDORDERSTATUS", precision = 2, scale = 0)
	public Byte getBackendorderstatus() {
		return this.backendorderstatus;
	}

	public void setBackendorderstatus(Byte backendorderstatus) {
		this.backendorderstatus = backendorderstatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "TIMESTAMPCONFIRMATION", length = 19)
	public Date getTimestampconfirmation() {
		return this.timestampconfirmation;
	}

	public void setTimestampconfirmation(Date timestampconfirmation) {
		this.timestampconfirmation = timestampconfirmation;
	}

	@Column(name = "PROGRAMNAME", length = 10)
	public String getProgramname() {
		return this.programname;
	}

	public void setProgramname(String programname) {
		this.programname = programname;
	}

	@Column(name = "PROCESSINGFLAG1", length = 1)
	public String getProcessingflag1() {
		return this.processingflag1;
	}

	public void setProcessingflag1(String processingflag1) {
		this.processingflag1 = processingflag1;
	}

	@Column(name = "PROCESSINGFLAG2", length = 1)
	public String getProcessingflag2() {
		return this.processingflag2;
	}

	public void setProcessingflag2(String processingflag2) {
		this.processingflag2 = processingflag2;
	}

	@Column(name = "PROCESSINGFLAG3", length = 1)
	public String getProcessingflag3() {
		return this.processingflag3;
	}

	public void setProcessingflag3(String processingflag3) {
		this.processingflag3 = processingflag3;
	}

	@Column(name = "PROCESSINGFLAG4", length = 1)
	public String getProcessingflag4() {
		return this.processingflag4;
	}

	public void setProcessingflag4(String processingflag4) {
		this.processingflag4 = processingflag4;
	}

	@Column(name = "PROCESSINGFLAG5", length = 1)
	public String getProcessingflag5() {
		return this.processingflag5;
	}

	public void setProcessingflag5(String processingflag5) {
		this.processingflag5 = processingflag5;
	}

	@Column(name = "PROCESSINGFLAG6", length = 1)
	public String getProcessingflag6() {
		return this.processingflag6;
	}

	public void setProcessingflag6(String processingflag6) {
		this.processingflag6 = processingflag6;
	}

	@Column(name = "PROCESSINGFLAG7", length = 1)
	public String getProcessingflag7() {
		return this.processingflag7;
	}

	public void setProcessingflag7(String processingflag7) {
		this.processingflag7 = processingflag7;
	}

	@Column(name = "PROCESSINGFLAG8", length = 1)
	public String getProcessingflag8() {
		return this.processingflag8;
	}

	public void setProcessingflag8(String processingflag8) {
		this.processingflag8 = processingflag8;
	}

	@Column(name = "PROCESSINGFLAG9", length = 1)
	public String getProcessingflag9() {
		return this.processingflag9;
	}

	public void setProcessingflag9(String processingflag9) {
		this.processingflag9 = processingflag9;
	}

	@Column(name = "PROCESSINGFLAG10", length = 1)
	public String getProcessingflag10() {
		return this.processingflag10;
	}

	public void setProcessingflag10(String processingflag10) {
		this.processingflag10 = processingflag10;
	}

	@Column(name = "RECORDPROCESSEDFLAG", length = 1)
	public String getRecordprocessedflag() {
		return this.recordprocessedflag;
	}

	public void setRecordprocessedflag(String recordprocessedflag) {
		this.recordprocessedflag = recordprocessedflag;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "RECORDPROCESSINGTIME", length = 19)
	public Date getRecordprocessingtime() {
		return this.recordprocessingtime;
	}

	public void setRecordprocessingtime(Date recordprocessingtime) {
		this.recordprocessingtime = recordprocessingtime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "RECORDLASTCHANGETIME", length = 19)
	public Date getRecordlastchangetime() {
		return this.recordlastchangetime;
	}

	public void setRecordlastchangetime(Date recordlastchangetime) {
		this.recordlastchangetime = recordlastchangetime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "RECORDCREATIONTIME", nullable = false, length = 19)
	public Date getRecordcreationtime() {
		return this.recordcreationtime;
	}

	public void setRecordcreationtime(Date recordcreationtime) {
		this.recordcreationtime = recordcreationtime;
	}

	@Column(name = "ORDERINGPARTYPURCHORDNUMBER", length = 35)
	public String getOrderingpartypurchordnumber() {
		return this.orderingpartypurchordnumber;
	}

	public void setOrderingpartypurchordnumber(String orderingpartypurchordnumber) {
		this.orderingpartypurchordnumber = orderingpartypurchordnumber;
	}

	@Column(name = "ORDERINGPARTYPURCHORDLINE", length = 35)
	public String getOrderingpartypurchordline() {
		return this.orderingpartypurchordline;
	}

	public void setOrderingpartypurchordline(String orderingpartypurchordline) {
		this.orderingpartypurchordline = orderingpartypurchordline;
	}

	@Column(name = "CUSTOMERORDERREFERENCE", length = 35)
	public String getCustomerorderreference() {
		return this.customerorderreference;
	}

	public void setCustomerorderreference(String customerorderreference) {
		this.customerorderreference = customerorderreference;
	}

	@Column(name = "CUSTOMERORDERREFERENCELINE", length = 35)
	public String getCustomerorderreferenceline() {
		return this.customerorderreferenceline;
	}

	public void setCustomerorderreferenceline(String customerorderreferenceline) {
		this.customerorderreferenceline = customerorderreferenceline;
	}

	@Column(name = "CUSTOMERREFERENCE1", length = 35)
	public String getCustomerreference1() {
		return this.customerreference1;
	}

	public void setCustomerreference1(String customerreference1) {
		this.customerreference1 = customerreference1;
	}

	@Column(name = "CUSTOMERREFERENCE2", length = 35)
	public String getCustomerreference2() {
		return this.customerreference2;
	}

	public void setCustomerreference2(String customerreference2) {
		this.customerreference2 = customerreference2;
	}

	@Column(name = "CUSTOMERREFERENCE3", length = 35)
	public String getCustomerreference3() {
		return this.customerreference3;
	}

	public void setCustomerreference3(String customerreference3) {
		this.customerreference3 = customerreference3;
	}

	@Column(name = "CUSTOMERREFERENCE4", length = 35)
	public String getCustomerreference4() {
		return this.customerreference4;
	}

	public void setCustomerreference4(String customerreference4) {
		this.customerreference4 = customerreference4;
	}

	@Column(name = "CUSTOMERREFERENCE5", length = 35)
	public String getCustomerreference5() {
		return this.customerreference5;
	}

	public void setCustomerreference5(String customerreference5) {
		this.customerreference5 = customerreference5;
	}

	@Column(name = "SUPERIORPOSITIONLINENR", precision = 6, scale = 0)
	public Integer getSuperiorpositionlinenr() {
		return this.superiorpositionlinenr;
	}

	public void setSuperiorpositionlinenr(Integer superiorpositionlinenr) {
		this.superiorpositionlinenr = superiorpositionlinenr;
	}

}
