package com.galexis.alloga2mysql.model;

// Generated Mar 4, 2013 4:41:13 PM by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Custordhdr generated by hbm2java
 */
@Entity
@Table(name = "CUSTORDHDR")
public class Custordhdr implements java.io.Serializable {

	private long pk;

	private Long contrdefpk;

	private String deliverynr;

	private String documenttype;

	private String salesorderdocumenttype;

	private String shippingpoint;

	private String salesordernr;

	private String customerpurchaseordernr;

	private Date orderdate;

	private Date requireddeliverydate;

	private String exportindicatorflag;

	private String galHandler;

	private String handlerphonenr;

	private String customerreference;

	private String pickinginformation;

	private String shiptocustomergroup;

	private String shiptocustomernr;

	private String shiptocustomername;

	private String shiptoaddressline2;

	private String shiptoaddressline3;

	private String shiptoaddressline4;

	private String shiptostreet;

	private String shiptocity;

	private String shiptopostalcode;

	private String shiptocountry;

	private String shiptophonenr;

	private String shiptolanguage;

	private String billtocustomernr;

	private String billtocustomername;

	private String billtoaddressline2;

	private String billtoaddressline3;

	private String billtoaddressline4;

	private String billtostreet;

	private String billtocity;

	private String billtopostalcode;

	private String billtocountry;

	private String billtophonenr;

	private String billtolanguage;

	private String shippingconditions;

	private String deliverypriority;

	private String termsofdelivery;

	private String customereannr;

	private String orderholdflag;

	private String orderprintflag;

	private String filereceived;

	private Date timestampreceived;

	private Integer filesequencenr;

	private String transactionid;

	private Long backendordernr;

	private String backendordertype;

	private Byte backendorderstatus;

	private String orderSourceCode;

	private Date timestampconfirmation;

	private String fileconfirmed;

	private String programname;

	private String processingflag1;

	private String processingflag2;

	private String processingflag3;

	private String processingflag4;

	private String processingflag5;

	private String processingflag6;

	private String processingflag7;

	private String processingflag8;

	private String processingflag9;

	private String processingflag10;

	private String recordprocessedflag;

	private Date recordprocessingtime;

	private Date recordlastchangetime;

	private Date recordcreationtime;

	private String customertourid;

	private String customertoursequence;

	private String destination;

	private String customerreference1;

	private String customerreference2;

	private String customerreference3;

	private String customerreference4;

	private String customerreference5;

	private String backendcustomernr;

	private String orderingpartyid;

	public Custordhdr() {
	}

	public Custordhdr(long pk, String deliverynr, Date recordcreationtime) {
		this.pk = pk;
		this.deliverynr = deliverynr;
		this.recordcreationtime = recordcreationtime;
	}

	public Custordhdr(long pk, Long contrdefpk, String deliverynr, String documenttype, String salesorderdocumenttype, String shippingpoint, String salesordernr,
	        String customerpurchaseordernr, Date orderdate, Date requireddeliverydate, String exportindicatorflag, String handler, String handlerphonenr, String customerreference,
	        String pickinginformation, String shiptocustomergroup, String shiptocustomernr, String shiptocustomername, String shiptoaddressline2, String shiptoaddressline3,
	        String shiptoaddressline4, String shiptostreet, String shiptocity, String shiptopostalcode, String shiptocountry, String shiptophonenr, String shiptolanguage,
	        String billtocustomernr, String billtocustomername, String billtoaddressline2, String billtoaddressline3, String billtoaddressline4, String billtostreet,
	        String billtocity, String billtopostalcode, String billtocountry, String billtophonenr, String billtolanguage, String shippingconditions, String deliverypriority,
	        String termsofdelivery, String customereannr, String orderholdflag, String orderprintflag, String filereceived, Date timestampreceived, Integer filesequencenr,
	        String transactionid, Long backendordernr, String backendordertype, Byte backendorderstatus, String orderSourceCode, Date timestampconfirmation, String fileconfirmed,
	        String programname, String processingflag1, String processingflag2, String processingflag3, String processingflag4, String processingflag5, String processingflag6,
	        String processingflag7, String processingflag8, String processingflag9, String processingflag10, String recordprocessedflag, Date recordprocessingtime,
	        Date recordlastchangetime, Date recordcreationtime, String customertourid, String customertoursequence, String destination, String customerreference1,
	        String customerreference2, String customerreference3, String customerreference4, String customerreference5, String backendcustomernr, String orderingpartyid) {
		this.pk = pk;
		this.contrdefpk = contrdefpk;
		this.deliverynr = deliverynr;
		this.documenttype = documenttype;
		this.salesorderdocumenttype = salesorderdocumenttype;
		this.shippingpoint = shippingpoint;
		this.salesordernr = salesordernr;
		this.customerpurchaseordernr = customerpurchaseordernr;
		this.orderdate = orderdate;
		this.requireddeliverydate = requireddeliverydate;
		this.exportindicatorflag = exportindicatorflag;
		this.galHandler = handler;
		this.handlerphonenr = handlerphonenr;
		this.customerreference = customerreference;
		this.pickinginformation = pickinginformation;
		this.shiptocustomergroup = shiptocustomergroup;
		this.shiptocustomernr = shiptocustomernr;
		this.shiptocustomername = shiptocustomername;
		this.shiptoaddressline2 = shiptoaddressline2;
		this.shiptoaddressline3 = shiptoaddressline3;
		this.shiptoaddressline4 = shiptoaddressline4;
		this.shiptostreet = shiptostreet;
		this.shiptocity = shiptocity;
		this.shiptopostalcode = shiptopostalcode;
		this.shiptocountry = shiptocountry;
		this.shiptophonenr = shiptophonenr;
		this.shiptolanguage = shiptolanguage;
		this.billtocustomernr = billtocustomernr;
		this.billtocustomername = billtocustomername;
		this.billtoaddressline2 = billtoaddressline2;
		this.billtoaddressline3 = billtoaddressline3;
		this.billtoaddressline4 = billtoaddressline4;
		this.billtostreet = billtostreet;
		this.billtocity = billtocity;
		this.billtopostalcode = billtopostalcode;
		this.billtocountry = billtocountry;
		this.billtophonenr = billtophonenr;
		this.billtolanguage = billtolanguage;
		this.shippingconditions = shippingconditions;
		this.deliverypriority = deliverypriority;
		this.termsofdelivery = termsofdelivery;
		this.customereannr = customereannr;
		this.orderholdflag = orderholdflag;
		this.orderprintflag = orderprintflag;
		this.filereceived = filereceived;
		this.timestampreceived = timestampreceived;
		this.filesequencenr = filesequencenr;
		this.transactionid = transactionid;
		this.backendordernr = backendordernr;
		this.backendordertype = backendordertype;
		this.backendorderstatus = backendorderstatus;
		this.orderSourceCode = orderSourceCode;
		this.timestampconfirmation = timestampconfirmation;
		this.fileconfirmed = fileconfirmed;
		this.programname = programname;
		this.processingflag1 = processingflag1;
		this.processingflag2 = processingflag2;
		this.processingflag3 = processingflag3;
		this.processingflag4 = processingflag4;
		this.processingflag5 = processingflag5;
		this.processingflag6 = processingflag6;
		this.processingflag7 = processingflag7;
		this.processingflag8 = processingflag8;
		this.processingflag9 = processingflag9;
		this.processingflag10 = processingflag10;
		this.recordprocessedflag = recordprocessedflag;
		this.recordprocessingtime = recordprocessingtime;
		this.recordlastchangetime = recordlastchangetime;
		this.recordcreationtime = recordcreationtime;
		this.customertourid = customertourid;
		this.customertoursequence = customertoursequence;
		this.destination = destination;
		this.customerreference1 = customerreference1;
		this.customerreference2 = customerreference2;
		this.customerreference3 = customerreference3;
		this.customerreference4 = customerreference4;
		this.customerreference5 = customerreference5;
		this.backendcustomernr = backendcustomernr;
		this.orderingpartyid = orderingpartyid;
	}

	@Id
	@Column(name = "PK", unique = true, nullable = false, precision = 12, scale = 0)
	public long getPk() {
		return this.pk;
	}

	public void setPk(long pk) {
		this.pk = pk;
	}

	@Column(name = "CONTRDEFPK", precision = 12, scale = 0)
	public Long getContrdefpk() {
		return this.contrdefpk;
	}

	public void setContrdefpk(Long contrdefpk) {
		this.contrdefpk = contrdefpk;
	}

	@Column(name = "DELIVERYNR", nullable = false, length = 35)
	public String getDeliverynr() {
		return this.deliverynr;
	}

	public void setDeliverynr(String deliverynr) {
		this.deliverynr = deliverynr;
	}

	@Column(name = "DOCUMENTTYPE", length = 10)
	public String getDocumenttype() {
		return this.documenttype;
	}

	public void setDocumenttype(String documenttype) {
		this.documenttype = documenttype;
	}

	@Column(name = "SALESORDERDOCUMENTTYPE", length = 10)
	public String getSalesorderdocumenttype() {
		return this.salesorderdocumenttype;
	}

	public void setSalesorderdocumenttype(String salesorderdocumenttype) {
		this.salesorderdocumenttype = salesorderdocumenttype;
	}

	@Column(name = "SHIPPINGPOINT", length = 10)
	public String getShippingpoint() {
		return this.shippingpoint;
	}

	public void setShippingpoint(String shippingpoint) {
		this.shippingpoint = shippingpoint;
	}

	@Column(name = "SALESORDERNR", length = 35)
	public String getSalesordernr() {
		return this.salesordernr;
	}

	public void setSalesordernr(String salesordernr) {
		this.salesordernr = salesordernr;
	}

	@Column(name = "CUSTOMERPURCHASEORDERNR", length = 35)
	public String getCustomerpurchaseordernr() {
		return this.customerpurchaseordernr;
	}

	public void setCustomerpurchaseordernr(String customerpurchaseordernr) {
		this.customerpurchaseordernr = customerpurchaseordernr;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ORDERDATE", length = 19)
	public Date getOrderdate() {
		return this.orderdate;
	}

	public void setOrderdate(Date orderdate) {
		this.orderdate = orderdate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "REQUIREDDELIVERYDATE", length = 19)
	public Date getRequireddeliverydate() {
		return this.requireddeliverydate;
	}

	public void setRequireddeliverydate(Date requireddeliverydate) {
		this.requireddeliverydate = requireddeliverydate;
	}

	@Column(name = "EXPORTINDICATORFLAG", length = 1)
	public String getExportindicatorflag() {
		return this.exportindicatorflag;
	}

	public void setExportindicatorflag(String exportindicatorflag) {
		this.exportindicatorflag = exportindicatorflag;
	}

	@Column(name = "HANDLER", length = 30)
	public String getGalHandler() {
		return this.galHandler;
	}

	public void setGalHandler(String handler) {
		this.galHandler = handler;
	}

	@Column(name = "HANDLERPHONENR", length = 20)
	public String getHandlerphonenr() {
		return this.handlerphonenr;
	}

	public void setHandlerphonenr(String handlerphonenr) {
		this.handlerphonenr = handlerphonenr;
	}

	@Column(name = "CUSTOMERREFERENCE", length = 50)
	public String getCustomerreference() {
		return this.customerreference;
	}

	public void setCustomerreference(String customerreference) {
		this.customerreference = customerreference;
	}

	@Column(name = "PICKINGINFORMATION", length = 70)
	public String getPickinginformation() {
		return this.pickinginformation;
	}

	public void setPickinginformation(String pickinginformation) {
		this.pickinginformation = pickinginformation;
	}

	@Column(name = "SHIPTOCUSTOMERGROUP", length = 10)
	public String getShiptocustomergroup() {
		return this.shiptocustomergroup;
	}

	public void setShiptocustomergroup(String shiptocustomergroup) {
		this.shiptocustomergroup = shiptocustomergroup;
	}

	@Column(name = "SHIPTOCUSTOMERNR", length = 20)
	public String getShiptocustomernr() {
		return this.shiptocustomernr;
	}

	public void setShiptocustomernr(String shiptocustomernr) {
		this.shiptocustomernr = shiptocustomernr;
	}

	@Column(name = "SHIPTOCUSTOMERNAME", length = 50)
	public String getShiptocustomername() {
		return this.shiptocustomername;
	}

	public void setShiptocustomername(String shiptocustomername) {
		this.shiptocustomername = shiptocustomername;
	}

	@Column(name = "SHIPTOADDRESSLINE2", length = 50)
	public String getShiptoaddressline2() {
		return this.shiptoaddressline2;
	}

	public void setShiptoaddressline2(String shiptoaddressline2) {
		this.shiptoaddressline2 = shiptoaddressline2;
	}

	@Column(name = "SHIPTOADDRESSLINE3", length = 50)
	public String getShiptoaddressline3() {
		return this.shiptoaddressline3;
	}

	public void setShiptoaddressline3(String shiptoaddressline3) {
		this.shiptoaddressline3 = shiptoaddressline3;
	}

	@Column(name = "SHIPTOADDRESSLINE4", length = 50)
	public String getShiptoaddressline4() {
		return this.shiptoaddressline4;
	}

	public void setShiptoaddressline4(String shiptoaddressline4) {
		this.shiptoaddressline4 = shiptoaddressline4;
	}

	@Column(name = "SHIPTOSTREET", length = 50)
	public String getShiptostreet() {
		return this.shiptostreet;
	}

	public void setShiptostreet(String shiptostreet) {
		this.shiptostreet = shiptostreet;
	}

	@Column(name = "SHIPTOCITY", length = 50)
	public String getShiptocity() {
		return this.shiptocity;
	}

	public void setShiptocity(String shiptocity) {
		this.shiptocity = shiptocity;
	}

	@Column(name = "SHIPTOPOSTALCODE", length = 16)
	public String getShiptopostalcode() {
		return this.shiptopostalcode;
	}

	public void setShiptopostalcode(String shiptopostalcode) {
		this.shiptopostalcode = shiptopostalcode;
	}

	@Column(name = "SHIPTOCOUNTRY", length = 4)
	public String getShiptocountry() {
		return this.shiptocountry;
	}

	public void setShiptocountry(String shiptocountry) {
		this.shiptocountry = shiptocountry;
	}

	@Column(name = "SHIPTOPHONENR", length = 20)
	public String getShiptophonenr() {
		return this.shiptophonenr;
	}

	public void setShiptophonenr(String shiptophonenr) {
		this.shiptophonenr = shiptophonenr;
	}

	@Column(name = "SHIPTOLANGUAGE", length = 3)
	public String getShiptolanguage() {
		return this.shiptolanguage;
	}

	public void setShiptolanguage(String shiptolanguage) {
		this.shiptolanguage = shiptolanguage;
	}

	@Column(name = "BILLTOCUSTOMERNR", length = 20)
	public String getBilltocustomernr() {
		return this.billtocustomernr;
	}

	public void setBilltocustomernr(String billtocustomernr) {
		this.billtocustomernr = billtocustomernr;
	}

	@Column(name = "BILLTOCUSTOMERNAME", length = 50)
	public String getBilltocustomername() {
		return this.billtocustomername;
	}

	public void setBilltocustomername(String billtocustomername) {
		this.billtocustomername = billtocustomername;
	}

	@Column(name = "BILLTOADDRESSLINE2", length = 50)
	public String getBilltoaddressline2() {
		return this.billtoaddressline2;
	}

	public void setBilltoaddressline2(String billtoaddressline2) {
		this.billtoaddressline2 = billtoaddressline2;
	}

	@Column(name = "BILLTOADDRESSLINE3", length = 50)
	public String getBilltoaddressline3() {
		return this.billtoaddressline3;
	}

	public void setBilltoaddressline3(String billtoaddressline3) {
		this.billtoaddressline3 = billtoaddressline3;
	}

	@Column(name = "BILLTOADDRESSLINE4", length = 50)
	public String getBilltoaddressline4() {
		return this.billtoaddressline4;
	}

	public void setBilltoaddressline4(String billtoaddressline4) {
		this.billtoaddressline4 = billtoaddressline4;
	}

	@Column(name = "BILLTOSTREET", length = 50)
	public String getBilltostreet() {
		return this.billtostreet;
	}

	public void setBilltostreet(String billtostreet) {
		this.billtostreet = billtostreet;
	}

	@Column(name = "BILLTOCITY", length = 50)
	public String getBilltocity() {
		return this.billtocity;
	}

	public void setBilltocity(String billtocity) {
		this.billtocity = billtocity;
	}

	@Column(name = "BILLTOPOSTALCODE", length = 16)
	public String getBilltopostalcode() {
		return this.billtopostalcode;
	}

	public void setBilltopostalcode(String billtopostalcode) {
		this.billtopostalcode = billtopostalcode;
	}

	@Column(name = "BILLTOCOUNTRY", length = 4)
	public String getBilltocountry() {
		return this.billtocountry;
	}

	public void setBilltocountry(String billtocountry) {
		this.billtocountry = billtocountry;
	}

	@Column(name = "BILLTOPHONENR", length = 20)
	public String getBilltophonenr() {
		return this.billtophonenr;
	}

	public void setBilltophonenr(String billtophonenr) {
		this.billtophonenr = billtophonenr;
	}

	@Column(name = "BILLTOLANGUAGE", length = 3)
	public String getBilltolanguage() {
		return this.billtolanguage;
	}

	public void setBilltolanguage(String billtolanguage) {
		this.billtolanguage = billtolanguage;
	}

	@Column(name = "SHIPPINGCONDITIONS", length = 10)
	public String getShippingconditions() {
		return this.shippingconditions;
	}

	public void setShippingconditions(String shippingconditions) {
		this.shippingconditions = shippingconditions;
	}

	@Column(name = "DELIVERYPRIORITY", length = 10)
	public String getDeliverypriority() {
		return this.deliverypriority;
	}

	public void setDeliverypriority(String deliverypriority) {
		this.deliverypriority = deliverypriority;
	}

	@Column(name = "TERMSOFDELIVERY", length = 30)
	public String getTermsofdelivery() {
		return this.termsofdelivery;
	}

	public void setTermsofdelivery(String termsofdelivery) {
		this.termsofdelivery = termsofdelivery;
	}

	@Column(name = "CUSTOMEREANNR", length = 20)
	public String getCustomereannr() {
		return this.customereannr;
	}

	public void setCustomereannr(String customereannr) {
		this.customereannr = customereannr;
	}

	@Column(name = "ORDERHOLDFLAG", length = 1)
	public String getOrderholdflag() {
		return this.orderholdflag;
	}

	public void setOrderholdflag(String orderholdflag) {
		this.orderholdflag = orderholdflag;
	}

	@Column(name = "ORDERPRINTFLAG", length = 1)
	public String getOrderprintflag() {
		return this.orderprintflag;
	}

	public void setOrderprintflag(String orderprintflag) {
		this.orderprintflag = orderprintflag;
	}

	@Column(name = "FILERECEIVED", length = 50)
	public String getFilereceived() {
		return this.filereceived;
	}

	public void setFilereceived(String filereceived) {
		this.filereceived = filereceived;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "TIMESTAMPRECEIVED", length = 19)
	public Date getTimestampreceived() {
		return this.timestampreceived;
	}

	public void setTimestampreceived(Date timestampreceived) {
		this.timestampreceived = timestampreceived;
	}

	@Column(name = "FILESEQUENCENR", precision = 7, scale = 0)
	public Integer getFilesequencenr() {
		return this.filesequencenr;
	}

	public void setFilesequencenr(Integer filesequencenr) {
		this.filesequencenr = filesequencenr;
	}

	@Column(name = "TRANSACTIONID", length = 50)
	public String getTransactionid() {
		return this.transactionid;
	}

	public void setTransactionid(String transactionid) {
		this.transactionid = transactionid;
	}

	@Column(name = "BACKENDORDERNR", precision = 12, scale = 0)
	public Long getBackendordernr() {
		return this.backendordernr;
	}

	public void setBackendordernr(Long backendordernr) {
		this.backendordernr = backendordernr;
	}

	@Column(name = "BACKENDORDERTYPE", length = 10)
	public String getBackendordertype() {
		return this.backendordertype;
	}

	public void setBackendordertype(String backendordertype) {
		this.backendordertype = backendordertype;
	}

	@Column(name = "BACKENDORDERSTATUS", precision = 2, scale = 0)
	public Byte getBackendorderstatus() {
		return this.backendorderstatus;
	}

	public void setBackendorderstatus(Byte backendorderstatus) {
		this.backendorderstatus = backendorderstatus;
	}

	@Column(name = "ORDER_SOURCE_CODE", length = 20)
	public String getOrderSourceCode() {
		return this.orderSourceCode;
	}

	public void setOrderSourceCode(String orderSourceCode) {
		this.orderSourceCode = orderSourceCode;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "TIMESTAMPCONFIRMATION", length = 19)
	public Date getTimestampconfirmation() {
		return this.timestampconfirmation;
	}

	public void setTimestampconfirmation(Date timestampconfirmation) {
		this.timestampconfirmation = timestampconfirmation;
	}

	@Column(name = "FILECONFIRMED", length = 50)
	public String getFileconfirmed() {
		return this.fileconfirmed;
	}

	public void setFileconfirmed(String fileconfirmed) {
		this.fileconfirmed = fileconfirmed;
	}

	@Column(name = "PROGRAMNAME", length = 10)
	public String getProgramname() {
		return this.programname;
	}

	public void setProgramname(String programname) {
		this.programname = programname;
	}

	@Column(name = "PROCESSINGFLAG1", length = 1)
	public String getProcessingflag1() {
		return this.processingflag1;
	}

	public void setProcessingflag1(String processingflag1) {
		this.processingflag1 = processingflag1;
	}

	@Column(name = "PROCESSINGFLAG2", length = 1)
	public String getProcessingflag2() {
		return this.processingflag2;
	}

	public void setProcessingflag2(String processingflag2) {
		this.processingflag2 = processingflag2;
	}

	@Column(name = "PROCESSINGFLAG3", length = 1)
	public String getProcessingflag3() {
		return this.processingflag3;
	}

	public void setProcessingflag3(String processingflag3) {
		this.processingflag3 = processingflag3;
	}

	@Column(name = "PROCESSINGFLAG4", length = 1)
	public String getProcessingflag4() {
		return this.processingflag4;
	}

	public void setProcessingflag4(String processingflag4) {
		this.processingflag4 = processingflag4;
	}

	@Column(name = "PROCESSINGFLAG5", length = 1)
	public String getProcessingflag5() {
		return this.processingflag5;
	}

	public void setProcessingflag5(String processingflag5) {
		this.processingflag5 = processingflag5;
	}

	@Column(name = "PROCESSINGFLAG6", length = 1)
	public String getProcessingflag6() {
		return this.processingflag6;
	}

	public void setProcessingflag6(String processingflag6) {
		this.processingflag6 = processingflag6;
	}

	@Column(name = "PROCESSINGFLAG7", length = 1)
	public String getProcessingflag7() {
		return this.processingflag7;
	}

	public void setProcessingflag7(String processingflag7) {
		this.processingflag7 = processingflag7;
	}

	@Column(name = "PROCESSINGFLAG8", length = 1)
	public String getProcessingflag8() {
		return this.processingflag8;
	}

	public void setProcessingflag8(String processingflag8) {
		this.processingflag8 = processingflag8;
	}

	@Column(name = "PROCESSINGFLAG9", length = 1)
	public String getProcessingflag9() {
		return this.processingflag9;
	}

	public void setProcessingflag9(String processingflag9) {
		this.processingflag9 = processingflag9;
	}

	@Column(name = "PROCESSINGFLAG10", length = 1)
	public String getProcessingflag10() {
		return this.processingflag10;
	}

	public void setProcessingflag10(String processingflag10) {
		this.processingflag10 = processingflag10;
	}

	@Column(name = "RECORDPROCESSEDFLAG", length = 1)
	public String getRecordprocessedflag() {
		return this.recordprocessedflag;
	}

	public void setRecordprocessedflag(String recordprocessedflag) {
		this.recordprocessedflag = recordprocessedflag;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "RECORDPROCESSINGTIME", length = 19)
	public Date getRecordprocessingtime() {
		return this.recordprocessingtime;
	}

	public void setRecordprocessingtime(Date recordprocessingtime) {
		this.recordprocessingtime = recordprocessingtime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "RECORDLASTCHANGETIME", length = 19)
	public Date getRecordlastchangetime() {
		return this.recordlastchangetime;
	}

	public void setRecordlastchangetime(Date recordlastchangetime) {
		this.recordlastchangetime = recordlastchangetime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "RECORDCREATIONTIME", nullable = false, length = 19)
	public Date getRecordcreationtime() {
		return this.recordcreationtime;
	}

	public void setRecordcreationtime(Date recordcreationtime) {
		this.recordcreationtime = recordcreationtime;
	}

	@Column(name = "CUSTOMERTOURID", length = 20)
	public String getCustomertourid() {
		return this.customertourid;
	}

	public void setCustomertourid(String customertourid) {
		this.customertourid = customertourid;
	}

	@Column(name = "CUSTOMERTOURSEQUENCE", length = 20)
	public String getCustomertoursequence() {
		return this.customertoursequence;
	}

	public void setCustomertoursequence(String customertoursequence) {
		this.customertoursequence = customertoursequence;
	}

	@Column(name = "DESTINATION", length = 10)
	public String getDestination() {
		return this.destination;
	}

	public void setDestination(String destination) {
		this.destination = destination;
	}

	@Column(name = "CUSTOMERREFERENCE1", length = 35)
	public String getCustomerreference1() {
		return this.customerreference1;
	}

	public void setCustomerreference1(String customerreference1) {
		this.customerreference1 = customerreference1;
	}

	@Column(name = "CUSTOMERREFERENCE2", length = 35)
	public String getCustomerreference2() {
		return this.customerreference2;
	}

	public void setCustomerreference2(String customerreference2) {
		this.customerreference2 = customerreference2;
	}

	@Column(name = "CUSTOMERREFERENCE3", length = 35)
	public String getCustomerreference3() {
		return this.customerreference3;
	}

	public void setCustomerreference3(String customerreference3) {
		this.customerreference3 = customerreference3;
	}

	@Column(name = "CUSTOMERREFERENCE4", length = 35)
	public String getCustomerreference4() {
		return this.customerreference4;
	}

	public void setCustomerreference4(String customerreference4) {
		this.customerreference4 = customerreference4;
	}

	@Column(name = "CUSTOMERREFERENCE5", length = 35)
	public String getCustomerreference5() {
		return this.customerreference5;
	}

	public void setCustomerreference5(String customerreference5) {
		this.customerreference5 = customerreference5;
	}

	@Column(name = "BACKENDCUSTOMERNR", length = 20)
	public String getBackendcustomernr() {
		return this.backendcustomernr;
	}

	public void setBackendcustomernr(String backendcustomernr) {
		this.backendcustomernr = backendcustomernr;
	}

	@Column(name = "ORDERINGPARTYID")
	public String getOrderingpartyid() {
		return this.orderingpartyid;
	}

	public void setOrderingpartyid(String orderingpartyid) {
		this.orderingpartyid = orderingpartyid;
	}

}
