package com.galexis.alloga2mysql.model;

// Generated Mar 4, 2013 4:41:13 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Custordtxt generated by hbm2java
 */
@Entity
@Table(name = "CUSTORDTXT")
public class Custordtxt implements java.io.Serializable {

	private long pk;

	private Long custordhdrpk;

	private Long custordlinpk;

	private int textsequencenr;

	private String textid;

	private String text;

	private String transactionid;

	private Date timestampreceived;

	private String programname;

	private String processingflag1;

	private String processingflag2;

	private String processingflag3;

	private String processingflag4;

	private String processingflag5;

	private String processingflag6;

	private String processingflag7;

	private String processingflag8;

	private String processingflag9;

	private String processingflag10;

	private String recordprocessedflag;

	private Date recordprocessingtime;

	private Date recordlastchangetime;

	private Date recordcreationtime;

	public Custordtxt() {
	}

	public Custordtxt(long pk, int textsequencenr, Date recordcreationtime) {
		this.pk = pk;
		this.textsequencenr = textsequencenr;
		this.recordcreationtime = recordcreationtime;
	}

	public Custordtxt(long pk, Long custordhdrpk, Long custordlinpk, int textsequencenr, String textid, String text, String transactionid, Date timestampreceived,
	        String programname, String processingflag1, String processingflag2, String processingflag3, String processingflag4, String processingflag5, String processingflag6,
	        String processingflag7, String processingflag8, String processingflag9, String processingflag10, String recordprocessedflag, Date recordprocessingtime,
	        Date recordlastchangetime, Date recordcreationtime) {
		this.pk = pk;
		this.custordhdrpk = custordhdrpk;
		this.custordlinpk = custordlinpk;
		this.textsequencenr = textsequencenr;
		this.textid = textid;
		this.text = text;
		this.transactionid = transactionid;
		this.timestampreceived = timestampreceived;
		this.programname = programname;
		this.processingflag1 = processingflag1;
		this.processingflag2 = processingflag2;
		this.processingflag3 = processingflag3;
		this.processingflag4 = processingflag4;
		this.processingflag5 = processingflag5;
		this.processingflag6 = processingflag6;
		this.processingflag7 = processingflag7;
		this.processingflag8 = processingflag8;
		this.processingflag9 = processingflag9;
		this.processingflag10 = processingflag10;
		this.recordprocessedflag = recordprocessedflag;
		this.recordprocessingtime = recordprocessingtime;
		this.recordlastchangetime = recordlastchangetime;
		this.recordcreationtime = recordcreationtime;
	}

	@Id
	@Column(name = "PK", unique = true, nullable = false, precision = 12, scale = 0)
	public long getPk() {
		return this.pk;
	}

	public void setPk(long pk) {
		this.pk = pk;
	}

	@Column(name = "CUSTORDHDRPK", precision = 12, scale = 0)
	public Long getCustordhdrpk() {
		return this.custordhdrpk;
	}

	public void setCustordhdrpk(Long custordhdrpk) {
		this.custordhdrpk = custordhdrpk;
	}

	@Column(name = "CUSTORDLINPK", precision = 12, scale = 0)
	public Long getCustordlinpk() {
		return this.custordlinpk;
	}

	public void setCustordlinpk(Long custordlinpk) {
		this.custordlinpk = custordlinpk;
	}

	@Column(name = "TEXTSEQUENCENR", nullable = false, precision = 6, scale = 0)
	public int getTextsequencenr() {
		return this.textsequencenr;
	}

	public void setTextsequencenr(int textsequencenr) {
		this.textsequencenr = textsequencenr;
	}

	@Column(name = "TEXTID", length = 10)
	public String getTextid() {
		return this.textid;
	}

	public void setTextid(String textid) {
		this.textid = textid;
	}

	@Column(name = "TEXT", length = 100)
	public String getText() {
		return this.text;
	}

	public void setText(String text) {
		this.text = text;
	}

	@Column(name = "TRANSACTIONID", length = 50)
	public String getTransactionid() {
		return this.transactionid;
	}

	public void setTransactionid(String transactionid) {
		this.transactionid = transactionid;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "TIMESTAMPRECEIVED", length = 19)
	public Date getTimestampreceived() {
		return this.timestampreceived;
	}

	public void setTimestampreceived(Date timestampreceived) {
		this.timestampreceived = timestampreceived;
	}

	@Column(name = "PROGRAMNAME", length = 10)
	public String getProgramname() {
		return this.programname;
	}

	public void setProgramname(String programname) {
		this.programname = programname;
	}

	@Column(name = "PROCESSINGFLAG1", length = 1)
	public String getProcessingflag1() {
		return this.processingflag1;
	}

	public void setProcessingflag1(String processingflag1) {
		this.processingflag1 = processingflag1;
	}

	@Column(name = "PROCESSINGFLAG2", length = 1)
	public String getProcessingflag2() {
		return this.processingflag2;
	}

	public void setProcessingflag2(String processingflag2) {
		this.processingflag2 = processingflag2;
	}

	@Column(name = "PROCESSINGFLAG3", length = 1)
	public String getProcessingflag3() {
		return this.processingflag3;
	}

	public void setProcessingflag3(String processingflag3) {
		this.processingflag3 = processingflag3;
	}

	@Column(name = "PROCESSINGFLAG4", length = 1)
	public String getProcessingflag4() {
		return this.processingflag4;
	}

	public void setProcessingflag4(String processingflag4) {
		this.processingflag4 = processingflag4;
	}

	@Column(name = "PROCESSINGFLAG5", length = 1)
	public String getProcessingflag5() {
		return this.processingflag5;
	}

	public void setProcessingflag5(String processingflag5) {
		this.processingflag5 = processingflag5;
	}

	@Column(name = "PROCESSINGFLAG6", length = 1)
	public String getProcessingflag6() {
		return this.processingflag6;
	}

	public void setProcessingflag6(String processingflag6) {
		this.processingflag6 = processingflag6;
	}

	@Column(name = "PROCESSINGFLAG7", length = 1)
	public String getProcessingflag7() {
		return this.processingflag7;
	}

	public void setProcessingflag7(String processingflag7) {
		this.processingflag7 = processingflag7;
	}

	@Column(name = "PROCESSINGFLAG8", length = 1)
	public String getProcessingflag8() {
		return this.processingflag8;
	}

	public void setProcessingflag8(String processingflag8) {
		this.processingflag8 = processingflag8;
	}

	@Column(name = "PROCESSINGFLAG9", length = 1)
	public String getProcessingflag9() {
		return this.processingflag9;
	}

	public void setProcessingflag9(String processingflag9) {
		this.processingflag9 = processingflag9;
	}

	@Column(name = "PROCESSINGFLAG10", length = 1)
	public String getProcessingflag10() {
		return this.processingflag10;
	}

	public void setProcessingflag10(String processingflag10) {
		this.processingflag10 = processingflag10;
	}

	@Column(name = "RECORDPROCESSEDFLAG", length = 1)
	public String getRecordprocessedflag() {
		return this.recordprocessedflag;
	}

	public void setRecordprocessedflag(String recordprocessedflag) {
		this.recordprocessedflag = recordprocessedflag;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "RECORDPROCESSINGTIME", length = 19)
	public Date getRecordprocessingtime() {
		return this.recordprocessingtime;
	}

	public void setRecordprocessingtime(Date recordprocessingtime) {
		this.recordprocessingtime = recordprocessingtime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "RECORDLASTCHANGETIME", length = 19)
	public Date getRecordlastchangetime() {
		return this.recordlastchangetime;
	}

	public void setRecordlastchangetime(Date recordlastchangetime) {
		this.recordlastchangetime = recordlastchangetime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "RECORDCREATIONTIME", nullable = false, length = 19)
	public Date getRecordcreationtime() {
		return this.recordcreationtime;
	}

	public void setRecordcreationtime(Date recordcreationtime) {
		this.recordcreationtime = recordcreationtime;
	}

}
