package com.galexis.alloga2mysql.model;

// Generated Mar 4, 2013 4:41:13 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Dayend generated by hbm2java
 */
@Entity
@Table(name = "DAYEND", uniqueConstraints = @UniqueConstraint(columnNames = { "DAYENDRELEASEDATE", "CONTRDEFPK" }))
public class Dayend implements java.io.Serializable {

	private long pk;

	private int dayendreleasedate;

	private long contrdefpk;

	private Date stockreconciliationtime;

	private String stockreconciliationtransactid;

	private String programname;

	private String dayendreleaseuser;

	private Date considered;

	private Date ipDayendjobsprocessed;

	private Date recordcreationtime;

	public Dayend() {
	}

	public Dayend(long pk, int dayendreleasedate, long contrdefpk, Date recordcreationtime) {
		this.pk = pk;
		this.dayendreleasedate = dayendreleasedate;
		this.contrdefpk = contrdefpk;
		this.recordcreationtime = recordcreationtime;
	}

	public Dayend(long pk, int dayendreleasedate, long contrdefpk, Date stockreconciliationtime, String stockreconciliationtransactid, String programname,
	        String dayendreleaseuser, Date considered, Date ipDayendjobsprocessed, Date recordcreationtime) {
		this.pk = pk;
		this.dayendreleasedate = dayendreleasedate;
		this.contrdefpk = contrdefpk;
		this.stockreconciliationtime = stockreconciliationtime;
		this.stockreconciliationtransactid = stockreconciliationtransactid;
		this.programname = programname;
		this.dayendreleaseuser = dayendreleaseuser;
		this.considered = considered;
		this.ipDayendjobsprocessed = ipDayendjobsprocessed;
		this.recordcreationtime = recordcreationtime;
	}

	@Id
	@Column(name = "PK", unique = true, nullable = false, precision = 12, scale = 0)
	public long getPk() {
		return this.pk;
	}

	public void setPk(long pk) {
		this.pk = pk;
	}

	@Column(name = "DAYENDRELEASEDATE", nullable = false, precision = 8, scale = 0)
	public int getDayendreleasedate() {
		return this.dayendreleasedate;
	}

	public void setDayendreleasedate(int dayendreleasedate) {
		this.dayendreleasedate = dayendreleasedate;
	}

	@Column(name = "CONTRDEFPK", nullable = false, precision = 12, scale = 0)
	public long getContrdefpk() {
		return this.contrdefpk;
	}

	public void setContrdefpk(long contrdefpk) {
		this.contrdefpk = contrdefpk;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "STOCKRECONCILIATIONTIME", length = 19)
	public Date getStockreconciliationtime() {
		return this.stockreconciliationtime;
	}

	public void setStockreconciliationtime(Date stockreconciliationtime) {
		this.stockreconciliationtime = stockreconciliationtime;
	}

	@Column(name = "STOCKRECONCILIATIONTRANSACTID", length = 50)
	public String getStockreconciliationtransactid() {
		return this.stockreconciliationtransactid;
	}

	public void setStockreconciliationtransactid(String stockreconciliationtransactid) {
		this.stockreconciliationtransactid = stockreconciliationtransactid;
	}

	@Column(name = "PROGRAMNAME", length = 10)
	public String getProgramname() {
		return this.programname;
	}

	public void setProgramname(String programname) {
		this.programname = programname;
	}

	@Column(name = "DAYENDRELEASEUSER", length = 10)
	public String getDayendreleaseuser() {
		return this.dayendreleaseuser;
	}

	public void setDayendreleaseuser(String dayendreleaseuser) {
		this.dayendreleaseuser = dayendreleaseuser;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CONSIDERED", length = 19)
	public Date getConsidered() {
		return this.considered;
	}

	public void setConsidered(Date considered) {
		this.considered = considered;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "IP_DAYENDJOBSPROCESSED", length = 19)
	public Date getIpDayendjobsprocessed() {
		return this.ipDayendjobsprocessed;
	}

	public void setIpDayendjobsprocessed(Date ipDayendjobsprocessed) {
		this.ipDayendjobsprocessed = ipDayendjobsprocessed;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "RECORDCREATIONTIME", nullable = false, length = 19)
	public Date getRecordcreationtime() {
		return this.recordcreationtime;
	}

	public void setRecordcreationtime(Date recordcreationtime) {
		this.recordcreationtime = recordcreationtime;
	}

}
