package com.galexis.alloga2mysql.model;

// Generated Mar 4, 2013 4:41:13 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Dayendext generated by hbm2java
 */
@Entity
@Table(name = "DAYENDEXT", uniqueConstraints = @UniqueConstraint(columnNames = { "DAYENDRELEASEDATE", "CONTRDEFPK", "PHASE" }))
public class Dayendext implements java.io.Serializable {

	private long pk;

	private int dayendreleasedate;

	private Long contrdefpk;

	private String phase;

	private Date validfrom;

	private Date validto;

	private Date considered;

	private Date recordcreationtime;

	public Dayendext() {
	}

	public Dayendext(long pk, int dayendreleasedate, String phase, Date recordcreationtime) {
		this.pk = pk;
		this.dayendreleasedate = dayendreleasedate;
		this.phase = phase;
		this.recordcreationtime = recordcreationtime;
	}

	public Dayendext(long pk, int dayendreleasedate, Long contrdefpk, String phase, Date validfrom, Date validto, Date considered, Date recordcreationtime) {
		this.pk = pk;
		this.dayendreleasedate = dayendreleasedate;
		this.contrdefpk = contrdefpk;
		this.phase = phase;
		this.validfrom = validfrom;
		this.validto = validto;
		this.considered = considered;
		this.recordcreationtime = recordcreationtime;
	}

	@Id
	@Column(name = "PK", unique = true, nullable = false, precision = 12, scale = 0)
	public long getPk() {
		return this.pk;
	}

	public void setPk(long pk) {
		this.pk = pk;
	}

	@Column(name = "DAYENDRELEASEDATE", nullable = false, precision = 8, scale = 0)
	public int getDayendreleasedate() {
		return this.dayendreleasedate;
	}

	public void setDayendreleasedate(int dayendreleasedate) {
		this.dayendreleasedate = dayendreleasedate;
	}

	@Column(name = "CONTRDEFPK", precision = 12, scale = 0)
	public Long getContrdefpk() {
		return this.contrdefpk;
	}

	public void setContrdefpk(Long contrdefpk) {
		this.contrdefpk = contrdefpk;
	}

	@Column(name = "PHASE", nullable = false, length = 10)
	public String getPhase() {
		return this.phase;
	}

	public void setPhase(String phase) {
		this.phase = phase;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "VALIDFROM", length = 19)
	public Date getValidfrom() {
		return this.validfrom;
	}

	public void setValidfrom(Date validfrom) {
		this.validfrom = validfrom;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "VALIDTO", length = 19)
	public Date getValidto() {
		return this.validto;
	}

	public void setValidto(Date validto) {
		this.validto = validto;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CONSIDERED", length = 19)
	public Date getConsidered() {
		return this.considered;
	}

	public void setConsidered(Date considered) {
		this.considered = considered;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "RECORDCREATIONTIME", nullable = false, length = 19)
	public Date getRecordcreationtime() {
		return this.recordcreationtime;
	}

	public void setRecordcreationtime(Date recordcreationtime) {
		this.recordcreationtime = recordcreationtime;
	}

}
