package com.galexis.alloga2mysql.model;

// Generated Mar 4, 2013 4:41:13 PM by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Delconf generated by hbm2java
 */
@Entity
@Table(name = "DELCONF")
public class Delconf implements java.io.Serializable {

	private long pk;

	private String mandant;

	private String pvsshipmentno;

	private String confirmationdate;

	private String confirmationtime;

	private String signature;

	private String transactionid;

	private String recordprocessedflag;

	private Date recordprocessingtime;

	private Date creationtimestamp;

	@Id
	@Column(name = "PK", nullable = false, precision = 12, scale = 0)
	public long getPk() {
		return this.pk;
	}

	public void setPk(long pk) {
		this.pk = pk;
	}

	@Column(name = "MANDANT", nullable = false, length = 40)
	public String getMandant() {
		return this.mandant;
	}

	public void setMandant(String mandant) {
		this.mandant = mandant;
	}

	@Column(name = "PVSSHIPMENTNO", nullable = false, length = 40)
	public String getPvsshipmentno() {
		return this.pvsshipmentno;
	}

	public void setPvsshipmentno(String pvsshipmentno) {
		this.pvsshipmentno = pvsshipmentno;
	}

	@Column(name = "CONFIRMATIONDATE", nullable = false, length = 8)
	public String getConfirmationdate() {
		return this.confirmationdate;
	}

	public void setConfirmationdate(String confirmationdate) {
		this.confirmationdate = confirmationdate;
	}

	@Column(name = "CONFIRMATIONTIME", nullable = false, length = 6)
	public String getConfirmationtime() {
		return this.confirmationtime;
	}

	public void setConfirmationtime(String confirmationtime) {
		this.confirmationtime = confirmationtime;
	}

	@Column(name = "SIGNATURE", nullable = false, length = 40)
	public String getSignature() {
		return this.signature;
	}

	public void setSignature(String signature) {
		this.signature = signature;
	}

	@Column(name = "TRANSACTIONID", nullable = false, length = 50)
	public String getTransactionid() {
		return this.transactionid;
	}

	public void setTransactionid(String transactionid) {
		this.transactionid = transactionid;
	}

	@Column(name = "RECORDPROCESSEDFLAG", nullable = false, length = 1)
	public String getRecordprocessedflag() {
		return this.recordprocessedflag;
	}

	public void setRecordprocessedflag(String recordprocessedflag) {
		this.recordprocessedflag = recordprocessedflag;
	}

	@Column(name = "RECORDPROCESSINGTIME", nullable = false, length = 19)
	public Date getRecordprocessingtime() {
		return this.recordprocessingtime;
	}

	public void setRecordprocessingtime(Date recordprocessingtime) {
		this.recordprocessingtime = recordprocessingtime;
	}

	@Column(name = "CREATIONTIMESTAMP", nullable = false, length = 19)
	public Date getCreationtimestamp() {
		return this.creationtimestamp;
	}

	public void setCreationtimestamp(Date creationtimestamp) {
		this.creationtimestamp = creationtimestamp;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATIONTIMESTAMP", length = 19, updatable = false, insertable = false)
	public Date getRecordcreationtime() {
		return this.getCreationtimestamp();
	}

	public void setRecordcreationtime(Date recordcreationtime) {
		this.setCreationtimestamp(recordcreationtime);
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "RECORDPROCESSINGTIME", length = 19, updatable = false, insertable = false)
	public Date getRecordlastchangetime() {
		return this.getRecordprocessingtime();
	}

	public void setRecordlastchangetime(Date recordlastchangetime) {
		this.setRecordprocessingtime(recordlastchangetime);
	}

}
