package com.galexis.alloga2mysql.model;

// Generated Mar 4, 2013 4:41:13 PM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Grelinbtc generated by hbm2java
 */
@Entity
@Table(name = "GRELINBTC")
public class Grelinbtc implements java.io.Serializable {

	private long pk;

	private long grelinpk;

	private long grehdrpk;

	private short goodsreceptionlineseq;

	private String itemnrcontractor;

	private BigDecimal batchqty;

	private String batchid;

	private Date batchexpirydate;

	private String serialnr;

	private String batchidcontractor;

	private String whs;

	private String zone;

	private String location;

	private String stockstatus;

	private String qualitycontrolflag;

	private Integer ipWarehouse;

	private Integer ipLocationzone;

	private Integer ipStockcategory;

	private String ipMovementcode;

	private String ipMovementreason;

	private String ipDamagedgoods;

	private String filename;

	private String processingflag1;

	private String processingflag2;

	private String processingflag3;

	private String processingflag4;

	private String processingflag5;

	private String processingflag6;

	private String processingflag7;

	private String processingflag8;

	private String processingflag9;

	private String processingflag10;

	private String outboundignore;

	private Date recordlastchangetime;

	private Date recordcreationtime;

	public Grelinbtc() {
	}

	public Grelinbtc(long pk, long grelinpk, long grehdrpk, short goodsreceptionlineseq, String outboundignore, Date recordcreationtime) {
		this.pk = pk;
		this.grelinpk = grelinpk;
		this.grehdrpk = grehdrpk;
		this.goodsreceptionlineseq = goodsreceptionlineseq;
		this.outboundignore = outboundignore;
		this.recordcreationtime = recordcreationtime;
	}

	public Grelinbtc(long pk, long grelinpk, long grehdrpk, short goodsreceptionlineseq, String itemnrcontractor, BigDecimal batchqty, String batchid, Date batchexpirydate,
	        String serialnr, String batchidcontractor, String whs, String zone, String location, String stockstatus, String qualitycontrolflag, Integer ipWarehouse,
	        Integer ipLocationzone, Integer ipStockcategory, String ipMovementcode, String ipMovementreason, String ipDamagedgoods, String filename, String processingflag1,
	        String processingflag2, String processingflag3, String processingflag4, String processingflag5, String processingflag6, String processingflag7, String processingflag8,
	        String processingflag9, String processingflag10, String outboundignore, Date recordlastchangetime, Date recordcreationtime) {
		this.pk = pk;
		this.grelinpk = grelinpk;
		this.grehdrpk = grehdrpk;
		this.goodsreceptionlineseq = goodsreceptionlineseq;
		this.itemnrcontractor = itemnrcontractor;
		this.batchqty = batchqty;
		this.batchid = batchid;
		this.batchexpirydate = batchexpirydate;
		this.serialnr = serialnr;
		this.batchidcontractor = batchidcontractor;
		this.whs = whs;
		this.zone = zone;
		this.location = location;
		this.stockstatus = stockstatus;
		this.qualitycontrolflag = qualitycontrolflag;
		this.ipWarehouse = ipWarehouse;
		this.ipLocationzone = ipLocationzone;
		this.ipStockcategory = ipStockcategory;
		this.ipMovementcode = ipMovementcode;
		this.ipMovementreason = ipMovementreason;
		this.ipDamagedgoods = ipDamagedgoods;
		this.filename = filename;
		this.processingflag1 = processingflag1;
		this.processingflag2 = processingflag2;
		this.processingflag3 = processingflag3;
		this.processingflag4 = processingflag4;
		this.processingflag5 = processingflag5;
		this.processingflag6 = processingflag6;
		this.processingflag7 = processingflag7;
		this.processingflag8 = processingflag8;
		this.processingflag9 = processingflag9;
		this.processingflag10 = processingflag10;
		this.outboundignore = outboundignore;
		this.recordlastchangetime = recordlastchangetime;
		this.recordcreationtime = recordcreationtime;
	}

	@Id
	@Column(name = "PK", unique = true, nullable = false, precision = 12, scale = 0)
	public long getPk() {
		return this.pk;
	}

	public void setPk(long pk) {
		this.pk = pk;
	}

	@Column(name = "GRELINPK", nullable = false, precision = 12, scale = 0)
	public long getGrelinpk() {
		return this.grelinpk;
	}

	public void setGrelinpk(long grelinpk) {
		this.grelinpk = grelinpk;
	}

	@Column(name = "GREHDRPK", nullable = false, precision = 12, scale = 0)
	public long getGrehdrpk() {
		return this.grehdrpk;
	}

	public void setGrehdrpk(long grehdrpk) {
		this.grehdrpk = grehdrpk;
	}

	@Column(name = "GOODSRECEPTIONLINESEQ", nullable = false, precision = 3, scale = 0)
	public short getGoodsreceptionlineseq() {
		return this.goodsreceptionlineseq;
	}

	public void setGoodsreceptionlineseq(short goodsreceptionlineseq) {
		this.goodsreceptionlineseq = goodsreceptionlineseq;
	}

	@Column(name = "ITEMNRCONTRACTOR", length = 35)
	public String getItemnrcontractor() {
		return this.itemnrcontractor;
	}

	public void setItemnrcontractor(String itemnrcontractor) {
		this.itemnrcontractor = itemnrcontractor;
	}

	@Column(name = "BATCHQTY", precision = 15, scale = 3)
	public BigDecimal getBatchqty() {
		return this.batchqty;
	}

	public void setBatchqty(BigDecimal batchqty) {
		this.batchqty = batchqty;
	}

	@Column(name = "BATCHID", length = 20)
	public String getBatchid() {
		return this.batchid;
	}

	public void setBatchid(String batchid) {
		this.batchid = batchid;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "BATCHEXPIRYDATE", length = 19)
	public Date getBatchexpirydate() {
		return this.batchexpirydate;
	}

	public void setBatchexpirydate(Date batchexpirydate) {
		this.batchexpirydate = batchexpirydate;
	}

	@Column(name = "SERIALNR", length = 30)
	public String getSerialnr() {
		return this.serialnr;
	}

	public void setSerialnr(String serialnr) {
		this.serialnr = serialnr;
	}

	@Column(name = "BATCHIDCONTRACTOR", length = 20)
	public String getBatchidcontractor() {
		return this.batchidcontractor;
	}

	public void setBatchidcontractor(String batchidcontractor) {
		this.batchidcontractor = batchidcontractor;
	}

	@Column(name = "WHS", length = 10)
	public String getWhs() {
		return this.whs;
	}

	public void setWhs(String whs) {
		this.whs = whs;
	}

	@Column(name = "ZONE", length = 10)
	public String getZone() {
		return this.zone;
	}

	public void setZone(String zone) {
		this.zone = zone;
	}

	@Column(name = "LOCATION", length = 10)
	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	@Column(name = "STOCKSTATUS", length = 10)
	public String getStockstatus() {
		return this.stockstatus;
	}

	public void setStockstatus(String stockstatus) {
		this.stockstatus = stockstatus;
	}

	@Column(name = "QUALITYCONTROLFLAG", length = 1)
	public String getQualitycontrolflag() {
		return this.qualitycontrolflag;
	}

	public void setQualitycontrolflag(String qualitycontrolflag) {
		this.qualitycontrolflag = qualitycontrolflag;
	}

	@Column(name = "IP_WAREHOUSE", precision = 5, scale = 0)
	public Integer getIpWarehouse() {
		return this.ipWarehouse;
	}

	public void setIpWarehouse(Integer ipWarehouse) {
		this.ipWarehouse = ipWarehouse;
	}

	@Column(name = "IP_LOCATIONZONE", precision = 5, scale = 0)
	public Integer getIpLocationzone() {
		return this.ipLocationzone;
	}

	public void setIpLocationzone(Integer ipLocationzone) {
		this.ipLocationzone = ipLocationzone;
	}

	@Column(name = "IP_STOCKCATEGORY", precision = 5, scale = 0)
	public Integer getIpStockcategory() {
		return this.ipStockcategory;
	}

	public void setIpStockcategory(Integer ipStockcategory) {
		this.ipStockcategory = ipStockcategory;
	}

	@Column(name = "IP_MOVEMENTCODE", length = 20)
	public String getIpMovementcode() {
		return this.ipMovementcode;
	}

	public void setIpMovementcode(String ipMovementcode) {
		this.ipMovementcode = ipMovementcode;
	}

	@Column(name = "IP_MOVEMENTREASON", length = 20)
	public String getIpMovementreason() {
		return this.ipMovementreason;
	}

	public void setIpMovementreason(String ipMovementreason) {
		this.ipMovementreason = ipMovementreason;
	}

	@Column(name = "IP_DAMAGEDGOODS", length = 1)
	public String getIpDamagedgoods() {
		return this.ipDamagedgoods;
	}

	public void setIpDamagedgoods(String ipDamagedgoods) {
		this.ipDamagedgoods = ipDamagedgoods;
	}

	@Column(name = "FILENAME", length = 10)
	public String getFilename() {
		return this.filename;
	}

	public void setFilename(String filename) {
		this.filename = filename;
	}

	@Column(name = "PROCESSINGFLAG1", length = 1)
	public String getProcessingflag1() {
		return this.processingflag1;
	}

	public void setProcessingflag1(String processingflag1) {
		this.processingflag1 = processingflag1;
	}

	@Column(name = "PROCESSINGFLAG2", length = 1)
	public String getProcessingflag2() {
		return this.processingflag2;
	}

	public void setProcessingflag2(String processingflag2) {
		this.processingflag2 = processingflag2;
	}

	@Column(name = "PROCESSINGFLAG3", length = 1)
	public String getProcessingflag3() {
		return this.processingflag3;
	}

	public void setProcessingflag3(String processingflag3) {
		this.processingflag3 = processingflag3;
	}

	@Column(name = "PROCESSINGFLAG4", length = 1)
	public String getProcessingflag4() {
		return this.processingflag4;
	}

	public void setProcessingflag4(String processingflag4) {
		this.processingflag4 = processingflag4;
	}

	@Column(name = "PROCESSINGFLAG5", length = 1)
	public String getProcessingflag5() {
		return this.processingflag5;
	}

	public void setProcessingflag5(String processingflag5) {
		this.processingflag5 = processingflag5;
	}

	@Column(name = "PROCESSINGFLAG6", length = 1)
	public String getProcessingflag6() {
		return this.processingflag6;
	}

	public void setProcessingflag6(String processingflag6) {
		this.processingflag6 = processingflag6;
	}

	@Column(name = "PROCESSINGFLAG7", length = 1)
	public String getProcessingflag7() {
		return this.processingflag7;
	}

	public void setProcessingflag7(String processingflag7) {
		this.processingflag7 = processingflag7;
	}

	@Column(name = "PROCESSINGFLAG8", length = 1)
	public String getProcessingflag8() {
		return this.processingflag8;
	}

	public void setProcessingflag8(String processingflag8) {
		this.processingflag8 = processingflag8;
	}

	@Column(name = "PROCESSINGFLAG9", length = 1)
	public String getProcessingflag9() {
		return this.processingflag9;
	}

	public void setProcessingflag9(String processingflag9) {
		this.processingflag9 = processingflag9;
	}

	@Column(name = "PROCESSINGFLAG10", length = 1)
	public String getProcessingflag10() {
		return this.processingflag10;
	}

	public void setProcessingflag10(String processingflag10) {
		this.processingflag10 = processingflag10;
	}

	@Column(name = "OUTBOUNDIGNORE", nullable = false, length = 1)
	public String getOutboundignore() {
		return this.outboundignore;
	}

	public void setOutboundignore(String outboundignore) {
		this.outboundignore = outboundignore;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "RECORDLASTCHANGETIME", length = 19)
	public Date getRecordlastchangetime() {
		return this.recordlastchangetime;
	}

	public void setRecordlastchangetime(Date recordlastchangetime) {
		this.recordlastchangetime = recordlastchangetime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "RECORDCREATIONTIME", nullable = false, length = 19)
	public Date getRecordcreationtime() {
		return this.recordcreationtime;
	}

	public void setRecordcreationtime(Date recordcreationtime) {
		this.recordcreationtime = recordcreationtime;
	}

}
