package com.galexis.alloga2mysql.model;

// Generated Mar 4, 2013 4:41:13 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Identnrf generated by hbm2java
 */
@Entity
@Table(name = "IDENTNRF", uniqueConstraints = @UniqueConstraint(columnNames = "FILENAME"))
public class Identnrf implements java.io.Serializable {

	private long pk;

	private String filename;

	private long lastidentifier;

	private Date recordlastchangetime;

	public Identnrf() {
	}

	public Identnrf(long pk, String filename, long lastidentifier, Date recordlastchangetime) {
		this.pk = pk;
		this.filename = filename;
		this.lastidentifier = lastidentifier;
		this.recordlastchangetime = recordlastchangetime;
	}

	@Id
	@Column(name = "PK", unique = true, nullable = false, precision = 12, scale = 0)
	public long getPk() {
		return this.pk;
	}

	public void setPk(long pk) {
		this.pk = pk;
	}

	@Column(name = "FILENAME", unique = true, nullable = false, length = 50)
	public String getFilename() {
		return this.filename;
	}

	public void setFilename(String filename) {
		this.filename = filename;
	}

	@Column(name = "LASTIDENTIFIER", nullable = false, precision = 12, scale = 0)
	public long getLastidentifier() {
		return this.lastidentifier;
	}

	public void setLastidentifier(long lastidentifier) {
		this.lastidentifier = lastidentifier;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "RECORDLASTCHANGETIME", nullable = false, length = 19)
	public Date getRecordlastchangetime() {
		return this.recordlastchangetime;
	}

	public void setRecordlastchangetime(Date recordlastchangetime) {
		this.recordlastchangetime = recordlastchangetime;
	}

}
