package com.galexis.alloga2mysql.model;

// Generated Mar 4, 2013 4:41:13 PM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Invlinbtc generated by hbm2java
 */
@Entity
@Table(name = "INVLINBTC")
public class Invlinbtc implements java.io.Serializable {

	private long pk;

	private long invlinpk;

	private long invhdrpk;

	private short invoicelineseq;

	private Long dellinbtcpk;

	private Integer contractordeliverylinenr;

	private String itemnrcontractor;

	private BigDecimal batchqty;

	private BigDecimal naturaldiscountqty;

	private String batchid;

	private Date batchexpirydate;

	private String batchidcontractor;

	private String serialnr;

	private BigDecimal calculatedsalesamount;

	private BigDecimal calcualtednetsalesvalue;

	private BigDecimal rounddiffsalesamount;

	private BigDecimal rounddiffnetsalesvalue;

	private String programname;

	private String filename;

	private String processingflag1;

	private String processingflag2;

	private String processingflag3;

	private String processingflag4;

	private String processingflag5;

	private String processingflag6;

	private String processingflag7;

	private String processingflag8;

	private String processingflag9;

	private String processingflag10;

	private String outboundignore;

	private Date recordlastchangetime;

	private Date recordcreationtime;

	public Invlinbtc() {
	}

	public Invlinbtc(long pk, long invlinpk, long invhdrpk, short invoicelineseq, String outboundignore, Date recordcreationtime) {
		this.pk = pk;
		this.invlinpk = invlinpk;
		this.invhdrpk = invhdrpk;
		this.invoicelineseq = invoicelineseq;
		this.outboundignore = outboundignore;
		this.recordcreationtime = recordcreationtime;
	}

	public Invlinbtc(long pk, long invlinpk, long invhdrpk, short invoicelineseq, Long dellinbtcpk, Integer contractordeliverylinenr, String itemnrcontractor, BigDecimal batchqty,
	        BigDecimal naturaldiscountqty, String batchid, Date batchexpirydate, String batchidcontractor, String serialnr, BigDecimal calculatedsalesamount,
	        BigDecimal calcualtednetsalesvalue, BigDecimal rounddiffsalesamount, BigDecimal rounddiffnetsalesvalue, String programname, String filename, String processingflag1,
	        String processingflag2, String processingflag3, String processingflag4, String processingflag5, String processingflag6, String processingflag7, String processingflag8,
	        String processingflag9, String processingflag10, String outboundignore, Date recordlastchangetime, Date recordcreationtime) {
		this.pk = pk;
		this.invlinpk = invlinpk;
		this.invhdrpk = invhdrpk;
		this.invoicelineseq = invoicelineseq;
		this.dellinbtcpk = dellinbtcpk;
		this.contractordeliverylinenr = contractordeliverylinenr;
		this.itemnrcontractor = itemnrcontractor;
		this.batchqty = batchqty;
		this.naturaldiscountqty = naturaldiscountqty;
		this.batchid = batchid;
		this.batchexpirydate = batchexpirydate;
		this.batchidcontractor = batchidcontractor;
		this.serialnr = serialnr;
		this.calculatedsalesamount = calculatedsalesamount;
		this.calcualtednetsalesvalue = calcualtednetsalesvalue;
		this.rounddiffsalesamount = rounddiffsalesamount;
		this.rounddiffnetsalesvalue = rounddiffnetsalesvalue;
		this.programname = programname;
		this.filename = filename;
		this.processingflag1 = processingflag1;
		this.processingflag2 = processingflag2;
		this.processingflag3 = processingflag3;
		this.processingflag4 = processingflag4;
		this.processingflag5 = processingflag5;
		this.processingflag6 = processingflag6;
		this.processingflag7 = processingflag7;
		this.processingflag8 = processingflag8;
		this.processingflag9 = processingflag9;
		this.processingflag10 = processingflag10;
		this.outboundignore = outboundignore;
		this.recordlastchangetime = recordlastchangetime;
		this.recordcreationtime = recordcreationtime;
	}

	@Id
	@Column(name = "PK", unique = true, nullable = false, precision = 12, scale = 0)
	public long getPk() {
		return this.pk;
	}

	public void setPk(long pk) {
		this.pk = pk;
	}

	@Column(name = "INVLINPK", nullable = false, precision = 12, scale = 0)
	public long getInvlinpk() {
		return this.invlinpk;
	}

	public void setInvlinpk(long invlinpk) {
		this.invlinpk = invlinpk;
	}

	@Column(name = "INVHDRPK", nullable = false, precision = 12, scale = 0)
	public long getInvhdrpk() {
		return this.invhdrpk;
	}

	public void setInvhdrpk(long invhdrpk) {
		this.invhdrpk = invhdrpk;
	}

	@Column(name = "INVOICELINESEQ", nullable = false, precision = 3, scale = 0)
	public short getInvoicelineseq() {
		return this.invoicelineseq;
	}

	public void setInvoicelineseq(short invoicelineseq) {
		this.invoicelineseq = invoicelineseq;
	}

	@Column(name = "DELLINBTCPK", precision = 12, scale = 0)
	public Long getDellinbtcpk() {
		return this.dellinbtcpk;
	}

	public void setDellinbtcpk(Long dellinbtcpk) {
		this.dellinbtcpk = dellinbtcpk;
	}

	@Column(name = "CONTRACTORDELIVERYLINENR", precision = 6, scale = 0)
	public Integer getContractordeliverylinenr() {
		return this.contractordeliverylinenr;
	}

	public void setContractordeliverylinenr(Integer contractordeliverylinenr) {
		this.contractordeliverylinenr = contractordeliverylinenr;
	}

	@Column(name = "ITEMNRCONTRACTOR", length = 35)
	public String getItemnrcontractor() {
		return this.itemnrcontractor;
	}

	public void setItemnrcontractor(String itemnrcontractor) {
		this.itemnrcontractor = itemnrcontractor;
	}

	@Column(name = "BATCHQTY", precision = 15, scale = 3)
	public BigDecimal getBatchqty() {
		return this.batchqty;
	}

	public void setBatchqty(BigDecimal batchqty) {
		this.batchqty = batchqty;
	}

	@Column(name = "NATURALDISCOUNTQTY", precision = 15, scale = 3)
	public BigDecimal getNaturaldiscountqty() {
		return this.naturaldiscountqty;
	}

	public void setNaturaldiscountqty(BigDecimal naturaldiscountqty) {
		this.naturaldiscountqty = naturaldiscountqty;
	}

	@Column(name = "BATCHID", length = 20)
	public String getBatchid() {
		return this.batchid;
	}

	public void setBatchid(String batchid) {
		this.batchid = batchid;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "BATCHEXPIRYDATE", length = 19)
	public Date getBatchexpirydate() {
		return this.batchexpirydate;
	}

	public void setBatchexpirydate(Date batchexpirydate) {
		this.batchexpirydate = batchexpirydate;
	}

	@Column(name = "BATCHIDCONTRACTOR", length = 20)
	public String getBatchidcontractor() {
		return this.batchidcontractor;
	}

	public void setBatchidcontractor(String batchidcontractor) {
		this.batchidcontractor = batchidcontractor;
	}

	@Column(name = "SERIALNR", length = 30)
	public String getSerialnr() {
		return this.serialnr;
	}

	public void setSerialnr(String serialnr) {
		this.serialnr = serialnr;
	}

	@Column(name = "CALCULATEDSALESAMOUNT", precision = 17, scale = 4)
	public BigDecimal getCalculatedsalesamount() {
		return this.calculatedsalesamount;
	}

	public void setCalculatedsalesamount(BigDecimal calculatedsalesamount) {
		this.calculatedsalesamount = calculatedsalesamount;
	}

	@Column(name = "CALCUALTEDNETSALESVALUE", precision = 17, scale = 4)
	public BigDecimal getCalcualtednetsalesvalue() {
		return this.calcualtednetsalesvalue;
	}

	public void setCalcualtednetsalesvalue(BigDecimal calcualtednetsalesvalue) {
		this.calcualtednetsalesvalue = calcualtednetsalesvalue;
	}

	@Column(name = "ROUNDDIFFSALESAMOUNT", precision = 17, scale = 4)
	public BigDecimal getRounddiffsalesamount() {
		return this.rounddiffsalesamount;
	}

	public void setRounddiffsalesamount(BigDecimal rounddiffsalesamount) {
		this.rounddiffsalesamount = rounddiffsalesamount;
	}

	@Column(name = "ROUNDDIFFNETSALESVALUE", precision = 17, scale = 4)
	public BigDecimal getRounddiffnetsalesvalue() {
		return this.rounddiffnetsalesvalue;
	}

	public void setRounddiffnetsalesvalue(BigDecimal rounddiffnetsalesvalue) {
		this.rounddiffnetsalesvalue = rounddiffnetsalesvalue;
	}

	@Column(name = "PROGRAMNAME", length = 10)
	public String getProgramname() {
		return this.programname;
	}

	public void setProgramname(String programname) {
		this.programname = programname;
	}

	@Column(name = "FILENAME", length = 10)
	public String getFilename() {
		return this.filename;
	}

	public void setFilename(String filename) {
		this.filename = filename;
	}

	@Column(name = "PROCESSINGFLAG1", length = 1)
	public String getProcessingflag1() {
		return this.processingflag1;
	}

	public void setProcessingflag1(String processingflag1) {
		this.processingflag1 = processingflag1;
	}

	@Column(name = "PROCESSINGFLAG2", length = 1)
	public String getProcessingflag2() {
		return this.processingflag2;
	}

	public void setProcessingflag2(String processingflag2) {
		this.processingflag2 = processingflag2;
	}

	@Column(name = "PROCESSINGFLAG3", length = 1)
	public String getProcessingflag3() {
		return this.processingflag3;
	}

	public void setProcessingflag3(String processingflag3) {
		this.processingflag3 = processingflag3;
	}

	@Column(name = "PROCESSINGFLAG4", length = 1)
	public String getProcessingflag4() {
		return this.processingflag4;
	}

	public void setProcessingflag4(String processingflag4) {
		this.processingflag4 = processingflag4;
	}

	@Column(name = "PROCESSINGFLAG5", length = 1)
	public String getProcessingflag5() {
		return this.processingflag5;
	}

	public void setProcessingflag5(String processingflag5) {
		this.processingflag5 = processingflag5;
	}

	@Column(name = "PROCESSINGFLAG6", length = 1)
	public String getProcessingflag6() {
		return this.processingflag6;
	}

	public void setProcessingflag6(String processingflag6) {
		this.processingflag6 = processingflag6;
	}

	@Column(name = "PROCESSINGFLAG7", length = 1)
	public String getProcessingflag7() {
		return this.processingflag7;
	}

	public void setProcessingflag7(String processingflag7) {
		this.processingflag7 = processingflag7;
	}

	@Column(name = "PROCESSINGFLAG8", length = 1)
	public String getProcessingflag8() {
		return this.processingflag8;
	}

	public void setProcessingflag8(String processingflag8) {
		this.processingflag8 = processingflag8;
	}

	@Column(name = "PROCESSINGFLAG9", length = 1)
	public String getProcessingflag9() {
		return this.processingflag9;
	}

	public void setProcessingflag9(String processingflag9) {
		this.processingflag9 = processingflag9;
	}

	@Column(name = "PROCESSINGFLAG10", length = 1)
	public String getProcessingflag10() {
		return this.processingflag10;
	}

	public void setProcessingflag10(String processingflag10) {
		this.processingflag10 = processingflag10;
	}

	@Column(name = "OUTBOUNDIGNORE", nullable = false, length = 1)
	public String getOutboundignore() {
		return this.outboundignore;
	}

	public void setOutboundignore(String outboundignore) {
		this.outboundignore = outboundignore;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "RECORDLASTCHANGETIME", length = 19)
	public Date getRecordlastchangetime() {
		return this.recordlastchangetime;
	}

	public void setRecordlastchangetime(Date recordlastchangetime) {
		this.recordlastchangetime = recordlastchangetime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "RECORDCREATIONTIME", nullable = false, length = 19)
	public Date getRecordcreationtime() {
		return this.recordcreationtime;
	}

	public void setRecordcreationtime(Date recordcreationtime) {
		this.recordcreationtime = recordcreationtime;
	}

}
