package com.galexis.alloga2mysql.model;

// Generated Mar 4, 2013 4:41:13 PM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Invmovmnt generated by hbm2java
 */
@Entity
@Table(name = "INVMOVMNT")
public class Invmovmnt implements java.io.Serializable {

	private long pk;

	private long contrdefpk;

	private long transnr;

	private short transseq;

	private Date transdate;

	private String transbookperiod;

	private String recordtype;

	private Integer transtype;

	private String transtypetext;

	private String eventcode;

	private String eventcodetext;

	private Long itemmasterpk;

	private String itemnr;

	private String itemnrcontractor;

	private String salesorganisation;

	private String batchid;

	private Date batchsellbydate;

	private Date batchexpirydate;

	private String batchidcontractor;

	private String batchreasoncode;

	private String serialnr;

	private String fromwhs;

	private String fromzone;

	private String fromlocation;

	private String fromstockstatus;

	private String towhs;

	private String tozone;

	private String tolocation;

	private String tostockstatus;

	private String fromqcflag;

	private String toqcflag;

	private String bulkflagfrom;

	private String bulkflagto;

	private BigDecimal frompalletid;

	private BigDecimal topalletid;

	private Long nccnr;

	private String internalproblemcode;

	private BigDecimal transqty;

	private String stockkeepingunit;

	private String reasoncode;

	private String reasoncodedesc;

	private String reasoncodeNcc;

	private String reasoncodedescNcc;

	private String transtext;

	private String referencetext;

	private String contractorreference;

	private BigDecimal standardcost;

	private BigDecimal transvalue;

	private Long itrtransnr;

	private Long suggestionnr;

	private Integer suggestionline;

	private Integer suggestionsubline;

	private Long salesordernr;

	private Integer salesorderline;

	private String salesordertype;

	private Long dellinbtcpk;

	private Long purchaseordernr;

	private Integer purchaseorderline;

	private String purchaseordertype;

	private Long grelinbtcpk;

	private Long orderreferencenr;

	private Integer orderreferenceline;

	private Long incidentnr;

	private Integer incidentline;

	private Long salesorderpicklistnr;

	private Integer salesorderpicklistline;

	private Long salesorderpickconsolidationnr;

	private Long salesordershipmentnr;

	private Long pogoodsreceptionnote;

	private Integer pogoodsreceptionnoteline;

	private String transitdeliveryflag;

	private String freeofchargeflag;

	private String freeofchargereasoncode;

	private String orderSourceCode;

	private String deliveryannouncementnr;

	private Integer deliveryannouncementline;

	private String usertransstarted;

	private String usertranscompleted;

	private Date timetransstarted;

	private Date timetranscompleted;

	private String fromreportingkey;

	private String toreportingkey;

	private String fromreportingstockstatus;

	private String toreportingstockstatus;

	private Long stocktakelistnr;

	private Integer stocktakelistline;

	private Integer rfbatchid;

	private Long rfinstructionnr;

	private String freetext;

	private Integer ipTranstype;

	private Integer ipEventcode;

	private Integer ipFromwarehouse;

	private Integer ipTowarehouse;

	private Integer ipFromlocationzone;

	private Integer ipTolocationzone;

	private Integer ipFromstockcategory;

	private Integer ipTostockcategory;

	private Integer ipPurchaseordertype;

	private Integer ipSalesordertype;

	private Integer ipInvoicetype;

	private String ipIsfreeofcharge;

	private Integer ipFreeofchargereasoncode;

	private String ipTransclas1;

	private String ipTransclas2;

	private String ipTransclas3;

	private String ipIsdebit;

	private String ipIssaleswithmovement;

	private String ipIsstockrelevant;

	private String ipMovementcode;

	private String ipMovementreason;

	private String ipPlantfrom;

	private String ipPlantto;

	private String ipStoragelocationfrom;

	private String ipStoragelocationto;

	private String ipStockstatusfrom;

	private String ipStockstatusto;

	private Integer timedatepk;

	private Integer ipTimedatepkReporting;

	private String programname;

	private String filename;

	private String processingflag1;

	private String processingflag2;

	private String processingflag3;

	private String processingflag4;

	private String processingflag5;

	private String processingflag6;

	private String processingflag7;

	private String processingflag8;

	private String processingflag9;

	private String processingflag10;

	private String backendreleased;

	private String outboundignore;

	private String transactionid;

	private String recordprocessedflag;

	private Date recordprocessingtime;

	private Date recordlastchangetime;

	private Date recordcreationtime;

	public Invmovmnt() {
	}

	public Invmovmnt(long pk, long contrdefpk, long transnr, short transseq, Date transdate, String backendreleased, String outboundignore, String recordprocessedflag,
	        Date recordcreationtime) {
		this.pk = pk;
		this.contrdefpk = contrdefpk;
		this.transnr = transnr;
		this.transseq = transseq;
		this.transdate = transdate;
		this.backendreleased = backendreleased;
		this.outboundignore = outboundignore;
		this.recordprocessedflag = recordprocessedflag;
		this.recordcreationtime = recordcreationtime;
	}

	public Invmovmnt(long pk, long contrdefpk, long transnr, short transseq, Date transdate, String transbookperiod, String recordtype, Integer transtype, String transtypetext,
	        String eventcode, String eventcodetext, Long itemmasterpk, String itemnr, String itemnrcontractor, String salesorganisation, String batchid, Date batchsellbydate,
	        Date batchexpirydate, String batchidcontractor, String batchreasoncode, String serialnr, String fromwhs, String fromzone, String fromlocation, String fromstockstatus,
	        String towhs, String tozone, String tolocation, String tostockstatus, String fromqcflag, String toqcflag, String bulkflagfrom, String bulkflagto,
	        BigDecimal frompalletid, BigDecimal topalletid, Long nccnr, String internalproblemcode, BigDecimal transqty, String stockkeepingunit, String reasoncode,
	        String reasoncodedesc, String reasoncodeNcc, String reasoncodedescNcc, String transtext, String referencetext, String contractorreference, BigDecimal standardcost,
	        BigDecimal transvalue, Long itrtransnr, Long suggestionnr, Integer suggestionline, Integer suggestionsubline, Long salesordernr, Integer salesorderline,
	        String salesordertype, Long dellinbtcpk, Long purchaseordernr, Integer purchaseorderline, String purchaseordertype, Long grelinbtcpk, Long orderreferencenr,
	        Integer orderreferenceline, Long incidentnr, Integer incidentline, Long salesorderpicklistnr, Integer salesorderpicklistline, Long salesorderpickconsolidationnr,
	        Long salesordershipmentnr, Long pogoodsreceptionnote, Integer pogoodsreceptionnoteline, String transitdeliveryflag, String freeofchargeflag,
	        String freeofchargereasoncode, String orderSourceCode, String deliveryannouncementnr, Integer deliveryannouncementline, String usertransstarted,
	        String usertranscompleted, Date timetransstarted, Date timetranscompleted, String fromreportingkey, String toreportingkey, String fromreportingstockstatus,
	        String toreportingstockstatus, Long stocktakelistnr, Integer stocktakelistline, Integer rfbatchid, Long rfinstructionnr, String freetext, Integer ipTranstype,
	        Integer ipEventcode, Integer ipFromwarehouse, Integer ipTowarehouse, Integer ipFromlocationzone, Integer ipTolocationzone, Integer ipFromstockcategory,
	        Integer ipTostockcategory, Integer ipPurchaseordertype, Integer ipSalesordertype, Integer ipInvoicetype, String ipIsfreeofcharge, Integer ipFreeofchargereasoncode,
	        String ipTransclas1, String ipTransclas2, String ipTransclas3, String ipIsdebit, String ipIssaleswithmovement, String ipIsstockrelevant, String ipMovementcode,
	        String ipMovementreason, String ipPlantfrom, String ipPlantto, String ipStoragelocationfrom, String ipStoragelocationto, String ipStockstatusfrom,
	        String ipStockstatusto, Integer timedatepk, Integer ipTimedatepkReporting, String programname, String filename, String processingflag1, String processingflag2,
	        String processingflag3, String processingflag4, String processingflag5, String processingflag6, String processingflag7, String processingflag8, String processingflag9,
	        String processingflag10, String backendreleased, String outboundignore, String transactionid, String recordprocessedflag, Date recordprocessingtime,
	        Date recordlastchangetime, Date recordcreationtime) {
		this.pk = pk;
		this.contrdefpk = contrdefpk;
		this.transnr = transnr;
		this.transseq = transseq;
		this.transdate = transdate;
		this.transbookperiod = transbookperiod;
		this.recordtype = recordtype;
		this.transtype = transtype;
		this.transtypetext = transtypetext;
		this.eventcode = eventcode;
		this.eventcodetext = eventcodetext;
		this.itemmasterpk = itemmasterpk;
		this.itemnr = itemnr;
		this.itemnrcontractor = itemnrcontractor;
		this.salesorganisation = salesorganisation;
		this.batchid = batchid;
		this.batchsellbydate = batchsellbydate;
		this.batchexpirydate = batchexpirydate;
		this.batchidcontractor = batchidcontractor;
		this.batchreasoncode = batchreasoncode;
		this.serialnr = serialnr;
		this.fromwhs = fromwhs;
		this.fromzone = fromzone;
		this.fromlocation = fromlocation;
		this.fromstockstatus = fromstockstatus;
		this.towhs = towhs;
		this.tozone = tozone;
		this.tolocation = tolocation;
		this.tostockstatus = tostockstatus;
		this.fromqcflag = fromqcflag;
		this.toqcflag = toqcflag;
		this.bulkflagfrom = bulkflagfrom;
		this.bulkflagto = bulkflagto;
		this.frompalletid = frompalletid;
		this.topalletid = topalletid;
		this.nccnr = nccnr;
		this.internalproblemcode = internalproblemcode;
		this.transqty = transqty;
		this.stockkeepingunit = stockkeepingunit;
		this.reasoncode = reasoncode;
		this.reasoncodedesc = reasoncodedesc;
		this.reasoncodeNcc = reasoncodeNcc;
		this.reasoncodedescNcc = reasoncodedescNcc;
		this.transtext = transtext;
		this.referencetext = referencetext;
		this.contractorreference = contractorreference;
		this.standardcost = standardcost;
		this.transvalue = transvalue;
		this.itrtransnr = itrtransnr;
		this.suggestionnr = suggestionnr;
		this.suggestionline = suggestionline;
		this.suggestionsubline = suggestionsubline;
		this.salesordernr = salesordernr;
		this.salesorderline = salesorderline;
		this.salesordertype = salesordertype;
		this.dellinbtcpk = dellinbtcpk;
		this.purchaseordernr = purchaseordernr;
		this.purchaseorderline = purchaseorderline;
		this.purchaseordertype = purchaseordertype;
		this.grelinbtcpk = grelinbtcpk;
		this.orderreferencenr = orderreferencenr;
		this.orderreferenceline = orderreferenceline;
		this.incidentnr = incidentnr;
		this.incidentline = incidentline;
		this.salesorderpicklistnr = salesorderpicklistnr;
		this.salesorderpicklistline = salesorderpicklistline;
		this.salesorderpickconsolidationnr = salesorderpickconsolidationnr;
		this.salesordershipmentnr = salesordershipmentnr;
		this.pogoodsreceptionnote = pogoodsreceptionnote;
		this.pogoodsreceptionnoteline = pogoodsreceptionnoteline;
		this.transitdeliveryflag = transitdeliveryflag;
		this.freeofchargeflag = freeofchargeflag;
		this.freeofchargereasoncode = freeofchargereasoncode;
		this.orderSourceCode = orderSourceCode;
		this.deliveryannouncementnr = deliveryannouncementnr;
		this.deliveryannouncementline = deliveryannouncementline;
		this.usertransstarted = usertransstarted;
		this.usertranscompleted = usertranscompleted;
		this.timetransstarted = timetransstarted;
		this.timetranscompleted = timetranscompleted;
		this.fromreportingkey = fromreportingkey;
		this.toreportingkey = toreportingkey;
		this.fromreportingstockstatus = fromreportingstockstatus;
		this.toreportingstockstatus = toreportingstockstatus;
		this.stocktakelistnr = stocktakelistnr;
		this.stocktakelistline = stocktakelistline;
		this.rfbatchid = rfbatchid;
		this.rfinstructionnr = rfinstructionnr;
		this.freetext = freetext;
		this.ipTranstype = ipTranstype;
		this.ipEventcode = ipEventcode;
		this.ipFromwarehouse = ipFromwarehouse;
		this.ipTowarehouse = ipTowarehouse;
		this.ipFromlocationzone = ipFromlocationzone;
		this.ipTolocationzone = ipTolocationzone;
		this.ipFromstockcategory = ipFromstockcategory;
		this.ipTostockcategory = ipTostockcategory;
		this.ipPurchaseordertype = ipPurchaseordertype;
		this.ipSalesordertype = ipSalesordertype;
		this.ipInvoicetype = ipInvoicetype;
		this.ipIsfreeofcharge = ipIsfreeofcharge;
		this.ipFreeofchargereasoncode = ipFreeofchargereasoncode;
		this.ipTransclas1 = ipTransclas1;
		this.ipTransclas2 = ipTransclas2;
		this.ipTransclas3 = ipTransclas3;
		this.ipIsdebit = ipIsdebit;
		this.ipIssaleswithmovement = ipIssaleswithmovement;
		this.ipIsstockrelevant = ipIsstockrelevant;
		this.ipMovementcode = ipMovementcode;
		this.ipMovementreason = ipMovementreason;
		this.ipPlantfrom = ipPlantfrom;
		this.ipPlantto = ipPlantto;
		this.ipStoragelocationfrom = ipStoragelocationfrom;
		this.ipStoragelocationto = ipStoragelocationto;
		this.ipStockstatusfrom = ipStockstatusfrom;
		this.ipStockstatusto = ipStockstatusto;
		this.timedatepk = timedatepk;
		this.ipTimedatepkReporting = ipTimedatepkReporting;
		this.programname = programname;
		this.filename = filename;
		this.processingflag1 = processingflag1;
		this.processingflag2 = processingflag2;
		this.processingflag3 = processingflag3;
		this.processingflag4 = processingflag4;
		this.processingflag5 = processingflag5;
		this.processingflag6 = processingflag6;
		this.processingflag7 = processingflag7;
		this.processingflag8 = processingflag8;
		this.processingflag9 = processingflag9;
		this.processingflag10 = processingflag10;
		this.backendreleased = backendreleased;
		this.outboundignore = outboundignore;
		this.transactionid = transactionid;
		this.recordprocessedflag = recordprocessedflag;
		this.recordprocessingtime = recordprocessingtime;
		this.recordlastchangetime = recordlastchangetime;
		this.recordcreationtime = recordcreationtime;
	}

	@Id
	@Column(name = "PK", unique = true, nullable = false, precision = 12, scale = 0)
	public long getPk() {
		return this.pk;
	}

	public void setPk(long pk) {
		this.pk = pk;
	}

	@Column(name = "CONTRDEFPK", nullable = false, precision = 12, scale = 0)
	public long getContrdefpk() {
		return this.contrdefpk;
	}

	public void setContrdefpk(long contrdefpk) {
		this.contrdefpk = contrdefpk;
	}

	@Column(name = "TRANSNR", nullable = false, precision = 12, scale = 0)
	public long getTransnr() {
		return this.transnr;
	}

	public void setTransnr(long transnr) {
		this.transnr = transnr;
	}

	@Column(name = "TRANSSEQ", nullable = false, precision = 3, scale = 0)
	public short getTransseq() {
		return this.transseq;
	}

	public void setTransseq(short transseq) {
		this.transseq = transseq;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "TRANSDATE", nullable = false, length = 19)
	public Date getTransdate() {
		return this.transdate;
	}

	public void setTransdate(Date transdate) {
		this.transdate = transdate;
	}

	@Column(name = "TRANSBOOKPERIOD", length = 20)
	public String getTransbookperiod() {
		return this.transbookperiod;
	}

	public void setTransbookperiod(String transbookperiod) {
		this.transbookperiod = transbookperiod;
	}

	@Column(name = "RECORDTYPE", length = 30)
	public String getRecordtype() {
		return this.recordtype;
	}

	public void setRecordtype(String recordtype) {
		this.recordtype = recordtype;
	}

	@Column(name = "TRANSTYPE", precision = 5, scale = 0)
	public Integer getTranstype() {
		return this.transtype;
	}

	public void setTranstype(Integer transtype) {
		this.transtype = transtype;
	}

	@Column(name = "TRANSTYPETEXT", length = 50)
	public String getTranstypetext() {
		return this.transtypetext;
	}

	public void setTranstypetext(String transtypetext) {
		this.transtypetext = transtypetext;
	}

	@Column(name = "EVENTCODE", length = 4)
	public String getEventcode() {
		return this.eventcode;
	}

	public void setEventcode(String eventcode) {
		this.eventcode = eventcode;
	}

	@Column(name = "EVENTCODETEXT", length = 50)
	public String getEventcodetext() {
		return this.eventcodetext;
	}

	public void setEventcodetext(String eventcodetext) {
		this.eventcodetext = eventcodetext;
	}

	@Column(name = "ITEMMASTERPK", precision = 12, scale = 0)
	public Long getItemmasterpk() {
		return this.itemmasterpk;
	}

	public void setItemmasterpk(Long itemmasterpk) {
		this.itemmasterpk = itemmasterpk;
	}

	@Column(name = "ITEMNR", length = 35)
	public String getItemnr() {
		return this.itemnr;
	}

	public void setItemnr(String itemnr) {
		this.itemnr = itemnr;
	}

	@Column(name = "ITEMNRCONTRACTOR", length = 35)
	public String getItemnrcontractor() {
		return this.itemnrcontractor;
	}

	public void setItemnrcontractor(String itemnrcontractor) {
		this.itemnrcontractor = itemnrcontractor;
	}

	@Column(name = "SALESORGANISATION", length = 35)
	public String getSalesorganisation() {
		return this.salesorganisation;
	}

	public void setSalesorganisation(String salesorganisation) {
		this.salesorganisation = salesorganisation;
	}

	@Column(name = "BATCHID", length = 20)
	public String getBatchid() {
		return this.batchid;
	}

	public void setBatchid(String batchid) {
		this.batchid = batchid;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "BATCHSELLBYDATE", length = 19)
	public Date getBatchsellbydate() {
		return this.batchsellbydate;
	}

	public void setBatchsellbydate(Date batchsellbydate) {
		this.batchsellbydate = batchsellbydate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "BATCHEXPIRYDATE", length = 19)
	public Date getBatchexpirydate() {
		return this.batchexpirydate;
	}

	public void setBatchexpirydate(Date batchexpirydate) {
		this.batchexpirydate = batchexpirydate;
	}

	@Column(name = "BATCHIDCONTRACTOR", length = 20)
	public String getBatchidcontractor() {
		return this.batchidcontractor;
	}

	public void setBatchidcontractor(String batchidcontractor) {
		this.batchidcontractor = batchidcontractor;
	}

	@Column(name = "BATCHREASONCODE", length = 5)
	public String getBatchreasoncode() {
		return this.batchreasoncode;
	}

	public void setBatchreasoncode(String batchreasoncode) {
		this.batchreasoncode = batchreasoncode;
	}

	@Column(name = "SERIALNR", length = 30)
	public String getSerialnr() {
		return this.serialnr;
	}

	public void setSerialnr(String serialnr) {
		this.serialnr = serialnr;
	}

	@Column(name = "FROMWHS", length = 10)
	public String getFromwhs() {
		return this.fromwhs;
	}

	public void setFromwhs(String fromwhs) {
		this.fromwhs = fromwhs;
	}

	@Column(name = "FROMZONE", length = 10)
	public String getFromzone() {
		return this.fromzone;
	}

	public void setFromzone(String fromzone) {
		this.fromzone = fromzone;
	}

	@Column(name = "FROMLOCATION", length = 10)
	public String getFromlocation() {
		return this.fromlocation;
	}

	public void setFromlocation(String fromlocation) {
		this.fromlocation = fromlocation;
	}

	@Column(name = "FROMSTOCKSTATUS", length = 10)
	public String getFromstockstatus() {
		return this.fromstockstatus;
	}

	public void setFromstockstatus(String fromstockstatus) {
		this.fromstockstatus = fromstockstatus;
	}

	@Column(name = "TOWHS", length = 10)
	public String getTowhs() {
		return this.towhs;
	}

	public void setTowhs(String towhs) {
		this.towhs = towhs;
	}

	@Column(name = "TOZONE", length = 10)
	public String getTozone() {
		return this.tozone;
	}

	public void setTozone(String tozone) {
		this.tozone = tozone;
	}

	@Column(name = "TOLOCATION", length = 10)
	public String getTolocation() {
		return this.tolocation;
	}

	public void setTolocation(String tolocation) {
		this.tolocation = tolocation;
	}

	@Column(name = "TOSTOCKSTATUS", length = 10)
	public String getTostockstatus() {
		return this.tostockstatus;
	}

	public void setTostockstatus(String tostockstatus) {
		this.tostockstatus = tostockstatus;
	}

	@Column(name = "FROMQCFLAG", length = 1)
	public String getFromqcflag() {
		return this.fromqcflag;
	}

	public void setFromqcflag(String fromqcflag) {
		this.fromqcflag = fromqcflag;
	}

	@Column(name = "TOQCFLAG", length = 1)
	public String getToqcflag() {
		return this.toqcflag;
	}

	public void setToqcflag(String toqcflag) {
		this.toqcflag = toqcflag;
	}

	@Column(name = "BULKFLAGFROM", length = 1)
	public String getBulkflagfrom() {
		return this.bulkflagfrom;
	}

	public void setBulkflagfrom(String bulkflagfrom) {
		this.bulkflagfrom = bulkflagfrom;
	}

	@Column(name = "BULKFLAGTO", length = 1)
	public String getBulkflagto() {
		return this.bulkflagto;
	}

	public void setBulkflagto(String bulkflagto) {
		this.bulkflagto = bulkflagto;
	}

	@Column(name = "FROMPALLETID", precision = 30, scale = 0)
	public BigDecimal getFrompalletid() {
		return this.frompalletid;
	}

	public void setFrompalletid(BigDecimal frompalletid) {
		this.frompalletid = frompalletid;
	}

	@Column(name = "TOPALLETID", precision = 30, scale = 0)
	public BigDecimal getTopalletid() {
		return this.topalletid;
	}

	public void setTopalletid(BigDecimal topalletid) {
		this.topalletid = topalletid;
	}

	@Column(name = "NCCNR", precision = 12, scale = 0)
	public Long getNccnr() {
		return this.nccnr;
	}

	public void setNccnr(Long nccnr) {
		this.nccnr = nccnr;
	}

	@Column(name = "INTERNALPROBLEMCODE", length = 10)
	public String getInternalproblemcode() {
		return this.internalproblemcode;
	}

	public void setInternalproblemcode(String internalproblemcode) {
		this.internalproblemcode = internalproblemcode;
	}

	@Column(name = "TRANSQTY", precision = 15, scale = 3)
	public BigDecimal getTransqty() {
		return this.transqty;
	}

	public void setTransqty(BigDecimal transqty) {
		this.transqty = transqty;
	}

	@Column(name = "STOCKKEEPINGUNIT", length = 5)
	public String getStockkeepingunit() {
		return this.stockkeepingunit;
	}

	public void setStockkeepingunit(String stockkeepingunit) {
		this.stockkeepingunit = stockkeepingunit;
	}

	@Column(name = "REASONCODE", length = 3)
	public String getReasoncode() {
		return this.reasoncode;
	}

	public void setReasoncode(String reasoncode) {
		this.reasoncode = reasoncode;
	}

	@Column(name = "REASONCODEDESC", length = 50)
	public String getReasoncodedesc() {
		return this.reasoncodedesc;
	}

	public void setReasoncodedesc(String reasoncodedesc) {
		this.reasoncodedesc = reasoncodedesc;
	}

	@Column(name = "REASONCODE_NCC", length = 3)
	public String getReasoncodeNcc() {
		return this.reasoncodeNcc;
	}

	public void setReasoncodeNcc(String reasoncodeNcc) {
		this.reasoncodeNcc = reasoncodeNcc;
	}

	@Column(name = "REASONCODEDESC_NCC", length = 50)
	public String getReasoncodedescNcc() {
		return this.reasoncodedescNcc;
	}

	public void setReasoncodedescNcc(String reasoncodedescNcc) {
		this.reasoncodedescNcc = reasoncodedescNcc;
	}

	@Column(name = "TRANSTEXT", length = 50)
	public String getTranstext() {
		return this.transtext;
	}

	public void setTranstext(String transtext) {
		this.transtext = transtext;
	}

	@Column(name = "REFERENCETEXT", length = 50)
	public String getReferencetext() {
		return this.referencetext;
	}

	public void setReferencetext(String referencetext) {
		this.referencetext = referencetext;
	}

	@Column(name = "CONTRACTORREFERENCE", length = 100)
	public String getContractorreference() {
		return this.contractorreference;
	}

	public void setContractorreference(String contractorreference) {
		this.contractorreference = contractorreference;
	}

	@Column(name = "STANDARDCOST", precision = 17, scale = 4)
	public BigDecimal getStandardcost() {
		return this.standardcost;
	}

	public void setStandardcost(BigDecimal standardcost) {
		this.standardcost = standardcost;
	}

	@Column(name = "TRANSVALUE", precision = 17, scale = 4)
	public BigDecimal getTransvalue() {
		return this.transvalue;
	}

	public void setTransvalue(BigDecimal transvalue) {
		this.transvalue = transvalue;
	}

	@Column(name = "ITRTRANSNR", precision = 12, scale = 0)
	public Long getItrtransnr() {
		return this.itrtransnr;
	}

	public void setItrtransnr(Long itrtransnr) {
		this.itrtransnr = itrtransnr;
	}

	@Column(name = "SUGGESTIONNR", precision = 12, scale = 0)
	public Long getSuggestionnr() {
		return this.suggestionnr;
	}

	public void setSuggestionnr(Long suggestionnr) {
		this.suggestionnr = suggestionnr;
	}

	@Column(name = "SUGGESTIONLINE", precision = 6, scale = 0)
	public Integer getSuggestionline() {
		return this.suggestionline;
	}

	public void setSuggestionline(Integer suggestionline) {
		this.suggestionline = suggestionline;
	}

	@Column(name = "SUGGESTIONSUBLINE", precision = 6, scale = 0)
	public Integer getSuggestionsubline() {
		return this.suggestionsubline;
	}

	public void setSuggestionsubline(Integer suggestionsubline) {
		this.suggestionsubline = suggestionsubline;
	}

	@Column(name = "SALESORDERNR", precision = 12, scale = 0)
	public Long getSalesordernr() {
		return this.salesordernr;
	}

	public void setSalesordernr(Long salesordernr) {
		this.salesordernr = salesordernr;
	}

	@Column(name = "SALESORDERLINE", precision = 5, scale = 0)
	public Integer getSalesorderline() {
		return this.salesorderline;
	}

	public void setSalesorderline(Integer salesorderline) {
		this.salesorderline = salesorderline;
	}

	@Column(name = "SALESORDERTYPE", length = 2)
	public String getSalesordertype() {
		return this.salesordertype;
	}

	public void setSalesordertype(String salesordertype) {
		this.salesordertype = salesordertype;
	}

	@Column(name = "DELLINBTCPK", precision = 12, scale = 0)
	public Long getDellinbtcpk() {
		return this.dellinbtcpk;
	}

	public void setDellinbtcpk(Long dellinbtcpk) {
		this.dellinbtcpk = dellinbtcpk;
	}

	@Column(name = "PURCHASEORDERNR", precision = 12, scale = 0)
	public Long getPurchaseordernr() {
		return this.purchaseordernr;
	}

	public void setPurchaseordernr(Long purchaseordernr) {
		this.purchaseordernr = purchaseordernr;
	}

	@Column(name = "PURCHASEORDERLINE", precision = 6, scale = 0)
	public Integer getPurchaseorderline() {
		return this.purchaseorderline;
	}

	public void setPurchaseorderline(Integer purchaseorderline) {
		this.purchaseorderline = purchaseorderline;
	}

	@Column(name = "PURCHASEORDERTYPE", length = 2)
	public String getPurchaseordertype() {
		return this.purchaseordertype;
	}

	public void setPurchaseordertype(String purchaseordertype) {
		this.purchaseordertype = purchaseordertype;
	}

	@Column(name = "GRELINBTCPK", precision = 12, scale = 0)
	public Long getGrelinbtcpk() {
		return this.grelinbtcpk;
	}

	public void setGrelinbtcpk(Long grelinbtcpk) {
		this.grelinbtcpk = grelinbtcpk;
	}

	@Column(name = "ORDERREFERENCENR", precision = 12, scale = 0)
	public Long getOrderreferencenr() {
		return this.orderreferencenr;
	}

	public void setOrderreferencenr(Long orderreferencenr) {
		this.orderreferencenr = orderreferencenr;
	}

	@Column(name = "ORDERREFERENCELINE", precision = 6, scale = 0)
	public Integer getOrderreferenceline() {
		return this.orderreferenceline;
	}

	public void setOrderreferenceline(Integer orderreferenceline) {
		this.orderreferenceline = orderreferenceline;
	}

	@Column(name = "INCIDENTNR", precision = 12, scale = 0)
	public Long getIncidentnr() {
		return this.incidentnr;
	}

	public void setIncidentnr(Long incidentnr) {
		this.incidentnr = incidentnr;
	}

	@Column(name = "INCIDENTLINE", precision = 6, scale = 0)
	public Integer getIncidentline() {
		return this.incidentline;
	}

	public void setIncidentline(Integer incidentline) {
		this.incidentline = incidentline;
	}

	@Column(name = "SALESORDERPICKLISTNR", precision = 12, scale = 0)
	public Long getSalesorderpicklistnr() {
		return this.salesorderpicklistnr;
	}

	public void setSalesorderpicklistnr(Long salesorderpicklistnr) {
		this.salesorderpicklistnr = salesorderpicklistnr;
	}

	@Column(name = "SALESORDERPICKLISTLINE", precision = 6, scale = 0)
	public Integer getSalesorderpicklistline() {
		return this.salesorderpicklistline;
	}

	public void setSalesorderpicklistline(Integer salesorderpicklistline) {
		this.salesorderpicklistline = salesorderpicklistline;
	}

	@Column(name = "SALESORDERPICKCONSOLIDATIONNR", precision = 12, scale = 0)
	public Long getSalesorderpickconsolidationnr() {
		return this.salesorderpickconsolidationnr;
	}

	public void setSalesorderpickconsolidationnr(Long salesorderpickconsolidationnr) {
		this.salesorderpickconsolidationnr = salesorderpickconsolidationnr;
	}

	@Column(name = "SALESORDERSHIPMENTNR", precision = 12, scale = 0)
	public Long getSalesordershipmentnr() {
		return this.salesordershipmentnr;
	}

	public void setSalesordershipmentnr(Long salesordershipmentnr) {
		this.salesordershipmentnr = salesordershipmentnr;
	}

	@Column(name = "POGOODSRECEPTIONNOTE", precision = 12, scale = 0)
	public Long getPogoodsreceptionnote() {
		return this.pogoodsreceptionnote;
	}

	public void setPogoodsreceptionnote(Long pogoodsreceptionnote) {
		this.pogoodsreceptionnote = pogoodsreceptionnote;
	}

	@Column(name = "POGOODSRECEPTIONNOTELINE", precision = 6, scale = 0)
	public Integer getPogoodsreceptionnoteline() {
		return this.pogoodsreceptionnoteline;
	}

	public void setPogoodsreceptionnoteline(Integer pogoodsreceptionnoteline) {
		this.pogoodsreceptionnoteline = pogoodsreceptionnoteline;
	}

	@Column(name = "TRANSITDELIVERYFLAG", length = 1)
	public String getTransitdeliveryflag() {
		return this.transitdeliveryflag;
	}

	public void setTransitdeliveryflag(String transitdeliveryflag) {
		this.transitdeliveryflag = transitdeliveryflag;
	}

	@Column(name = "FREEOFCHARGEFLAG", length = 1)
	public String getFreeofchargeflag() {
		return this.freeofchargeflag;
	}

	public void setFreeofchargeflag(String freeofchargeflag) {
		this.freeofchargeflag = freeofchargeflag;
	}

	@Column(name = "FREEOFCHARGEREASONCODE", length = 2)
	public String getFreeofchargereasoncode() {
		return this.freeofchargereasoncode;
	}

	public void setFreeofchargereasoncode(String freeofchargereasoncode) {
		this.freeofchargereasoncode = freeofchargereasoncode;
	}

	@Column(name = "ORDER_SOURCE_CODE", length = 20)
	public String getOrderSourceCode() {
		return this.orderSourceCode;
	}

	public void setOrderSourceCode(String orderSourceCode) {
		this.orderSourceCode = orderSourceCode;
	}

	@Column(name = "DELIVERYANNOUNCEMENTNR", length = 35)
	public String getDeliveryannouncementnr() {
		return this.deliveryannouncementnr;
	}

	public void setDeliveryannouncementnr(String deliveryannouncementnr) {
		this.deliveryannouncementnr = deliveryannouncementnr;
	}

	@Column(name = "DELIVERYANNOUNCEMENTLINE", precision = 6, scale = 0)
	public Integer getDeliveryannouncementline() {
		return this.deliveryannouncementline;
	}

	public void setDeliveryannouncementline(Integer deliveryannouncementline) {
		this.deliveryannouncementline = deliveryannouncementline;
	}

	@Column(name = "USERTRANSSTARTED", length = 10)
	public String getUsertransstarted() {
		return this.usertransstarted;
	}

	public void setUsertransstarted(String usertransstarted) {
		this.usertransstarted = usertransstarted;
	}

	@Column(name = "USERTRANSCOMPLETED", length = 10)
	public String getUsertranscompleted() {
		return this.usertranscompleted;
	}

	public void setUsertranscompleted(String usertranscompleted) {
		this.usertranscompleted = usertranscompleted;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "TIMETRANSSTARTED", length = 19)
	public Date getTimetransstarted() {
		return this.timetransstarted;
	}

	public void setTimetransstarted(Date timetransstarted) {
		this.timetransstarted = timetransstarted;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "TIMETRANSCOMPLETED", length = 19)
	public Date getTimetranscompleted() {
		return this.timetranscompleted;
	}

	public void setTimetranscompleted(Date timetranscompleted) {
		this.timetranscompleted = timetranscompleted;
	}

	@Column(name = "FROMREPORTINGKEY", length = 20)
	public String getFromreportingkey() {
		return this.fromreportingkey;
	}

	public void setFromreportingkey(String fromreportingkey) {
		this.fromreportingkey = fromreportingkey;
	}

	@Column(name = "TOREPORTINGKEY", length = 20)
	public String getToreportingkey() {
		return this.toreportingkey;
	}

	public void setToreportingkey(String toreportingkey) {
		this.toreportingkey = toreportingkey;
	}

	@Column(name = "FROMREPORTINGSTOCKSTATUS", length = 10)
	public String getFromreportingstockstatus() {
		return this.fromreportingstockstatus;
	}

	public void setFromreportingstockstatus(String fromreportingstockstatus) {
		this.fromreportingstockstatus = fromreportingstockstatus;
	}

	@Column(name = "TOREPORTINGSTOCKSTATUS", length = 10)
	public String getToreportingstockstatus() {
		return this.toreportingstockstatus;
	}

	public void setToreportingstockstatus(String toreportingstockstatus) {
		this.toreportingstockstatus = toreportingstockstatus;
	}

	@Column(name = "STOCKTAKELISTNR", precision = 12, scale = 0)
	public Long getStocktakelistnr() {
		return this.stocktakelistnr;
	}

	public void setStocktakelistnr(Long stocktakelistnr) {
		this.stocktakelistnr = stocktakelistnr;
	}

	@Column(name = "STOCKTAKELISTLINE", precision = 6, scale = 0)
	public Integer getStocktakelistline() {
		return this.stocktakelistline;
	}

	public void setStocktakelistline(Integer stocktakelistline) {
		this.stocktakelistline = stocktakelistline;
	}

	@Column(name = "RFBATCHID", precision = 9, scale = 0)
	public Integer getRfbatchid() {
		return this.rfbatchid;
	}

	public void setRfbatchid(Integer rfbatchid) {
		this.rfbatchid = rfbatchid;
	}

	@Column(name = "RFINSTRUCTIONNR", precision = 17, scale = 0)
	public Long getRfinstructionnr() {
		return this.rfinstructionnr;
	}

	public void setRfinstructionnr(Long rfinstructionnr) {
		this.rfinstructionnr = rfinstructionnr;
	}

	@Column(name = "FREETEXT")
	public String getFreetext() {
		return this.freetext;
	}

	public void setFreetext(String freetext) {
		this.freetext = freetext;
	}

	@Column(name = "IP_TRANSTYPE", precision = 5, scale = 0)
	public Integer getIpTranstype() {
		return this.ipTranstype;
	}

	public void setIpTranstype(Integer ipTranstype) {
		this.ipTranstype = ipTranstype;
	}

	@Column(name = "IP_EVENTCODE", precision = 5, scale = 0)
	public Integer getIpEventcode() {
		return this.ipEventcode;
	}

	public void setIpEventcode(Integer ipEventcode) {
		this.ipEventcode = ipEventcode;
	}

	@Column(name = "IP_FROMWAREHOUSE", precision = 5, scale = 0)
	public Integer getIpFromwarehouse() {
		return this.ipFromwarehouse;
	}

	public void setIpFromwarehouse(Integer ipFromwarehouse) {
		this.ipFromwarehouse = ipFromwarehouse;
	}

	@Column(name = "IP_TOWAREHOUSE", precision = 5, scale = 0)
	public Integer getIpTowarehouse() {
		return this.ipTowarehouse;
	}

	public void setIpTowarehouse(Integer ipTowarehouse) {
		this.ipTowarehouse = ipTowarehouse;
	}

	@Column(name = "IP_FROMLOCATIONZONE", precision = 5, scale = 0)
	public Integer getIpFromlocationzone() {
		return this.ipFromlocationzone;
	}

	public void setIpFromlocationzone(Integer ipFromlocationzone) {
		this.ipFromlocationzone = ipFromlocationzone;
	}

	@Column(name = "IP_TOLOCATIONZONE", precision = 5, scale = 0)
	public Integer getIpTolocationzone() {
		return this.ipTolocationzone;
	}

	public void setIpTolocationzone(Integer ipTolocationzone) {
		this.ipTolocationzone = ipTolocationzone;
	}

	@Column(name = "IP_FROMSTOCKCATEGORY", precision = 5, scale = 0)
	public Integer getIpFromstockcategory() {
		return this.ipFromstockcategory;
	}

	public void setIpFromstockcategory(Integer ipFromstockcategory) {
		this.ipFromstockcategory = ipFromstockcategory;
	}

	@Column(name = "IP_TOSTOCKCATEGORY", precision = 5, scale = 0)
	public Integer getIpTostockcategory() {
		return this.ipTostockcategory;
	}

	public void setIpTostockcategory(Integer ipTostockcategory) {
		this.ipTostockcategory = ipTostockcategory;
	}

	@Column(name = "IP_PURCHASEORDERTYPE", precision = 5, scale = 0)
	public Integer getIpPurchaseordertype() {
		return this.ipPurchaseordertype;
	}

	public void setIpPurchaseordertype(Integer ipPurchaseordertype) {
		this.ipPurchaseordertype = ipPurchaseordertype;
	}

	@Column(name = "IP_SALESORDERTYPE", precision = 5, scale = 0)
	public Integer getIpSalesordertype() {
		return this.ipSalesordertype;
	}

	public void setIpSalesordertype(Integer ipSalesordertype) {
		this.ipSalesordertype = ipSalesordertype;
	}

	@Column(name = "IP_INVOICETYPE", precision = 5, scale = 0)
	public Integer getIpInvoicetype() {
		return this.ipInvoicetype;
	}

	public void setIpInvoicetype(Integer ipInvoicetype) {
		this.ipInvoicetype = ipInvoicetype;
	}

	@Column(name = "IP_ISFREEOFCHARGE", length = 1)
	public String getIpIsfreeofcharge() {
		return this.ipIsfreeofcharge;
	}

	public void setIpIsfreeofcharge(String ipIsfreeofcharge) {
		this.ipIsfreeofcharge = ipIsfreeofcharge;
	}

	@Column(name = "IP_FREEOFCHARGEREASONCODE", precision = 5, scale = 0)
	public Integer getIpFreeofchargereasoncode() {
		return this.ipFreeofchargereasoncode;
	}

	public void setIpFreeofchargereasoncode(Integer ipFreeofchargereasoncode) {
		this.ipFreeofchargereasoncode = ipFreeofchargereasoncode;
	}

	@Column(name = "IP_TRANSCLAS_1", length = 10)
	public String getIpTransclas1() {
		return this.ipTransclas1;
	}

	public void setIpTransclas1(String ipTransclas1) {
		this.ipTransclas1 = ipTransclas1;
	}

	@Column(name = "IP_TRANSCLAS_2", length = 10)
	public String getIpTransclas2() {
		return this.ipTransclas2;
	}

	public void setIpTransclas2(String ipTransclas2) {
		this.ipTransclas2 = ipTransclas2;
	}

	@Column(name = "IP_TRANSCLAS_3", length = 10)
	public String getIpTransclas3() {
		return this.ipTransclas3;
	}

	public void setIpTransclas3(String ipTransclas3) {
		this.ipTransclas3 = ipTransclas3;
	}

	@Column(name = "IP_ISDEBIT", length = 1)
	public String getIpIsdebit() {
		return this.ipIsdebit;
	}

	public void setIpIsdebit(String ipIsdebit) {
		this.ipIsdebit = ipIsdebit;
	}

	@Column(name = "IP_ISSALESWITHMOVEMENT", length = 1)
	public String getIpIssaleswithmovement() {
		return this.ipIssaleswithmovement;
	}

	public void setIpIssaleswithmovement(String ipIssaleswithmovement) {
		this.ipIssaleswithmovement = ipIssaleswithmovement;
	}

	@Column(name = "IP_ISSTOCKRELEVANT", length = 1)
	public String getIpIsstockrelevant() {
		return this.ipIsstockrelevant;
	}

	public void setIpIsstockrelevant(String ipIsstockrelevant) {
		this.ipIsstockrelevant = ipIsstockrelevant;
	}

	@Column(name = "IP_MOVEMENTCODE", length = 20)
	public String getIpMovementcode() {
		return this.ipMovementcode;
	}

	public void setIpMovementcode(String ipMovementcode) {
		this.ipMovementcode = ipMovementcode;
	}

	@Column(name = "IP_MOVEMENTREASON", length = 20)
	public String getIpMovementreason() {
		return this.ipMovementreason;
	}

	public void setIpMovementreason(String ipMovementreason) {
		this.ipMovementreason = ipMovementreason;
	}

	@Column(name = "IP_PLANTFROM", length = 20)
	public String getIpPlantfrom() {
		return this.ipPlantfrom;
	}

	public void setIpPlantfrom(String ipPlantfrom) {
		this.ipPlantfrom = ipPlantfrom;
	}

	@Column(name = "IP_PLANTTO", length = 20)
	public String getIpPlantto() {
		return this.ipPlantto;
	}

	public void setIpPlantto(String ipPlantto) {
		this.ipPlantto = ipPlantto;
	}

	@Column(name = "IP_STORAGELOCATIONFROM", length = 20)
	public String getIpStoragelocationfrom() {
		return this.ipStoragelocationfrom;
	}

	public void setIpStoragelocationfrom(String ipStoragelocationfrom) {
		this.ipStoragelocationfrom = ipStoragelocationfrom;
	}

	@Column(name = "IP_STORAGELOCATIONTO", length = 20)
	public String getIpStoragelocationto() {
		return this.ipStoragelocationto;
	}

	public void setIpStoragelocationto(String ipStoragelocationto) {
		this.ipStoragelocationto = ipStoragelocationto;
	}

	@Column(name = "IP_STOCKSTATUSFROM", length = 20)
	public String getIpStockstatusfrom() {
		return this.ipStockstatusfrom;
	}

	public void setIpStockstatusfrom(String ipStockstatusfrom) {
		this.ipStockstatusfrom = ipStockstatusfrom;
	}

	@Column(name = "IP_STOCKSTATUSTO", length = 20)
	public String getIpStockstatusto() {
		return this.ipStockstatusto;
	}

	public void setIpStockstatusto(String ipStockstatusto) {
		this.ipStockstatusto = ipStockstatusto;
	}

	@Column(name = "TIMEDATEPK", precision = 8, scale = 0)
	public Integer getTimedatepk() {
		return this.timedatepk;
	}

	public void setTimedatepk(Integer timedatepk) {
		this.timedatepk = timedatepk;
	}

	@Column(name = "IP_TIMEDATEPK_REPORTING", precision = 8, scale = 0)
	public Integer getIpTimedatepkReporting() {
		return this.ipTimedatepkReporting;
	}

	public void setIpTimedatepkReporting(Integer ipTimedatepkReporting) {
		this.ipTimedatepkReporting = ipTimedatepkReporting;
	}

	@Column(name = "PROGRAMNAME", length = 10)
	public String getProgramname() {
		return this.programname;
	}

	public void setProgramname(String programname) {
		this.programname = programname;
	}

	@Column(name = "FILENAME", length = 10)
	public String getFilename() {
		return this.filename;
	}

	public void setFilename(String filename) {
		this.filename = filename;
	}

	@Column(name = "PROCESSINGFLAG1", length = 1)
	public String getProcessingflag1() {
		return this.processingflag1;
	}

	public void setProcessingflag1(String processingflag1) {
		this.processingflag1 = processingflag1;
	}

	@Column(name = "PROCESSINGFLAG2", length = 1)
	public String getProcessingflag2() {
		return this.processingflag2;
	}

	public void setProcessingflag2(String processingflag2) {
		this.processingflag2 = processingflag2;
	}

	@Column(name = "PROCESSINGFLAG3", length = 1)
	public String getProcessingflag3() {
		return this.processingflag3;
	}

	public void setProcessingflag3(String processingflag3) {
		this.processingflag3 = processingflag3;
	}

	@Column(name = "PROCESSINGFLAG4", length = 1)
	public String getProcessingflag4() {
		return this.processingflag4;
	}

	public void setProcessingflag4(String processingflag4) {
		this.processingflag4 = processingflag4;
	}

	@Column(name = "PROCESSINGFLAG5", length = 1)
	public String getProcessingflag5() {
		return this.processingflag5;
	}

	public void setProcessingflag5(String processingflag5) {
		this.processingflag5 = processingflag5;
	}

	@Column(name = "PROCESSINGFLAG6", length = 1)
	public String getProcessingflag6() {
		return this.processingflag6;
	}

	public void setProcessingflag6(String processingflag6) {
		this.processingflag6 = processingflag6;
	}

	@Column(name = "PROCESSINGFLAG7", length = 1)
	public String getProcessingflag7() {
		return this.processingflag7;
	}

	public void setProcessingflag7(String processingflag7) {
		this.processingflag7 = processingflag7;
	}

	@Column(name = "PROCESSINGFLAG8", length = 1)
	public String getProcessingflag8() {
		return this.processingflag8;
	}

	public void setProcessingflag8(String processingflag8) {
		this.processingflag8 = processingflag8;
	}

	@Column(name = "PROCESSINGFLAG9", length = 1)
	public String getProcessingflag9() {
		return this.processingflag9;
	}

	public void setProcessingflag9(String processingflag9) {
		this.processingflag9 = processingflag9;
	}

	@Column(name = "PROCESSINGFLAG10", length = 1)
	public String getProcessingflag10() {
		return this.processingflag10;
	}

	public void setProcessingflag10(String processingflag10) {
		this.processingflag10 = processingflag10;
	}

	@Column(name = "BACKENDRELEASED", nullable = false, length = 1)
	public String getBackendreleased() {
		return this.backendreleased;
	}

	public void setBackendreleased(String backendreleased) {
		this.backendreleased = backendreleased;
	}

	@Column(name = "OUTBOUNDIGNORE", nullable = false, length = 1)
	public String getOutboundignore() {
		return this.outboundignore;
	}

	public void setOutboundignore(String outboundignore) {
		this.outboundignore = outboundignore;
	}

	@Column(name = "TRANSACTIONID", length = 50)
	public String getTransactionid() {
		return this.transactionid;
	}

	public void setTransactionid(String transactionid) {
		this.transactionid = transactionid;
	}

	@Column(name = "RECORDPROCESSEDFLAG", nullable = false, length = 1)
	public String getRecordprocessedflag() {
		return this.recordprocessedflag;
	}

	public void setRecordprocessedflag(String recordprocessedflag) {
		this.recordprocessedflag = recordprocessedflag;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "RECORDPROCESSINGTIME", length = 19)
	public Date getRecordprocessingtime() {
		return this.recordprocessingtime;
	}

	public void setRecordprocessingtime(Date recordprocessingtime) {
		this.recordprocessingtime = recordprocessingtime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "RECORDLASTCHANGETIME", length = 19)
	public Date getRecordlastchangetime() {
		return this.recordlastchangetime;
	}

	public void setRecordlastchangetime(Date recordlastchangetime) {
		this.recordlastchangetime = recordlastchangetime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "RECORDCREATIONTIME", nullable = false, length = 19)
	public Date getRecordcreationtime() {
		return this.recordcreationtime;
	}

	public void setRecordcreationtime(Date recordcreationtime) {
		this.recordcreationtime = recordcreationtime;
	}

}
