package com.galexis.alloga2mysql.model;

// Generated Mar 4, 2013 4:41:13 PM by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Itembtcm generated by hbm2java
 */
@Entity
@Table(name = "ITEMBTCM", uniqueConstraints = @UniqueConstraint(columnNames = { "CONTRDEFPK", "WAREHOUSE", "ITEMNR", "BATCHID", "MATERIALBATCHID" }))
public class Itembtcm implements java.io.Serializable {

	private long pk;

	private long contrdefpk;

	private String itemnr;

	private String batchid;

	private String warehouse;

	private Date batchexpirydate;

	private Date batchsellbydate;

	private long itemmasterpk;

	private String itemnrcontractor;

	private Date createdate;

	private String purchaseordertype;

	private Long transnr;

	private Date transdate;

	private String materialbatchid;

	private Integer timedatepk;

	private String ipStockstatusfrom;

	private String ipStockstatusto;

	private String ipMovementreason;

	private Integer ipTimedatepkReporting;

	private Character processingflag1;

	private Character processingflag2;

	private Character processingflag3;

	private Character processingflag4;

	private Character processingflag5;

	private Character processingflag6;

	private Character processingflag7;

	private Character processingflag8;

	private Character processingflag9;

	private Character processingflag10;

	private String programname;

	private String filename;

	private Character backendreleased;

	private Character outboundignore;

	private String transactionid;

	private Character recordprocessedflag;

	private Date recordprocessingtime;

	private Date recordlastchangetime;

	private Date recordcreationtime;

	public Itembtcm() {
	}

	public Itembtcm(long pk, long contrdefpk, String itemnr, String batchid, String warehouse, Date batchexpirydate, long itemmasterpk, Date createdate, Date recordcreationtime) {
		this.pk = pk;
		this.contrdefpk = contrdefpk;
		this.itemnr = itemnr;
		this.batchid = batchid;
		this.warehouse = warehouse;
		this.batchexpirydate = batchexpirydate;
		this.itemmasterpk = itemmasterpk;
		this.createdate = createdate;
		this.recordcreationtime = recordcreationtime;
	}

	public Itembtcm(long pk, long contrdefpk, String itemnr, String batchid, String warehouse, Date batchexpirydate, Date batchsellbydate, long itemmasterpk,
	        String itemnrcontractor, Date createdate, String purchaseordertype, Long transnr, Date transdate, String materialbatchid, Integer timedatepk, String ipStockstatusfrom,
	        String ipStockstatusto, String ipMovementreason, Integer ipTimedatepkReporting, Character processingflag1, Character processingflag2, Character processingflag3,
	        Character processingflag4, Character processingflag5, Character processingflag6, Character processingflag7, Character processingflag8, Character processingflag9,
	        Character processingflag10, String programname, String filename, Character backendreleased, Character outboundignore, String transactionid,
	        Character recordprocessedflag, Date recordprocessingtime, Date recordlastchangetime, Date recordcreationtime) {
		this.pk = pk;
		this.contrdefpk = contrdefpk;
		this.itemnr = itemnr;
		this.batchid = batchid;
		this.warehouse = warehouse;
		this.batchexpirydate = batchexpirydate;
		this.batchsellbydate = batchsellbydate;
		this.itemmasterpk = itemmasterpk;
		this.itemnrcontractor = itemnrcontractor;
		this.createdate = createdate;
		this.purchaseordertype = purchaseordertype;
		this.transnr = transnr;
		this.transdate = transdate;
		this.materialbatchid = materialbatchid;
		this.timedatepk = timedatepk;
		this.ipStockstatusfrom = ipStockstatusfrom;
		this.ipStockstatusto = ipStockstatusto;
		this.ipMovementreason = ipMovementreason;
		this.ipTimedatepkReporting = ipTimedatepkReporting;
		this.processingflag1 = processingflag1;
		this.processingflag2 = processingflag2;
		this.processingflag3 = processingflag3;
		this.processingflag4 = processingflag4;
		this.processingflag5 = processingflag5;
		this.processingflag6 = processingflag6;
		this.processingflag7 = processingflag7;
		this.processingflag8 = processingflag8;
		this.processingflag9 = processingflag9;
		this.processingflag10 = processingflag10;
		this.programname = programname;
		this.filename = filename;
		this.backendreleased = backendreleased;
		this.outboundignore = outboundignore;
		this.transactionid = transactionid;
		this.recordprocessedflag = recordprocessedflag;
		this.recordprocessingtime = recordprocessingtime;
		this.recordlastchangetime = recordlastchangetime;
		this.recordcreationtime = recordcreationtime;
	}

	@Id
	@Column(name = "PK", unique = true, nullable = false, precision = 12, scale = 0)
	public long getPk() {
		return this.pk;
	}

	public void setPk(long pk) {
		this.pk = pk;
	}

	@Column(name = "CONTRDEFPK", nullable = false, precision = 12, scale = 0)
	public long getContrdefpk() {
		return this.contrdefpk;
	}

	public void setContrdefpk(long contrdefpk) {
		this.contrdefpk = contrdefpk;
	}

	@Column(name = "ITEMNR", nullable = false, length = 35)
	public String getItemnr() {
		return this.itemnr;
	}

	public void setItemnr(String itemnr) {
		this.itemnr = itemnr;
	}

	@Column(name = "BATCHID", nullable = false, length = 20)
	public String getBatchid() {
		return this.batchid;
	}

	public void setBatchid(String batchid) {
		this.batchid = batchid;
	}

	@Column(name = "WAREHOUSE", nullable = false, length = 10)
	public String getWarehouse() {
		return this.warehouse;
	}

	public void setWarehouse(String warehouse) {
		this.warehouse = warehouse;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "BATCHEXPIRYDATE", length = 19)
	public Date getBatchexpirydate() {
		return this.batchexpirydate;
	}

	public void setBatchexpirydate(Date batchexpirydate) {
		this.batchexpirydate = batchexpirydate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "BATCHSELLBYDATE", length = 19)
	public Date getBatchsellbydate() {
		return this.batchsellbydate;
	}

	public void setBatchsellbydate(Date batchsellbydate) {
		this.batchsellbydate = batchsellbydate;
	}

	@Column(name = "ITEMMASTERPK", nullable = false, precision = 12, scale = 0)
	public long getItemmasterpk() {
		return this.itemmasterpk;
	}

	public void setItemmasterpk(long itemmasterpk) {
		this.itemmasterpk = itemmasterpk;
	}

	@Column(name = "ITEMNRCONTRACTOR", length = 35)
	public String getItemnrcontractor() {
		return this.itemnrcontractor;
	}

	public void setItemnrcontractor(String itemnrcontractor) {
		this.itemnrcontractor = itemnrcontractor;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATEDATE", nullable = false, length = 19)
	public Date getCreatedate() {
		return this.createdate;
	}

	public void setCreatedate(Date createdate) {
		this.createdate = createdate;
	}

	@Column(name = "PURCHASEORDERTYPE", length = 2)
	public String getPurchaseordertype() {
		return this.purchaseordertype;
	}

	public void setPurchaseordertype(String purchaseordertype) {
		this.purchaseordertype = purchaseordertype;
	}

	@Column(name = "TRANSNR", precision = 12, scale = 0)
	public Long getTransnr() {
		return this.transnr;
	}

	public void setTransnr(Long transnr) {
		this.transnr = transnr;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "TRANSDATE", length = 19)
	public Date getTransdate() {
		return this.transdate;
	}

	public void setTransdate(Date transdate) {
		this.transdate = transdate;
	}

	@Column(name = "MATERIALBATCHID", length = 20)
	public String getMaterialbatchid() {
		return this.materialbatchid;
	}

	public void setMaterialbatchid(String materialbatchid) {
		this.materialbatchid = materialbatchid;
	}

	@Column(name = "TIMEDATEPK", precision = 8, scale = 0)
	public Integer getTimedatepk() {
		return this.timedatepk;
	}

	public void setTimedatepk(Integer timedatepk) {
		this.timedatepk = timedatepk;
	}

	@Column(name = "IP_STOCKSTATUSFROM", length = 20)
	public String getIpStockstatusfrom() {
		return this.ipStockstatusfrom;
	}

	public void setIpStockstatusfrom(String ipStockstatusfrom) {
		this.ipStockstatusfrom = ipStockstatusfrom;
	}

	@Column(name = "IP_STOCKSTATUSTO", length = 20)
	public String getIpStockstatusto() {
		return this.ipStockstatusto;
	}

	public void setIpStockstatusto(String ipStockstatusto) {
		this.ipStockstatusto = ipStockstatusto;
	}

	@Column(name = "IP_MOVEMENTREASON", length = 20)
	public String getIpMovementreason() {
		return this.ipMovementreason;
	}

	public void setIpMovementreason(String ipMovementreason) {
		this.ipMovementreason = ipMovementreason;
	}

	@Column(name = "IP_TIMEDATEPK_REPORTING", precision = 8, scale = 0)
	public Integer getIpTimedatepkReporting() {
		return this.ipTimedatepkReporting;
	}

	public void setIpTimedatepkReporting(Integer ipTimedatepkReporting) {
		this.ipTimedatepkReporting = ipTimedatepkReporting;
	}

	@Column(name = "PROCESSINGFLAG1", length = 1)
	public Character getProcessingflag1() {
		return this.processingflag1;
	}

	public void setProcessingflag1(Character processingflag1) {
		this.processingflag1 = processingflag1;
	}

	@Column(name = "PROCESSINGFLAG2", length = 1)
	public Character getProcessingflag2() {
		return this.processingflag2;
	}

	public void setProcessingflag2(Character processingflag2) {
		this.processingflag2 = processingflag2;
	}

	@Column(name = "PROCESSINGFLAG3", length = 1)
	public Character getProcessingflag3() {
		return this.processingflag3;
	}

	public void setProcessingflag3(Character processingflag3) {
		this.processingflag3 = processingflag3;
	}

	@Column(name = "PROCESSINGFLAG4", length = 1)
	public Character getProcessingflag4() {
		return this.processingflag4;
	}

	public void setProcessingflag4(Character processingflag4) {
		this.processingflag4 = processingflag4;
	}

	@Column(name = "PROCESSINGFLAG5", length = 1)
	public Character getProcessingflag5() {
		return this.processingflag5;
	}

	public void setProcessingflag5(Character processingflag5) {
		this.processingflag5 = processingflag5;
	}

	@Column(name = "PROCESSINGFLAG6", length = 1)
	public Character getProcessingflag6() {
		return this.processingflag6;
	}

	public void setProcessingflag6(Character processingflag6) {
		this.processingflag6 = processingflag6;
	}

	@Column(name = "PROCESSINGFLAG7", length = 1)
	public Character getProcessingflag7() {
		return this.processingflag7;
	}

	public void setProcessingflag7(Character processingflag7) {
		this.processingflag7 = processingflag7;
	}

	@Column(name = "PROCESSINGFLAG8", length = 1)
	public Character getProcessingflag8() {
		return this.processingflag8;
	}

	public void setProcessingflag8(Character processingflag8) {
		this.processingflag8 = processingflag8;
	}

	@Column(name = "PROCESSINGFLAG9", length = 1)
	public Character getProcessingflag9() {
		return this.processingflag9;
	}

	public void setProcessingflag9(Character processingflag9) {
		this.processingflag9 = processingflag9;
	}

	@Column(name = "PROCESSINGFLAG10", length = 1)
	public Character getProcessingflag10() {
		return this.processingflag10;
	}

	public void setProcessingflag10(Character processingflag10) {
		this.processingflag10 = processingflag10;
	}

	@Column(name = "PROGRAMNAME", length = 10)
	public String getProgramname() {
		return this.programname;
	}

	public void setProgramname(String programname) {
		this.programname = programname;
	}

	@Column(name = "FILENAME", length = 10)
	public String getFilename() {
		return this.filename;
	}

	public void setFilename(String filename) {
		this.filename = filename;
	}

	@Column(name = "BACKENDRELEASED", length = 1)
	public Character getBackendreleased() {
		return this.backendreleased;
	}

	public void setBackendreleased(Character backendreleased) {
		this.backendreleased = backendreleased;
	}

	@Column(name = "OUTBOUNDIGNORE", length = 1)
	public Character getOutboundignore() {
		return this.outboundignore;
	}

	public void setOutboundignore(Character outboundignore) {
		this.outboundignore = outboundignore;
	}

	@Column(name = "TRANSACTIONID", length = 50)
	public String getTransactionid() {
		return this.transactionid;
	}

	public void setTransactionid(String transactionid) {
		this.transactionid = transactionid;
	}

	@Column(name = "RECORDPROCESSEDFLAG", length = 1)
	public Character getRecordprocessedflag() {
		return this.recordprocessedflag;
	}

	public void setRecordprocessedflag(Character recordprocessedflag) {
		this.recordprocessedflag = recordprocessedflag;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "RECORDPROCESSINGTIME", length = 19)
	public Date getRecordprocessingtime() {
		return this.recordprocessingtime;
	}

	public void setRecordprocessingtime(Date recordprocessingtime) {
		this.recordprocessingtime = recordprocessingtime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "RECORDLASTCHANGETIME", length = 19)
	public Date getRecordlastchangetime() {
		return this.recordlastchangetime;
	}

	public void setRecordlastchangetime(Date recordlastchangetime) {
		this.recordlastchangetime = recordlastchangetime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "RECORDCREATIONTIME", nullable = false, length = 19)
	public Date getRecordcreationtime() {
		return this.recordcreationtime;
	}

	public void setRecordcreationtime(Date recordcreationtime) {
		this.recordcreationtime = recordcreationtime;
	}

}
