package com.galexis.alloga2mysql.model;

// Generated Mar 4, 2013 4:41:13 PM by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Pod generated by hbm2java
 */
@Entity
@Table(name = "POD")
public class Pod implements java.io.Serializable {

	private PodId id;

	public Pod() {
	}

	public Pod(PodId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "pk", column = @Column(name = "PK", nullable = false, precision = 12, scale = 0)),
	        @AttributeOverride(name = "mandant", column = @Column(name = "MANDANT", nullable = false, length = 40)),
	        @AttributeOverride(name = "pvsshipmentno", column = @Column(name = "PVSSHIPMENTNO", nullable = false, length = 40)),
	        @AttributeOverride(name = "confirmationdate", column = @Column(name = "CONFIRMATIONDATE", nullable = false, length = 8)),
	        @AttributeOverride(name = "confirmationtime", column = @Column(name = "CONFIRMATIONTIME", nullable = false, length = 6)),
	        @AttributeOverride(name = "signature", column = @Column(name = "SIGNATURE", nullable = false, length = 40)),
	        @AttributeOverride(name = "transactionid", column = @Column(name = "TRANSACTIONID", nullable = false, length = 50)),
	        @AttributeOverride(name = "creationtimestamp", column = @Column(name = "CREATIONTIMESTAMP", nullable = false, length = 19)) })
	public PodId getId() {
		return this.id;
	}

	public void setId(PodId id) {
		this.id = id;
	}

}
