package com.galexis.alloga2mysql.model;

// Generated Mar 4, 2013 4:41:13 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Psihdr generated by hbm2java
 */
@Entity
@Table(name = "PSIHDR", uniqueConstraints = @UniqueConstraint(columnNames = { "CONTRDEFPK", "INSTRUCTIONNR", "DOCUMENTTYPE" }))
public class Psihdr implements java.io.Serializable {

	private long pk;

	private long contrdefpk;

	private String instructionnr;

	private String salesorganisation;

	private String documenttype;

	private String businessidentifier;

	private Date instructiondate;

	private Date requestedprocessdate;

	private String referencetypecode;

	private String shippingconditions;

	private String businesspartnernr;

	private String businesspartnername;

	private String addressline1;

	private String addressline2;

	private String addressline3;

	private String street;

	private String city;

	private String postalcode;

	private String country;

	private String instructionnotes;

	private String filereceived;

	private Date timestampreceived;

	private Integer filesequencenr;

	private String transactionid;

	private Date timestampconfirmation;

	private String fileconfirmed;

	private String programname;

	private String processingflag1;

	private String processingflag2;

	private String processingflag3;

	private String processingflag4;

	private String processingflag5;

	private String processingflag6;

	private String processingflag7;

	private String processingflag8;

	private String processingflag9;

	private String processingflag10;

	private String recordprocessedflag;

	private Date recordprocessingtime;

	private Date recordlastchangetime;

	private Date recordcreationtime;

	public Psihdr() {
	}

	public Psihdr(long pk, long contrdefpk, String instructionnr, Date recordcreationtime) {
		this.pk = pk;
		this.contrdefpk = contrdefpk;
		this.instructionnr = instructionnr;
		this.recordcreationtime = recordcreationtime;
	}

	public Psihdr(long pk, long contrdefpk, String instructionnr, String salesorganisation, String documenttype, String businessidentifier, Date instructiondate,
	        Date requestedprocessdate, String referencetypecode, String shippingconditions, String businesspartnernr, String businesspartnername, String addressline1,
	        String addressline2, String addressline3, String street, String city, String postalcode, String country, String instructionnotes, String filereceived,
	        Date timestampreceived, Integer filesequencenr, String transactionid, Date timestampconfirmation, String fileconfirmed, String programname, String processingflag1,
	        String processingflag2, String processingflag3, String processingflag4, String processingflag5, String processingflag6, String processingflag7, String processingflag8,
	        String processingflag9, String processingflag10, String recordprocessedflag, Date recordprocessingtime, Date recordlastchangetime, Date recordcreationtime) {
		this.pk = pk;
		this.contrdefpk = contrdefpk;
		this.instructionnr = instructionnr;
		this.salesorganisation = salesorganisation;
		this.documenttype = documenttype;
		this.businessidentifier = businessidentifier;
		this.instructiondate = instructiondate;
		this.requestedprocessdate = requestedprocessdate;
		this.referencetypecode = referencetypecode;
		this.shippingconditions = shippingconditions;
		this.businesspartnernr = businesspartnernr;
		this.businesspartnername = businesspartnername;
		this.addressline1 = addressline1;
		this.addressline2 = addressline2;
		this.addressline3 = addressline3;
		this.street = street;
		this.city = city;
		this.postalcode = postalcode;
		this.country = country;
		this.instructionnotes = instructionnotes;
		this.filereceived = filereceived;
		this.timestampreceived = timestampreceived;
		this.filesequencenr = filesequencenr;
		this.transactionid = transactionid;
		this.timestampconfirmation = timestampconfirmation;
		this.fileconfirmed = fileconfirmed;
		this.programname = programname;
		this.processingflag1 = processingflag1;
		this.processingflag2 = processingflag2;
		this.processingflag3 = processingflag3;
		this.processingflag4 = processingflag4;
		this.processingflag5 = processingflag5;
		this.processingflag6 = processingflag6;
		this.processingflag7 = processingflag7;
		this.processingflag8 = processingflag8;
		this.processingflag9 = processingflag9;
		this.processingflag10 = processingflag10;
		this.recordprocessedflag = recordprocessedflag;
		this.recordprocessingtime = recordprocessingtime;
		this.recordlastchangetime = recordlastchangetime;
		this.recordcreationtime = recordcreationtime;
	}

	@Id
	@Column(name = "PK", unique = true, nullable = false, precision = 12, scale = 0)
	public long getPk() {
		return this.pk;
	}

	public void setPk(long pk) {
		this.pk = pk;
	}

	@Column(name = "CONTRDEFPK", nullable = false, precision = 12, scale = 0)
	public long getContrdefpk() {
		return this.contrdefpk;
	}

	public void setContrdefpk(long contrdefpk) {
		this.contrdefpk = contrdefpk;
	}

	@Column(name = "INSTRUCTIONNR", nullable = false, length = 30)
	public String getInstructionnr() {
		return this.instructionnr;
	}

	public void setInstructionnr(String instructionnr) {
		this.instructionnr = instructionnr;
	}

	@Column(name = "SALESORGANISATION", length = 35)
	public String getSalesorganisation() {
		return this.salesorganisation;
	}

	public void setSalesorganisation(String salesorganisation) {
		this.salesorganisation = salesorganisation;
	}

	@Column(name = "DOCUMENTTYPE", length = 40)
	public String getDocumenttype() {
		return this.documenttype;
	}

	public void setDocumenttype(String documenttype) {
		this.documenttype = documenttype;
	}

	@Column(name = "BUSINESSIDENTIFIER", length = 30)
	public String getBusinessidentifier() {
		return this.businessidentifier;
	}

	public void setBusinessidentifier(String businessidentifier) {
		this.businessidentifier = businessidentifier;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "INSTRUCTIONDATE", length = 19)
	public Date getInstructiondate() {
		return this.instructiondate;
	}

	public void setInstructiondate(Date instructiondate) {
		this.instructiondate = instructiondate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "REQUESTEDPROCESSDATE", length = 19)
	public Date getRequestedprocessdate() {
		return this.requestedprocessdate;
	}

	public void setRequestedprocessdate(Date requestedprocessdate) {
		this.requestedprocessdate = requestedprocessdate;
	}

	@Column(name = "REFERENCETYPECODE", length = 20)
	public String getReferencetypecode() {
		return this.referencetypecode;
	}

	public void setReferencetypecode(String referencetypecode) {
		this.referencetypecode = referencetypecode;
	}

	@Column(name = "SHIPPINGCONDITIONS", length = 20)
	public String getShippingconditions() {
		return this.shippingconditions;
	}

	public void setShippingconditions(String shippingconditions) {
		this.shippingconditions = shippingconditions;
	}

	@Column(name = "BUSINESSPARTNERNR", length = 20)
	public String getBusinesspartnernr() {
		return this.businesspartnernr;
	}

	public void setBusinesspartnernr(String businesspartnernr) {
		this.businesspartnernr = businesspartnernr;
	}

	@Column(name = "BUSINESSPARTNERNAME", length = 50)
	public String getBusinesspartnername() {
		return this.businesspartnername;
	}

	public void setBusinesspartnername(String businesspartnername) {
		this.businesspartnername = businesspartnername;
	}

	@Column(name = "ADDRESSLINE1", length = 50)
	public String getAddressline1() {
		return this.addressline1;
	}

	public void setAddressline1(String addressline1) {
		this.addressline1 = addressline1;
	}

	@Column(name = "ADDRESSLINE2", length = 50)
	public String getAddressline2() {
		return this.addressline2;
	}

	public void setAddressline2(String addressline2) {
		this.addressline2 = addressline2;
	}

	@Column(name = "ADDRESSLINE3", length = 50)
	public String getAddressline3() {
		return this.addressline3;
	}

	public void setAddressline3(String addressline3) {
		this.addressline3 = addressline3;
	}

	@Column(name = "STREET", length = 50)
	public String getStreet() {
		return this.street;
	}

	public void setStreet(String street) {
		this.street = street;
	}

	@Column(name = "CITY", length = 50)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "POSTALCODE", length = 16)
	public String getPostalcode() {
		return this.postalcode;
	}

	public void setPostalcode(String postalcode) {
		this.postalcode = postalcode;
	}

	@Column(name = "COUNTRY", length = 4)
	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	@Column(name = "INSTRUCTIONNOTES", length = 80)
	public String getInstructionnotes() {
		return this.instructionnotes;
	}

	public void setInstructionnotes(String instructionnotes) {
		this.instructionnotes = instructionnotes;
	}

	@Column(name = "FILERECEIVED", length = 50)
	public String getFilereceived() {
		return this.filereceived;
	}

	public void setFilereceived(String filereceived) {
		this.filereceived = filereceived;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "TIMESTAMPRECEIVED", length = 19)
	public Date getTimestampreceived() {
		return this.timestampreceived;
	}

	public void setTimestampreceived(Date timestampreceived) {
		this.timestampreceived = timestampreceived;
	}

	@Column(name = "FILESEQUENCENR", precision = 7, scale = 0)
	public Integer getFilesequencenr() {
		return this.filesequencenr;
	}

	public void setFilesequencenr(Integer filesequencenr) {
		this.filesequencenr = filesequencenr;
	}

	@Column(name = "TRANSACTIONID", length = 50)
	public String getTransactionid() {
		return this.transactionid;
	}

	public void setTransactionid(String transactionid) {
		this.transactionid = transactionid;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "TIMESTAMPCONFIRMATION", length = 19)
	public Date getTimestampconfirmation() {
		return this.timestampconfirmation;
	}

	public void setTimestampconfirmation(Date timestampconfirmation) {
		this.timestampconfirmation = timestampconfirmation;
	}

	@Column(name = "FILECONFIRMED", length = 50)
	public String getFileconfirmed() {
		return this.fileconfirmed;
	}

	public void setFileconfirmed(String fileconfirmed) {
		this.fileconfirmed = fileconfirmed;
	}

	@Column(name = "PROGRAMNAME", length = 10)
	public String getProgramname() {
		return this.programname;
	}

	public void setProgramname(String programname) {
		this.programname = programname;
	}

	@Column(name = "PROCESSINGFLAG1", length = 1)
	public String getProcessingflag1() {
		return this.processingflag1;
	}

	public void setProcessingflag1(String processingflag1) {
		this.processingflag1 = processingflag1;
	}

	@Column(name = "PROCESSINGFLAG2", length = 1)
	public String getProcessingflag2() {
		return this.processingflag2;
	}

	public void setProcessingflag2(String processingflag2) {
		this.processingflag2 = processingflag2;
	}

	@Column(name = "PROCESSINGFLAG3", length = 1)
	public String getProcessingflag3() {
		return this.processingflag3;
	}

	public void setProcessingflag3(String processingflag3) {
		this.processingflag3 = processingflag3;
	}

	@Column(name = "PROCESSINGFLAG4", length = 1)
	public String getProcessingflag4() {
		return this.processingflag4;
	}

	public void setProcessingflag4(String processingflag4) {
		this.processingflag4 = processingflag4;
	}

	@Column(name = "PROCESSINGFLAG5", length = 1)
	public String getProcessingflag5() {
		return this.processingflag5;
	}

	public void setProcessingflag5(String processingflag5) {
		this.processingflag5 = processingflag5;
	}

	@Column(name = "PROCESSINGFLAG6", length = 1)
	public String getProcessingflag6() {
		return this.processingflag6;
	}

	public void setProcessingflag6(String processingflag6) {
		this.processingflag6 = processingflag6;
	}

	@Column(name = "PROCESSINGFLAG7", length = 1)
	public String getProcessingflag7() {
		return this.processingflag7;
	}

	public void setProcessingflag7(String processingflag7) {
		this.processingflag7 = processingflag7;
	}

	@Column(name = "PROCESSINGFLAG8", length = 1)
	public String getProcessingflag8() {
		return this.processingflag8;
	}

	public void setProcessingflag8(String processingflag8) {
		this.processingflag8 = processingflag8;
	}

	@Column(name = "PROCESSINGFLAG9", length = 1)
	public String getProcessingflag9() {
		return this.processingflag9;
	}

	public void setProcessingflag9(String processingflag9) {
		this.processingflag9 = processingflag9;
	}

	@Column(name = "PROCESSINGFLAG10", length = 1)
	public String getProcessingflag10() {
		return this.processingflag10;
	}

	public void setProcessingflag10(String processingflag10) {
		this.processingflag10 = processingflag10;
	}

	@Column(name = "RECORDPROCESSEDFLAG", length = 1)
	public String getRecordprocessedflag() {
		return this.recordprocessedflag;
	}

	public void setRecordprocessedflag(String recordprocessedflag) {
		this.recordprocessedflag = recordprocessedflag;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "RECORDPROCESSINGTIME", length = 19)
	public Date getRecordprocessingtime() {
		return this.recordprocessingtime;
	}

	public void setRecordprocessingtime(Date recordprocessingtime) {
		this.recordprocessingtime = recordprocessingtime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "RECORDLASTCHANGETIME", length = 19)
	public Date getRecordlastchangetime() {
		return this.recordlastchangetime;
	}

	public void setRecordlastchangetime(Date recordlastchangetime) {
		this.recordlastchangetime = recordlastchangetime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "RECORDCREATIONTIME", nullable = false, length = 19)
	public Date getRecordcreationtime() {
		return this.recordcreationtime;
	}

	public void setRecordcreationtime(Date recordcreationtime) {
		this.recordcreationtime = recordcreationtime;
	}

}
