package com.galexis.alloga2mysql.model;

// Generated Mar 4, 2013 4:41:13 PM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Psilincnf generated by hbm2java
 */
@Entity
@Table(name = "PSILINCNF")
public class Psilincnf implements java.io.Serializable {

	private long pk;

	private long psilinpk;

	private long psihdrpk;

	private int confirmationlinenr;

	private String salesorganisation;

	private long itemmasterpk;

	private String itemnr;

	private String itemnrcontractor;

	private String batchid;

	private Date batchexpirydate;

	private String batchidcontractor;

	private String serialnr;

	private BigDecimal processedqty;

	private String unit;

	private Date transactiondate;

	private Long invmovmntpk;

	private String warehouse;

	private String zone;

	private String location;

	private String stockstatus;

	private String qcflag;

	private Integer timedatepk;

	private Integer ipWarehouse;

	private Integer ipZone;

	private Integer ipLocation;

	private Integer ipStockstatus;

	private Integer ipTimedatepkReporting;

	private String programname;

	private String filename;

	private String processingflag1;

	private String processingflag2;

	private String processingflag3;

	private String processingflag4;

	private String processingflag5;

	private String processingflag6;

	private String processingflag7;

	private String processingflag8;

	private String processingflag9;

	private String processingflag10;

	private String backendreleased;

	private String outboundignore;

	private String transactionid;

	private String recordprocessedflag;

	private Date recordprocessingtime;

	private Date recordlastchangetime;

	private Date recordcreationtime;

	public Psilincnf() {
	}

	public Psilincnf(long pk, long psilinpk, long psihdrpk, int confirmationlinenr, long itemmasterpk, String itemnr, Date recordcreationtime) {
		this.pk = pk;
		this.psilinpk = psilinpk;
		this.psihdrpk = psihdrpk;
		this.confirmationlinenr = confirmationlinenr;
		this.itemmasterpk = itemmasterpk;
		this.itemnr = itemnr;
		this.recordcreationtime = recordcreationtime;
	}

	public Psilincnf(long pk, long psilinpk, long psihdrpk, int confirmationlinenr, String salesorganisation, long itemmasterpk, String itemnr, String itemnrcontractor,
	        String batchid, Date batchexpirydate, String batchidcontractor, String serialnr, BigDecimal processedqty, String unit, Date transactiondate, Long invmovmntpk,
	        String warehouse, String zone, String location, String stockstatus, String qcflag, Integer timedatepk, Integer ipWarehouse, Integer ipZone, Integer ipLocation,
	        Integer ipStockstatus, Integer ipTimedatepkReporting, String programname, String filename, String processingflag1, String processingflag2, String processingflag3,
	        String processingflag4, String processingflag5, String processingflag6, String processingflag7, String processingflag8, String processingflag9,
	        String processingflag10, String backendreleased, String outboundignore, String transactionid, String recordprocessedflag, Date recordprocessingtime,
	        Date recordlastchangetime, Date recordcreationtime) {
		this.pk = pk;
		this.psilinpk = psilinpk;
		this.psihdrpk = psihdrpk;
		this.confirmationlinenr = confirmationlinenr;
		this.salesorganisation = salesorganisation;
		this.itemmasterpk = itemmasterpk;
		this.itemnr = itemnr;
		this.itemnrcontractor = itemnrcontractor;
		this.batchid = batchid;
		this.batchexpirydate = batchexpirydate;
		this.batchidcontractor = batchidcontractor;
		this.serialnr = serialnr;
		this.processedqty = processedqty;
		this.unit = unit;
		this.transactiondate = transactiondate;
		this.invmovmntpk = invmovmntpk;
		this.warehouse = warehouse;
		this.zone = zone;
		this.location = location;
		this.stockstatus = stockstatus;
		this.qcflag = qcflag;
		this.timedatepk = timedatepk;
		this.ipWarehouse = ipWarehouse;
		this.ipZone = ipZone;
		this.ipLocation = ipLocation;
		this.ipStockstatus = ipStockstatus;
		this.ipTimedatepkReporting = ipTimedatepkReporting;
		this.programname = programname;
		this.filename = filename;
		this.processingflag1 = processingflag1;
		this.processingflag2 = processingflag2;
		this.processingflag3 = processingflag3;
		this.processingflag4 = processingflag4;
		this.processingflag5 = processingflag5;
		this.processingflag6 = processingflag6;
		this.processingflag7 = processingflag7;
		this.processingflag8 = processingflag8;
		this.processingflag9 = processingflag9;
		this.processingflag10 = processingflag10;
		this.backendreleased = backendreleased;
		this.outboundignore = outboundignore;
		this.transactionid = transactionid;
		this.recordprocessedflag = recordprocessedflag;
		this.recordprocessingtime = recordprocessingtime;
		this.recordlastchangetime = recordlastchangetime;
		this.recordcreationtime = recordcreationtime;
	}

	@Id
	@Column(name = "PK", unique = true, nullable = false, precision = 12, scale = 0)
	public long getPk() {
		return this.pk;
	}

	public void setPk(long pk) {
		this.pk = pk;
	}

	@Column(name = "PSILINPK", nullable = false, precision = 12, scale = 0)
	public long getPsilinpk() {
		return this.psilinpk;
	}

	public void setPsilinpk(long psilinpk) {
		this.psilinpk = psilinpk;
	}

	@Column(name = "PSIHDRPK", nullable = false, precision = 12, scale = 0)
	public long getPsihdrpk() {
		return this.psihdrpk;
	}

	public void setPsihdrpk(long psihdrpk) {
		this.psihdrpk = psihdrpk;
	}

	@Column(name = "CONFIRMATIONLINENR", nullable = false, precision = 6, scale = 0)
	public int getConfirmationlinenr() {
		return this.confirmationlinenr;
	}

	public void setConfirmationlinenr(int confirmationlinenr) {
		this.confirmationlinenr = confirmationlinenr;
	}

	@Column(name = "SALESORGANISATION", length = 35)
	public String getSalesorganisation() {
		return this.salesorganisation;
	}

	public void setSalesorganisation(String salesorganisation) {
		this.salesorganisation = salesorganisation;
	}

	@Column(name = "ITEMMASTERPK", nullable = false, precision = 12, scale = 0)
	public long getItemmasterpk() {
		return this.itemmasterpk;
	}

	public void setItemmasterpk(long itemmasterpk) {
		this.itemmasterpk = itemmasterpk;
	}

	@Column(name = "ITEMNR", nullable = false, length = 35)
	public String getItemnr() {
		return this.itemnr;
	}

	public void setItemnr(String itemnr) {
		this.itemnr = itemnr;
	}

	@Column(name = "ITEMNRCONTRACTOR", length = 35)
	public String getItemnrcontractor() {
		return this.itemnrcontractor;
	}

	public void setItemnrcontractor(String itemnrcontractor) {
		this.itemnrcontractor = itemnrcontractor;
	}

	@Column(name = "BATCHID", length = 20)
	public String getBatchid() {
		return this.batchid;
	}

	public void setBatchid(String batchid) {
		this.batchid = batchid;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "BATCHEXPIRYDATE", length = 19)
	public Date getBatchexpirydate() {
		return this.batchexpirydate;
	}

	public void setBatchexpirydate(Date batchexpirydate) {
		this.batchexpirydate = batchexpirydate;
	}

	@Column(name = "BATCHIDCONTRACTOR", length = 20)
	public String getBatchidcontractor() {
		return this.batchidcontractor;
	}

	public void setBatchidcontractor(String batchidcontractor) {
		this.batchidcontractor = batchidcontractor;
	}

	@Column(name = "SERIALNR", length = 30)
	public String getSerialnr() {
		return this.serialnr;
	}

	public void setSerialnr(String serialnr) {
		this.serialnr = serialnr;
	}

	@Column(name = "PROCESSEDQTY", precision = 15, scale = 3)
	public BigDecimal getProcessedqty() {
		return this.processedqty;
	}

	public void setProcessedqty(BigDecimal processedqty) {
		this.processedqty = processedqty;
	}

	@Column(name = "UNIT", length = 10)
	public String getUnit() {
		return this.unit;
	}

	public void setUnit(String unit) {
		this.unit = unit;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "TRANSACTIONDATE", length = 19)
	public Date getTransactiondate() {
		return this.transactiondate;
	}

	public void setTransactiondate(Date transactiondate) {
		this.transactiondate = transactiondate;
	}

	@Column(name = "INVMOVMNTPK", precision = 12, scale = 0)
	public Long getInvmovmntpk() {
		return this.invmovmntpk;
	}

	public void setInvmovmntpk(Long invmovmntpk) {
		this.invmovmntpk = invmovmntpk;
	}

	@Column(name = "WAREHOUSE", length = 10)
	public String getWarehouse() {
		return this.warehouse;
	}

	public void setWarehouse(String warehouse) {
		this.warehouse = warehouse;
	}

	@Column(name = "ZONE", length = 10)
	public String getZone() {
		return this.zone;
	}

	public void setZone(String zone) {
		this.zone = zone;
	}

	@Column(name = "LOCATION", length = 10)
	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	@Column(name = "STOCKSTATUS", length = 10)
	public String getStockstatus() {
		return this.stockstatus;
	}

	public void setStockstatus(String stockstatus) {
		this.stockstatus = stockstatus;
	}

	@Column(name = "QCFLAG", length = 1)
	public String getQcflag() {
		return this.qcflag;
	}

	public void setQcflag(String qcflag) {
		this.qcflag = qcflag;
	}

	@Column(name = "TIMEDATEPK", precision = 8, scale = 0)
	public Integer getTimedatepk() {
		return this.timedatepk;
	}

	public void setTimedatepk(Integer timedatepk) {
		this.timedatepk = timedatepk;
	}

	@Column(name = "IP_WAREHOUSE", precision = 5, scale = 0)
	public Integer getIpWarehouse() {
		return this.ipWarehouse;
	}

	public void setIpWarehouse(Integer ipWarehouse) {
		this.ipWarehouse = ipWarehouse;
	}

	@Column(name = "IP_ZONE", precision = 5, scale = 0)
	public Integer getIpZone() {
		return this.ipZone;
	}

	public void setIpZone(Integer ipZone) {
		this.ipZone = ipZone;
	}

	@Column(name = "IP_LOCATION", precision = 5, scale = 0)
	public Integer getIpLocation() {
		return this.ipLocation;
	}

	public void setIpLocation(Integer ipLocation) {
		this.ipLocation = ipLocation;
	}

	@Column(name = "IP_STOCKSTATUS", precision = 5, scale = 0)
	public Integer getIpStockstatus() {
		return this.ipStockstatus;
	}

	public void setIpStockstatus(Integer ipStockstatus) {
		this.ipStockstatus = ipStockstatus;
	}

	@Column(name = "IP_TIMEDATEPK_REPORTING", precision = 8, scale = 0)
	public Integer getIpTimedatepkReporting() {
		return this.ipTimedatepkReporting;
	}

	public void setIpTimedatepkReporting(Integer ipTimedatepkReporting) {
		this.ipTimedatepkReporting = ipTimedatepkReporting;
	}

	@Column(name = "PROGRAMNAME", length = 10)
	public String getProgramname() {
		return this.programname;
	}

	public void setProgramname(String programname) {
		this.programname = programname;
	}

	@Column(name = "FILENAME", length = 10)
	public String getFilename() {
		return this.filename;
	}

	public void setFilename(String filename) {
		this.filename = filename;
	}

	@Column(name = "PROCESSINGFLAG1", length = 1)
	public String getProcessingflag1() {
		return this.processingflag1;
	}

	public void setProcessingflag1(String processingflag1) {
		this.processingflag1 = processingflag1;
	}

	@Column(name = "PROCESSINGFLAG2", length = 1)
	public String getProcessingflag2() {
		return this.processingflag2;
	}

	public void setProcessingflag2(String processingflag2) {
		this.processingflag2 = processingflag2;
	}

	@Column(name = "PROCESSINGFLAG3", length = 1)
	public String getProcessingflag3() {
		return this.processingflag3;
	}

	public void setProcessingflag3(String processingflag3) {
		this.processingflag3 = processingflag3;
	}

	@Column(name = "PROCESSINGFLAG4", length = 1)
	public String getProcessingflag4() {
		return this.processingflag4;
	}

	public void setProcessingflag4(String processingflag4) {
		this.processingflag4 = processingflag4;
	}

	@Column(name = "PROCESSINGFLAG5", length = 1)
	public String getProcessingflag5() {
		return this.processingflag5;
	}

	public void setProcessingflag5(String processingflag5) {
		this.processingflag5 = processingflag5;
	}

	@Column(name = "PROCESSINGFLAG6", length = 1)
	public String getProcessingflag6() {
		return this.processingflag6;
	}

	public void setProcessingflag6(String processingflag6) {
		this.processingflag6 = processingflag6;
	}

	@Column(name = "PROCESSINGFLAG7", length = 1)
	public String getProcessingflag7() {
		return this.processingflag7;
	}

	public void setProcessingflag7(String processingflag7) {
		this.processingflag7 = processingflag7;
	}

	@Column(name = "PROCESSINGFLAG8", length = 1)
	public String getProcessingflag8() {
		return this.processingflag8;
	}

	public void setProcessingflag8(String processingflag8) {
		this.processingflag8 = processingflag8;
	}

	@Column(name = "PROCESSINGFLAG9", length = 1)
	public String getProcessingflag9() {
		return this.processingflag9;
	}

	public void setProcessingflag9(String processingflag9) {
		this.processingflag9 = processingflag9;
	}

	@Column(name = "PROCESSINGFLAG10", length = 1)
	public String getProcessingflag10() {
		return this.processingflag10;
	}

	public void setProcessingflag10(String processingflag10) {
		this.processingflag10 = processingflag10;
	}

	@Column(name = "BACKENDRELEASED", length = 1)
	public String getBackendreleased() {
		return this.backendreleased;
	}

	public void setBackendreleased(String backendreleased) {
		this.backendreleased = backendreleased;
	}

	@Column(name = "OUTBOUNDIGNORE", length = 1)
	public String getOutboundignore() {
		return this.outboundignore;
	}

	public void setOutboundignore(String outboundignore) {
		this.outboundignore = outboundignore;
	}

	@Column(name = "TRANSACTIONID", length = 50)
	public String getTransactionid() {
		return this.transactionid;
	}

	public void setTransactionid(String transactionid) {
		this.transactionid = transactionid;
	}

	@Column(name = "RECORDPROCESSEDFLAG", length = 1)
	public String getRecordprocessedflag() {
		return this.recordprocessedflag;
	}

	public void setRecordprocessedflag(String recordprocessedflag) {
		this.recordprocessedflag = recordprocessedflag;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "RECORDPROCESSINGTIME", length = 19)
	public Date getRecordprocessingtime() {
		return this.recordprocessingtime;
	}

	public void setRecordprocessingtime(Date recordprocessingtime) {
		this.recordprocessingtime = recordprocessingtime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "RECORDLASTCHANGETIME", length = 19)
	public Date getRecordlastchangetime() {
		return this.recordlastchangetime;
	}

	public void setRecordlastchangetime(Date recordlastchangetime) {
		this.recordlastchangetime = recordlastchangetime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "RECORDCREATIONTIME", nullable = false, length = 19)
	public Date getRecordcreationtime() {
		return this.recordcreationtime;
	}

	public void setRecordcreationtime(Date recordcreationtime) {
		this.recordcreationtime = recordcreationtime;
	}

}
