package com.galexis.alloga2mysql.model;

// Generated Mar 4, 2013 4:41:13 PM by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Rethdr generated by hbm2java
 */
@Entity
@Table(name = "RETHDR")
public class Rethdr implements java.io.Serializable {

	private long pk;

	private long contrdefpk;

	private long incidentnr;

	private Date incidentdate;

	private String salesorganisation;

	private String salesorganisationdesc;

	private String principlereferencenr;

	private long bizparaddrpk;

	private String customercontractor;

	private String problemcode;

	private String resolutioncode;

	private String galHandler;

	private Date customerreturndate;

	private String customerreference;

	private String typeofreference;

	private Long referencenr;

	private Integer timedatepk;

	private Integer ipTimedatepkReporting;

	private String programname;

	private String filename;

	private String processingflag1;

	private String processingflag2;

	private String processingflag3;

	private String processingflag4;

	private String processingflag5;

	private String processingflag6;

	private String processingflag7;

	private String processingflag8;

	private String processingflag9;

	private String processingflag10;

	private String backendreleased;

	private String outboundignore;

	private String transactionid;

	private String recordprocessedflag;

	private Date recordprocessingtime;

	private Date recordlastchangetime;

	private Date recordcreationtime;

	public Rethdr() {
	}

	public Rethdr(long pk, long contrdefpk, long incidentnr, Date incidentdate, long bizparaddrpk, String backendreleased, String outboundignore, String recordprocessedflag,
	        Date recordcreationtime) {
		this.pk = pk;
		this.contrdefpk = contrdefpk;
		this.incidentnr = incidentnr;
		this.incidentdate = incidentdate;
		this.bizparaddrpk = bizparaddrpk;
		this.backendreleased = backendreleased;
		this.outboundignore = outboundignore;
		this.recordprocessedflag = recordprocessedflag;
		this.recordcreationtime = recordcreationtime;
	}

	public Rethdr(long pk, long contrdefpk, long incidentnr, Date incidentdate, String salesorganisation, String salesorganisationdesc, String principlereferencenr,
	        long bizparaddrpk, String customercontractor, String problemcode, String resolutioncode, String handler, Date customerreturndate, String customerreference,
	        String typeofreference, Long referencenr, Integer timedatepk, Integer ipTimedatepkReporting, String programname, String filename, String processingflag1,
	        String processingflag2, String processingflag3, String processingflag4, String processingflag5, String processingflag6, String processingflag7, String processingflag8,
	        String processingflag9, String processingflag10, String backendreleased, String outboundignore, String transactionid, String recordprocessedflag,
	        Date recordprocessingtime, Date recordlastchangetime, Date recordcreationtime) {
		this.pk = pk;
		this.contrdefpk = contrdefpk;
		this.incidentnr = incidentnr;
		this.incidentdate = incidentdate;
		this.salesorganisation = salesorganisation;
		this.salesorganisationdesc = salesorganisationdesc;
		this.principlereferencenr = principlereferencenr;
		this.bizparaddrpk = bizparaddrpk;
		this.customercontractor = customercontractor;
		this.problemcode = problemcode;
		this.resolutioncode = resolutioncode;
		this.galHandler = handler;
		this.customerreturndate = customerreturndate;
		this.customerreference = customerreference;
		this.typeofreference = typeofreference;
		this.referencenr = referencenr;
		this.timedatepk = timedatepk;
		this.ipTimedatepkReporting = ipTimedatepkReporting;
		this.programname = programname;
		this.filename = filename;
		this.processingflag1 = processingflag1;
		this.processingflag2 = processingflag2;
		this.processingflag3 = processingflag3;
		this.processingflag4 = processingflag4;
		this.processingflag5 = processingflag5;
		this.processingflag6 = processingflag6;
		this.processingflag7 = processingflag7;
		this.processingflag8 = processingflag8;
		this.processingflag9 = processingflag9;
		this.processingflag10 = processingflag10;
		this.backendreleased = backendreleased;
		this.outboundignore = outboundignore;
		this.transactionid = transactionid;
		this.recordprocessedflag = recordprocessedflag;
		this.recordprocessingtime = recordprocessingtime;
		this.recordlastchangetime = recordlastchangetime;
		this.recordcreationtime = recordcreationtime;
	}

	@Id
	@Column(name = "PK", unique = true, nullable = false, precision = 12, scale = 0)
	public long getPk() {
		return this.pk;
	}

	public void setPk(long pk) {
		this.pk = pk;
	}

	@Column(name = "CONTRDEFPK", nullable = false, precision = 12, scale = 0)
	public long getContrdefpk() {
		return this.contrdefpk;
	}

	public void setContrdefpk(long contrdefpk) {
		this.contrdefpk = contrdefpk;
	}

	@Column(name = "INCIDENTNR", nullable = false, precision = 12, scale = 0)
	public long getIncidentnr() {
		return this.incidentnr;
	}

	public void setIncidentnr(long incidentnr) {
		this.incidentnr = incidentnr;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "INCIDENTDATE", nullable = false, length = 19)
	public Date getIncidentdate() {
		return this.incidentdate;
	}

	public void setIncidentdate(Date incidentdate) {
		this.incidentdate = incidentdate;
	}

	@Column(name = "SALESORGANISATION", length = 30)
	public String getSalesorganisation() {
		return this.salesorganisation;
	}

	public void setSalesorganisation(String salesorganisation) {
		this.salesorganisation = salesorganisation;
	}

	@Column(name = "SALESORGANISATIONDESC", length = 50)
	public String getSalesorganisationdesc() {
		return this.salesorganisationdesc;
	}

	public void setSalesorganisationdesc(String salesorganisationdesc) {
		this.salesorganisationdesc = salesorganisationdesc;
	}

	@Column(name = "PRINCIPLEREFERENCENR", length = 35)
	public String getPrinciplereferencenr() {
		return this.principlereferencenr;
	}

	public void setPrinciplereferencenr(String principlereferencenr) {
		this.principlereferencenr = principlereferencenr;
	}

	@Column(name = "BIZPARADDRPK", nullable = false, precision = 12, scale = 0)
	public long getBizparaddrpk() {
		return this.bizparaddrpk;
	}

	public void setBizparaddrpk(long bizparaddrpk) {
		this.bizparaddrpk = bizparaddrpk;
	}

	@Column(name = "CUSTOMERCONTRACTOR", length = 30)
	public String getCustomercontractor() {
		return this.customercontractor;
	}

	public void setCustomercontractor(String customercontractor) {
		this.customercontractor = customercontractor;
	}

	@Column(name = "PROBLEMCODE", length = 10)
	public String getProblemcode() {
		return this.problemcode;
	}

	public void setProblemcode(String problemcode) {
		this.problemcode = problemcode;
	}

	@Column(name = "RESOLUTIONCODE", length = 10)
	public String getResolutioncode() {
		return this.resolutioncode;
	}

	public void setResolutioncode(String resolutioncode) {
		this.resolutioncode = resolutioncode;
	}

	@Column(name = "HANDLER", length = 10)
	public String getGalHandler() {
		return this.galHandler;
	}

	public void setGalHandler(String handler) {
		this.galHandler = handler;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CUSTOMERRETURNDATE", length = 19)
	public Date getCustomerreturndate() {
		return this.customerreturndate;
	}

	public void setCustomerreturndate(Date customerreturndate) {
		this.customerreturndate = customerreturndate;
	}

	@Column(name = "CUSTOMERREFERENCE", length = 30)
	public String getCustomerreference() {
		return this.customerreference;
	}

	public void setCustomerreference(String customerreference) {
		this.customerreference = customerreference;
	}

	@Column(name = "TYPEOFREFERENCE", length = 1)
	public String getTypeofreference() {
		return this.typeofreference;
	}

	public void setTypeofreference(String typeofreference) {
		this.typeofreference = typeofreference;
	}

	@Column(name = "REFERENCENR", precision = 12, scale = 0)
	public Long getReferencenr() {
		return this.referencenr;
	}

	public void setReferencenr(Long referencenr) {
		this.referencenr = referencenr;
	}

	@Column(name = "TIMEDATEPK", precision = 8, scale = 0)
	public Integer getTimedatepk() {
		return this.timedatepk;
	}

	public void setTimedatepk(Integer timedatepk) {
		this.timedatepk = timedatepk;
	}

	@Column(name = "IP_TIMEDATEPK_REPORTING", precision = 8, scale = 0)
	public Integer getIpTimedatepkReporting() {
		return this.ipTimedatepkReporting;
	}

	public void setIpTimedatepkReporting(Integer ipTimedatepkReporting) {
		this.ipTimedatepkReporting = ipTimedatepkReporting;
	}

	@Column(name = "PROGRAMNAME", length = 10)
	public String getProgramname() {
		return this.programname;
	}

	public void setProgramname(String programname) {
		this.programname = programname;
	}

	@Column(name = "FILENAME", length = 10)
	public String getFilename() {
		return this.filename;
	}

	public void setFilename(String filename) {
		this.filename = filename;
	}

	@Column(name = "PROCESSINGFLAG1", length = 1)
	public String getProcessingflag1() {
		return this.processingflag1;
	}

	public void setProcessingflag1(String processingflag1) {
		this.processingflag1 = processingflag1;
	}

	@Column(name = "PROCESSINGFLAG2", length = 1)
	public String getProcessingflag2() {
		return this.processingflag2;
	}

	public void setProcessingflag2(String processingflag2) {
		this.processingflag2 = processingflag2;
	}

	@Column(name = "PROCESSINGFLAG3", length = 1)
	public String getProcessingflag3() {
		return this.processingflag3;
	}

	public void setProcessingflag3(String processingflag3) {
		this.processingflag3 = processingflag3;
	}

	@Column(name = "PROCESSINGFLAG4", length = 1)
	public String getProcessingflag4() {
		return this.processingflag4;
	}

	public void setProcessingflag4(String processingflag4) {
		this.processingflag4 = processingflag4;
	}

	@Column(name = "PROCESSINGFLAG5", length = 1)
	public String getProcessingflag5() {
		return this.processingflag5;
	}

	public void setProcessingflag5(String processingflag5) {
		this.processingflag5 = processingflag5;
	}

	@Column(name = "PROCESSINGFLAG6", length = 1)
	public String getProcessingflag6() {
		return this.processingflag6;
	}

	public void setProcessingflag6(String processingflag6) {
		this.processingflag6 = processingflag6;
	}

	@Column(name = "PROCESSINGFLAG7", length = 1)
	public String getProcessingflag7() {
		return this.processingflag7;
	}

	public void setProcessingflag7(String processingflag7) {
		this.processingflag7 = processingflag7;
	}

	@Column(name = "PROCESSINGFLAG8", length = 1)
	public String getProcessingflag8() {
		return this.processingflag8;
	}

	public void setProcessingflag8(String processingflag8) {
		this.processingflag8 = processingflag8;
	}

	@Column(name = "PROCESSINGFLAG9", length = 1)
	public String getProcessingflag9() {
		return this.processingflag9;
	}

	public void setProcessingflag9(String processingflag9) {
		this.processingflag9 = processingflag9;
	}

	@Column(name = "PROCESSINGFLAG10", length = 1)
	public String getProcessingflag10() {
		return this.processingflag10;
	}

	public void setProcessingflag10(String processingflag10) {
		this.processingflag10 = processingflag10;
	}

	@Column(name = "BACKENDRELEASED", nullable = false, length = 1)
	public String getBackendreleased() {
		return this.backendreleased;
	}

	public void setBackendreleased(String backendreleased) {
		this.backendreleased = backendreleased;
	}

	@Column(name = "OUTBOUNDIGNORE", nullable = false, length = 1)
	public String getOutboundignore() {
		return this.outboundignore;
	}

	public void setOutboundignore(String outboundignore) {
		this.outboundignore = outboundignore;
	}

	@Column(name = "TRANSACTIONID", length = 50)
	public String getTransactionid() {
		return this.transactionid;
	}

	public void setTransactionid(String transactionid) {
		this.transactionid = transactionid;
	}

	@Column(name = "RECORDPROCESSEDFLAG", nullable = false, length = 1)
	public String getRecordprocessedflag() {
		return this.recordprocessedflag;
	}

	public void setRecordprocessedflag(String recordprocessedflag) {
		this.recordprocessedflag = recordprocessedflag;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "RECORDPROCESSINGTIME", length = 19)
	public Date getRecordprocessingtime() {
		return this.recordprocessingtime;
	}

	public void setRecordprocessingtime(Date recordprocessingtime) {
		this.recordprocessingtime = recordprocessingtime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "RECORDLASTCHANGETIME", length = 19)
	public Date getRecordlastchangetime() {
		return this.recordlastchangetime;
	}

	public void setRecordlastchangetime(Date recordlastchangetime) {
		this.recordlastchangetime = recordlastchangetime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "RECORDCREATIONTIME", nullable = false, length = 19)
	public Date getRecordcreationtime() {
		return this.recordcreationtime;
	}

	public void setRecordcreationtime(Date recordcreationtime) {
		this.recordcreationtime = recordcreationtime;
	}

}
