package com.galexis.alloga2mysql.model;

// Generated Mar 4, 2013 4:41:13 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Selstcattr generated by hbm2java
 */
@Entity
@Table(name = "SELSTCATTR")
public class Selstcattr implements java.io.Serializable {

	private long pk;

	private String name;

	private String value;

	private Long selstcelempk;

	public Selstcattr() {
	}

	public Selstcattr(long pk, String name, String value) {
		this.pk = pk;
		this.name = name;
		this.value = value;
	}

	public Selstcattr(long pk, String name, String value, Long selstcelempk) {
		this.pk = pk;
		this.name = name;
		this.value = value;
		this.selstcelempk = selstcelempk;
	}

	@Id
	@Column(name = "PK", unique = true, nullable = false, precision = 12, scale = 0)
	public long getPk() {
		return this.pk;
	}

	public void setPk(long pk) {
		this.pk = pk;
	}

	@Column(name = "NAME", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "VALUE", nullable = false, length = 2048)
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	@Column(name = "SELSTCELEMPK", precision = 12, scale = 0)
	public Long getSelstcelempk() {
		return this.selstcelempk;
	}

	public void setSelstcelempk(Long selstcelempk) {
		this.selstcelempk = selstcelempk;
	}

}
