package com.galexis.alloga2mysql.model;

// Generated Mar 4, 2013 4:41:13 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Selstcelem generated by hbm2java
 */
@Entity
@Table(name = "SELSTCELEM")
public class Selstcelem implements java.io.Serializable {

	private long pk;

	private String version;

	private String name;

	private String token;

	private String value;

	private Long selmsgtdefpk;

	private Long selstcelempk;

	public Selstcelem() {
	}

	public Selstcelem(long pk, String name, String token, String value) {
		this.pk = pk;
		this.name = name;
		this.token = token;
		this.value = value;
	}

	public Selstcelem(long pk, String name, String token, String value, Long selmsgtdefpk, Long selstcelempk) {
		this.pk = pk;
		this.name = name;
		this.token = token;
		this.value = value;
		this.selmsgtdefpk = selmsgtdefpk;
		this.selstcelempk = selstcelempk;
	}

	@Id
	@Column(name = "PK", unique = true, nullable = false, precision = 12, scale = 0)
	public long getPk() {
		return this.pk;
	}

	public void setPk(long pk) {
		this.pk = pk;
	}

	@Column(name = "VERSION", nullable = false, length = 8)
	public String getVersion() {
		return this.version;
	}

	public void setVersion(String version) {
		this.version = version;
	}

	@Column(name = "NAME", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "TOKEN", nullable = false)
	public String getToken() {
		return this.token;
	}

	public void setToken(String token) {
		this.token = token;
	}

	@Column(name = "VALUE", nullable = false, length = 2048)
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	@Column(name = "SELMSGTDEFPK", precision = 12, scale = 0)
	public Long getSelmsgtdefpk() {
		return this.selmsgtdefpk;
	}

	public void setSelmsgtdefpk(Long selmsgtdefpk) {
		this.selmsgtdefpk = selmsgtdefpk;
	}

	@Column(name = "SELSTCELEMPK", precision = 12, scale = 0)
	public Long getSelstcelempk() {
		return this.selstcelempk;
	}

	public void setSelstcelempk(Long selstcelempk) {
		this.selstcelempk = selstcelempk;
	}

}
