package com.galexis.alloga2mysql.model;

// Generated Mar 4, 2013 4:41:13 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Stockrcmap generated by hbm2java
 */
@Entity
@Table(name = "STOCKRCMAP", uniqueConstraints = @UniqueConstraint(columnNames = { "CONTRDEFPK", "SALESORGANISATION", "WAREHOUSE",
        "LOCATIONZONE", "LOCATIONID", "LOCATIONSTATUS", "BULKFLAG", "QCFLAG", "NCCFLAG", "BATCHREASONCODE" }))
public class Stockrcmap implements java.io.Serializable {

	private long pk;

	private long contrdefpk;

	private String salesorganisation;

	private String warehouse;

	private String locationzone;

	private String locationid;

	private String locationstatus;

	private String bulkflag;

	private String qcflag;

	private String batchreasoncode;

	private String nccflag;

	private String plant;

	private String storagelocation;

	private String stockstatus;

	private Short reportcolumn;

	private String notreportedstockflag;

	private String valueconversiononip;

	private String isactiveflag;

	private Date recordcreationtime;

	private Date recordlastchangetime;

	private String userlastchange;

	public Stockrcmap() {
	}

	public Stockrcmap(long pk, long contrdefpk, String isactiveflag, Date recordcreationtime) {
		this.pk = pk;
		this.contrdefpk = contrdefpk;
		this.isactiveflag = isactiveflag;
		this.recordcreationtime = recordcreationtime;
	}

	public Stockrcmap(long pk, long contrdefpk, String salesorganisation, String warehouse, String locationzone, String locationid, String locationstatus, String bulkflag,
	        String qcflag, String batchreasoncode, String nccflag, String plant, String storagelocation, String stockstatus, Short reportcolumn, String notreportedstockflag,
	        String valueconversiononip, String isactiveflag, Date recordcreationtime, Date recordlastchangetime, String userlastchange) {
		this.pk = pk;
		this.contrdefpk = contrdefpk;
		this.salesorganisation = salesorganisation;
		this.warehouse = warehouse;
		this.locationzone = locationzone;
		this.locationid = locationid;
		this.locationstatus = locationstatus;
		this.bulkflag = bulkflag;
		this.qcflag = qcflag;
		this.batchreasoncode = batchreasoncode;
		this.nccflag = nccflag;
		this.plant = plant;
		this.storagelocation = storagelocation;
		this.stockstatus = stockstatus;
		this.reportcolumn = reportcolumn;
		this.notreportedstockflag = notreportedstockflag;
		this.valueconversiononip = valueconversiononip;
		this.isactiveflag = isactiveflag;
		this.recordcreationtime = recordcreationtime;
		this.recordlastchangetime = recordlastchangetime;
		this.userlastchange = userlastchange;
	}

	@Id
	@Column(name = "PK", unique = true, nullable = false, precision = 12, scale = 0)
	public long getPk() {
		return this.pk;
	}

	public void setPk(long pk) {
		this.pk = pk;
	}

	@Column(name = "CONTRDEFPK", nullable = false, precision = 12, scale = 0)
	public long getContrdefpk() {
		return this.contrdefpk;
	}

	public void setContrdefpk(long contrdefpk) {
		this.contrdefpk = contrdefpk;
	}

	@Column(name = "SALESORGANISATION", length = 20)
	public String getSalesorganisation() {
		return this.salesorganisation;
	}

	public void setSalesorganisation(String salesorganisation) {
		this.salesorganisation = salesorganisation;
	}

	@Column(name = "WAREHOUSE", length = 4)
	public String getWarehouse() {
		return this.warehouse;
	}

	public void setWarehouse(String warehouse) {
		this.warehouse = warehouse;
	}

	@Column(name = "LOCATIONZONE", length = 4)
	public String getLocationzone() {
		return this.locationzone;
	}

	public void setLocationzone(String locationzone) {
		this.locationzone = locationzone;
	}

	@Column(name = "LOCATIONID", length = 8)
	public String getLocationid() {
		return this.locationid;
	}

	public void setLocationid(String locationid) {
		this.locationid = locationid;
	}

	@Column(name = "LOCATIONSTATUS", length = 4)
	public String getLocationstatus() {
		return this.locationstatus;
	}

	public void setLocationstatus(String locationstatus) {
		this.locationstatus = locationstatus;
	}

	@Column(name = "BULKFLAG", length = 1)
	public String getBulkflag() {
		return this.bulkflag;
	}

	public void setBulkflag(String bulkflag) {
		this.bulkflag = bulkflag;
	}

	@Column(name = "QCFLAG", length = 1)
	public String getQcflag() {
		return this.qcflag;
	}

	public void setQcflag(String qcflag) {
		this.qcflag = qcflag;
	}

	@Column(name = "BATCHREASONCODE", length = 5)
	public String getBatchreasoncode() {
		return this.batchreasoncode;
	}

	public void setBatchreasoncode(String batchreasoncode) {
		this.batchreasoncode = batchreasoncode;
	}

	@Column(name = "NCCFLAG", length = 1)
	public String getNccflag() {
		return this.nccflag;
	}

	public void setNccflag(String nccflag) {
		this.nccflag = nccflag;
	}

	@Column(name = "PLANT", length = 20)
	public String getPlant() {
		return this.plant;
	}

	public void setPlant(String plant) {
		this.plant = plant;
	}

	@Column(name = "STORAGELOCATION", length = 20)
	public String getStoragelocation() {
		return this.storagelocation;
	}

	public void setStoragelocation(String storagelocation) {
		this.storagelocation = storagelocation;
	}

	@Column(name = "STOCKSTATUS", length = 20)
	public String getStockstatus() {
		return this.stockstatus;
	}

	public void setStockstatus(String stockstatus) {
		this.stockstatus = stockstatus;
	}

	@Column(name = "REPORTCOLUMN", precision = 3, scale = 0)
	public Short getReportcolumn() {
		return this.reportcolumn;
	}

	public void setReportcolumn(Short reportcolumn) {
		this.reportcolumn = reportcolumn;
	}

	@Column(name = "NOTREPORTEDSTOCKFLAG", length = 1)
	public String getNotreportedstockflag() {
		return this.notreportedstockflag;
	}

	public void setNotreportedstockflag(String notreportedstockflag) {
		this.notreportedstockflag = notreportedstockflag;
	}

	@Column(name = "VALUECONVERSIONONIP", length = 1)
	public String getValueconversiononip() {
		return this.valueconversiononip;
	}

	public void setValueconversiononip(String valueconversiononip) {
		this.valueconversiononip = valueconversiononip;
	}

	@Column(name = "ISACTIVEFLAG", nullable = false, length = 1)
	public String getIsactiveflag() {
		return this.isactiveflag;
	}

	public void setIsactiveflag(String isactiveflag) {
		this.isactiveflag = isactiveflag;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "RECORDCREATIONTIME", nullable = false, length = 19)
	public Date getRecordcreationtime() {
		return this.recordcreationtime;
	}

	public void setRecordcreationtime(Date recordcreationtime) {
		this.recordcreationtime = recordcreationtime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "RECORDLASTCHANGETIME", length = 19)
	public Date getRecordlastchangetime() {
		return this.recordlastchangetime;
	}

	public void setRecordlastchangetime(Date recordlastchangetime) {
		this.recordlastchangetime = recordlastchangetime;
	}

	@Column(name = "USERLASTCHANGE", length = 20)
	public String getUserlastchange() {
		return this.userlastchange;
	}

	public void setUserlastchange(String userlastchange) {
		this.userlastchange = userlastchange;
	}

}
