package com.galexis.alloga2mysql.model;

// Generated Mar 4, 2013 4:41:13 PM by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TrLgProc generated by hbm2java
 */
@Entity
@Table(name = "TR_LG_PROC")
public class TrLgProc implements java.io.Serializable {

	private TrLgProcId id;

	public TrLgProc() {
	}

	public TrLgProc(TrLgProcId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "crTime", column = @Column(name = "CR_TIME", nullable = false, length = 19)),
	        @AttributeOverride(name = "serverId", column = @Column(name = "SERVER_ID", nullable = false, length = 10)),
	        @AttributeOverride(name = "appId", column = @Column(name = "APP_ID", nullable = false, length = 10)),
	        @AttributeOverride(name = "tag", column = @Column(name = "TAG", nullable = false, length = 80)),
	        @AttributeOverride(name = "messagetyp", column = @Column(name = "MESSAGETYP", nullable = false, length = 50)),
	        @AttributeOverride(name = "messagever", column = @Column(name = "MESSAGEVER", nullable = false, length = 5)),
	        @AttributeOverride(name = "taskId", column = @Column(name = "TASK_ID", nullable = false, length = 36)),
	        @AttributeOverride(name = "refId", column = @Column(name = "REF_ID", nullable = false, length = 50)),
	        @AttributeOverride(name = "transId", column = @Column(name = "TRANS_ID", nullable = false, length = 36)),
	        @AttributeOverride(name = "partnerId", column = @Column(name = "PARTNER_ID", nullable = false, length = 50)),
	        @AttributeOverride(name = "clientId", column = @Column(name = "CLIENT_ID", nullable = false, length = 30)),
	        @AttributeOverride(name = "severity", column = @Column(name = "SEVERITY", nullable = false, length = 1)),
	        @AttributeOverride(name = "info", column = @Column(name = "INFO", nullable = false, length = 2048)),
	        @AttributeOverride(name = "summary", column = @Column(name = "SUMMARY", nullable = false, length = 250)) })
	public TrLgProcId getId() {
		return this.id;
	}

	public void setId(TrLgProcId id) {
		this.id = id;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CR_TIME", length = 19, updatable = false, insertable = false)
	public Date getRecordcreationtime() {
		return this.id.getCrTime();
	}

	public void setRecordcreationtime(Date recordcreationtime) {
		this.id.setCrTime(recordcreationtime);
	}

}
