package com.galexis.alloga2mysql.model;

// Generated Mar 4, 2013 4:41:13 PM by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Trstatinf generated by hbm2java
 */
@Entity
@Table(name = "TRSTATINF", uniqueConstraints = @UniqueConstraint(columnNames = { "PARTNER", "MESSAGETYP", "SEQ_NO" }))
public class Trstatinf implements java.io.Serializable {

	private TrstatinfId id;

	public Trstatinf() {
	}

	public Trstatinf(TrstatinfId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "taskId", column = @Column(name = "TASK_ID", nullable = false, length = 36)),
	        @AttributeOverride(name = "transId", column = @Column(name = "TRANS_ID", nullable = false, length = 36)),
	        @AttributeOverride(name = "partner", column = @Column(name = "PARTNER", nullable = false, length = 10)),
	        @AttributeOverride(name = "contrdefpk", column = @Column(name = "CONTRDEFPK", precision = 12, scale = 0)),
	        @AttributeOverride(name = "messagetyp", column = @Column(name = "MESSAGETYP", nullable = false, length = 50)),
	        @AttributeOverride(name = "messagever", column = @Column(name = "MESSAGEVER", nullable = false, length = 5)),
	        @AttributeOverride(name = "seqNo", column = @Column(name = "SEQ_NO", nullable = false, precision = 35, scale = 0)),
	        @AttributeOverride(name = "filename", column = @Column(name = "FILENAME", nullable = false, length = 250)),
	        @AttributeOverride(name = "direction", column = @Column(name = "DIRECTION", nullable = false, length = 1)),
	        @AttributeOverride(name = "recordCnt", column = @Column(name = "RECORD_CNT", nullable = false, precision = 10, scale = 0)),
	        @AttributeOverride(name = "processed", column = @Column(name = "PROCESSED", nullable = false, length = 1)),
	        @AttributeOverride(name = "procTs", column = @Column(name = "PROC_TS", nullable = false, length = 19)),
	        @AttributeOverride(name = "pcmlRetc", column = @Column(name = "PCML_RETC", nullable = false, length = 1)),
	        @AttributeOverride(name = "pcmlRetm", column = @Column(name = "PCML_RETM", nullable = false, length = 100)),
	        @AttributeOverride(name = "creatTs", column = @Column(name = "CREAT_TS", nullable = false, length = 19)) })
	public TrstatinfId getId() {
		return this.id;
	}

	public void setId(TrstatinfId id) {
		this.id = id;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREAT_TS", length = 19, updatable = false, insertable = false)
	public Date getRecordcreationtime() {
		return this.id.getCreatTs();
	}

	public void setRecordcreationtime(Date recordcreationtime) {
		this.id.setCreatTs(recordcreationtime);
	}

}
