package com.galexis.configdb;
// Generated Sep 6, 2013 10:20:44 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * BackendResource generated by hbm2java
 */
@Entity
@Table(name="BackendResource"
    ,catalog="integrationConfigDB"
    , uniqueConstraints = @UniqueConstraint(columnNames="BackendResource") 
)
public class BackendResource  implements java.io.Serializable {


     private Integer pk;
     private Metadata metadata;
     private String backendResource;
     private boolean global;
     private Set<ConversionDefinition> conversionDefinitions = new HashSet<ConversionDefinition>(0);
     private Set<DataStoreEntity> dataStoreEntities = new HashSet<DataStoreEntity>(0);
     private Set<MessageTypeDefinition> messageTypeDefinitions = new HashSet<MessageTypeDefinition>(0);
     private Set<PartnerGroup> partnerGroups = new HashSet<PartnerGroup>(0);
     private Set<Partner> partners = new HashSet<Partner>(0);
     private Set<TaskMessageTypeDefinition> taskMessageTypeDefinitions = new HashSet<TaskMessageTypeDefinition>(0);
     private Set<BusinessServiceDefinition> businessServiceDefinitions = new HashSet<BusinessServiceDefinition>(0);
     private Set<ConfigurationHeader> configurationHeaders = new HashSet<ConfigurationHeader>(0);
     private Set<ValueConversion> valueConversions = new HashSet<ValueConversion>(0);
     private Set<StartTaskContentElement> startTaskContentElements = new HashSet<StartTaskContentElement>(0);
     private Set<ConditionSchema> conditionSchemas = new HashSet<ConditionSchema>(0);
     private Set<MappingDefinition> mappingDefinitions = new HashSet<MappingDefinition>(0);

    public BackendResource() {
    }

	
    public BackendResource(Metadata metadata, String backendResource, boolean global) {
        this.metadata = metadata;
        this.backendResource = backendResource;
        this.global = global;
    }
    public BackendResource(Metadata metadata, String backendResource, boolean global, Set<ConversionDefinition> conversionDefinitions, Set<DataStoreEntity> dataStoreEntities, Set<MessageTypeDefinition> messageTypeDefinitions, Set<PartnerGroup> partnerGroups, Set<Partner> partners, Set<TaskMessageTypeDefinition> taskMessageTypeDefinitions, Set<BusinessServiceDefinition> businessServiceDefinitions, Set<ConfigurationHeader> configurationHeaders, Set<ValueConversion> valueConversions, Set<StartTaskContentElement> startTaskContentElements, Set<ConditionSchema> conditionSchemas, Set<MappingDefinition> mappingDefinitions) {
       this.metadata = metadata;
       this.backendResource = backendResource;
       this.global = global;
       this.conversionDefinitions = conversionDefinitions;
       this.dataStoreEntities = dataStoreEntities;
       this.messageTypeDefinitions = messageTypeDefinitions;
       this.partnerGroups = partnerGroups;
       this.partners = partners;
       this.taskMessageTypeDefinitions = taskMessageTypeDefinitions;
       this.businessServiceDefinitions = businessServiceDefinitions;
       this.configurationHeaders = configurationHeaders;
       this.valueConversions = valueConversions;
       this.startTaskContentElements = startTaskContentElements;
       this.conditionSchemas = conditionSchemas;
       this.mappingDefinitions = mappingDefinitions;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="PK", unique=true, nullable=false)
    public Integer getPk() {
        return this.pk;
    }
    
    public void setPk(Integer pk) {
        this.pk = pk;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="MetadataPK", nullable=false)
    public Metadata getMetadata() {
        return this.metadata;
    }
    
    public void setMetadata(Metadata metadata) {
        this.metadata = metadata;
    }

    
    @Column(name="BackendResource", unique=true, nullable=false, length=20)
    public String getBackendResource() {
        return this.backendResource;
    }
    
    public void setBackendResource(String backendResource) {
        this.backendResource = backendResource;
    }

    
    @Column(name="Global", nullable=false)
    public boolean isGlobal() {
        return this.global;
    }
    
    public void setGlobal(boolean global) {
        this.global = global;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="backendResource")
    public Set<ConversionDefinition> getConversionDefinitions() {
        return this.conversionDefinitions;
    }
    
    public void setConversionDefinitions(Set<ConversionDefinition> conversionDefinitions) {
        this.conversionDefinitions = conversionDefinitions;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="backendResource")
    public Set<DataStoreEntity> getDataStoreEntities() {
        return this.dataStoreEntities;
    }
    
    public void setDataStoreEntities(Set<DataStoreEntity> dataStoreEntities) {
        this.dataStoreEntities = dataStoreEntities;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="backendResource")
    public Set<MessageTypeDefinition> getMessageTypeDefinitions() {
        return this.messageTypeDefinitions;
    }
    
    public void setMessageTypeDefinitions(Set<MessageTypeDefinition> messageTypeDefinitions) {
        this.messageTypeDefinitions = messageTypeDefinitions;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="backendResource")
    public Set<PartnerGroup> getPartnerGroups() {
        return this.partnerGroups;
    }
    
    public void setPartnerGroups(Set<PartnerGroup> partnerGroups) {
        this.partnerGroups = partnerGroups;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="backendResource")
    public Set<Partner> getPartners() {
        return this.partners;
    }
    
    public void setPartners(Set<Partner> partners) {
        this.partners = partners;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="backendResource")
    public Set<TaskMessageTypeDefinition> getTaskMessageTypeDefinitions() {
        return this.taskMessageTypeDefinitions;
    }
    
    public void setTaskMessageTypeDefinitions(Set<TaskMessageTypeDefinition> taskMessageTypeDefinitions) {
        this.taskMessageTypeDefinitions = taskMessageTypeDefinitions;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="backendResource")
    public Set<BusinessServiceDefinition> getBusinessServiceDefinitions() {
        return this.businessServiceDefinitions;
    }
    
    public void setBusinessServiceDefinitions(Set<BusinessServiceDefinition> businessServiceDefinitions) {
        this.businessServiceDefinitions = businessServiceDefinitions;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="backendResource")
    public Set<ConfigurationHeader> getConfigurationHeaders() {
        return this.configurationHeaders;
    }
    
    public void setConfigurationHeaders(Set<ConfigurationHeader> configurationHeaders) {
        this.configurationHeaders = configurationHeaders;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="backendResource")
    public Set<ValueConversion> getValueConversions() {
        return this.valueConversions;
    }
    
    public void setValueConversions(Set<ValueConversion> valueConversions) {
        this.valueConversions = valueConversions;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="backendResource")
    public Set<StartTaskContentElement> getStartTaskContentElements() {
        return this.startTaskContentElements;
    }
    
    public void setStartTaskContentElements(Set<StartTaskContentElement> startTaskContentElements) {
        this.startTaskContentElements = startTaskContentElements;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="backendResource")
    public Set<ConditionSchema> getConditionSchemas() {
        return this.conditionSchemas;
    }
    
    public void setConditionSchemas(Set<ConditionSchema> conditionSchemas) {
        this.conditionSchemas = conditionSchemas;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="backendResource")
    public Set<MappingDefinition> getMappingDefinitions() {
        return this.mappingDefinitions;
    }
    
    public void setMappingDefinitions(Set<MappingDefinition> mappingDefinitions) {
        this.mappingDefinitions = mappingDefinitions;
    }




}


