package com.galexis.configdb;
// Generated Sep 6, 2013 10:20:44 AM by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ConditionDefinitionDetails generated by hbm2java
 */
@Entity
@Table(name="ConditionDefinitionDetails"
    ,catalog="integrationConfigDB"
)
public class ConditionDefinitionDetails  implements java.io.Serializable {


     private Integer pk;
     private ConditionDefinition conditionDefinition;
     private ConditionSchema2dataStoreFieldRelation conditionSchema2dataStoreFieldRelation;
     private String conditionValue;
     private boolean ognlExpression;

    public ConditionDefinitionDetails() {
    }

	
    public ConditionDefinitionDetails(ConditionDefinition conditionDefinition, ConditionSchema2dataStoreFieldRelation conditionSchema2dataStoreFieldRelation, boolean ognlExpression) {
        this.conditionDefinition = conditionDefinition;
        this.conditionSchema2dataStoreFieldRelation = conditionSchema2dataStoreFieldRelation;
        this.ognlExpression = ognlExpression;
    }
    public ConditionDefinitionDetails(ConditionDefinition conditionDefinition, ConditionSchema2dataStoreFieldRelation conditionSchema2dataStoreFieldRelation, String conditionValue, boolean ognlExpression) {
       this.conditionDefinition = conditionDefinition;
       this.conditionSchema2dataStoreFieldRelation = conditionSchema2dataStoreFieldRelation;
       this.conditionValue = conditionValue;
       this.ognlExpression = ognlExpression;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="PK", unique=true, nullable=false)
    public Integer getPk() {
        return this.pk;
    }
    
    public void setPk(Integer pk) {
        this.pk = pk;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ConditionDefinitionPK", nullable=false)
    public ConditionDefinition getConditionDefinition() {
        return this.conditionDefinition;
    }
    
    public void setConditionDefinition(ConditionDefinition conditionDefinition) {
        this.conditionDefinition = conditionDefinition;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ConditionSchema2DataStoreFieldRelationPK", nullable=false)
    public ConditionSchema2dataStoreFieldRelation getConditionSchema2dataStoreFieldRelation() {
        return this.conditionSchema2dataStoreFieldRelation;
    }
    
    public void setConditionSchema2dataStoreFieldRelation(ConditionSchema2dataStoreFieldRelation conditionSchema2dataStoreFieldRelation) {
        this.conditionSchema2dataStoreFieldRelation = conditionSchema2dataStoreFieldRelation;
    }

    
    @Column(name="ConditionValue")
    public String getConditionValue() {
        return this.conditionValue;
    }
    
    public void setConditionValue(String conditionValue) {
        this.conditionValue = conditionValue;
    }

    
    @Column(name="OgnlExpression", nullable=false)
    public boolean isOgnlExpression() {
        return this.ognlExpression;
    }
    
    public void setOgnlExpression(boolean ognlExpression) {
        this.ognlExpression = ognlExpression;
    }




}


