package com.galexis.configdb;
// Generated Sep 6, 2013 10:20:44 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;

/**
 * ConditionSchema generated by hbm2java
 */
@Entity
@Table(name="ConditionSchema"
    ,catalog="integrationConfigDB"
    , uniqueConstraints = @UniqueConstraint(columnNames={"Name", "Version", "PartnerGroupPK"}) 
)
public class ConditionSchema  implements java.io.Serializable {


     private Integer pk;
     private int version;
     private BackendResource backendResource;
     private PartnerGroup partnerGroup;
     private Metadata metadata;
     private String partner;
     private String name;
     private int state;
     private Set<ValueConversion> valueConversions = new HashSet<ValueConversion>(0);
     private Set<ConditionDefinition> conditionDefinitions = new HashSet<ConditionDefinition>(0);
     private Set<ConditionSchema2dataStoreFieldRelation> conditionSchema2dataStoreFieldRelations = new HashSet<ConditionSchema2dataStoreFieldRelation>(0);

    public ConditionSchema() {
    }

	
    public ConditionSchema(PartnerGroup partnerGroup, Metadata metadata, String name, int state) {
        this.partnerGroup = partnerGroup;
        this.metadata = metadata;
        this.name = name;
        this.state = state;
    }
    public ConditionSchema(BackendResource backendResource, PartnerGroup partnerGroup, Metadata metadata, String partner, String name, int state, Set<ValueConversion> valueConversions, Set<ConditionDefinition> conditionDefinitions, Set<ConditionSchema2dataStoreFieldRelation> conditionSchema2dataStoreFieldRelations) {
       this.backendResource = backendResource;
       this.partnerGroup = partnerGroup;
       this.metadata = metadata;
       this.partner = partner;
       this.name = name;
       this.state = state;
       this.valueConversions = valueConversions;
       this.conditionDefinitions = conditionDefinitions;
       this.conditionSchema2dataStoreFieldRelations = conditionSchema2dataStoreFieldRelations;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="PK", unique=true, nullable=false)
    public Integer getPk() {
        return this.pk;
    }
    
    public void setPk(Integer pk) {
        this.pk = pk;
    }

    @Version
    @Column(name="Version", nullable=false)
    public int getVersion() {
        return this.version;
    }
    
    public void setVersion(int version) {
        this.version = version;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="BackendResourcePK")
    public BackendResource getBackendResource() {
        return this.backendResource;
    }
    
    public void setBackendResource(BackendResource backendResource) {
        this.backendResource = backendResource;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PartnerGroupPK", nullable=false)
    public PartnerGroup getPartnerGroup() {
        return this.partnerGroup;
    }
    
    public void setPartnerGroup(PartnerGroup partnerGroup) {
        this.partnerGroup = partnerGroup;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="MetadataPK", nullable=false)
    public Metadata getMetadata() {
        return this.metadata;
    }
    
    public void setMetadata(Metadata metadata) {
        this.metadata = metadata;
    }

    
    @Column(name="Partner", length=20)
    public String getPartner() {
        return this.partner;
    }
    
    public void setPartner(String partner) {
        this.partner = partner;
    }

    
    @Column(name="Name", nullable=false, length=128)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="State", nullable=false)
    public int getState() {
        return this.state;
    }
    
    public void setState(int state) {
        this.state = state;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="conditionSchema")
    public Set<ValueConversion> getValueConversions() {
        return this.valueConversions;
    }
    
    public void setValueConversions(Set<ValueConversion> valueConversions) {
        this.valueConversions = valueConversions;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="conditionSchema")
    public Set<ConditionDefinition> getConditionDefinitions() {
        return this.conditionDefinitions;
    }
    
    public void setConditionDefinitions(Set<ConditionDefinition> conditionDefinitions) {
        this.conditionDefinitions = conditionDefinitions;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="conditionSchema")
    public Set<ConditionSchema2dataStoreFieldRelation> getConditionSchema2dataStoreFieldRelations() {
        return this.conditionSchema2dataStoreFieldRelations;
    }
    
    public void setConditionSchema2dataStoreFieldRelations(Set<ConditionSchema2dataStoreFieldRelation> conditionSchema2dataStoreFieldRelations) {
        this.conditionSchema2dataStoreFieldRelations = conditionSchema2dataStoreFieldRelations;
    }




}


