package com.galexis.configdb;
// Generated Sep 6, 2013 10:20:44 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;

/**
 * ConfigurationHeader generated by hbm2java
 */
@Entity
@Table(name="ConfigurationHeader"
    ,catalog="integrationConfigDB"
    , uniqueConstraints = @UniqueConstraint(columnNames={"Name", "Version", "PartnerGroupPK"}) 
)
public class ConfigurationHeader  implements java.io.Serializable {


     private int pk;
     private int version;
     private BackendResource backendResource;
     private PartnerGroup partnerGroup;
     private Metadata metadata;
     private String name;
     private String partner;
     private int state;
     private Set<ConfigurationHeaderMessageTypeDefinition> configurationHeaderMessageTypeDefinitions = new HashSet<ConfigurationHeaderMessageTypeDefinition>(0);
     private Set<StartTaskContentAttribute> startTaskContentAttributes = new HashSet<StartTaskContentAttribute>(0);
     private Set<ConfigurationValue> configurationValues = new HashSet<ConfigurationValue>(0);

    public ConfigurationHeader() {
    }

	
    public ConfigurationHeader(int pk, PartnerGroup partnerGroup, Metadata metadata, String name, int state) {
        this.pk = pk;
        this.partnerGroup = partnerGroup;
        this.metadata = metadata;
        this.name = name;
        this.state = state;
    }
    public ConfigurationHeader(int pk, BackendResource backendResource, PartnerGroup partnerGroup, Metadata metadata, String name, String partner, int state, Set<ConfigurationHeaderMessageTypeDefinition> configurationHeaderMessageTypeDefinitions, Set<StartTaskContentAttribute> startTaskContentAttributes, Set<ConfigurationValue> configurationValues) {
       this.pk = pk;
       this.backendResource = backendResource;
       this.partnerGroup = partnerGroup;
       this.metadata = metadata;
       this.name = name;
       this.partner = partner;
       this.state = state;
       this.configurationHeaderMessageTypeDefinitions = configurationHeaderMessageTypeDefinitions;
       this.startTaskContentAttributes = startTaskContentAttributes;
       this.configurationValues = configurationValues;
    }
   
     @Id 

    
    @Column(name="PK", unique=true, nullable=false)
    public int getPk() {
        return this.pk;
    }
    
    public void setPk(int pk) {
        this.pk = pk;
    }

    @Version
    @Column(name="Version", nullable=false)
    public int getVersion() {
        return this.version;
    }
    
    public void setVersion(int version) {
        this.version = version;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="BackendResourcePK")
    public BackendResource getBackendResource() {
        return this.backendResource;
    }
    
    public void setBackendResource(BackendResource backendResource) {
        this.backendResource = backendResource;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PartnerGroupPK", nullable=false)
    public PartnerGroup getPartnerGroup() {
        return this.partnerGroup;
    }
    
    public void setPartnerGroup(PartnerGroup partnerGroup) {
        this.partnerGroup = partnerGroup;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="MetadataPK", nullable=false)
    public Metadata getMetadata() {
        return this.metadata;
    }
    
    public void setMetadata(Metadata metadata) {
        this.metadata = metadata;
    }

    
    @Column(name="Name", nullable=false, length=128)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="Partner", length=20)
    public String getPartner() {
        return this.partner;
    }
    
    public void setPartner(String partner) {
        this.partner = partner;
    }

    
    @Column(name="State", nullable=false)
    public int getState() {
        return this.state;
    }
    
    public void setState(int state) {
        this.state = state;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="configurationHeader")
    public Set<ConfigurationHeaderMessageTypeDefinition> getConfigurationHeaderMessageTypeDefinitions() {
        return this.configurationHeaderMessageTypeDefinitions;
    }
    
    public void setConfigurationHeaderMessageTypeDefinitions(Set<ConfigurationHeaderMessageTypeDefinition> configurationHeaderMessageTypeDefinitions) {
        this.configurationHeaderMessageTypeDefinitions = configurationHeaderMessageTypeDefinitions;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="configurationHeader")
    public Set<StartTaskContentAttribute> getStartTaskContentAttributes() {
        return this.startTaskContentAttributes;
    }
    
    public void setStartTaskContentAttributes(Set<StartTaskContentAttribute> startTaskContentAttributes) {
        this.startTaskContentAttributes = startTaskContentAttributes;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="configurationHeader")
    public Set<ConfigurationValue> getConfigurationValues() {
        return this.configurationValues;
    }
    
    public void setConfigurationValues(Set<ConfigurationValue> configurationValues) {
        this.configurationValues = configurationValues;
    }




}


