package com.galexis.configdb;
// Generated Sep 6, 2013 10:20:44 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * ConfigurationKey generated by hbm2java
 */
@Entity
@Table(name="ConfigurationKey"
    ,catalog="integrationConfigDB"
    , uniqueConstraints = @UniqueConstraint(columnNames="Key") 
)
public class ConfigurationKey  implements java.io.Serializable {


     private Integer pk;
     private Metadata metadata;
     private String key;
     private int keyRelationType;
     private Set<ConfigurationHeaderMessageTypeDefinition> configurationHeaderMessageTypeDefinitions = new HashSet<ConfigurationHeaderMessageTypeDefinition>(0);
     private Set<MsgTypeDef2msgTypeDef> msgTypeDef2msgTypeDefs = new HashSet<MsgTypeDef2msgTypeDef>(0);

    public ConfigurationKey() {
    }

	
    public ConfigurationKey(Metadata metadata, String key, int keyRelationType) {
        this.metadata = metadata;
        this.key = key;
        this.keyRelationType = keyRelationType;
    }
    public ConfigurationKey(Metadata metadata, String key, int keyRelationType, Set<ConfigurationHeaderMessageTypeDefinition> configurationHeaderMessageTypeDefinitions, Set<MsgTypeDef2msgTypeDef> msgTypeDef2msgTypeDefs) {
       this.metadata = metadata;
       this.key = key;
       this.keyRelationType = keyRelationType;
       this.configurationHeaderMessageTypeDefinitions = configurationHeaderMessageTypeDefinitions;
       this.msgTypeDef2msgTypeDefs = msgTypeDef2msgTypeDefs;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="PK", unique=true, nullable=false)
    public Integer getPk() {
        return this.pk;
    }
    
    public void setPk(Integer pk) {
        this.pk = pk;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="MetadataPK", nullable=false)
    public Metadata getMetadata() {
        return this.metadata;
    }
    
    public void setMetadata(Metadata metadata) {
        this.metadata = metadata;
    }

    
    @Column(name="Key", unique=true, nullable=false, length=128)
    public String getKey() {
        return this.key;
    }
    
    public void setKey(String key) {
        this.key = key;
    }

    
    @Column(name="KeyRelationType", nullable=false)
    public int getKeyRelationType() {
        return this.keyRelationType;
    }
    
    public void setKeyRelationType(int keyRelationType) {
        this.keyRelationType = keyRelationType;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="configurationKey")
    public Set<ConfigurationHeaderMessageTypeDefinition> getConfigurationHeaderMessageTypeDefinitions() {
        return this.configurationHeaderMessageTypeDefinitions;
    }
    
    public void setConfigurationHeaderMessageTypeDefinitions(Set<ConfigurationHeaderMessageTypeDefinition> configurationHeaderMessageTypeDefinitions) {
        this.configurationHeaderMessageTypeDefinitions = configurationHeaderMessageTypeDefinitions;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="configurationKey")
    public Set<MsgTypeDef2msgTypeDef> getMsgTypeDef2msgTypeDefs() {
        return this.msgTypeDef2msgTypeDefs;
    }
    
    public void setMsgTypeDef2msgTypeDefs(Set<MsgTypeDef2msgTypeDef> msgTypeDef2msgTypeDefs) {
        this.msgTypeDef2msgTypeDefs = msgTypeDef2msgTypeDefs;
    }




}


