package com.galexis.configdb;
// Generated Sep 6, 2013 10:20:44 AM by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * ConfigurationHeaderMessageTypeDefinition generated by hbm2java
 */
@Entity
@Table(name="ConfigurationHeader_MessageTypeDefinition"
    ,catalog="integrationConfigDB"
    , uniqueConstraints = @UniqueConstraint(columnNames={"MessageTypeDefinitionPK", "ConfigurationHeaderPK", "ConfigurationKeyPK"}) 
)
public class ConfigurationHeaderMessageTypeDefinition  implements java.io.Serializable {


     private Integer pk;
     private MessageTypeDefinition messageTypeDefinition;
     private ConfigurationKey configurationKey;
     private ConfigurationHeader configurationHeader;
     private Metadata metadata;

    public ConfigurationHeaderMessageTypeDefinition() {
    }

    public ConfigurationHeaderMessageTypeDefinition(MessageTypeDefinition messageTypeDefinition, ConfigurationKey configurationKey, ConfigurationHeader configurationHeader, Metadata metadata) {
       this.messageTypeDefinition = messageTypeDefinition;
       this.configurationKey = configurationKey;
       this.configurationHeader = configurationHeader;
       this.metadata = metadata;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="PK", unique=true, nullable=false)
    public Integer getPk() {
        return this.pk;
    }
    
    public void setPk(Integer pk) {
        this.pk = pk;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="MessageTypeDefinitionPK", nullable=false)
    public MessageTypeDefinition getMessageTypeDefinition() {
        return this.messageTypeDefinition;
    }
    
    public void setMessageTypeDefinition(MessageTypeDefinition messageTypeDefinition) {
        this.messageTypeDefinition = messageTypeDefinition;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ConfigurationKeyPK", nullable=false)
    public ConfigurationKey getConfigurationKey() {
        return this.configurationKey;
    }
    
    public void setConfigurationKey(ConfigurationKey configurationKey) {
        this.configurationKey = configurationKey;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ConfigurationHeaderPK", nullable=false)
    public ConfigurationHeader getConfigurationHeader() {
        return this.configurationHeader;
    }
    
    public void setConfigurationHeader(ConfigurationHeader configurationHeader) {
        this.configurationHeader = configurationHeader;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="MetadataPK", nullable=false)
    public Metadata getMetadata() {
        return this.metadata;
    }
    
    public void setMetadata(Metadata metadata) {
        this.metadata = metadata;
    }




}


