package com.galexis.configdb;
// Generated Sep 6, 2013 10:20:44 AM by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * MappingDefinitionBusinessServiceDefinition generated by hbm2java
 */
@Entity
@Table(name="MappingDefinition_BusinessServiceDefinition"
    ,catalog="integrationConfigDB"
    , uniqueConstraints = @UniqueConstraint(columnNames={"BusinessServiceDefinitionPK", "MappingDefinitionPK"}) 
)
public class MappingDefinitionBusinessServiceDefinition  implements java.io.Serializable {


     private int pk;
     private MappingDefinition mappingDefinition;
     private BusinessServiceDefinition businessServiceDefinition;
     private Metadata metadata;

    public MappingDefinitionBusinessServiceDefinition() {
    }

    public MappingDefinitionBusinessServiceDefinition(int pk, MappingDefinition mappingDefinition, BusinessServiceDefinition businessServiceDefinition, Metadata metadata) {
       this.pk = pk;
       this.mappingDefinition = mappingDefinition;
       this.businessServiceDefinition = businessServiceDefinition;
       this.metadata = metadata;
    }
   
     @Id 

    
    @Column(name="PK", unique=true, nullable=false)
    public int getPk() {
        return this.pk;
    }
    
    public void setPk(int pk) {
        this.pk = pk;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="MappingDefinitionPK", nullable=false)
    public MappingDefinition getMappingDefinition() {
        return this.mappingDefinition;
    }
    
    public void setMappingDefinition(MappingDefinition mappingDefinition) {
        this.mappingDefinition = mappingDefinition;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="BusinessServiceDefinitionPK", nullable=false)
    public BusinessServiceDefinition getBusinessServiceDefinition() {
        return this.businessServiceDefinition;
    }
    
    public void setBusinessServiceDefinition(BusinessServiceDefinition businessServiceDefinition) {
        this.businessServiceDefinition = businessServiceDefinition;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="MetadataPK", nullable=false)
    public Metadata getMetadata() {
        return this.metadata;
    }
    
    public void setMetadata(Metadata metadata) {
        this.metadata = metadata;
    }




}


