package com.galexis.configdb;
// Generated Sep 6, 2013 10:20:44 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;

/**
 * MappingDefinition generated by hbm2java
 */
@Entity
@Table(name="MappingDefinition"
    ,catalog="integrationConfigDB"
    , uniqueConstraints = @UniqueConstraint(columnNames={"Name", "Version", "PartnerGroupPK"}) 
)
public class MappingDefinition  implements java.io.Serializable {


     private int pk;
     private int version;
     private BackendResource backendResource;
     private PartnerGroup partnerGroup;
     private Metadata metadata;
     private String name;
     private String partner;
     private String description;
     private int state;
     private Set<MappingDefinitionBusinessServiceDefinition> mappingDefinitionBusinessServiceDefinitions = new HashSet<MappingDefinitionBusinessServiceDefinition>(0);
     private Set<MappingConfiguration> mappingConfigurations = new HashSet<MappingConfiguration>(0);
     private Set<HandlerMappingConfiguration> handlerMappingConfigurations = new HashSet<HandlerMappingConfiguration>(0);
     private Set<DataMapping> dataMappings = new HashSet<DataMapping>(0);

    public MappingDefinition() {
    }

	
    public MappingDefinition(int pk, PartnerGroup partnerGroup, Metadata metadata, String name, int state) {
        this.pk = pk;
        this.partnerGroup = partnerGroup;
        this.metadata = metadata;
        this.name = name;
        this.state = state;
    }
    public MappingDefinition(int pk, BackendResource backendResource, PartnerGroup partnerGroup, Metadata metadata, String name, String partner, String description, int state, Set<MappingDefinitionBusinessServiceDefinition> mappingDefinitionBusinessServiceDefinitions, Set<MappingConfiguration> mappingConfigurations, Set<HandlerMappingConfiguration> handlerMappingConfigurations, Set<DataMapping> dataMappings) {
       this.pk = pk;
       this.backendResource = backendResource;
       this.partnerGroup = partnerGroup;
       this.metadata = metadata;
       this.name = name;
       this.partner = partner;
       this.description = description;
       this.state = state;
       this.mappingDefinitionBusinessServiceDefinitions = mappingDefinitionBusinessServiceDefinitions;
       this.mappingConfigurations = mappingConfigurations;
       this.handlerMappingConfigurations = handlerMappingConfigurations;
       this.dataMappings = dataMappings;
    }
   
     @Id 

    
    @Column(name="PK", unique=true, nullable=false)
    public int getPk() {
        return this.pk;
    }
    
    public void setPk(int pk) {
        this.pk = pk;
    }

    @Version
    @Column(name="Version", nullable=false)
    public int getVersion() {
        return this.version;
    }
    
    public void setVersion(int version) {
        this.version = version;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="BackendResourcePK")
    public BackendResource getBackendResource() {
        return this.backendResource;
    }
    
    public void setBackendResource(BackendResource backendResource) {
        this.backendResource = backendResource;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PartnerGroupPK", nullable=false)
    public PartnerGroup getPartnerGroup() {
        return this.partnerGroup;
    }
    
    public void setPartnerGroup(PartnerGroup partnerGroup) {
        this.partnerGroup = partnerGroup;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="MetadataPK", nullable=false)
    public Metadata getMetadata() {
        return this.metadata;
    }
    
    public void setMetadata(Metadata metadata) {
        this.metadata = metadata;
    }

    
    @Column(name="Name", nullable=false)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="Partner", length=20)
    public String getPartner() {
        return this.partner;
    }
    
    public void setPartner(String partner) {
        this.partner = partner;
    }

    
    @Column(name="Description")
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="State", nullable=false)
    public int getState() {
        return this.state;
    }
    
    public void setState(int state) {
        this.state = state;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="mappingDefinition")
    public Set<MappingDefinitionBusinessServiceDefinition> getMappingDefinitionBusinessServiceDefinitions() {
        return this.mappingDefinitionBusinessServiceDefinitions;
    }
    
    public void setMappingDefinitionBusinessServiceDefinitions(Set<MappingDefinitionBusinessServiceDefinition> mappingDefinitionBusinessServiceDefinitions) {
        this.mappingDefinitionBusinessServiceDefinitions = mappingDefinitionBusinessServiceDefinitions;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="mappingDefinition")
    public Set<MappingConfiguration> getMappingConfigurations() {
        return this.mappingConfigurations;
    }
    
    public void setMappingConfigurations(Set<MappingConfiguration> mappingConfigurations) {
        this.mappingConfigurations = mappingConfigurations;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="mappingDefinition")
    public Set<HandlerMappingConfiguration> getHandlerMappingConfigurations() {
        return this.handlerMappingConfigurations;
    }
    
    public void setHandlerMappingConfigurations(Set<HandlerMappingConfiguration> handlerMappingConfigurations) {
        this.handlerMappingConfigurations = handlerMappingConfigurations;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="mappingDefinition")
    public Set<DataMapping> getDataMappings() {
        return this.dataMappings;
    }
    
    public void setDataMappings(Set<DataMapping> dataMappings) {
        this.dataMappings = dataMappings;
    }




}


