package com.galexis.configdb;
// Generated Sep 6, 2013 10:20:44 AM by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * MsgTypeDef2msgTypeDef generated by hbm2java
 */
@Entity
@Table(name="MsgTypeDef2MsgTypeDef"
    ,catalog="integrationConfigDB"
    , uniqueConstraints = @UniqueConstraint(columnNames={"ParentMessageTypeDefinitionPK", "ConfigurationKeyPK"}) 
)
public class MsgTypeDef2msgTypeDef  implements java.io.Serializable {


     private Integer pk;
     private ConfigurationKey configurationKey;
     private MessageTypeDefinition messageTypeDefinitionByChildMessageTypeDefinitionPk;
     private MessageTypeDefinition messageTypeDefinitionByParentMessageTypeDefinitionPk;
     private Metadata metadata;
     private int sequence;

    public MsgTypeDef2msgTypeDef() {
    }

    public MsgTypeDef2msgTypeDef(ConfigurationKey configurationKey, MessageTypeDefinition messageTypeDefinitionByChildMessageTypeDefinitionPk, MessageTypeDefinition messageTypeDefinitionByParentMessageTypeDefinitionPk, Metadata metadata, int sequence) {
       this.configurationKey = configurationKey;
       this.messageTypeDefinitionByChildMessageTypeDefinitionPk = messageTypeDefinitionByChildMessageTypeDefinitionPk;
       this.messageTypeDefinitionByParentMessageTypeDefinitionPk = messageTypeDefinitionByParentMessageTypeDefinitionPk;
       this.metadata = metadata;
       this.sequence = sequence;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="PK", unique=true, nullable=false)
    public Integer getPk() {
        return this.pk;
    }
    
    public void setPk(Integer pk) {
        this.pk = pk;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ConfigurationKeyPK", nullable=false)
    public ConfigurationKey getConfigurationKey() {
        return this.configurationKey;
    }
    
    public void setConfigurationKey(ConfigurationKey configurationKey) {
        this.configurationKey = configurationKey;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ChildMessageTypeDefinitionPK", nullable=false)
    public MessageTypeDefinition getMessageTypeDefinitionByChildMessageTypeDefinitionPk() {
        return this.messageTypeDefinitionByChildMessageTypeDefinitionPk;
    }
    
    public void setMessageTypeDefinitionByChildMessageTypeDefinitionPk(MessageTypeDefinition messageTypeDefinitionByChildMessageTypeDefinitionPk) {
        this.messageTypeDefinitionByChildMessageTypeDefinitionPk = messageTypeDefinitionByChildMessageTypeDefinitionPk;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ParentMessageTypeDefinitionPK", nullable=false)
    public MessageTypeDefinition getMessageTypeDefinitionByParentMessageTypeDefinitionPk() {
        return this.messageTypeDefinitionByParentMessageTypeDefinitionPk;
    }
    
    public void setMessageTypeDefinitionByParentMessageTypeDefinitionPk(MessageTypeDefinition messageTypeDefinitionByParentMessageTypeDefinitionPk) {
        this.messageTypeDefinitionByParentMessageTypeDefinitionPk = messageTypeDefinitionByParentMessageTypeDefinitionPk;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="MetadataPK", nullable=false)
    public Metadata getMetadata() {
        return this.metadata;
    }
    
    public void setMetadata(Metadata metadata) {
        this.metadata = metadata;
    }

    
    @Column(name="Sequence", nullable=false)
    public int getSequence() {
        return this.sequence;
    }
    
    public void setSequence(int sequence) {
        this.sequence = sequence;
    }




}


