package com.galexis.configdb;
// Generated Sep 6, 2013 10:20:44 AM by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Partner generated by hbm2java
 */
@Entity
@Table(name="Partner"
    ,catalog="integrationConfigDB"
    , uniqueConstraints = @UniqueConstraint(columnNames={"Name", "BackendResourcePK"}) 
)
public class Partner  implements java.io.Serializable {


     private Integer pk;
     private PartnerGroup partnerGroupByPartnerGroupPublicPk;
     private BackendResource backendResource;
     private PartnerGroup partnerGroupByPartnerGroupGlobalPk;
     private PartnerGroup partnerGroupByPartnerGroupPrivatePk;
     private Metadata metadata;
     private String name;

    public Partner() {
    }

	
    public Partner(BackendResource backendResource, Metadata metadata, String name) {
        this.backendResource = backendResource;
        this.metadata = metadata;
        this.name = name;
    }
    public Partner(PartnerGroup partnerGroupByPartnerGroupPublicPk, BackendResource backendResource, PartnerGroup partnerGroupByPartnerGroupGlobalPk, PartnerGroup partnerGroupByPartnerGroupPrivatePk, Metadata metadata, String name) {
       this.partnerGroupByPartnerGroupPublicPk = partnerGroupByPartnerGroupPublicPk;
       this.backendResource = backendResource;
       this.partnerGroupByPartnerGroupGlobalPk = partnerGroupByPartnerGroupGlobalPk;
       this.partnerGroupByPartnerGroupPrivatePk = partnerGroupByPartnerGroupPrivatePk;
       this.metadata = metadata;
       this.name = name;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="PK", unique=true, nullable=false)
    public Integer getPk() {
        return this.pk;
    }
    
    public void setPk(Integer pk) {
        this.pk = pk;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PartnerGroupPublicPK")
    public PartnerGroup getPartnerGroupByPartnerGroupPublicPk() {
        return this.partnerGroupByPartnerGroupPublicPk;
    }
    
    public void setPartnerGroupByPartnerGroupPublicPk(PartnerGroup partnerGroupByPartnerGroupPublicPk) {
        this.partnerGroupByPartnerGroupPublicPk = partnerGroupByPartnerGroupPublicPk;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="BackendResourcePK", nullable=false)
    public BackendResource getBackendResource() {
        return this.backendResource;
    }
    
    public void setBackendResource(BackendResource backendResource) {
        this.backendResource = backendResource;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PartnerGroupGlobalPK")
    public PartnerGroup getPartnerGroupByPartnerGroupGlobalPk() {
        return this.partnerGroupByPartnerGroupGlobalPk;
    }
    
    public void setPartnerGroupByPartnerGroupGlobalPk(PartnerGroup partnerGroupByPartnerGroupGlobalPk) {
        this.partnerGroupByPartnerGroupGlobalPk = partnerGroupByPartnerGroupGlobalPk;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PartnerGroupPrivatePK")
    public PartnerGroup getPartnerGroupByPartnerGroupPrivatePk() {
        return this.partnerGroupByPartnerGroupPrivatePk;
    }
    
    public void setPartnerGroupByPartnerGroupPrivatePk(PartnerGroup partnerGroupByPartnerGroupPrivatePk) {
        this.partnerGroupByPartnerGroupPrivatePk = partnerGroupByPartnerGroupPrivatePk;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="MetadataPK", nullable=false)
    public Metadata getMetadata() {
        return this.metadata;
    }
    
    public void setMetadata(Metadata metadata) {
        this.metadata = metadata;
    }

    
    @Column(name="Name", nullable=false, length=50)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }




}


