package com.galexis.configdb;
// Generated Sep 6, 2013 10:20:44 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * StartTaskContentAttribute generated by hbm2java
 */
@Entity
@Table(name="StartTaskContentAttribute"
    ,catalog="integrationConfigDB"
    , uniqueConstraints = @UniqueConstraint(columnNames={"Name", "StartTaskContentElementPK"}) 
)
public class StartTaskContentAttribute  implements java.io.Serializable {


     private Integer pk;
     private StartTaskContentElement startTaskContentElement;
     private ConfigurationHeader configurationHeader;
     private Metadata metadata;
     private String name;
     private String defaultValue;
     private int attributeType;
     private String formatRegularExpression;
     private String formatDescription;
     private boolean mandatory;
     private String viewPermission;
     private Set<StartTaskContentAttributeValue> startTaskContentAttributeValues = new HashSet<StartTaskContentAttributeValue>(0);
     private Set<StartTaskContentElement> startTaskContentElements = new HashSet<StartTaskContentElement>(0);

    public StartTaskContentAttribute() {
    }

	
    public StartTaskContentAttribute(Metadata metadata, String name, int attributeType, boolean mandatory) {
        this.metadata = metadata;
        this.name = name;
        this.attributeType = attributeType;
        this.mandatory = mandatory;
    }
    public StartTaskContentAttribute(StartTaskContentElement startTaskContentElement, ConfigurationHeader configurationHeader, Metadata metadata, String name, String defaultValue, int attributeType, String formatRegularExpression, String formatDescription, boolean mandatory, String viewPermission, Set<StartTaskContentAttributeValue> startTaskContentAttributeValues, Set<StartTaskContentElement> startTaskContentElements) {
       this.startTaskContentElement = startTaskContentElement;
       this.configurationHeader = configurationHeader;
       this.metadata = metadata;
       this.name = name;
       this.defaultValue = defaultValue;
       this.attributeType = attributeType;
       this.formatRegularExpression = formatRegularExpression;
       this.formatDescription = formatDescription;
       this.mandatory = mandatory;
       this.viewPermission = viewPermission;
       this.startTaskContentAttributeValues = startTaskContentAttributeValues;
       this.startTaskContentElements = startTaskContentElements;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="PK", unique=true, nullable=false)
    public Integer getPk() {
        return this.pk;
    }
    
    public void setPk(Integer pk) {
        this.pk = pk;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="StartTaskContentElementPK")
    public StartTaskContentElement getStartTaskContentElement() {
        return this.startTaskContentElement;
    }
    
    public void setStartTaskContentElement(StartTaskContentElement startTaskContentElement) {
        this.startTaskContentElement = startTaskContentElement;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ConfigurationHeaderPK")
    public ConfigurationHeader getConfigurationHeader() {
        return this.configurationHeader;
    }
    
    public void setConfigurationHeader(ConfigurationHeader configurationHeader) {
        this.configurationHeader = configurationHeader;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="MetadataPK", nullable=false)
    public Metadata getMetadata() {
        return this.metadata;
    }
    
    public void setMetadata(Metadata metadata) {
        this.metadata = metadata;
    }

    
    @Column(name="Name", nullable=false)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="DefaultValue", length=2048)
    public String getDefaultValue() {
        return this.defaultValue;
    }
    
    public void setDefaultValue(String defaultValue) {
        this.defaultValue = defaultValue;
    }

    
    @Column(name="AttributeType", nullable=false)
    public int getAttributeType() {
        return this.attributeType;
    }
    
    public void setAttributeType(int attributeType) {
        this.attributeType = attributeType;
    }

    
    @Column(name="FormatRegularExpression")
    public String getFormatRegularExpression() {
        return this.formatRegularExpression;
    }
    
    public void setFormatRegularExpression(String formatRegularExpression) {
        this.formatRegularExpression = formatRegularExpression;
    }

    
    @Column(name="FormatDescription")
    public String getFormatDescription() {
        return this.formatDescription;
    }
    
    public void setFormatDescription(String formatDescription) {
        this.formatDescription = formatDescription;
    }

    
    @Column(name="Mandatory", nullable=false)
    public boolean isMandatory() {
        return this.mandatory;
    }
    
    public void setMandatory(boolean mandatory) {
        this.mandatory = mandatory;
    }

    
    @Column(name="ViewPermission")
    public String getViewPermission() {
        return this.viewPermission;
    }
    
    public void setViewPermission(String viewPermission) {
        this.viewPermission = viewPermission;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="startTaskContentAttribute")
    public Set<StartTaskContentAttributeValue> getStartTaskContentAttributeValues() {
        return this.startTaskContentAttributeValues;
    }
    
    public void setStartTaskContentAttributeValues(Set<StartTaskContentAttributeValue> startTaskContentAttributeValues) {
        this.startTaskContentAttributeValues = startTaskContentAttributeValues;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="startTaskContentAttribute")
    public Set<StartTaskContentElement> getStartTaskContentElements() {
        return this.startTaskContentElements;
    }
    
    public void setStartTaskContentElements(Set<StartTaskContentElement> startTaskContentElements) {
        this.startTaskContentElements = startTaskContentElements;
    }




}


