package com.galexis.configdb;
// Generated Sep 6, 2013 10:20:44 AM by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * StartTaskContentAttributeValue generated by hbm2java
 */
@Entity
@Table(name="StartTaskContentAttributeValue"
    ,catalog="integrationConfigDB"
)
public class StartTaskContentAttributeValue  implements java.io.Serializable {


     private Integer pk;
     private MessageTypeDefinition messageTypeDefinition;
     private StartTaskContentAttribute startTaskContentAttribute;
     private StartTaskContentElement2startTaskContentElement startTaskContentElement2startTaskContentElement;
     private Metadata metadata;
     private String value;

    public StartTaskContentAttributeValue() {
    }

	
    public StartTaskContentAttributeValue(MessageTypeDefinition messageTypeDefinition, StartTaskContentAttribute startTaskContentAttribute, Metadata metadata, String value) {
        this.messageTypeDefinition = messageTypeDefinition;
        this.startTaskContentAttribute = startTaskContentAttribute;
        this.metadata = metadata;
        this.value = value;
    }
    public StartTaskContentAttributeValue(MessageTypeDefinition messageTypeDefinition, StartTaskContentAttribute startTaskContentAttribute, StartTaskContentElement2startTaskContentElement startTaskContentElement2startTaskContentElement, Metadata metadata, String value) {
       this.messageTypeDefinition = messageTypeDefinition;
       this.startTaskContentAttribute = startTaskContentAttribute;
       this.startTaskContentElement2startTaskContentElement = startTaskContentElement2startTaskContentElement;
       this.metadata = metadata;
       this.value = value;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="PK", unique=true, nullable=false)
    public Integer getPk() {
        return this.pk;
    }
    
    public void setPk(Integer pk) {
        this.pk = pk;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="MessageTypeDefinitionPK", nullable=false)
    public MessageTypeDefinition getMessageTypeDefinition() {
        return this.messageTypeDefinition;
    }
    
    public void setMessageTypeDefinition(MessageTypeDefinition messageTypeDefinition) {
        this.messageTypeDefinition = messageTypeDefinition;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="StartTaskContentAttributePK", nullable=false)
    public StartTaskContentAttribute getStartTaskContentAttribute() {
        return this.startTaskContentAttribute;
    }
    
    public void setStartTaskContentAttribute(StartTaskContentAttribute startTaskContentAttribute) {
        this.startTaskContentAttribute = startTaskContentAttribute;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="StartTaskContentElement2StartTaskContentElementPK")
    public StartTaskContentElement2startTaskContentElement getStartTaskContentElement2startTaskContentElement() {
        return this.startTaskContentElement2startTaskContentElement;
    }
    
    public void setStartTaskContentElement2startTaskContentElement(StartTaskContentElement2startTaskContentElement startTaskContentElement2startTaskContentElement) {
        this.startTaskContentElement2startTaskContentElement = startTaskContentElement2startTaskContentElement;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="MetadataPK", nullable=false)
    public Metadata getMetadata() {
        return this.metadata;
    }
    
    public void setMetadata(Metadata metadata) {
        this.metadata = metadata;
    }

    
    @Column(name="Value", nullable=false, length=2048)
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }




}


