package com.galexis.configdb;
// Generated Sep 6, 2013 10:20:44 AM by Hibernate Tools 3.6.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TaskLock generated by hbm2java
 */
@Entity
@Table(name="TASK_LOCK"
    ,catalog="integrationConfigDB"
)
public class TaskLock  implements java.io.Serializable {


     private String lockKey;
     private Date crTime;

    public TaskLock() {
    }

    public TaskLock(String lockKey, Date crTime) {
       this.lockKey = lockKey;
       this.crTime = crTime;
    }
   
     @Id 

    
    @Column(name="LOCK_KEY", unique=true, nullable=false, length=250)
    public String getLockKey() {
        return this.lockKey;
    }
    
    public void setLockKey(String lockKey) {
        this.lockKey = lockKey;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CR_TIME", nullable=false, length=19)
    public Date getCrTime() {
        return this.crTime;
    }
    
    public void setCrTime(Date crTime) {
        this.crTime = crTime;
    }




}


