package com.galexis.configdb;
// Generated Sep 6, 2013 10:20:44 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;

/**
 * TaskMessageTypeDefinition generated by hbm2java
 */
@Entity
@Table(name="TaskMessageTypeDefinition"
    ,catalog="integrationConfigDB"
    , uniqueConstraints = @UniqueConstraint(columnNames={"Name", "Version", "PartnerGroupPK"}) 
)
public class TaskMessageTypeDefinition  implements java.io.Serializable {


     private Integer pk;
     private int version;
     private BackendResource backendResource;
     private StartTaskContentElement startTaskContentElement;
     private PartnerGroup partnerGroup;
     private Metadata metadata;
     private String name;
     private int state;
     private String partner;
     private Set<TaskMsgType2msgType> taskMsgType2msgTypes = new HashSet<TaskMsgType2msgType>(0);

    public TaskMessageTypeDefinition() {
    }

	
    public TaskMessageTypeDefinition(PartnerGroup partnerGroup, Metadata metadata, String name, int state) {
        this.partnerGroup = partnerGroup;
        this.metadata = metadata;
        this.name = name;
        this.state = state;
    }
    public TaskMessageTypeDefinition(BackendResource backendResource, StartTaskContentElement startTaskContentElement, PartnerGroup partnerGroup, Metadata metadata, String name, int state, String partner, Set<TaskMsgType2msgType> taskMsgType2msgTypes) {
       this.backendResource = backendResource;
       this.startTaskContentElement = startTaskContentElement;
       this.partnerGroup = partnerGroup;
       this.metadata = metadata;
       this.name = name;
       this.state = state;
       this.partner = partner;
       this.taskMsgType2msgTypes = taskMsgType2msgTypes;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="PK", unique=true, nullable=false)
    public Integer getPk() {
        return this.pk;
    }
    
    public void setPk(Integer pk) {
        this.pk = pk;
    }

    @Version
    @Column(name="Version", nullable=false)
    public int getVersion() {
        return this.version;
    }
    
    public void setVersion(int version) {
        this.version = version;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="BackendResourcePK")
    public BackendResource getBackendResource() {
        return this.backendResource;
    }
    
    public void setBackendResource(BackendResource backendResource) {
        this.backendResource = backendResource;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="StartTaskContentElementPK")
    public StartTaskContentElement getStartTaskContentElement() {
        return this.startTaskContentElement;
    }
    
    public void setStartTaskContentElement(StartTaskContentElement startTaskContentElement) {
        this.startTaskContentElement = startTaskContentElement;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PartnerGroupPK", nullable=false)
    public PartnerGroup getPartnerGroup() {
        return this.partnerGroup;
    }
    
    public void setPartnerGroup(PartnerGroup partnerGroup) {
        this.partnerGroup = partnerGroup;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="MetadataPK", nullable=false)
    public Metadata getMetadata() {
        return this.metadata;
    }
    
    public void setMetadata(Metadata metadata) {
        this.metadata = metadata;
    }

    
    @Column(name="Name", nullable=false)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="State", nullable=false)
    public int getState() {
        return this.state;
    }
    
    public void setState(int state) {
        this.state = state;
    }

    
    @Column(name="Partner", length=20)
    public String getPartner() {
        return this.partner;
    }
    
    public void setPartner(String partner) {
        this.partner = partner;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="taskMessageTypeDefinition")
    public Set<TaskMsgType2msgType> getTaskMsgType2msgTypes() {
        return this.taskMsgType2msgTypes;
    }
    
    public void setTaskMsgType2msgTypes(Set<TaskMsgType2msgType> taskMsgType2msgTypes) {
        this.taskMsgType2msgTypes = taskMsgType2msgTypes;
    }




}


