package com.galexis.allog2mysql.deleteme;
// Generated Sep 6, 2013 9:37:59 AM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Bizparaddr generated by hbm2java
 */
@Entity
@Table(name="BIZPARADDR"
    ,schema="INTEGAP"
    ,catalog="CHGALE11RDB"
)
public class Bizparaddr  implements java.io.Serializable {


     private long pk;
     private Bizpmaster bizpmaster;
     private String partnernr;
     private String manualmodifiedflag;
     private String name1;
     private String address1;
     private String address2;
     private String address3;
     private String address4;
     private String town;
     private String zip;
     private String country;
     private String state;
     private String language;
     private String contractordeliverycustomernr;
     private Date recordlastchangetime;
     private Date recordcreationtime;
     private Set<Delhdr> delhdrsForBizparaddrpkDelivery = new HashSet<Delhdr>(0);
     private Set<Bizpmaster> bizpmastersForBizparaddrpkInvoice = new HashSet<Bizpmaster>(0);
     private Set<Delhdr> delhdrsForBizparaddrpkOrder = new HashSet<Delhdr>(0);
     private Set<Bizpmaster> bizpmastersForBizparaddrpkDelivery = new HashSet<Bizpmaster>(0);
     private Set<Delhdr> delhdrsForBizparaddrpkInvoice = new HashSet<Delhdr>(0);
     private Set<Bizpmaster> bizpmastersForBizparaddrpkMain = new HashSet<Bizpmaster>(0);
     private Set<Grehdr> grehdrs = new HashSet<Grehdr>(0);
     private Set<Invhdr> invhdrsForBizparaddrpkDebtor = new HashSet<Invhdr>(0);
     private Set<Invhdr> invhdrsForBizparaddrpkDelivery = new HashSet<Invhdr>(0);
     private Set<Invhdr> invhdrsForBizparaddrpkInvoice = new HashSet<Invhdr>(0);
     private Set<Stockrebtc> stockrebtcsForBizparaddrpkOrder = new HashSet<Stockrebtc>(0);
     private Set<Invhdr> invhdrsForBizparaddrpkOrder = new HashSet<Invhdr>(0);
     private Set<Stockrebtc> stockrebtcsForBizparaddrpkInvoice = new HashSet<Stockrebtc>(0);
     private Set<Custopohdr> custopohdrsForBizparaddrpkOrder = new HashSet<Custopohdr>(0);
     private Set<Stockrebtc> stockrebtcsForBizparaddrpkDelivery = new HashSet<Stockrebtc>(0);
     private Set<Custopohdr> custopohdrsForBizparaddrpkInvoice = new HashSet<Custopohdr>(0);
     private Set<Custopohdr> custopohdrsForBizparaddrpkDelivery = new HashSet<Custopohdr>(0);
     private Set<Rethdr> rethdrs = new HashSet<Rethdr>(0);

    public Bizparaddr() {
    }

	
    public Bizparaddr(long pk, String partnernr, String manualmodifiedflag, Date recordcreationtime) {
        this.pk = pk;
        this.partnernr = partnernr;
        this.manualmodifiedflag = manualmodifiedflag;
        this.recordcreationtime = recordcreationtime;
    }
    public Bizparaddr(long pk, Bizpmaster bizpmaster, String partnernr, String manualmodifiedflag, String name1, String address1, String address2, String address3, String address4, String town, String zip, String country, String state, String language, String contractordeliverycustomernr, Date recordlastchangetime, Date recordcreationtime, Set<Delhdr> delhdrsForBizparaddrpkDelivery, Set<Bizpmaster> bizpmastersForBizparaddrpkInvoice, Set<Delhdr> delhdrsForBizparaddrpkOrder, Set<Bizpmaster> bizpmastersForBizparaddrpkDelivery, Set<Delhdr> delhdrsForBizparaddrpkInvoice, Set<Bizpmaster> bizpmastersForBizparaddrpkMain, Set<Grehdr> grehdrs, Set<Invhdr> invhdrsForBizparaddrpkDebtor, Set<Invhdr> invhdrsForBizparaddrpkDelivery, Set<Invhdr> invhdrsForBizparaddrpkInvoice, Set<Stockrebtc> stockrebtcsForBizparaddrpkOrder, Set<Invhdr> invhdrsForBizparaddrpkOrder, Set<Stockrebtc> stockrebtcsForBizparaddrpkInvoice, Set<Custopohdr> custopohdrsForBizparaddrpkOrder, Set<Stockrebtc> stockrebtcsForBizparaddrpkDelivery, Set<Custopohdr> custopohdrsForBizparaddrpkInvoice, Set<Custopohdr> custopohdrsForBizparaddrpkDelivery, Set<Rethdr> rethdrs) {
       this.pk = pk;
       this.bizpmaster = bizpmaster;
       this.partnernr = partnernr;
       this.manualmodifiedflag = manualmodifiedflag;
       this.name1 = name1;
       this.address1 = address1;
       this.address2 = address2;
       this.address3 = address3;
       this.address4 = address4;
       this.town = town;
       this.zip = zip;
       this.country = country;
       this.state = state;
       this.language = language;
       this.contractordeliverycustomernr = contractordeliverycustomernr;
       this.recordlastchangetime = recordlastchangetime;
       this.recordcreationtime = recordcreationtime;
       this.delhdrsForBizparaddrpkDelivery = delhdrsForBizparaddrpkDelivery;
       this.bizpmastersForBizparaddrpkInvoice = bizpmastersForBizparaddrpkInvoice;
       this.delhdrsForBizparaddrpkOrder = delhdrsForBizparaddrpkOrder;
       this.bizpmastersForBizparaddrpkDelivery = bizpmastersForBizparaddrpkDelivery;
       this.delhdrsForBizparaddrpkInvoice = delhdrsForBizparaddrpkInvoice;
       this.bizpmastersForBizparaddrpkMain = bizpmastersForBizparaddrpkMain;
       this.grehdrs = grehdrs;
       this.invhdrsForBizparaddrpkDebtor = invhdrsForBizparaddrpkDebtor;
       this.invhdrsForBizparaddrpkDelivery = invhdrsForBizparaddrpkDelivery;
       this.invhdrsForBizparaddrpkInvoice = invhdrsForBizparaddrpkInvoice;
       this.stockrebtcsForBizparaddrpkOrder = stockrebtcsForBizparaddrpkOrder;
       this.invhdrsForBizparaddrpkOrder = invhdrsForBizparaddrpkOrder;
       this.stockrebtcsForBizparaddrpkInvoice = stockrebtcsForBizparaddrpkInvoice;
       this.custopohdrsForBizparaddrpkOrder = custopohdrsForBizparaddrpkOrder;
       this.stockrebtcsForBizparaddrpkDelivery = stockrebtcsForBizparaddrpkDelivery;
       this.custopohdrsForBizparaddrpkInvoice = custopohdrsForBizparaddrpkInvoice;
       this.custopohdrsForBizparaddrpkDelivery = custopohdrsForBizparaddrpkDelivery;
       this.rethdrs = rethdrs;
    }
   
     @Id 

    
    @Column(name="PK", unique=true, nullable=false, precision=12, scale=0)
    public long getPk() {
        return this.pk;
    }
    
    public void setPk(long pk) {
        this.pk = pk;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="BIZPMASTERPK")
    public Bizpmaster getBizpmaster() {
        return this.bizpmaster;
    }
    
    public void setBizpmaster(Bizpmaster bizpmaster) {
        this.bizpmaster = bizpmaster;
    }

    
    @Column(name="PARTNERNR", nullable=false, length=20)
    public String getPartnernr() {
        return this.partnernr;
    }
    
    public void setPartnernr(String partnernr) {
        this.partnernr = partnernr;
    }

    
    @Column(name="MANUALMODIFIEDFLAG", nullable=false, length=1)
    public String getManualmodifiedflag() {
        return this.manualmodifiedflag;
    }
    
    public void setManualmodifiedflag(String manualmodifiedflag) {
        this.manualmodifiedflag = manualmodifiedflag;
    }

    
    @Column(name="NAME1", length=50)
    public String getName1() {
        return this.name1;
    }
    
    public void setName1(String name1) {
        this.name1 = name1;
    }

    
    @Column(name="ADDRESS1", length=50)
    public String getAddress1() {
        return this.address1;
    }
    
    public void setAddress1(String address1) {
        this.address1 = address1;
    }

    
    @Column(name="ADDRESS2", length=50)
    public String getAddress2() {
        return this.address2;
    }
    
    public void setAddress2(String address2) {
        this.address2 = address2;
    }

    
    @Column(name="ADDRESS3", length=50)
    public String getAddress3() {
        return this.address3;
    }
    
    public void setAddress3(String address3) {
        this.address3 = address3;
    }

    
    @Column(name="ADDRESS4", length=50)
    public String getAddress4() {
        return this.address4;
    }
    
    public void setAddress4(String address4) {
        this.address4 = address4;
    }

    
    @Column(name="TOWN", length=35)
    public String getTown() {
        return this.town;
    }
    
    public void setTown(String town) {
        this.town = town;
    }

    
    @Column(name="ZIP", length=16)
    public String getZip() {
        return this.zip;
    }
    
    public void setZip(String zip) {
        this.zip = zip;
    }

    
    @Column(name="COUNTRY", length=4)
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }

    
    @Column(name="STATE", length=2)
    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }

    
    @Column(name="LANGUAGE", length=3)
    public String getLanguage() {
        return this.language;
    }
    
    public void setLanguage(String language) {
        this.language = language;
    }

    
    @Column(name="CONTRACTORDELIVERYCUSTOMERNR", length=30)
    public String getContractordeliverycustomernr() {
        return this.contractordeliverycustomernr;
    }
    
    public void setContractordeliverycustomernr(String contractordeliverycustomernr) {
        this.contractordeliverycustomernr = contractordeliverycustomernr;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="RECORDLASTCHANGETIME", length=26)
    public Date getRecordlastchangetime() {
        return this.recordlastchangetime;
    }
    
    public void setRecordlastchangetime(Date recordlastchangetime) {
        this.recordlastchangetime = recordlastchangetime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="RECORDCREATIONTIME", nullable=false, length=26)
    public Date getRecordcreationtime() {
        return this.recordcreationtime;
    }
    
    public void setRecordcreationtime(Date recordcreationtime) {
        this.recordcreationtime = recordcreationtime;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="bizparaddrByBizparaddrpkDelivery")
    public Set<Delhdr> getDelhdrsForBizparaddrpkDelivery() {
        return this.delhdrsForBizparaddrpkDelivery;
    }
    
    public void setDelhdrsForBizparaddrpkDelivery(Set<Delhdr> delhdrsForBizparaddrpkDelivery) {
        this.delhdrsForBizparaddrpkDelivery = delhdrsForBizparaddrpkDelivery;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="bizparaddrByBizparaddrpkInvoice")
    public Set<Bizpmaster> getBizpmastersForBizparaddrpkInvoice() {
        return this.bizpmastersForBizparaddrpkInvoice;
    }
    
    public void setBizpmastersForBizparaddrpkInvoice(Set<Bizpmaster> bizpmastersForBizparaddrpkInvoice) {
        this.bizpmastersForBizparaddrpkInvoice = bizpmastersForBizparaddrpkInvoice;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="bizparaddrByBizparaddrpkOrder")
    public Set<Delhdr> getDelhdrsForBizparaddrpkOrder() {
        return this.delhdrsForBizparaddrpkOrder;
    }
    
    public void setDelhdrsForBizparaddrpkOrder(Set<Delhdr> delhdrsForBizparaddrpkOrder) {
        this.delhdrsForBizparaddrpkOrder = delhdrsForBizparaddrpkOrder;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="bizparaddrByBizparaddrpkDelivery")
    public Set<Bizpmaster> getBizpmastersForBizparaddrpkDelivery() {
        return this.bizpmastersForBizparaddrpkDelivery;
    }
    
    public void setBizpmastersForBizparaddrpkDelivery(Set<Bizpmaster> bizpmastersForBizparaddrpkDelivery) {
        this.bizpmastersForBizparaddrpkDelivery = bizpmastersForBizparaddrpkDelivery;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="bizparaddrByBizparaddrpkInvoice")
    public Set<Delhdr> getDelhdrsForBizparaddrpkInvoice() {
        return this.delhdrsForBizparaddrpkInvoice;
    }
    
    public void setDelhdrsForBizparaddrpkInvoice(Set<Delhdr> delhdrsForBizparaddrpkInvoice) {
        this.delhdrsForBizparaddrpkInvoice = delhdrsForBizparaddrpkInvoice;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="bizparaddrByBizparaddrpkMain")
    public Set<Bizpmaster> getBizpmastersForBizparaddrpkMain() {
        return this.bizpmastersForBizparaddrpkMain;
    }
    
    public void setBizpmastersForBizparaddrpkMain(Set<Bizpmaster> bizpmastersForBizparaddrpkMain) {
        this.bizpmastersForBizparaddrpkMain = bizpmastersForBizparaddrpkMain;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="bizparaddr")
    public Set<Grehdr> getGrehdrs() {
        return this.grehdrs;
    }
    
    public void setGrehdrs(Set<Grehdr> grehdrs) {
        this.grehdrs = grehdrs;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="bizparaddrByBizparaddrpkDebtor")
    public Set<Invhdr> getInvhdrsForBizparaddrpkDebtor() {
        return this.invhdrsForBizparaddrpkDebtor;
    }
    
    public void setInvhdrsForBizparaddrpkDebtor(Set<Invhdr> invhdrsForBizparaddrpkDebtor) {
        this.invhdrsForBizparaddrpkDebtor = invhdrsForBizparaddrpkDebtor;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="bizparaddrByBizparaddrpkDelivery")
    public Set<Invhdr> getInvhdrsForBizparaddrpkDelivery() {
        return this.invhdrsForBizparaddrpkDelivery;
    }
    
    public void setInvhdrsForBizparaddrpkDelivery(Set<Invhdr> invhdrsForBizparaddrpkDelivery) {
        this.invhdrsForBizparaddrpkDelivery = invhdrsForBizparaddrpkDelivery;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="bizparaddrByBizparaddrpkInvoice")
    public Set<Invhdr> getInvhdrsForBizparaddrpkInvoice() {
        return this.invhdrsForBizparaddrpkInvoice;
    }
    
    public void setInvhdrsForBizparaddrpkInvoice(Set<Invhdr> invhdrsForBizparaddrpkInvoice) {
        this.invhdrsForBizparaddrpkInvoice = invhdrsForBizparaddrpkInvoice;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="bizparaddrByBizparaddrpkOrder")
    public Set<Stockrebtc> getStockrebtcsForBizparaddrpkOrder() {
        return this.stockrebtcsForBizparaddrpkOrder;
    }
    
    public void setStockrebtcsForBizparaddrpkOrder(Set<Stockrebtc> stockrebtcsForBizparaddrpkOrder) {
        this.stockrebtcsForBizparaddrpkOrder = stockrebtcsForBizparaddrpkOrder;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="bizparaddrByBizparaddrpkOrder")
    public Set<Invhdr> getInvhdrsForBizparaddrpkOrder() {
        return this.invhdrsForBizparaddrpkOrder;
    }
    
    public void setInvhdrsForBizparaddrpkOrder(Set<Invhdr> invhdrsForBizparaddrpkOrder) {
        this.invhdrsForBizparaddrpkOrder = invhdrsForBizparaddrpkOrder;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="bizparaddrByBizparaddrpkInvoice")
    public Set<Stockrebtc> getStockrebtcsForBizparaddrpkInvoice() {
        return this.stockrebtcsForBizparaddrpkInvoice;
    }
    
    public void setStockrebtcsForBizparaddrpkInvoice(Set<Stockrebtc> stockrebtcsForBizparaddrpkInvoice) {
        this.stockrebtcsForBizparaddrpkInvoice = stockrebtcsForBizparaddrpkInvoice;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="bizparaddrByBizparaddrpkOrder")
    public Set<Custopohdr> getCustopohdrsForBizparaddrpkOrder() {
        return this.custopohdrsForBizparaddrpkOrder;
    }
    
    public void setCustopohdrsForBizparaddrpkOrder(Set<Custopohdr> custopohdrsForBizparaddrpkOrder) {
        this.custopohdrsForBizparaddrpkOrder = custopohdrsForBizparaddrpkOrder;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="bizparaddrByBizparaddrpkDelivery")
    public Set<Stockrebtc> getStockrebtcsForBizparaddrpkDelivery() {
        return this.stockrebtcsForBizparaddrpkDelivery;
    }
    
    public void setStockrebtcsForBizparaddrpkDelivery(Set<Stockrebtc> stockrebtcsForBizparaddrpkDelivery) {
        this.stockrebtcsForBizparaddrpkDelivery = stockrebtcsForBizparaddrpkDelivery;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="bizparaddrByBizparaddrpkInvoice")
    public Set<Custopohdr> getCustopohdrsForBizparaddrpkInvoice() {
        return this.custopohdrsForBizparaddrpkInvoice;
    }
    
    public void setCustopohdrsForBizparaddrpkInvoice(Set<Custopohdr> custopohdrsForBizparaddrpkInvoice) {
        this.custopohdrsForBizparaddrpkInvoice = custopohdrsForBizparaddrpkInvoice;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="bizparaddrByBizparaddrpkDelivery")
    public Set<Custopohdr> getCustopohdrsForBizparaddrpkDelivery() {
        return this.custopohdrsForBizparaddrpkDelivery;
    }
    
    public void setCustopohdrsForBizparaddrpkDelivery(Set<Custopohdr> custopohdrsForBizparaddrpkDelivery) {
        this.custopohdrsForBizparaddrpkDelivery = custopohdrsForBizparaddrpkDelivery;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="bizparaddr")
    public Set<Rethdr> getRethdrs() {
        return this.rethdrs;
    }
    
    public void setRethdrs(Set<Rethdr> rethdrs) {
        this.rethdrs = rethdrs;
    }




}


