package com.galexis.allog2mysql.deleteme;
// Generated Sep 6, 2013 9:37:59 AM by Hibernate Tools 3.6.0


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Bizparmail generated by hbm2java
 */
@Entity
@Table(name="BIZPARMAIL"
    ,schema="INTEGAP"
    ,catalog="CHGALE11RDB"
    , uniqueConstraints = @UniqueConstraint(columnNames="PK") 
)
public class Bizparmail  implements java.io.Serializable {


     private BizparmailId id;

    public Bizparmail() {
    }

    public Bizparmail(BizparmailId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="pk", column=@Column(name="PK", unique=true, nullable=false, precision=12, scale=0) ), 
        @AttributeOverride(name="bizpmasterpk", column=@Column(name="BIZPMASTERPK", precision=12, scale=0) ), 
        @AttributeOverride(name="function", column=@Column(name="FUNCTION", nullable=false, length=50) ), 
        @AttributeOverride(name="mailaddress", column=@Column(name="MAILADDRESS", nullable=false, length=1000) ), 
        @AttributeOverride(name="recordlastchangetime", column=@Column(name="RECORDLASTCHANGETIME", length=26) ), 
        @AttributeOverride(name="userlastchange", column=@Column(name="USERLASTCHANGE", length=20) ), 
        @AttributeOverride(name="recordcreationtime", column=@Column(name="RECORDCREATIONTIME", nullable=false, length=26) ) } )
    public BizparmailId getId() {
        return this.id;
    }
    
    public void setId(BizparmailId id) {
        this.id = id;
    }




}


