package com.galexis.allog2mysql.deleteme;
// Generated Sep 6, 2013 9:37:59 AM by Hibernate Tools 3.6.0


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Bizpitgaut generated by hbm2java
 */
@Entity
@Table(name="BIZPITGAUT"
    ,schema="INTEGAP"
    ,catalog="CHGALE11RDB"
    , uniqueConstraints = @UniqueConstraint(columnNames="PK") 
)
public class Bizpitgaut  implements java.io.Serializable {


     private BizpitgautId id;
     private Bizpmaster bizpmaster;

    public Bizpitgaut() {
    }

    public Bizpitgaut(BizpitgautId id, Bizpmaster bizpmaster) {
       this.id = id;
       this.bizpmaster = bizpmaster;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="pk", column=@Column(name="PK", unique=true, nullable=false, precision=12, scale=0) ), 
        @AttributeOverride(name="bizpmasterpk", column=@Column(name="BIZPMASTERPK", nullable=false, precision=12, scale=0) ), 
        @AttributeOverride(name="authorizationkey", column=@Column(name="AUTHORIZATIONKEY", length=10) ), 
        @AttributeOverride(name="isactiveflag", column=@Column(name="ISACTIVEFLAG", length=1) ), 
        @AttributeOverride(name="programname", column=@Column(name="PROGRAMNAME", length=10) ), 
        @AttributeOverride(name="filename", column=@Column(name="FILENAME", length=10) ), 
        @AttributeOverride(name="recordlastchangetime", column=@Column(name="RECORDLASTCHANGETIME", length=26) ), 
        @AttributeOverride(name="recordcreationtime", column=@Column(name="RECORDCREATIONTIME", nullable=false, length=26) ) } )
    public BizpitgautId getId() {
        return this.id;
    }
    
    public void setId(BizpitgautId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="BIZPMASTERPK", nullable=false, insertable=false, updatable=false)
    public Bizpmaster getBizpmaster() {
        return this.bizpmaster;
    }
    
    public void setBizpmaster(Bizpmaster bizpmaster) {
        this.bizpmaster = bizpmaster;
    }




}


