package com.galexis.allog2mysql.deleteme;
// Generated Sep 6, 2013 9:37:59 AM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Bizwebfunh generated by hbm2java
 */
@Entity
@Table(name="BIZWEBFUNH"
    ,schema="INTEGAP"
    ,catalog="CHGALE11RDB"
    , uniqueConstraints = @UniqueConstraint(columnNames="FUNCTIONNAME") 
)
public class Bizwebfunh  implements java.io.Serializable {


     private long pk;
     private String functionname;
     private String functiondescription;
     private String applicationname;
     private String businessobjecttype;
     private String userid;
     private Date recordlastchangetime;
     private Date recordcreationtime;
     private Set<Bizwclfunc> bizwclfuncs = new HashSet<Bizwclfunc>(0);
     private Set<Bizwebfunl> bizwebfunls = new HashSet<Bizwebfunl>(0);

    public Bizwebfunh() {
    }

	
    public Bizwebfunh(long pk, String functionname, Date recordcreationtime) {
        this.pk = pk;
        this.functionname = functionname;
        this.recordcreationtime = recordcreationtime;
    }
    public Bizwebfunh(long pk, String functionname, String functiondescription, String applicationname, String businessobjecttype, String userid, Date recordlastchangetime, Date recordcreationtime, Set<Bizwclfunc> bizwclfuncs, Set<Bizwebfunl> bizwebfunls) {
       this.pk = pk;
       this.functionname = functionname;
       this.functiondescription = functiondescription;
       this.applicationname = applicationname;
       this.businessobjecttype = businessobjecttype;
       this.userid = userid;
       this.recordlastchangetime = recordlastchangetime;
       this.recordcreationtime = recordcreationtime;
       this.bizwclfuncs = bizwclfuncs;
       this.bizwebfunls = bizwebfunls;
    }
   
     @Id 

    
    @Column(name="PK", unique=true, nullable=false, precision=12, scale=0)
    public long getPk() {
        return this.pk;
    }
    
    public void setPk(long pk) {
        this.pk = pk;
    }

    
    @Column(name="FUNCTIONNAME", unique=true, nullable=false, length=30)
    public String getFunctionname() {
        return this.functionname;
    }
    
    public void setFunctionname(String functionname) {
        this.functionname = functionname;
    }

    
    @Column(name="FUNCTIONDESCRIPTION")
    public String getFunctiondescription() {
        return this.functiondescription;
    }
    
    public void setFunctiondescription(String functiondescription) {
        this.functiondescription = functiondescription;
    }

    
    @Column(name="APPLICATIONNAME", length=30)
    public String getApplicationname() {
        return this.applicationname;
    }
    
    public void setApplicationname(String applicationname) {
        this.applicationname = applicationname;
    }

    
    @Column(name="BUSINESSOBJECTTYPE", length=30)
    public String getBusinessobjecttype() {
        return this.businessobjecttype;
    }
    
    public void setBusinessobjecttype(String businessobjecttype) {
        this.businessobjecttype = businessobjecttype;
    }

    
    @Column(name="USERID", length=10)
    public String getUserid() {
        return this.userid;
    }
    
    public void setUserid(String userid) {
        this.userid = userid;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="RECORDLASTCHANGETIME", length=26)
    public Date getRecordlastchangetime() {
        return this.recordlastchangetime;
    }
    
    public void setRecordlastchangetime(Date recordlastchangetime) {
        this.recordlastchangetime = recordlastchangetime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="RECORDCREATIONTIME", nullable=false, length=26)
    public Date getRecordcreationtime() {
        return this.recordcreationtime;
    }
    
    public void setRecordcreationtime(Date recordcreationtime) {
        this.recordcreationtime = recordcreationtime;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="bizwebfunh")
    public Set<Bizwclfunc> getBizwclfuncs() {
        return this.bizwclfuncs;
    }
    
    public void setBizwclfuncs(Set<Bizwclfunc> bizwclfuncs) {
        this.bizwclfuncs = bizwclfuncs;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="bizwebfunh")
    public Set<Bizwebfunl> getBizwebfunls() {
        return this.bizwebfunls;
    }
    
    public void setBizwebfunls(Set<Bizwebfunl> bizwebfunls) {
        this.bizwebfunls = bizwebfunls;
    }




}


