package com.galexis.allog2mysql.deleteme;
// Generated Sep 6, 2013 9:37:59 AM by Hibernate Tools 3.6.0


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Bizwebfunl generated by hbm2java
 */
@Entity
@Table(name="BIZWEBFUNL"
    ,schema="INTEGAP"
    ,catalog="CHGALE11RDB"
    , uniqueConstraints = {@UniqueConstraint(columnNames="PK"), @UniqueConstraint(columnNames={"BIZWEBFUNHPK", "ATTRIBUTENAME"})} 
)
public class Bizwebfunl  implements java.io.Serializable {


     private BizwebfunlId id;
     private Bizwebfunh bizwebfunh;

    public Bizwebfunl() {
    }

    public Bizwebfunl(BizwebfunlId id, Bizwebfunh bizwebfunh) {
       this.id = id;
       this.bizwebfunh = bizwebfunh;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="pk", column=@Column(name="PK", unique=true, nullable=false, precision=12, scale=0) ), 
        @AttributeOverride(name="bizwebfunhpk", column=@Column(name="BIZWEBFUNHPK", nullable=false, precision=12, scale=0) ), 
        @AttributeOverride(name="attributename", column=@Column(name="ATTRIBUTENAME", length=50) ), 
        @AttributeOverride(name="attributevalue", column=@Column(name="ATTRIBUTEVALUE", length=50) ), 
        @AttributeOverride(name="attributetype", column=@Column(name="ATTRIBUTETYPE", length=20) ), 
        @AttributeOverride(name="attributedescription", column=@Column(name="ATTRIBUTEDESCRIPTION", length=100) ), 
        @AttributeOverride(name="userid", column=@Column(name="USERID", length=10) ), 
        @AttributeOverride(name="recordlastchangetime", column=@Column(name="RECORDLASTCHANGETIME", length=26) ), 
        @AttributeOverride(name="recordcreationtime", column=@Column(name="RECORDCREATIONTIME", nullable=false, length=26) ) } )
    public BizwebfunlId getId() {
        return this.id;
    }
    
    public void setId(BizwebfunlId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="BIZWEBFUNHPK", nullable=false, insertable=false, updatable=false)
    public Bizwebfunh getBizwebfunh() {
        return this.bizwebfunh;
    }
    
    public void setBizwebfunh(Bizwebfunh bizwebfunh) {
        this.bizwebfunh = bizwebfunh;
    }




}


