package com.galexis.allog2mysql.deleteme;
// Generated Sep 6, 2013 9:37:59 AM by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Consordldt generated by hbm2java
 */
@Entity
@Table(name="CONSORDLDT"
    ,schema="INTEGAP"
    ,catalog="CHGALE11RDB"
)
public class Consordldt  implements java.io.Serializable {


     private long pk;
     private Consordhdr consordhdr;
     private Consordlin consordlin;
     private int lineseq;
     private BigDecimal orderqty;
     private Long originalordernr;
     private Integer originalorderline;
     private String programname;
     private String filename;
     private String processingflag1;
     private String processingflag2;
     private String processingflag3;
     private String processingflag4;
     private String processingflag5;
     private String processingflag6;
     private String processingflag7;
     private String processingflag8;
     private String processingflag9;
     private String processingflag10;
     private String outboundignore;
     private Date recordlastchangetime;
     private Date recordcreationtime;

    public Consordldt() {
    }

	
    public Consordldt(long pk, Consordhdr consordhdr, Consordlin consordlin, int lineseq, String outboundignore, Date recordcreationtime) {
        this.pk = pk;
        this.consordhdr = consordhdr;
        this.consordlin = consordlin;
        this.lineseq = lineseq;
        this.outboundignore = outboundignore;
        this.recordcreationtime = recordcreationtime;
    }
    public Consordldt(long pk, Consordhdr consordhdr, Consordlin consordlin, int lineseq, BigDecimal orderqty, Long originalordernr, Integer originalorderline, String programname, String filename, String processingflag1, String processingflag2, String processingflag3, String processingflag4, String processingflag5, String processingflag6, String processingflag7, String processingflag8, String processingflag9, String processingflag10, String outboundignore, Date recordlastchangetime, Date recordcreationtime) {
       this.pk = pk;
       this.consordhdr = consordhdr;
       this.consordlin = consordlin;
       this.lineseq = lineseq;
       this.orderqty = orderqty;
       this.originalordernr = originalordernr;
       this.originalorderline = originalorderline;
       this.programname = programname;
       this.filename = filename;
       this.processingflag1 = processingflag1;
       this.processingflag2 = processingflag2;
       this.processingflag3 = processingflag3;
       this.processingflag4 = processingflag4;
       this.processingflag5 = processingflag5;
       this.processingflag6 = processingflag6;
       this.processingflag7 = processingflag7;
       this.processingflag8 = processingflag8;
       this.processingflag9 = processingflag9;
       this.processingflag10 = processingflag10;
       this.outboundignore = outboundignore;
       this.recordlastchangetime = recordlastchangetime;
       this.recordcreationtime = recordcreationtime;
    }
   
     @Id 

    
    @Column(name="PK", unique=true, nullable=false, precision=12, scale=0)
    public long getPk() {
        return this.pk;
    }
    
    public void setPk(long pk) {
        this.pk = pk;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CONSHDRPK", nullable=false)
    public Consordhdr getConsordhdr() {
        return this.consordhdr;
    }
    
    public void setConsordhdr(Consordhdr consordhdr) {
        this.consordhdr = consordhdr;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CONSLINPK", nullable=false)
    public Consordlin getConsordlin() {
        return this.consordlin;
    }
    
    public void setConsordlin(Consordlin consordlin) {
        this.consordlin = consordlin;
    }

    
    @Column(name="LINESEQ", nullable=false, precision=5, scale=0)
    public int getLineseq() {
        return this.lineseq;
    }
    
    public void setLineseq(int lineseq) {
        this.lineseq = lineseq;
    }

    
    @Column(name="ORDERQTY", precision=15, scale=6)
    public BigDecimal getOrderqty() {
        return this.orderqty;
    }
    
    public void setOrderqty(BigDecimal orderqty) {
        this.orderqty = orderqty;
    }

    
    @Column(name="ORIGINALORDERNR", precision=12, scale=0)
    public Long getOriginalordernr() {
        return this.originalordernr;
    }
    
    public void setOriginalordernr(Long originalordernr) {
        this.originalordernr = originalordernr;
    }

    
    @Column(name="ORIGINALORDERLINE", precision=6, scale=0)
    public Integer getOriginalorderline() {
        return this.originalorderline;
    }
    
    public void setOriginalorderline(Integer originalorderline) {
        this.originalorderline = originalorderline;
    }

    
    @Column(name="PROGRAMNAME", length=10)
    public String getProgramname() {
        return this.programname;
    }
    
    public void setProgramname(String programname) {
        this.programname = programname;
    }

    
    @Column(name="FILENAME", length=10)
    public String getFilename() {
        return this.filename;
    }
    
    public void setFilename(String filename) {
        this.filename = filename;
    }

    
    @Column(name="PROCESSINGFLAG1", length=1)
    public String getProcessingflag1() {
        return this.processingflag1;
    }
    
    public void setProcessingflag1(String processingflag1) {
        this.processingflag1 = processingflag1;
    }

    
    @Column(name="PROCESSINGFLAG2", length=1)
    public String getProcessingflag2() {
        return this.processingflag2;
    }
    
    public void setProcessingflag2(String processingflag2) {
        this.processingflag2 = processingflag2;
    }

    
    @Column(name="PROCESSINGFLAG3", length=1)
    public String getProcessingflag3() {
        return this.processingflag3;
    }
    
    public void setProcessingflag3(String processingflag3) {
        this.processingflag3 = processingflag3;
    }

    
    @Column(name="PROCESSINGFLAG4", length=1)
    public String getProcessingflag4() {
        return this.processingflag4;
    }
    
    public void setProcessingflag4(String processingflag4) {
        this.processingflag4 = processingflag4;
    }

    
    @Column(name="PROCESSINGFLAG5", length=1)
    public String getProcessingflag5() {
        return this.processingflag5;
    }
    
    public void setProcessingflag5(String processingflag5) {
        this.processingflag5 = processingflag5;
    }

    
    @Column(name="PROCESSINGFLAG6", length=1)
    public String getProcessingflag6() {
        return this.processingflag6;
    }
    
    public void setProcessingflag6(String processingflag6) {
        this.processingflag6 = processingflag6;
    }

    
    @Column(name="PROCESSINGFLAG7", length=1)
    public String getProcessingflag7() {
        return this.processingflag7;
    }
    
    public void setProcessingflag7(String processingflag7) {
        this.processingflag7 = processingflag7;
    }

    
    @Column(name="PROCESSINGFLAG8", length=1)
    public String getProcessingflag8() {
        return this.processingflag8;
    }
    
    public void setProcessingflag8(String processingflag8) {
        this.processingflag8 = processingflag8;
    }

    
    @Column(name="PROCESSINGFLAG9", length=1)
    public String getProcessingflag9() {
        return this.processingflag9;
    }
    
    public void setProcessingflag9(String processingflag9) {
        this.processingflag9 = processingflag9;
    }

    
    @Column(name="PROCESSINGFLAG10", length=1)
    public String getProcessingflag10() {
        return this.processingflag10;
    }
    
    public void setProcessingflag10(String processingflag10) {
        this.processingflag10 = processingflag10;
    }

    
    @Column(name="OUTBOUNDIGNORE", nullable=false, length=1)
    public String getOutboundignore() {
        return this.outboundignore;
    }
    
    public void setOutboundignore(String outboundignore) {
        this.outboundignore = outboundignore;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="RECORDLASTCHANGETIME", length=26)
    public Date getRecordlastchangetime() {
        return this.recordlastchangetime;
    }
    
    public void setRecordlastchangetime(Date recordlastchangetime) {
        this.recordlastchangetime = recordlastchangetime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="RECORDCREATIONTIME", nullable=false, length=26)
    public Date getRecordcreationtime() {
        return this.recordcreationtime;
    }
    
    public void setRecordcreationtime(Date recordcreationtime) {
        this.recordcreationtime = recordcreationtime;
    }




}


