package com.galexis.allog2mysql.deleteme;
// Generated Sep 6, 2013 9:37:59 AM by Hibernate Tools 3.6.0


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Contrpgrp generated by hbm2java
 */
@Entity
@Table(name="CONTRPGRP"
    ,schema="INTEGAP"
    ,catalog="CHGALE11RDB"
    , uniqueConstraints = {@UniqueConstraint(columnNames="PK"), @UniqueConstraint(columnNames="PRODUCTGROUP")} 
)
public class Contrpgrp  implements java.io.Serializable {


     private ContrpgrpId id;
     private Contrdef contrdef;

    public Contrpgrp() {
    }

    public Contrpgrp(ContrpgrpId id, Contrdef contrdef) {
       this.id = id;
       this.contrdef = contrdef;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="pk", column=@Column(name="PK", unique=true, nullable=false, precision=12, scale=0) ), 
        @AttributeOverride(name="contrdefpk", column=@Column(name="CONTRDEFPK", nullable=false, precision=12, scale=0) ), 
        @AttributeOverride(name="productgroup", column=@Column(name="PRODUCTGROUP", unique=true, nullable=false, length=5) ), 
        @AttributeOverride(name="isactiveflag", column=@Column(name="ISACTIVEFLAG", nullable=false, length=1) ), 
        @AttributeOverride(name="recordcreationtime", column=@Column(name="RECORDCREATIONTIME", nullable=false, length=26) ), 
        @AttributeOverride(name="recordlastchangetime", column=@Column(name="RECORDLASTCHANGETIME", length=26) ), 
        @AttributeOverride(name="userlastchange", column=@Column(name="USERLASTCHANGE", length=20) ) } )
    public ContrpgrpId getId() {
        return this.id;
    }
    
    public void setId(ContrpgrpId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CONTRDEFPK", nullable=false, insertable=false, updatable=false)
    public Contrdef getContrdef() {
        return this.contrdef;
    }
    
    public void setContrdef(Contrdef contrdef) {
        this.contrdef = contrdef;
    }




}


