package com.galexis.allog2mysql.deleteme;
// Generated Sep 6, 2013 9:37:59 AM by Hibernate Tools 3.6.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Contrsndid generated by hbm2java
 */
@Entity
@Table(name="CONTRSNDID"
    ,schema="INTEGAP"
    ,catalog="CHGALE11RDB"
    , uniqueConstraints = @UniqueConstraint(columnNames={"SENDERIDENTIFICATION", "PROTOCOL"}) 
)
public class Contrsndid  implements java.io.Serializable {


     private long pk;
     private String senderidentification;
     private String protocol;
     private String description;
     private Long contrdefpk;
     private String userlastchange;
     private Date recordlastchangetime;
     private Date recordcreationtime;

    public Contrsndid() {
    }

	
    public Contrsndid(long pk, String senderidentification, Date recordcreationtime) {
        this.pk = pk;
        this.senderidentification = senderidentification;
        this.recordcreationtime = recordcreationtime;
    }
    public Contrsndid(long pk, String senderidentification, String protocol, String description, Long contrdefpk, String userlastchange, Date recordlastchangetime, Date recordcreationtime) {
       this.pk = pk;
       this.senderidentification = senderidentification;
       this.protocol = protocol;
       this.description = description;
       this.contrdefpk = contrdefpk;
       this.userlastchange = userlastchange;
       this.recordlastchangetime = recordlastchangetime;
       this.recordcreationtime = recordcreationtime;
    }
   
     @Id 

    
    @Column(name="PK", unique=true, nullable=false, precision=12, scale=0)
    public long getPk() {
        return this.pk;
    }
    
    public void setPk(long pk) {
        this.pk = pk;
    }

    
    @Column(name="SENDERIDENTIFICATION", nullable=false)
    public String getSenderidentification() {
        return this.senderidentification;
    }
    
    public void setSenderidentification(String senderidentification) {
        this.senderidentification = senderidentification;
    }

    
    @Column(name="PROTOCOL", length=50)
    public String getProtocol() {
        return this.protocol;
    }
    
    public void setProtocol(String protocol) {
        this.protocol = protocol;
    }

    
    @Column(name="DESCRIPTION")
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="CONTRDEFPK", precision=12, scale=0)
    public Long getContrdefpk() {
        return this.contrdefpk;
    }
    
    public void setContrdefpk(Long contrdefpk) {
        this.contrdefpk = contrdefpk;
    }

    
    @Column(name="USERLASTCHANGE")
    public String getUserlastchange() {
        return this.userlastchange;
    }
    
    public void setUserlastchange(String userlastchange) {
        this.userlastchange = userlastchange;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="RECORDLASTCHANGETIME", length=26)
    public Date getRecordlastchangetime() {
        return this.recordlastchangetime;
    }
    
    public void setRecordlastchangetime(Date recordlastchangetime) {
        this.recordlastchangetime = recordlastchangetime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="RECORDCREATIONTIME", nullable=false, length=26)
    public Date getRecordcreationtime() {
        return this.recordcreationtime;
    }
    
    public void setRecordcreationtime(Date recordcreationtime) {
        this.recordcreationtime = recordcreationtime;
    }




}


