package com.galexis.allog2mysql.deleteme;
// Generated Sep 6, 2013 9:37:59 AM by Hibernate Tools 3.6.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ContrpgrpId generated by hbm2java
 */
@Embeddable
public class ContrpgrpId  implements java.io.Serializable {


     private long pk;
     private long contrdefpk;
     private String productgroup;
     private String isactiveflag;
     private Date recordcreationtime;
     private Date recordlastchangetime;
     private String userlastchange;

    public ContrpgrpId() {
    }

	
    public ContrpgrpId(long pk, long contrdefpk, String productgroup, String isactiveflag, Date recordcreationtime) {
        this.pk = pk;
        this.contrdefpk = contrdefpk;
        this.productgroup = productgroup;
        this.isactiveflag = isactiveflag;
        this.recordcreationtime = recordcreationtime;
    }
    public ContrpgrpId(long pk, long contrdefpk, String productgroup, String isactiveflag, Date recordcreationtime, Date recordlastchangetime, String userlastchange) {
       this.pk = pk;
       this.contrdefpk = contrdefpk;
       this.productgroup = productgroup;
       this.isactiveflag = isactiveflag;
       this.recordcreationtime = recordcreationtime;
       this.recordlastchangetime = recordlastchangetime;
       this.userlastchange = userlastchange;
    }
   


    @Column(name="PK", unique=true, nullable=false, precision=12, scale=0)
    public long getPk() {
        return this.pk;
    }
    
    public void setPk(long pk) {
        this.pk = pk;
    }


    @Column(name="CONTRDEFPK", nullable=false, precision=12, scale=0)
    public long getContrdefpk() {
        return this.contrdefpk;
    }
    
    public void setContrdefpk(long contrdefpk) {
        this.contrdefpk = contrdefpk;
    }


    @Column(name="PRODUCTGROUP", unique=true, nullable=false, length=5)
    public String getProductgroup() {
        return this.productgroup;
    }
    
    public void setProductgroup(String productgroup) {
        this.productgroup = productgroup;
    }


    @Column(name="ISACTIVEFLAG", nullable=false, length=1)
    public String getIsactiveflag() {
        return this.isactiveflag;
    }
    
    public void setIsactiveflag(String isactiveflag) {
        this.isactiveflag = isactiveflag;
    }


    @Column(name="RECORDCREATIONTIME", nullable=false, length=26)
    public Date getRecordcreationtime() {
        return this.recordcreationtime;
    }
    
    public void setRecordcreationtime(Date recordcreationtime) {
        this.recordcreationtime = recordcreationtime;
    }


    @Column(name="RECORDLASTCHANGETIME", length=26)
    public Date getRecordlastchangetime() {
        return this.recordlastchangetime;
    }
    
    public void setRecordlastchangetime(Date recordlastchangetime) {
        this.recordlastchangetime = recordlastchangetime;
    }


    @Column(name="USERLASTCHANGE", length=20)
    public String getUserlastchange() {
        return this.userlastchange;
    }
    
    public void setUserlastchange(String userlastchange) {
        this.userlastchange = userlastchange;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ContrpgrpId) ) return false;
		 ContrpgrpId castOther = ( ContrpgrpId ) other; 
         
		 return (this.getPk()==castOther.getPk())
 && (this.getContrdefpk()==castOther.getContrdefpk())
 && ( (this.getProductgroup()==castOther.getProductgroup()) || ( this.getProductgroup()!=null && castOther.getProductgroup()!=null && this.getProductgroup().equals(castOther.getProductgroup()) ) )
 && ( (this.getIsactiveflag()==castOther.getIsactiveflag()) || ( this.getIsactiveflag()!=null && castOther.getIsactiveflag()!=null && this.getIsactiveflag().equals(castOther.getIsactiveflag()) ) )
 && ( (this.getRecordcreationtime()==castOther.getRecordcreationtime()) || ( this.getRecordcreationtime()!=null && castOther.getRecordcreationtime()!=null && this.getRecordcreationtime().equals(castOther.getRecordcreationtime()) ) )
 && ( (this.getRecordlastchangetime()==castOther.getRecordlastchangetime()) || ( this.getRecordlastchangetime()!=null && castOther.getRecordlastchangetime()!=null && this.getRecordlastchangetime().equals(castOther.getRecordlastchangetime()) ) )
 && ( (this.getUserlastchange()==castOther.getUserlastchange()) || ( this.getUserlastchange()!=null && castOther.getUserlastchange()!=null && this.getUserlastchange().equals(castOther.getUserlastchange()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getPk();
         result = 37 * result + (int) this.getContrdefpk();
         result = 37 * result + ( getProductgroup() == null ? 0 : this.getProductgroup().hashCode() );
         result = 37 * result + ( getIsactiveflag() == null ? 0 : this.getIsactiveflag().hashCode() );
         result = 37 * result + ( getRecordcreationtime() == null ? 0 : this.getRecordcreationtime().hashCode() );
         result = 37 * result + ( getRecordlastchangetime() == null ? 0 : this.getRecordlastchangetime().hashCode() );
         result = 37 * result + ( getUserlastchange() == null ? 0 : this.getUserlastchange().hashCode() );
         return result;
   }   


}


