package com.galexis.allog2mysql.deleteme;
// Generated Sep 6, 2013 9:37:59 AM by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Custordlbt generated by hbm2java
 */
@Entity
@Table(name="CUSTORDLBT"
    ,schema="INTEGAP"
    ,catalog="CHGALE11RDB"
)
public class Custordlbt  implements java.io.Serializable {


     private long pk;
     private Custordhdr custordhdr;
     private Custordlin custordlin;
     private int deliverylinenr;
     private String batchnumber;
     private Date expirydate;
     private BigDecimal deliveryquantity;
     private Integer superiorpositionlinenr;
     private String serialnr;

    public Custordlbt() {
    }

	
    public Custordlbt(long pk, Custordhdr custordhdr, Custordlin custordlin, int deliverylinenr, String batchnumber, BigDecimal deliveryquantity) {
        this.pk = pk;
        this.custordhdr = custordhdr;
        this.custordlin = custordlin;
        this.deliverylinenr = deliverylinenr;
        this.batchnumber = batchnumber;
        this.deliveryquantity = deliveryquantity;
    }
    public Custordlbt(long pk, Custordhdr custordhdr, Custordlin custordlin, int deliverylinenr, String batchnumber, Date expirydate, BigDecimal deliveryquantity, Integer superiorpositionlinenr, String serialnr) {
       this.pk = pk;
       this.custordhdr = custordhdr;
       this.custordlin = custordlin;
       this.deliverylinenr = deliverylinenr;
       this.batchnumber = batchnumber;
       this.expirydate = expirydate;
       this.deliveryquantity = deliveryquantity;
       this.superiorpositionlinenr = superiorpositionlinenr;
       this.serialnr = serialnr;
    }
   
     @Id 

    
    @Column(name="PK", unique=true, nullable=false, precision=12, scale=0)
    public long getPk() {
        return this.pk;
    }
    
    public void setPk(long pk) {
        this.pk = pk;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CUSTORDHDRPK", nullable=false)
    public Custordhdr getCustordhdr() {
        return this.custordhdr;
    }
    
    public void setCustordhdr(Custordhdr custordhdr) {
        this.custordhdr = custordhdr;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CUSTORDLINPK", nullable=false)
    public Custordlin getCustordlin() {
        return this.custordlin;
    }
    
    public void setCustordlin(Custordlin custordlin) {
        this.custordlin = custordlin;
    }

    
    @Column(name="DELIVERYLINENR", nullable=false, precision=6, scale=0)
    public int getDeliverylinenr() {
        return this.deliverylinenr;
    }
    
    public void setDeliverylinenr(int deliverylinenr) {
        this.deliverylinenr = deliverylinenr;
    }

    
    @Column(name="BATCHNUMBER", nullable=false, length=20)
    public String getBatchnumber() {
        return this.batchnumber;
    }
    
    public void setBatchnumber(String batchnumber) {
        this.batchnumber = batchnumber;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="EXPIRYDATE", length=10)
    public Date getExpirydate() {
        return this.expirydate;
    }
    
    public void setExpirydate(Date expirydate) {
        this.expirydate = expirydate;
    }

    
    @Column(name="DELIVERYQUANTITY", nullable=false, precision=15, scale=3)
    public BigDecimal getDeliveryquantity() {
        return this.deliveryquantity;
    }
    
    public void setDeliveryquantity(BigDecimal deliveryquantity) {
        this.deliveryquantity = deliveryquantity;
    }

    
    @Column(name="SUPERIORPOSITIONLINENR", precision=6, scale=0)
    public Integer getSuperiorpositionlinenr() {
        return this.superiorpositionlinenr;
    }
    
    public void setSuperiorpositionlinenr(Integer superiorpositionlinenr) {
        this.superiorpositionlinenr = superiorpositionlinenr;
    }

    
    @Column(name="SERIALNR", length=30)
    public String getSerialnr() {
        return this.serialnr;
    }
    
    public void setSerialnr(String serialnr) {
        this.serialnr = serialnr;
    }




}


