package com.galexis.allog2mysql.deleteme;
// Generated Sep 6, 2013 9:37:59 AM by Hibernate Tools 3.6.0


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Custopolin generated by hbm2java
 */
@Entity
@Table(name="CUSTOPOLIN"
    ,schema="INTEGAP"
    ,catalog="CHGALE11RDB"
    , uniqueConstraints = @UniqueConstraint(columnNames="PK") 
)
public class Custopolin  implements java.io.Serializable {


     private CustopolinId id;
     private Retlin retlin;
     private Itemmaster itemmaster;
     private Custopohdr custopohdr;

    public Custopolin() {
    }

	
    public Custopolin(CustopolinId id, Itemmaster itemmaster, Custopohdr custopohdr) {
        this.id = id;
        this.itemmaster = itemmaster;
        this.custopohdr = custopohdr;
    }
    public Custopolin(CustopolinId id, Retlin retlin, Itemmaster itemmaster, Custopohdr custopohdr) {
       this.id = id;
       this.retlin = retlin;
       this.itemmaster = itemmaster;
       this.custopohdr = custopohdr;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="pk", column=@Column(name="PK", unique=true, nullable=false, precision=12, scale=0) ), 
        @AttributeOverride(name="custopohdrpk", column=@Column(name="CUSTOPOHDRPK", nullable=false, precision=12, scale=0) ), 
        @AttributeOverride(name="orderline", column=@Column(name="ORDERLINE", nullable=false, precision=5, scale=0) ), 
        @AttributeOverride(name="deliverylinenr", column=@Column(name="DELIVERYLINENR", precision=5, scale=0) ), 
        @AttributeOverride(name="orderlinestatus", column=@Column(name="ORDERLINESTATUS", precision=2, scale=0) ), 
        @AttributeOverride(name="itemmasterpk", column=@Column(name="ITEMMASTERPK", nullable=false, precision=12, scale=0) ), 
        @AttributeOverride(name="itemnr", column=@Column(name="ITEMNR", nullable=false, length=35) ), 
        @AttributeOverride(name="itemnrcontractor", column=@Column(name="ITEMNRCONTRACTOR", length=35) ), 
        @AttributeOverride(name="salesrepresentative", column=@Column(name="SALESREPRESENTATIVE", length=30) ), 
        @AttributeOverride(name="requesteddeliverydate", column=@Column(name="REQUESTEDDELIVERYDATE", length=26) ), 
        @AttributeOverride(name="freeofchargeflag", column=@Column(name="FREEOFCHARGEFLAG", length=1) ), 
        @AttributeOverride(name="freeofchargereasoncode", column=@Column(name="FREEOFCHARGEREASONCODE", length=2) ), 
        @AttributeOverride(name="orderquantity", column=@Column(name="ORDERQUANTITY", precision=15, scale=3) ), 
        @AttributeOverride(name="deliveredquantity", column=@Column(name="DELIVEREDQUANTITY", precision=15, scale=3) ), 
        @AttributeOverride(name="remainingquantity", column=@Column(name="REMAININGQUANTITY", precision=15, scale=3) ), 
        @AttributeOverride(name="invoicequantity", column=@Column(name="INVOICEQUANTITY", precision=15, scale=3) ), 
        @AttributeOverride(name="unit", column=@Column(name="UNIT", length=5) ), 
        @AttributeOverride(name="requestedbatchid", column=@Column(name="REQUESTEDBATCHID", length=20) ), 
        @AttributeOverride(name="batchexpirydate", column=@Column(name="BATCHEXPIRYDATE", length=26) ), 
        @AttributeOverride(name="salesprice", column=@Column(name="SALESPRICE", precision=17, scale=4) ), 
        @AttributeOverride(name="netsalesprice", column=@Column(name="NETSALESPRICE", precision=17, scale=4) ), 
        @AttributeOverride(name="incidentnr", column=@Column(name="INCIDENTNR", precision=12, scale=0) ), 
        @AttributeOverride(name="incidentline", column=@Column(name="INCIDENTLINE", precision=5, scale=0) ), 
        @AttributeOverride(name="retlinpk", column=@Column(name="RETLINPK", precision=12, scale=0) ), 
        @AttributeOverride(name="backloggedflag", column=@Column(name="BACKLOGGEDFLAG", length=1) ), 
        @AttributeOverride(name="ipFreeofchargereasoncode", column=@Column(name="IP_FREEOFCHARGEREASONCODE", precision=5, scale=0) ), 
        @AttributeOverride(name="programname", column=@Column(name="PROGRAMNAME", length=10) ), 
        @AttributeOverride(name="filename", column=@Column(name="FILENAME", length=10) ), 
        @AttributeOverride(name="processingflag1", column=@Column(name="PROCESSINGFLAG1", length=1) ), 
        @AttributeOverride(name="processingflag2", column=@Column(name="PROCESSINGFLAG2", length=1) ), 
        @AttributeOverride(name="processingflag3", column=@Column(name="PROCESSINGFLAG3", length=1) ), 
        @AttributeOverride(name="processingflag4", column=@Column(name="PROCESSINGFLAG4", length=1) ), 
        @AttributeOverride(name="processingflag5", column=@Column(name="PROCESSINGFLAG5", length=1) ), 
        @AttributeOverride(name="processingflag6", column=@Column(name="PROCESSINGFLAG6", length=1) ), 
        @AttributeOverride(name="processingflag7", column=@Column(name="PROCESSINGFLAG7", length=1) ), 
        @AttributeOverride(name="processingflag8", column=@Column(name="PROCESSINGFLAG8", length=1) ), 
        @AttributeOverride(name="processingflag9", column=@Column(name="PROCESSINGFLAG9", length=1) ), 
        @AttributeOverride(name="processingflag10", column=@Column(name="PROCESSINGFLAG10", length=1) ), 
        @AttributeOverride(name="outboundignore", column=@Column(name="OUTBOUNDIGNORE", nullable=false, length=1) ), 
        @AttributeOverride(name="recordlastchangetime", column=@Column(name="RECORDLASTCHANGETIME", length=26) ), 
        @AttributeOverride(name="recordcreationtime", column=@Column(name="RECORDCREATIONTIME", nullable=false, length=26) ) } )
    public CustopolinId getId() {
        return this.id;
    }
    
    public void setId(CustopolinId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="RETLINPK", insertable=false, updatable=false)
    public Retlin getRetlin() {
        return this.retlin;
    }
    
    public void setRetlin(Retlin retlin) {
        this.retlin = retlin;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ITEMMASTERPK", nullable=false, insertable=false, updatable=false)
    public Itemmaster getItemmaster() {
        return this.itemmaster;
    }
    
    public void setItemmaster(Itemmaster itemmaster) {
        this.itemmaster = itemmaster;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CUSTOPOHDRPK", nullable=false, insertable=false, updatable=false)
    public Custopohdr getCustopohdr() {
        return this.custopohdr;
    }
    
    public void setCustopohdr(Custopohdr custopohdr) {
        this.custopohdr = custopohdr;
    }




}


