package com.galexis.allog2mysql.deleteme;
// Generated Sep 6, 2013 9:37:59 AM by Hibernate Tools 3.6.0


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Delannlin generated by hbm2java
 */
@Entity
@Table(name="DELANNLIN"
    ,schema="INTEGAP"
    ,catalog="CHGALE11RDB"
    , uniqueConstraints = @UniqueConstraint(columnNames="PK") 
)
public class Delannlin  implements java.io.Serializable {


     private DelannlinId id;
     private Delannhdr delannhdr;

    public Delannlin() {
    }

	
    public Delannlin(DelannlinId id) {
        this.id = id;
    }
    public Delannlin(DelannlinId id, Delannhdr delannhdr) {
       this.id = id;
       this.delannhdr = delannhdr;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="pk", column=@Column(name="PK", unique=true, nullable=false, precision=12, scale=0) ), 
        @AttributeOverride(name="delannhdrpk", column=@Column(name="DELANNHDRPK", precision=12, scale=0) ), 
        @AttributeOverride(name="inbounddeliverynr", column=@Column(name="INBOUNDDELIVERYNR", length=35) ), 
        @AttributeOverride(name="inbounddeliveryline", column=@Column(name="INBOUNDDELIVERYLINE", precision=6, scale=0) ), 
        @AttributeOverride(name="materialnr", column=@Column(name="MATERIALNR", length=35) ), 
        @AttributeOverride(name="marketmaterialnr", column=@Column(name="MARKETMATERIALNR", length=35) ), 
        @AttributeOverride(name="purchaseqty", column=@Column(name="PURCHASEQTY", precision=15, scale=3) ), 
        @AttributeOverride(name="confirmedqty", column=@Column(name="CONFIRMEDQTY", precision=15, scale=3) ), 
        @AttributeOverride(name="unitofqty", column=@Column(name="UNITOFQTY", length=3) ), 
        @AttributeOverride(name="grossweight", column=@Column(name="GROSSWEIGHT", precision=15, scale=3) ), 
        @AttributeOverride(name="unitofweight", column=@Column(name="UNITOFWEIGHT", length=3) ), 
        @AttributeOverride(name="confirmeddeliverydate", column=@Column(name="CONFIRMEDDELIVERYDATE", precision=8, scale=0) ), 
        @AttributeOverride(name="purchaseordernr", column=@Column(name="PURCHASEORDERNR", length=35) ), 
        @AttributeOverride(name="purchaseorderline", column=@Column(name="PURCHASEORDERLINE", length=6) ), 
        @AttributeOverride(name="batchid", column=@Column(name="BATCHID", length=10) ), 
        @AttributeOverride(name="expirydate", column=@Column(name="EXPIRYDATE", length=8) ), 
        @AttributeOverride(name="uniqueid", column=@Column(name="UNIQUEID", length=15) ), 
        @AttributeOverride(name="itemnr", column=@Column(name="ITEMNR", length=35) ), 
        @AttributeOverride(name="mainsuppliernr", column=@Column(name="MAINSUPPLIERNR", length=11) ), 
        @AttributeOverride(name="recordstatus", column=@Column(name="RECORDSTATUS", length=1) ), 
        @AttributeOverride(name="textfield101", column=@Column(name="TEXTFIELD10_1", length=10) ), 
        @AttributeOverride(name="textfield102", column=@Column(name="TEXTFIELD10_2", length=10) ), 
        @AttributeOverride(name="textfield103", column=@Column(name="TEXTFIELD10_3", length=10) ), 
        @AttributeOverride(name="textfield351", column=@Column(name="TEXTFIELD35_1", length=35) ), 
        @AttributeOverride(name="textfield352", column=@Column(name="TEXTFIELD35_2", length=35) ), 
        @AttributeOverride(name="textfield353", column=@Column(name="TEXTFIELD35_3", length=35) ), 
        @AttributeOverride(name="deliverydonetime", column=@Column(name="DELIVERYDONETIME", length=26) ), 
        @AttributeOverride(name="timestampreceived", column=@Column(name="TIMESTAMPRECEIVED", length=26) ), 
        @AttributeOverride(name="status", column=@Column(name="STATUS", length=1) ), 
        @AttributeOverride(name="transactionid", column=@Column(name="TRANSACTIONID", length=50) ), 
        @AttributeOverride(name="timestampconfirmation", column=@Column(name="TIMESTAMPCONFIRMATION", length=26) ), 
        @AttributeOverride(name="programname", column=@Column(name="PROGRAMNAME", length=10) ), 
        @AttributeOverride(name="processingflag1", column=@Column(name="PROCESSINGFLAG1", length=1) ), 
        @AttributeOverride(name="processingflag2", column=@Column(name="PROCESSINGFLAG2", length=1) ), 
        @AttributeOverride(name="processingflag3", column=@Column(name="PROCESSINGFLAG3", length=1) ), 
        @AttributeOverride(name="processingflag4", column=@Column(name="PROCESSINGFLAG4", length=1) ), 
        @AttributeOverride(name="processingflag5", column=@Column(name="PROCESSINGFLAG5", length=1) ), 
        @AttributeOverride(name="processingflag6", column=@Column(name="PROCESSINGFLAG6", length=1) ), 
        @AttributeOverride(name="processingflag7", column=@Column(name="PROCESSINGFLAG7", length=1) ), 
        @AttributeOverride(name="processingflag8", column=@Column(name="PROCESSINGFLAG8", length=1) ), 
        @AttributeOverride(name="processingflag9", column=@Column(name="PROCESSINGFLAG9", length=1) ), 
        @AttributeOverride(name="processingflag10", column=@Column(name="PROCESSINGFLAG10", length=1) ), 
        @AttributeOverride(name="recordprocessedflag", column=@Column(name="RECORDPROCESSEDFLAG", length=1) ), 
        @AttributeOverride(name="recordprocessingtime", column=@Column(name="RECORDPROCESSINGTIME", length=26) ), 
        @AttributeOverride(name="recordlastchangetime", column=@Column(name="RECORDLASTCHANGETIME", length=26) ), 
        @AttributeOverride(name="recordcreationtime", column=@Column(name="RECORDCREATIONTIME", nullable=false, length=26) ) } )
    public DelannlinId getId() {
        return this.id;
    }
    
    public void setId(DelannlinId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="DELANNHDRPK", insertable=false, updatable=false)
    public Delannhdr getDelannhdr() {
        return this.delannhdr;
    }
    
    public void setDelannhdr(Delannhdr delannhdr) {
        this.delannhdr = delannhdr;
    }




}


