package com.galexis.allog2mysql.deleteme;
// Generated Sep 6, 2013 9:37:59 AM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Delannhdr generated by hbm2java
 */
@Entity
@Table(name="DELANNHDR"
    ,schema="INTEGAP"
    ,catalog="CHGALE11RDB"
)
public class Delannhdr  implements java.io.Serializable {


     private long pk;
     private Contrdef contrdef;
     private String inbounddeliverynr;
     private String vendornr;
     private String vendorname;
     private String purchaseordernr;
     private String billoflading;
     private String recordstatus;
     private String textfield101;
     private String textfield102;
     private String textfield103;
     private String textfield351;
     private String textfield352;
     private String textfield353;
     private String filereceived;
     private Date timestampreceived;
     private Integer filesequencenr;
     private String status;
     private String transactionid;
     private Date timestampconfirmation;
     private String fileconfirmed;
     private String programname;
     private String processingflag1;
     private String processingflag2;
     private String processingflag3;
     private String processingflag4;
     private String processingflag5;
     private String processingflag6;
     private String processingflag7;
     private String processingflag8;
     private String processingflag9;
     private String processingflag10;
     private String recordprocessedflag;
     private Date recordprocessingtime;
     private Date recordlastchangetime;
     private Date recordcreationtime;
     private Set<Delannlin> delannlins = new HashSet<Delannlin>(0);

    public Delannhdr() {
    }

	
    public Delannhdr(long pk, Date recordcreationtime) {
        this.pk = pk;
        this.recordcreationtime = recordcreationtime;
    }
    public Delannhdr(long pk, Contrdef contrdef, String inbounddeliverynr, String vendornr, String vendorname, String purchaseordernr, String billoflading, String recordstatus, String textfield101, String textfield102, String textfield103, String textfield351, String textfield352, String textfield353, String filereceived, Date timestampreceived, Integer filesequencenr, String status, String transactionid, Date timestampconfirmation, String fileconfirmed, String programname, String processingflag1, String processingflag2, String processingflag3, String processingflag4, String processingflag5, String processingflag6, String processingflag7, String processingflag8, String processingflag9, String processingflag10, String recordprocessedflag, Date recordprocessingtime, Date recordlastchangetime, Date recordcreationtime, Set<Delannlin> delannlins) {
       this.pk = pk;
       this.contrdef = contrdef;
       this.inbounddeliverynr = inbounddeliverynr;
       this.vendornr = vendornr;
       this.vendorname = vendorname;
       this.purchaseordernr = purchaseordernr;
       this.billoflading = billoflading;
       this.recordstatus = recordstatus;
       this.textfield101 = textfield101;
       this.textfield102 = textfield102;
       this.textfield103 = textfield103;
       this.textfield351 = textfield351;
       this.textfield352 = textfield352;
       this.textfield353 = textfield353;
       this.filereceived = filereceived;
       this.timestampreceived = timestampreceived;
       this.filesequencenr = filesequencenr;
       this.status = status;
       this.transactionid = transactionid;
       this.timestampconfirmation = timestampconfirmation;
       this.fileconfirmed = fileconfirmed;
       this.programname = programname;
       this.processingflag1 = processingflag1;
       this.processingflag2 = processingflag2;
       this.processingflag3 = processingflag3;
       this.processingflag4 = processingflag4;
       this.processingflag5 = processingflag5;
       this.processingflag6 = processingflag6;
       this.processingflag7 = processingflag7;
       this.processingflag8 = processingflag8;
       this.processingflag9 = processingflag9;
       this.processingflag10 = processingflag10;
       this.recordprocessedflag = recordprocessedflag;
       this.recordprocessingtime = recordprocessingtime;
       this.recordlastchangetime = recordlastchangetime;
       this.recordcreationtime = recordcreationtime;
       this.delannlins = delannlins;
    }
   
     @Id 

    
    @Column(name="PK", unique=true, nullable=false, precision=12, scale=0)
    public long getPk() {
        return this.pk;
    }
    
    public void setPk(long pk) {
        this.pk = pk;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CONTRDEFPK")
    public Contrdef getContrdef() {
        return this.contrdef;
    }
    
    public void setContrdef(Contrdef contrdef) {
        this.contrdef = contrdef;
    }

    
    @Column(name="INBOUNDDELIVERYNR", length=35)
    public String getInbounddeliverynr() {
        return this.inbounddeliverynr;
    }
    
    public void setInbounddeliverynr(String inbounddeliverynr) {
        this.inbounddeliverynr = inbounddeliverynr;
    }

    
    @Column(name="VENDORNR", length=10)
    public String getVendornr() {
        return this.vendornr;
    }
    
    public void setVendornr(String vendornr) {
        this.vendornr = vendornr;
    }

    
    @Column(name="VENDORNAME", length=35)
    public String getVendorname() {
        return this.vendorname;
    }
    
    public void setVendorname(String vendorname) {
        this.vendorname = vendorname;
    }

    
    @Column(name="PURCHASEORDERNR", length=35)
    public String getPurchaseordernr() {
        return this.purchaseordernr;
    }
    
    public void setPurchaseordernr(String purchaseordernr) {
        this.purchaseordernr = purchaseordernr;
    }

    
    @Column(name="BILLOFLADING", length=35)
    public String getBilloflading() {
        return this.billoflading;
    }
    
    public void setBilloflading(String billoflading) {
        this.billoflading = billoflading;
    }

    
    @Column(name="RECORDSTATUS", length=1)
    public String getRecordstatus() {
        return this.recordstatus;
    }
    
    public void setRecordstatus(String recordstatus) {
        this.recordstatus = recordstatus;
    }

    
    @Column(name="TEXTFIELD10_1", length=10)
    public String getTextfield101() {
        return this.textfield101;
    }
    
    public void setTextfield101(String textfield101) {
        this.textfield101 = textfield101;
    }

    
    @Column(name="TEXTFIELD10_2", length=10)
    public String getTextfield102() {
        return this.textfield102;
    }
    
    public void setTextfield102(String textfield102) {
        this.textfield102 = textfield102;
    }

    
    @Column(name="TEXTFIELD10_3", length=10)
    public String getTextfield103() {
        return this.textfield103;
    }
    
    public void setTextfield103(String textfield103) {
        this.textfield103 = textfield103;
    }

    
    @Column(name="TEXTFIELD35_1", length=35)
    public String getTextfield351() {
        return this.textfield351;
    }
    
    public void setTextfield351(String textfield351) {
        this.textfield351 = textfield351;
    }

    
    @Column(name="TEXTFIELD35_2", length=35)
    public String getTextfield352() {
        return this.textfield352;
    }
    
    public void setTextfield352(String textfield352) {
        this.textfield352 = textfield352;
    }

    
    @Column(name="TEXTFIELD35_3", length=35)
    public String getTextfield353() {
        return this.textfield353;
    }
    
    public void setTextfield353(String textfield353) {
        this.textfield353 = textfield353;
    }

    
    @Column(name="FILERECEIVED", length=50)
    public String getFilereceived() {
        return this.filereceived;
    }
    
    public void setFilereceived(String filereceived) {
        this.filereceived = filereceived;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="TIMESTAMPRECEIVED", length=26)
    public Date getTimestampreceived() {
        return this.timestampreceived;
    }
    
    public void setTimestampreceived(Date timestampreceived) {
        this.timestampreceived = timestampreceived;
    }

    
    @Column(name="FILESEQUENCENR", precision=7, scale=0)
    public Integer getFilesequencenr() {
        return this.filesequencenr;
    }
    
    public void setFilesequencenr(Integer filesequencenr) {
        this.filesequencenr = filesequencenr;
    }

    
    @Column(name="STATUS", length=1)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    
    @Column(name="TRANSACTIONID", length=36)
    public String getTransactionid() {
        return this.transactionid;
    }
    
    public void setTransactionid(String transactionid) {
        this.transactionid = transactionid;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="TIMESTAMPCONFIRMATION", length=26)
    public Date getTimestampconfirmation() {
        return this.timestampconfirmation;
    }
    
    public void setTimestampconfirmation(Date timestampconfirmation) {
        this.timestampconfirmation = timestampconfirmation;
    }

    
    @Column(name="FILECONFIRMED", length=50)
    public String getFileconfirmed() {
        return this.fileconfirmed;
    }
    
    public void setFileconfirmed(String fileconfirmed) {
        this.fileconfirmed = fileconfirmed;
    }

    
    @Column(name="PROGRAMNAME", length=10)
    public String getProgramname() {
        return this.programname;
    }
    
    public void setProgramname(String programname) {
        this.programname = programname;
    }

    
    @Column(name="PROCESSINGFLAG1", length=1)
    public String getProcessingflag1() {
        return this.processingflag1;
    }
    
    public void setProcessingflag1(String processingflag1) {
        this.processingflag1 = processingflag1;
    }

    
    @Column(name="PROCESSINGFLAG2", length=1)
    public String getProcessingflag2() {
        return this.processingflag2;
    }
    
    public void setProcessingflag2(String processingflag2) {
        this.processingflag2 = processingflag2;
    }

    
    @Column(name="PROCESSINGFLAG3", length=1)
    public String getProcessingflag3() {
        return this.processingflag3;
    }
    
    public void setProcessingflag3(String processingflag3) {
        this.processingflag3 = processingflag3;
    }

    
    @Column(name="PROCESSINGFLAG4", length=1)
    public String getProcessingflag4() {
        return this.processingflag4;
    }
    
    public void setProcessingflag4(String processingflag4) {
        this.processingflag4 = processingflag4;
    }

    
    @Column(name="PROCESSINGFLAG5", length=1)
    public String getProcessingflag5() {
        return this.processingflag5;
    }
    
    public void setProcessingflag5(String processingflag5) {
        this.processingflag5 = processingflag5;
    }

    
    @Column(name="PROCESSINGFLAG6", length=1)
    public String getProcessingflag6() {
        return this.processingflag6;
    }
    
    public void setProcessingflag6(String processingflag6) {
        this.processingflag6 = processingflag6;
    }

    
    @Column(name="PROCESSINGFLAG7", length=1)
    public String getProcessingflag7() {
        return this.processingflag7;
    }
    
    public void setProcessingflag7(String processingflag7) {
        this.processingflag7 = processingflag7;
    }

    
    @Column(name="PROCESSINGFLAG8", length=1)
    public String getProcessingflag8() {
        return this.processingflag8;
    }
    
    public void setProcessingflag8(String processingflag8) {
        this.processingflag8 = processingflag8;
    }

    
    @Column(name="PROCESSINGFLAG9", length=1)
    public String getProcessingflag9() {
        return this.processingflag9;
    }
    
    public void setProcessingflag9(String processingflag9) {
        this.processingflag9 = processingflag9;
    }

    
    @Column(name="PROCESSINGFLAG10", length=1)
    public String getProcessingflag10() {
        return this.processingflag10;
    }
    
    public void setProcessingflag10(String processingflag10) {
        this.processingflag10 = processingflag10;
    }

    
    @Column(name="RECORDPROCESSEDFLAG", length=1)
    public String getRecordprocessedflag() {
        return this.recordprocessedflag;
    }
    
    public void setRecordprocessedflag(String recordprocessedflag) {
        this.recordprocessedflag = recordprocessedflag;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="RECORDPROCESSINGTIME", length=26)
    public Date getRecordprocessingtime() {
        return this.recordprocessingtime;
    }
    
    public void setRecordprocessingtime(Date recordprocessingtime) {
        this.recordprocessingtime = recordprocessingtime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="RECORDLASTCHANGETIME", length=26)
    public Date getRecordlastchangetime() {
        return this.recordlastchangetime;
    }
    
    public void setRecordlastchangetime(Date recordlastchangetime) {
        this.recordlastchangetime = recordlastchangetime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="RECORDCREATIONTIME", nullable=false, length=26)
    public Date getRecordcreationtime() {
        return this.recordcreationtime;
    }
    
    public void setRecordcreationtime(Date recordcreationtime) {
        this.recordcreationtime = recordcreationtime;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="delannhdr")
    public Set<Delannlin> getDelannlins() {
        return this.delannlins;
    }
    
    public void setDelannlins(Set<Delannlin> delannlins) {
        this.delannlins = delannlins;
    }




}


