package com.galexis.allog2mysql.deleteme;
// Generated Sep 6, 2013 9:37:59 AM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Delhdr generated by hbm2java
 */
@Entity
@Table(name="DELHDR"
    ,schema="INTEGAP"
    ,catalog="CHGALE11RDB"
)
public class Delhdr  implements java.io.Serializable {


     private long pk;
     private Contrdef contrdef;
     private Timedate timedateByIpTimedatepkReporting;
     private Bizparaddr bizparaddrByBizparaddrpkOrder;
     private Bizparaddr bizparaddrByBizparaddrpkDelivery;
     private Bizparaddr bizparaddrByBizparaddrpkInvoice;
     private Timedate timedateByTimedatepk;
     private String deliverynr;
     private String salesorganisation;
     private String salesorganisationdesc;
     private long salesordernr;
     private String salesordertype;
     private String salesordertypedescription;
     private String salesordercustomernr;
     private String contractorordercustomernr;
     private String contractorinvoicecustomernr;
     private String contractordeliverycustomernr;
     private String customerreference;
     private String customerordernredifact;
     private String manneroftransport;
     private String manneroftransportdesc;
     private String termsofdelivery;
     private String termsofdeliverydesc;
     private Date orderdate;
     private String orderSourceCode;
     private String transportnotenr;
     private String customerreference1;
     private String customerreference2;
     private String customerreference3;
     private String customerreference4;
     private String customerreference5;
     private Integer ipSalesordertype;
     private Integer ipInvoicetype;
     private String programname;
     private String filename;
     private String processingflag1;
     private String processingflag2;
     private String processingflag3;
     private String processingflag4;
     private String processingflag5;
     private String processingflag6;
     private String processingflag7;
     private String processingflag8;
     private String processingflag9;
     private String processingflag10;
     private String backendreleased;
     private String outboundignore;
     private String transactionid;
     private String recordprocessedflag;
     private Date recordprocessingtime;
     private String toCusttransactionid;
     private String toCustrecordprocessedflag;
     private Date toCustrecordprocessingtime;
     private Date recordlastchangetime;
     private Date recordcreationtime;
     private Set<Dellinpck> dellinpcks = new HashSet<Dellinpck>(0);
     private Set<Dellinbtc> dellinbtcs = new HashSet<Dellinbtc>(0);
     private Set<Invhdr> invhdrs = new HashSet<Invhdr>(0);
     private Set<Dellin> dellins = new HashSet<Dellin>(0);

    public Delhdr() {
    }

	
    public Delhdr(long pk, Contrdef contrdef, Bizparaddr bizparaddrByBizparaddrpkOrder, long salesordernr, String salesordertype, Date orderdate, String backendreleased, String outboundignore, String recordprocessedflag, String toCustrecordprocessedflag, Date recordcreationtime) {
        this.pk = pk;
        this.contrdef = contrdef;
        this.bizparaddrByBizparaddrpkOrder = bizparaddrByBizparaddrpkOrder;
        this.salesordernr = salesordernr;
        this.salesordertype = salesordertype;
        this.orderdate = orderdate;
        this.backendreleased = backendreleased;
        this.outboundignore = outboundignore;
        this.recordprocessedflag = recordprocessedflag;
        this.toCustrecordprocessedflag = toCustrecordprocessedflag;
        this.recordcreationtime = recordcreationtime;
    }
    public Delhdr(long pk, Contrdef contrdef, Timedate timedateByIpTimedatepkReporting, Bizparaddr bizparaddrByBizparaddrpkOrder, Bizparaddr bizparaddrByBizparaddrpkDelivery, Bizparaddr bizparaddrByBizparaddrpkInvoice, Timedate timedateByTimedatepk, String deliverynr, String salesorganisation, String salesorganisationdesc, long salesordernr, String salesordertype, String salesordertypedescription, String salesordercustomernr, String contractorordercustomernr, String contractorinvoicecustomernr, String contractordeliverycustomernr, String customerreference, String customerordernredifact, String manneroftransport, String manneroftransportdesc, String termsofdelivery, String termsofdeliverydesc, Date orderdate, String orderSourceCode, String transportnotenr, String customerreference1, String customerreference2, String customerreference3, String customerreference4, String customerreference5, Integer ipSalesordertype, Integer ipInvoicetype, String programname, String filename, String processingflag1, String processingflag2, String processingflag3, String processingflag4, String processingflag5, String processingflag6, String processingflag7, String processingflag8, String processingflag9, String processingflag10, String backendreleased, String outboundignore, String transactionid, String recordprocessedflag, Date recordprocessingtime, String toCusttransactionid, String toCustrecordprocessedflag, Date toCustrecordprocessingtime, Date recordlastchangetime, Date recordcreationtime, Set<Dellinpck> dellinpcks, Set<Dellinbtc> dellinbtcs, Set<Invhdr> invhdrs, Set<Dellin> dellins) {
       this.pk = pk;
       this.contrdef = contrdef;
       this.timedateByIpTimedatepkReporting = timedateByIpTimedatepkReporting;
       this.bizparaddrByBizparaddrpkOrder = bizparaddrByBizparaddrpkOrder;
       this.bizparaddrByBizparaddrpkDelivery = bizparaddrByBizparaddrpkDelivery;
       this.bizparaddrByBizparaddrpkInvoice = bizparaddrByBizparaddrpkInvoice;
       this.timedateByTimedatepk = timedateByTimedatepk;
       this.deliverynr = deliverynr;
       this.salesorganisation = salesorganisation;
       this.salesorganisationdesc = salesorganisationdesc;
       this.salesordernr = salesordernr;
       this.salesordertype = salesordertype;
       this.salesordertypedescription = salesordertypedescription;
       this.salesordercustomernr = salesordercustomernr;
       this.contractorordercustomernr = contractorordercustomernr;
       this.contractorinvoicecustomernr = contractorinvoicecustomernr;
       this.contractordeliverycustomernr = contractordeliverycustomernr;
       this.customerreference = customerreference;
       this.customerordernredifact = customerordernredifact;
       this.manneroftransport = manneroftransport;
       this.manneroftransportdesc = manneroftransportdesc;
       this.termsofdelivery = termsofdelivery;
       this.termsofdeliverydesc = termsofdeliverydesc;
       this.orderdate = orderdate;
       this.orderSourceCode = orderSourceCode;
       this.transportnotenr = transportnotenr;
       this.customerreference1 = customerreference1;
       this.customerreference2 = customerreference2;
       this.customerreference3 = customerreference3;
       this.customerreference4 = customerreference4;
       this.customerreference5 = customerreference5;
       this.ipSalesordertype = ipSalesordertype;
       this.ipInvoicetype = ipInvoicetype;
       this.programname = programname;
       this.filename = filename;
       this.processingflag1 = processingflag1;
       this.processingflag2 = processingflag2;
       this.processingflag3 = processingflag3;
       this.processingflag4 = processingflag4;
       this.processingflag5 = processingflag5;
       this.processingflag6 = processingflag6;
       this.processingflag7 = processingflag7;
       this.processingflag8 = processingflag8;
       this.processingflag9 = processingflag9;
       this.processingflag10 = processingflag10;
       this.backendreleased = backendreleased;
       this.outboundignore = outboundignore;
       this.transactionid = transactionid;
       this.recordprocessedflag = recordprocessedflag;
       this.recordprocessingtime = recordprocessingtime;
       this.toCusttransactionid = toCusttransactionid;
       this.toCustrecordprocessedflag = toCustrecordprocessedflag;
       this.toCustrecordprocessingtime = toCustrecordprocessingtime;
       this.recordlastchangetime = recordlastchangetime;
       this.recordcreationtime = recordcreationtime;
       this.dellinpcks = dellinpcks;
       this.dellinbtcs = dellinbtcs;
       this.invhdrs = invhdrs;
       this.dellins = dellins;
    }
   
     @Id 

    
    @Column(name="PK", unique=true, nullable=false, precision=12, scale=0)
    public long getPk() {
        return this.pk;
    }
    
    public void setPk(long pk) {
        this.pk = pk;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CONTRDEFPK", nullable=false)
    public Contrdef getContrdef() {
        return this.contrdef;
    }
    
    public void setContrdef(Contrdef contrdef) {
        this.contrdef = contrdef;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IP_TIMEDATEPK_REPORTING")
    public Timedate getTimedateByIpTimedatepkReporting() {
        return this.timedateByIpTimedatepkReporting;
    }
    
    public void setTimedateByIpTimedatepkReporting(Timedate timedateByIpTimedatepkReporting) {
        this.timedateByIpTimedatepkReporting = timedateByIpTimedatepkReporting;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="BIZPARADDRPK_ORDER", nullable=false)
    public Bizparaddr getBizparaddrByBizparaddrpkOrder() {
        return this.bizparaddrByBizparaddrpkOrder;
    }
    
    public void setBizparaddrByBizparaddrpkOrder(Bizparaddr bizparaddrByBizparaddrpkOrder) {
        this.bizparaddrByBizparaddrpkOrder = bizparaddrByBizparaddrpkOrder;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="BIZPARADDRPK_DELIVERY")
    public Bizparaddr getBizparaddrByBizparaddrpkDelivery() {
        return this.bizparaddrByBizparaddrpkDelivery;
    }
    
    public void setBizparaddrByBizparaddrpkDelivery(Bizparaddr bizparaddrByBizparaddrpkDelivery) {
        this.bizparaddrByBizparaddrpkDelivery = bizparaddrByBizparaddrpkDelivery;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="BIZPARADDRPK_INVOICE")
    public Bizparaddr getBizparaddrByBizparaddrpkInvoice() {
        return this.bizparaddrByBizparaddrpkInvoice;
    }
    
    public void setBizparaddrByBizparaddrpkInvoice(Bizparaddr bizparaddrByBizparaddrpkInvoice) {
        this.bizparaddrByBizparaddrpkInvoice = bizparaddrByBizparaddrpkInvoice;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="TIMEDATEPK")
    public Timedate getTimedateByTimedatepk() {
        return this.timedateByTimedatepk;
    }
    
    public void setTimedateByTimedatepk(Timedate timedateByTimedatepk) {
        this.timedateByTimedatepk = timedateByTimedatepk;
    }

    
    @Column(name="DELIVERYNR", length=35)
    public String getDeliverynr() {
        return this.deliverynr;
    }
    
    public void setDeliverynr(String deliverynr) {
        this.deliverynr = deliverynr;
    }

    
    @Column(name="SALESORGANISATION", length=30)
    public String getSalesorganisation() {
        return this.salesorganisation;
    }
    
    public void setSalesorganisation(String salesorganisation) {
        this.salesorganisation = salesorganisation;
    }

    
    @Column(name="SALESORGANISATIONDESC", length=50)
    public String getSalesorganisationdesc() {
        return this.salesorganisationdesc;
    }
    
    public void setSalesorganisationdesc(String salesorganisationdesc) {
        this.salesorganisationdesc = salesorganisationdesc;
    }

    
    @Column(name="SALESORDERNR", nullable=false, precision=12, scale=0)
    public long getSalesordernr() {
        return this.salesordernr;
    }
    
    public void setSalesordernr(long salesordernr) {
        this.salesordernr = salesordernr;
    }

    
    @Column(name="SALESORDERTYPE", nullable=false, length=2)
    public String getSalesordertype() {
        return this.salesordertype;
    }
    
    public void setSalesordertype(String salesordertype) {
        this.salesordertype = salesordertype;
    }

    
    @Column(name="SALESORDERTYPEDESCRIPTION", length=50)
    public String getSalesordertypedescription() {
        return this.salesordertypedescription;
    }
    
    public void setSalesordertypedescription(String salesordertypedescription) {
        this.salesordertypedescription = salesordertypedescription;
    }

    
    @Column(name="SALESORDERCUSTOMERNR", length=20)
    public String getSalesordercustomernr() {
        return this.salesordercustomernr;
    }
    
    public void setSalesordercustomernr(String salesordercustomernr) {
        this.salesordercustomernr = salesordercustomernr;
    }

    
    @Column(name="CONTRACTORORDERCUSTOMERNR", length=30)
    public String getContractorordercustomernr() {
        return this.contractorordercustomernr;
    }
    
    public void setContractorordercustomernr(String contractorordercustomernr) {
        this.contractorordercustomernr = contractorordercustomernr;
    }

    
    @Column(name="CONTRACTORINVOICECUSTOMERNR", length=30)
    public String getContractorinvoicecustomernr() {
        return this.contractorinvoicecustomernr;
    }
    
    public void setContractorinvoicecustomernr(String contractorinvoicecustomernr) {
        this.contractorinvoicecustomernr = contractorinvoicecustomernr;
    }

    
    @Column(name="CONTRACTORDELIVERYCUSTOMERNR", length=30)
    public String getContractordeliverycustomernr() {
        return this.contractordeliverycustomernr;
    }
    
    public void setContractordeliverycustomernr(String contractordeliverycustomernr) {
        this.contractordeliverycustomernr = contractordeliverycustomernr;
    }

    
    @Column(name="CUSTOMERREFERENCE", length=30)
    public String getCustomerreference() {
        return this.customerreference;
    }
    
    public void setCustomerreference(String customerreference) {
        this.customerreference = customerreference;
    }

    
    @Column(name="CUSTOMERORDERNREDIFACT", length=35)
    public String getCustomerordernredifact() {
        return this.customerordernredifact;
    }
    
    public void setCustomerordernredifact(String customerordernredifact) {
        this.customerordernredifact = customerordernredifact;
    }

    
    @Column(name="MANNEROFTRANSPORT", length=10)
    public String getManneroftransport() {
        return this.manneroftransport;
    }
    
    public void setManneroftransport(String manneroftransport) {
        this.manneroftransport = manneroftransport;
    }

    
    @Column(name="MANNEROFTRANSPORTDESC", length=50)
    public String getManneroftransportdesc() {
        return this.manneroftransportdesc;
    }
    
    public void setManneroftransportdesc(String manneroftransportdesc) {
        this.manneroftransportdesc = manneroftransportdesc;
    }

    
    @Column(name="TERMSOFDELIVERY", length=10)
    public String getTermsofdelivery() {
        return this.termsofdelivery;
    }
    
    public void setTermsofdelivery(String termsofdelivery) {
        this.termsofdelivery = termsofdelivery;
    }

    
    @Column(name="TERMSOFDELIVERYDESC", length=50)
    public String getTermsofdeliverydesc() {
        return this.termsofdeliverydesc;
    }
    
    public void setTermsofdeliverydesc(String termsofdeliverydesc) {
        this.termsofdeliverydesc = termsofdeliverydesc;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ORDERDATE", nullable=false, length=26)
    public Date getOrderdate() {
        return this.orderdate;
    }
    
    public void setOrderdate(Date orderdate) {
        this.orderdate = orderdate;
    }

    
    @Column(name="ORDER_SOURCE_CODE", length=20)
    public String getOrderSourceCode() {
        return this.orderSourceCode;
    }
    
    public void setOrderSourceCode(String orderSourceCode) {
        this.orderSourceCode = orderSourceCode;
    }

    
    @Column(name="TRANSPORTNOTENR", length=35)
    public String getTransportnotenr() {
        return this.transportnotenr;
    }
    
    public void setTransportnotenr(String transportnotenr) {
        this.transportnotenr = transportnotenr;
    }

    
    @Column(name="CUSTOMERREFERENCE1", length=35)
    public String getCustomerreference1() {
        return this.customerreference1;
    }
    
    public void setCustomerreference1(String customerreference1) {
        this.customerreference1 = customerreference1;
    }

    
    @Column(name="CUSTOMERREFERENCE2", length=35)
    public String getCustomerreference2() {
        return this.customerreference2;
    }
    
    public void setCustomerreference2(String customerreference2) {
        this.customerreference2 = customerreference2;
    }

    
    @Column(name="CUSTOMERREFERENCE3", length=35)
    public String getCustomerreference3() {
        return this.customerreference3;
    }
    
    public void setCustomerreference3(String customerreference3) {
        this.customerreference3 = customerreference3;
    }

    
    @Column(name="CUSTOMERREFERENCE4", length=35)
    public String getCustomerreference4() {
        return this.customerreference4;
    }
    
    public void setCustomerreference4(String customerreference4) {
        this.customerreference4 = customerreference4;
    }

    
    @Column(name="CUSTOMERREFERENCE5", length=35)
    public String getCustomerreference5() {
        return this.customerreference5;
    }
    
    public void setCustomerreference5(String customerreference5) {
        this.customerreference5 = customerreference5;
    }

    
    @Column(name="IP_SALESORDERTYPE", precision=5, scale=0)
    public Integer getIpSalesordertype() {
        return this.ipSalesordertype;
    }
    
    public void setIpSalesordertype(Integer ipSalesordertype) {
        this.ipSalesordertype = ipSalesordertype;
    }

    
    @Column(name="IP_INVOICETYPE", precision=5, scale=0)
    public Integer getIpInvoicetype() {
        return this.ipInvoicetype;
    }
    
    public void setIpInvoicetype(Integer ipInvoicetype) {
        this.ipInvoicetype = ipInvoicetype;
    }

    
    @Column(name="PROGRAMNAME", length=10)
    public String getProgramname() {
        return this.programname;
    }
    
    public void setProgramname(String programname) {
        this.programname = programname;
    }

    
    @Column(name="FILENAME", length=10)
    public String getFilename() {
        return this.filename;
    }
    
    public void setFilename(String filename) {
        this.filename = filename;
    }

    
    @Column(name="PROCESSINGFLAG1", length=1)
    public String getProcessingflag1() {
        return this.processingflag1;
    }
    
    public void setProcessingflag1(String processingflag1) {
        this.processingflag1 = processingflag1;
    }

    
    @Column(name="PROCESSINGFLAG2", length=1)
    public String getProcessingflag2() {
        return this.processingflag2;
    }
    
    public void setProcessingflag2(String processingflag2) {
        this.processingflag2 = processingflag2;
    }

    
    @Column(name="PROCESSINGFLAG3", length=1)
    public String getProcessingflag3() {
        return this.processingflag3;
    }
    
    public void setProcessingflag3(String processingflag3) {
        this.processingflag3 = processingflag3;
    }

    
    @Column(name="PROCESSINGFLAG4", length=1)
    public String getProcessingflag4() {
        return this.processingflag4;
    }
    
    public void setProcessingflag4(String processingflag4) {
        this.processingflag4 = processingflag4;
    }

    
    @Column(name="PROCESSINGFLAG5", length=1)
    public String getProcessingflag5() {
        return this.processingflag5;
    }
    
    public void setProcessingflag5(String processingflag5) {
        this.processingflag5 = processingflag5;
    }

    
    @Column(name="PROCESSINGFLAG6", length=1)
    public String getProcessingflag6() {
        return this.processingflag6;
    }
    
    public void setProcessingflag6(String processingflag6) {
        this.processingflag6 = processingflag6;
    }

    
    @Column(name="PROCESSINGFLAG7", length=1)
    public String getProcessingflag7() {
        return this.processingflag7;
    }
    
    public void setProcessingflag7(String processingflag7) {
        this.processingflag7 = processingflag7;
    }

    
    @Column(name="PROCESSINGFLAG8", length=1)
    public String getProcessingflag8() {
        return this.processingflag8;
    }
    
    public void setProcessingflag8(String processingflag8) {
        this.processingflag8 = processingflag8;
    }

    
    @Column(name="PROCESSINGFLAG9", length=1)
    public String getProcessingflag9() {
        return this.processingflag9;
    }
    
    public void setProcessingflag9(String processingflag9) {
        this.processingflag9 = processingflag9;
    }

    
    @Column(name="PROCESSINGFLAG10", length=1)
    public String getProcessingflag10() {
        return this.processingflag10;
    }
    
    public void setProcessingflag10(String processingflag10) {
        this.processingflag10 = processingflag10;
    }

    
    @Column(name="BACKENDRELEASED", nullable=false, length=1)
    public String getBackendreleased() {
        return this.backendreleased;
    }
    
    public void setBackendreleased(String backendreleased) {
        this.backendreleased = backendreleased;
    }

    
    @Column(name="OUTBOUNDIGNORE", nullable=false, length=1)
    public String getOutboundignore() {
        return this.outboundignore;
    }
    
    public void setOutboundignore(String outboundignore) {
        this.outboundignore = outboundignore;
    }

    
    @Column(name="TRANSACTIONID", length=50)
    public String getTransactionid() {
        return this.transactionid;
    }
    
    public void setTransactionid(String transactionid) {
        this.transactionid = transactionid;
    }

    
    @Column(name="RECORDPROCESSEDFLAG", nullable=false, length=1)
    public String getRecordprocessedflag() {
        return this.recordprocessedflag;
    }
    
    public void setRecordprocessedflag(String recordprocessedflag) {
        this.recordprocessedflag = recordprocessedflag;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="RECORDPROCESSINGTIME", length=26)
    public Date getRecordprocessingtime() {
        return this.recordprocessingtime;
    }
    
    public void setRecordprocessingtime(Date recordprocessingtime) {
        this.recordprocessingtime = recordprocessingtime;
    }

    
    @Column(name="TO_CUSTTRANSACTIONID", length=50)
    public String getToCusttransactionid() {
        return this.toCusttransactionid;
    }
    
    public void setToCusttransactionid(String toCusttransactionid) {
        this.toCusttransactionid = toCusttransactionid;
    }

    
    @Column(name="TO_CUSTRECORDPROCESSEDFLAG", nullable=false, length=1)
    public String getToCustrecordprocessedflag() {
        return this.toCustrecordprocessedflag;
    }
    
    public void setToCustrecordprocessedflag(String toCustrecordprocessedflag) {
        this.toCustrecordprocessedflag = toCustrecordprocessedflag;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="TO_CUSTRECORDPROCESSINGTIME", length=26)
    public Date getToCustrecordprocessingtime() {
        return this.toCustrecordprocessingtime;
    }
    
    public void setToCustrecordprocessingtime(Date toCustrecordprocessingtime) {
        this.toCustrecordprocessingtime = toCustrecordprocessingtime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="RECORDLASTCHANGETIME", length=26)
    public Date getRecordlastchangetime() {
        return this.recordlastchangetime;
    }
    
    public void setRecordlastchangetime(Date recordlastchangetime) {
        this.recordlastchangetime = recordlastchangetime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="RECORDCREATIONTIME", nullable=false, length=26)
    public Date getRecordcreationtime() {
        return this.recordcreationtime;
    }
    
    public void setRecordcreationtime(Date recordcreationtime) {
        this.recordcreationtime = recordcreationtime;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="delhdr")
    public Set<Dellinpck> getDellinpcks() {
        return this.dellinpcks;
    }
    
    public void setDellinpcks(Set<Dellinpck> dellinpcks) {
        this.dellinpcks = dellinpcks;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="delhdr")
    public Set<Dellinbtc> getDellinbtcs() {
        return this.dellinbtcs;
    }
    
    public void setDellinbtcs(Set<Dellinbtc> dellinbtcs) {
        this.dellinbtcs = dellinbtcs;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="delhdr")
    public Set<Invhdr> getInvhdrs() {
        return this.invhdrs;
    }
    
    public void setInvhdrs(Set<Invhdr> invhdrs) {
        this.invhdrs = invhdrs;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="delhdr")
    public Set<Dellin> getDellins() {
        return this.dellins;
    }
    
    public void setDellins(Set<Dellin> dellins) {
        this.dellins = dellins;
    }




}


