package com.galexis.allog2mysql.deleteme;
// Generated Sep 6, 2013 9:37:59 AM by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Dellinbtc generated by hbm2java
 */
@Entity
@Table(name="DELLINBTC"
    ,schema="INTEGAP"
    ,catalog="CHGALE11RDB"
)
public class Dellinbtc  implements java.io.Serializable {


     private long pk;
     private Delhdr delhdr;
     private Dellin dellin;
     private short deliverylineseq;
     private Integer contractordeliverylinenr;
     private BigDecimal deliveredqty;
     private String itemnrcontractor;
     private String batchid;
     private Date batchexpirydate;
     private String serialnr;
     private String batchidcontractor;
     private String zeroconfirmedflag;
     private String deliverywarehouse;
     private String zone;
     private String location;
     private String stockstatus;
     private String qualitycontrolflag;
     private Integer superiorpositionlinenr;
     private Integer ipWarehouse;
     private Integer ipLocationzone;
     private Integer ipStockcategory;
     private String programname;
     private String filename;
     private String processingflag1;
     private String processingflag2;
     private String processingflag3;
     private String processingflag4;
     private String processingflag5;
     private String processingflag6;
     private String processingflag7;
     private String processingflag8;
     private String processingflag9;
     private String processingflag10;
     private String outboundignore;
     private Date recordlastchangetime;
     private Date recordcreationtime;
     private Set<Dellinpck> dellinpcks = new HashSet<Dellinpck>(0);
     private Set<Invlinbtc> invlinbtcs = new HashSet<Invlinbtc>(0);

    public Dellinbtc() {
    }

	
    public Dellinbtc(long pk, Delhdr delhdr, Dellin dellin, short deliverylineseq, String outboundignore, Date recordcreationtime) {
        this.pk = pk;
        this.delhdr = delhdr;
        this.dellin = dellin;
        this.deliverylineseq = deliverylineseq;
        this.outboundignore = outboundignore;
        this.recordcreationtime = recordcreationtime;
    }
    public Dellinbtc(long pk, Delhdr delhdr, Dellin dellin, short deliverylineseq, Integer contractordeliverylinenr, BigDecimal deliveredqty, String itemnrcontractor, String batchid, Date batchexpirydate, String serialnr, String batchidcontractor, String zeroconfirmedflag, String deliverywarehouse, String zone, String location, String stockstatus, String qualitycontrolflag, Integer superiorpositionlinenr, Integer ipWarehouse, Integer ipLocationzone, Integer ipStockcategory, String programname, String filename, String processingflag1, String processingflag2, String processingflag3, String processingflag4, String processingflag5, String processingflag6, String processingflag7, String processingflag8, String processingflag9, String processingflag10, String outboundignore, Date recordlastchangetime, Date recordcreationtime, Set<Dellinpck> dellinpcks, Set<Invlinbtc> invlinbtcs) {
       this.pk = pk;
       this.delhdr = delhdr;
       this.dellin = dellin;
       this.deliverylineseq = deliverylineseq;
       this.contractordeliverylinenr = contractordeliverylinenr;
       this.deliveredqty = deliveredqty;
       this.itemnrcontractor = itemnrcontractor;
       this.batchid = batchid;
       this.batchexpirydate = batchexpirydate;
       this.serialnr = serialnr;
       this.batchidcontractor = batchidcontractor;
       this.zeroconfirmedflag = zeroconfirmedflag;
       this.deliverywarehouse = deliverywarehouse;
       this.zone = zone;
       this.location = location;
       this.stockstatus = stockstatus;
       this.qualitycontrolflag = qualitycontrolflag;
       this.superiorpositionlinenr = superiorpositionlinenr;
       this.ipWarehouse = ipWarehouse;
       this.ipLocationzone = ipLocationzone;
       this.ipStockcategory = ipStockcategory;
       this.programname = programname;
       this.filename = filename;
       this.processingflag1 = processingflag1;
       this.processingflag2 = processingflag2;
       this.processingflag3 = processingflag3;
       this.processingflag4 = processingflag4;
       this.processingflag5 = processingflag5;
       this.processingflag6 = processingflag6;
       this.processingflag7 = processingflag7;
       this.processingflag8 = processingflag8;
       this.processingflag9 = processingflag9;
       this.processingflag10 = processingflag10;
       this.outboundignore = outboundignore;
       this.recordlastchangetime = recordlastchangetime;
       this.recordcreationtime = recordcreationtime;
       this.dellinpcks = dellinpcks;
       this.invlinbtcs = invlinbtcs;
    }
   
     @Id 

    
    @Column(name="PK", unique=true, nullable=false, precision=12, scale=0)
    public long getPk() {
        return this.pk;
    }
    
    public void setPk(long pk) {
        this.pk = pk;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="DELHDRPK", nullable=false)
    public Delhdr getDelhdr() {
        return this.delhdr;
    }
    
    public void setDelhdr(Delhdr delhdr) {
        this.delhdr = delhdr;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="DELLINPK", nullable=false)
    public Dellin getDellin() {
        return this.dellin;
    }
    
    public void setDellin(Dellin dellin) {
        this.dellin = dellin;
    }

    
    @Column(name="DELIVERYLINESEQ", nullable=false, precision=3, scale=0)
    public short getDeliverylineseq() {
        return this.deliverylineseq;
    }
    
    public void setDeliverylineseq(short deliverylineseq) {
        this.deliverylineseq = deliverylineseq;
    }

    
    @Column(name="CONTRACTORDELIVERYLINENR", precision=6, scale=0)
    public Integer getContractordeliverylinenr() {
        return this.contractordeliverylinenr;
    }
    
    public void setContractordeliverylinenr(Integer contractordeliverylinenr) {
        this.contractordeliverylinenr = contractordeliverylinenr;
    }

    
    @Column(name="DELIVEREDQTY", precision=15, scale=3)
    public BigDecimal getDeliveredqty() {
        return this.deliveredqty;
    }
    
    public void setDeliveredqty(BigDecimal deliveredqty) {
        this.deliveredqty = deliveredqty;
    }

    
    @Column(name="ITEMNRCONTRACTOR", length=35)
    public String getItemnrcontractor() {
        return this.itemnrcontractor;
    }
    
    public void setItemnrcontractor(String itemnrcontractor) {
        this.itemnrcontractor = itemnrcontractor;
    }

    
    @Column(name="BATCHID", length=20)
    public String getBatchid() {
        return this.batchid;
    }
    
    public void setBatchid(String batchid) {
        this.batchid = batchid;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="BATCHEXPIRYDATE", length=26)
    public Date getBatchexpirydate() {
        return this.batchexpirydate;
    }
    
    public void setBatchexpirydate(Date batchexpirydate) {
        this.batchexpirydate = batchexpirydate;
    }

    
    @Column(name="SERIALNR", length=30)
    public String getSerialnr() {
        return this.serialnr;
    }
    
    public void setSerialnr(String serialnr) {
        this.serialnr = serialnr;
    }

    
    @Column(name="BATCHIDCONTRACTOR", length=20)
    public String getBatchidcontractor() {
        return this.batchidcontractor;
    }
    
    public void setBatchidcontractor(String batchidcontractor) {
        this.batchidcontractor = batchidcontractor;
    }

    
    @Column(name="ZEROCONFIRMEDFLAG", length=1)
    public String getZeroconfirmedflag() {
        return this.zeroconfirmedflag;
    }
    
    public void setZeroconfirmedflag(String zeroconfirmedflag) {
        this.zeroconfirmedflag = zeroconfirmedflag;
    }

    
    @Column(name="DELIVERYWAREHOUSE", length=10)
    public String getDeliverywarehouse() {
        return this.deliverywarehouse;
    }
    
    public void setDeliverywarehouse(String deliverywarehouse) {
        this.deliverywarehouse = deliverywarehouse;
    }

    
    @Column(name="ZONE", length=10)
    public String getZone() {
        return this.zone;
    }
    
    public void setZone(String zone) {
        this.zone = zone;
    }

    
    @Column(name="LOCATION", length=10)
    public String getLocation() {
        return this.location;
    }
    
    public void setLocation(String location) {
        this.location = location;
    }

    
    @Column(name="STOCKSTATUS", length=10)
    public String getStockstatus() {
        return this.stockstatus;
    }
    
    public void setStockstatus(String stockstatus) {
        this.stockstatus = stockstatus;
    }

    
    @Column(name="QUALITYCONTROLFLAG", length=1)
    public String getQualitycontrolflag() {
        return this.qualitycontrolflag;
    }
    
    public void setQualitycontrolflag(String qualitycontrolflag) {
        this.qualitycontrolflag = qualitycontrolflag;
    }

    
    @Column(name="SUPERIORPOSITIONLINENR", precision=6, scale=0)
    public Integer getSuperiorpositionlinenr() {
        return this.superiorpositionlinenr;
    }
    
    public void setSuperiorpositionlinenr(Integer superiorpositionlinenr) {
        this.superiorpositionlinenr = superiorpositionlinenr;
    }

    
    @Column(name="IP_WAREHOUSE", precision=5, scale=0)
    public Integer getIpWarehouse() {
        return this.ipWarehouse;
    }
    
    public void setIpWarehouse(Integer ipWarehouse) {
        this.ipWarehouse = ipWarehouse;
    }

    
    @Column(name="IP_LOCATIONZONE", precision=5, scale=0)
    public Integer getIpLocationzone() {
        return this.ipLocationzone;
    }
    
    public void setIpLocationzone(Integer ipLocationzone) {
        this.ipLocationzone = ipLocationzone;
    }

    
    @Column(name="IP_STOCKCATEGORY", precision=5, scale=0)
    public Integer getIpStockcategory() {
        return this.ipStockcategory;
    }
    
    public void setIpStockcategory(Integer ipStockcategory) {
        this.ipStockcategory = ipStockcategory;
    }

    
    @Column(name="PROGRAMNAME", length=10)
    public String getProgramname() {
        return this.programname;
    }
    
    public void setProgramname(String programname) {
        this.programname = programname;
    }

    
    @Column(name="FILENAME", length=10)
    public String getFilename() {
        return this.filename;
    }
    
    public void setFilename(String filename) {
        this.filename = filename;
    }

    
    @Column(name="PROCESSINGFLAG1", length=1)
    public String getProcessingflag1() {
        return this.processingflag1;
    }
    
    public void setProcessingflag1(String processingflag1) {
        this.processingflag1 = processingflag1;
    }

    
    @Column(name="PROCESSINGFLAG2", length=1)
    public String getProcessingflag2() {
        return this.processingflag2;
    }
    
    public void setProcessingflag2(String processingflag2) {
        this.processingflag2 = processingflag2;
    }

    
    @Column(name="PROCESSINGFLAG3", length=1)
    public String getProcessingflag3() {
        return this.processingflag3;
    }
    
    public void setProcessingflag3(String processingflag3) {
        this.processingflag3 = processingflag3;
    }

    
    @Column(name="PROCESSINGFLAG4", length=1)
    public String getProcessingflag4() {
        return this.processingflag4;
    }
    
    public void setProcessingflag4(String processingflag4) {
        this.processingflag4 = processingflag4;
    }

    
    @Column(name="PROCESSINGFLAG5", length=1)
    public String getProcessingflag5() {
        return this.processingflag5;
    }
    
    public void setProcessingflag5(String processingflag5) {
        this.processingflag5 = processingflag5;
    }

    
    @Column(name="PROCESSINGFLAG6", length=1)
    public String getProcessingflag6() {
        return this.processingflag6;
    }
    
    public void setProcessingflag6(String processingflag6) {
        this.processingflag6 = processingflag6;
    }

    
    @Column(name="PROCESSINGFLAG7", length=1)
    public String getProcessingflag7() {
        return this.processingflag7;
    }
    
    public void setProcessingflag7(String processingflag7) {
        this.processingflag7 = processingflag7;
    }

    
    @Column(name="PROCESSINGFLAG8", length=1)
    public String getProcessingflag8() {
        return this.processingflag8;
    }
    
    public void setProcessingflag8(String processingflag8) {
        this.processingflag8 = processingflag8;
    }

    
    @Column(name="PROCESSINGFLAG9", length=1)
    public String getProcessingflag9() {
        return this.processingflag9;
    }
    
    public void setProcessingflag9(String processingflag9) {
        this.processingflag9 = processingflag9;
    }

    
    @Column(name="PROCESSINGFLAG10", length=1)
    public String getProcessingflag10() {
        return this.processingflag10;
    }
    
    public void setProcessingflag10(String processingflag10) {
        this.processingflag10 = processingflag10;
    }

    
    @Column(name="OUTBOUNDIGNORE", nullable=false, length=1)
    public String getOutboundignore() {
        return this.outboundignore;
    }
    
    public void setOutboundignore(String outboundignore) {
        this.outboundignore = outboundignore;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="RECORDLASTCHANGETIME", length=26)
    public Date getRecordlastchangetime() {
        return this.recordlastchangetime;
    }
    
    public void setRecordlastchangetime(Date recordlastchangetime) {
        this.recordlastchangetime = recordlastchangetime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="RECORDCREATIONTIME", nullable=false, length=26)
    public Date getRecordcreationtime() {
        return this.recordcreationtime;
    }
    
    public void setRecordcreationtime(Date recordcreationtime) {
        this.recordcreationtime = recordcreationtime;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="dellinbtc")
    public Set<Dellinpck> getDellinpcks() {
        return this.dellinpcks;
    }
    
    public void setDellinpcks(Set<Dellinpck> dellinpcks) {
        this.dellinpcks = dellinpcks;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="dellinbtc")
    public Set<Invlinbtc> getInvlinbtcs() {
        return this.invlinbtcs;
    }
    
    public void setInvlinbtcs(Set<Invlinbtc> invlinbtcs) {
        this.invlinbtcs = invlinbtcs;
    }




}


