package com.galexis.allog2mysql.deleteme;
// Generated Sep 6, 2013 9:37:59 AM by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Grelin generated by hbm2java
 */
@Entity
@Table(name="GRELIN"
    ,schema="INTEGAP"
    ,catalog="CHGALE11RDB"
)
public class Grelin  implements java.io.Serializable {


     private long pk;
     private Itemmaster itemmaster;
     private Grehdr grehdr;
     private Integer deliveryline;
     private Date deliverydate;
     private int purchaseorderline;
     private Long goodsreceptionnote;
     private Integer goodsreceptionnoteline;
     private String purchaseordernrDelannhdr;
     private String purchaseordernrDelannlin;
     private String purchaseorderlineDelann;
     private String itemnr;
     private String itemnrcontractor;
     private BigDecimal orderquantity;
     private BigDecimal purchaseprice;
     private BigDecimal standardcost;
     private BigDecimal amount;
     private BigDecimal deliveredquantity;
     private String stockkeepingunit;
     private String qualityapprovalflag;
     private String batchflag;
     private String serialnumbertrackingflag;
     private String warehouse;
     private String shipmentmarking;
     private String transitdeliveryflag;
     private String directdeliveryflag;
     private String dispatchnotesupplier;
     private String supplieritemdesc;
     private BigDecimal grossweight;
     private BigDecimal netweight;
     private BigDecimal grossvolume;
     private BigDecimal netvolume;
     private String partialdeliveryflag;
     private String deliverycompletedflag;
     private Date confirmeddeliverydate;
     private String delannlinSplit;
     private String programname;
     private String filename;
     private String processingflag1;
     private String processingflag2;
     private String processingflag3;
     private String processingflag4;
     private String processingflag5;
     private String processingflag6;
     private String processingflag7;
     private String processingflag8;
     private String processingflag9;
     private String processingflag10;
     private String outboundignore;
     private Date recordlastchangetime;
     private Date recordcreationtime;
     private Set<Grelinbtc> grelinbtcs = new HashSet<Grelinbtc>(0);

    public Grelin() {
    }

	
    public Grelin(long pk, Itemmaster itemmaster, Grehdr grehdr, int purchaseorderline, String itemnr, String outboundignore, Date recordcreationtime) {
        this.pk = pk;
        this.itemmaster = itemmaster;
        this.grehdr = grehdr;
        this.purchaseorderline = purchaseorderline;
        this.itemnr = itemnr;
        this.outboundignore = outboundignore;
        this.recordcreationtime = recordcreationtime;
    }
    public Grelin(long pk, Itemmaster itemmaster, Grehdr grehdr, Integer deliveryline, Date deliverydate, int purchaseorderline, Long goodsreceptionnote, Integer goodsreceptionnoteline, String purchaseordernrDelannhdr, String purchaseordernrDelannlin, String purchaseorderlineDelann, String itemnr, String itemnrcontractor, BigDecimal orderquantity, BigDecimal purchaseprice, BigDecimal standardcost, BigDecimal amount, BigDecimal deliveredquantity, String stockkeepingunit, String qualityapprovalflag, String batchflag, String serialnumbertrackingflag, String warehouse, String shipmentmarking, String transitdeliveryflag, String directdeliveryflag, String dispatchnotesupplier, String supplieritemdesc, BigDecimal grossweight, BigDecimal netweight, BigDecimal grossvolume, BigDecimal netvolume, String partialdeliveryflag, String deliverycompletedflag, Date confirmeddeliverydate, String delannlinSplit, String programname, String filename, String processingflag1, String processingflag2, String processingflag3, String processingflag4, String processingflag5, String processingflag6, String processingflag7, String processingflag8, String processingflag9, String processingflag10, String outboundignore, Date recordlastchangetime, Date recordcreationtime, Set<Grelinbtc> grelinbtcs) {
       this.pk = pk;
       this.itemmaster = itemmaster;
       this.grehdr = grehdr;
       this.deliveryline = deliveryline;
       this.deliverydate = deliverydate;
       this.purchaseorderline = purchaseorderline;
       this.goodsreceptionnote = goodsreceptionnote;
       this.goodsreceptionnoteline = goodsreceptionnoteline;
       this.purchaseordernrDelannhdr = purchaseordernrDelannhdr;
       this.purchaseordernrDelannlin = purchaseordernrDelannlin;
       this.purchaseorderlineDelann = purchaseorderlineDelann;
       this.itemnr = itemnr;
       this.itemnrcontractor = itemnrcontractor;
       this.orderquantity = orderquantity;
       this.purchaseprice = purchaseprice;
       this.standardcost = standardcost;
       this.amount = amount;
       this.deliveredquantity = deliveredquantity;
       this.stockkeepingunit = stockkeepingunit;
       this.qualityapprovalflag = qualityapprovalflag;
       this.batchflag = batchflag;
       this.serialnumbertrackingflag = serialnumbertrackingflag;
       this.warehouse = warehouse;
       this.shipmentmarking = shipmentmarking;
       this.transitdeliveryflag = transitdeliveryflag;
       this.directdeliveryflag = directdeliveryflag;
       this.dispatchnotesupplier = dispatchnotesupplier;
       this.supplieritemdesc = supplieritemdesc;
       this.grossweight = grossweight;
       this.netweight = netweight;
       this.grossvolume = grossvolume;
       this.netvolume = netvolume;
       this.partialdeliveryflag = partialdeliveryflag;
       this.deliverycompletedflag = deliverycompletedflag;
       this.confirmeddeliverydate = confirmeddeliverydate;
       this.delannlinSplit = delannlinSplit;
       this.programname = programname;
       this.filename = filename;
       this.processingflag1 = processingflag1;
       this.processingflag2 = processingflag2;
       this.processingflag3 = processingflag3;
       this.processingflag4 = processingflag4;
       this.processingflag5 = processingflag5;
       this.processingflag6 = processingflag6;
       this.processingflag7 = processingflag7;
       this.processingflag8 = processingflag8;
       this.processingflag9 = processingflag9;
       this.processingflag10 = processingflag10;
       this.outboundignore = outboundignore;
       this.recordlastchangetime = recordlastchangetime;
       this.recordcreationtime = recordcreationtime;
       this.grelinbtcs = grelinbtcs;
    }
   
     @Id 

    
    @Column(name="PK", unique=true, nullable=false, precision=12, scale=0)
    public long getPk() {
        return this.pk;
    }
    
    public void setPk(long pk) {
        this.pk = pk;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ITEMMASTERPK", nullable=false)
    public Itemmaster getItemmaster() {
        return this.itemmaster;
    }
    
    public void setItemmaster(Itemmaster itemmaster) {
        this.itemmaster = itemmaster;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="GREHDRPK", nullable=false)
    public Grehdr getGrehdr() {
        return this.grehdr;
    }
    
    public void setGrehdr(Grehdr grehdr) {
        this.grehdr = grehdr;
    }

    
    @Column(name="DELIVERYLINE", precision=6, scale=0)
    public Integer getDeliveryline() {
        return this.deliveryline;
    }
    
    public void setDeliveryline(Integer deliveryline) {
        this.deliveryline = deliveryline;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="DELIVERYDATE", length=26)
    public Date getDeliverydate() {
        return this.deliverydate;
    }
    
    public void setDeliverydate(Date deliverydate) {
        this.deliverydate = deliverydate;
    }

    
    @Column(name="PURCHASEORDERLINE", nullable=false, precision=5, scale=0)
    public int getPurchaseorderline() {
        return this.purchaseorderline;
    }
    
    public void setPurchaseorderline(int purchaseorderline) {
        this.purchaseorderline = purchaseorderline;
    }

    
    @Column(name="GOODSRECEPTIONNOTE", precision=12, scale=0)
    public Long getGoodsreceptionnote() {
        return this.goodsreceptionnote;
    }
    
    public void setGoodsreceptionnote(Long goodsreceptionnote) {
        this.goodsreceptionnote = goodsreceptionnote;
    }

    
    @Column(name="GOODSRECEPTIONNOTELINE", precision=6, scale=0)
    public Integer getGoodsreceptionnoteline() {
        return this.goodsreceptionnoteline;
    }
    
    public void setGoodsreceptionnoteline(Integer goodsreceptionnoteline) {
        this.goodsreceptionnoteline = goodsreceptionnoteline;
    }

    
    @Column(name="PURCHASEORDERNR_DELANNHDR", length=35)
    public String getPurchaseordernrDelannhdr() {
        return this.purchaseordernrDelannhdr;
    }
    
    public void setPurchaseordernrDelannhdr(String purchaseordernrDelannhdr) {
        this.purchaseordernrDelannhdr = purchaseordernrDelannhdr;
    }

    
    @Column(name="PURCHASEORDERNR_DELANNLIN", length=35)
    public String getPurchaseordernrDelannlin() {
        return this.purchaseordernrDelannlin;
    }
    
    public void setPurchaseordernrDelannlin(String purchaseordernrDelannlin) {
        this.purchaseordernrDelannlin = purchaseordernrDelannlin;
    }

    
    @Column(name="PURCHASEORDERLINE_DELANN", length=6)
    public String getPurchaseorderlineDelann() {
        return this.purchaseorderlineDelann;
    }
    
    public void setPurchaseorderlineDelann(String purchaseorderlineDelann) {
        this.purchaseorderlineDelann = purchaseorderlineDelann;
    }

    
    @Column(name="ITEMNR", nullable=false, length=35)
    public String getItemnr() {
        return this.itemnr;
    }
    
    public void setItemnr(String itemnr) {
        this.itemnr = itemnr;
    }

    
    @Column(name="ITEMNRCONTRACTOR", length=35)
    public String getItemnrcontractor() {
        return this.itemnrcontractor;
    }
    
    public void setItemnrcontractor(String itemnrcontractor) {
        this.itemnrcontractor = itemnrcontractor;
    }

    
    @Column(name="ORDERQUANTITY", precision=15, scale=3)
    public BigDecimal getOrderquantity() {
        return this.orderquantity;
    }
    
    public void setOrderquantity(BigDecimal orderquantity) {
        this.orderquantity = orderquantity;
    }

    
    @Column(name="PURCHASEPRICE", precision=17, scale=4)
    public BigDecimal getPurchaseprice() {
        return this.purchaseprice;
    }
    
    public void setPurchaseprice(BigDecimal purchaseprice) {
        this.purchaseprice = purchaseprice;
    }

    
    @Column(name="STANDARDCOST", precision=17, scale=4)
    public BigDecimal getStandardcost() {
        return this.standardcost;
    }
    
    public void setStandardcost(BigDecimal standardcost) {
        this.standardcost = standardcost;
    }

    
    @Column(name="AMOUNT", precision=17, scale=4)
    public BigDecimal getAmount() {
        return this.amount;
    }
    
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    
    @Column(name="DELIVEREDQUANTITY", precision=15, scale=3)
    public BigDecimal getDeliveredquantity() {
        return this.deliveredquantity;
    }
    
    public void setDeliveredquantity(BigDecimal deliveredquantity) {
        this.deliveredquantity = deliveredquantity;
    }

    
    @Column(name="STOCKKEEPINGUNIT", length=5)
    public String getStockkeepingunit() {
        return this.stockkeepingunit;
    }
    
    public void setStockkeepingunit(String stockkeepingunit) {
        this.stockkeepingunit = stockkeepingunit;
    }

    
    @Column(name="QUALITYAPPROVALFLAG", length=1)
    public String getQualityapprovalflag() {
        return this.qualityapprovalflag;
    }
    
    public void setQualityapprovalflag(String qualityapprovalflag) {
        this.qualityapprovalflag = qualityapprovalflag;
    }

    
    @Column(name="BATCHFLAG", length=1)
    public String getBatchflag() {
        return this.batchflag;
    }
    
    public void setBatchflag(String batchflag) {
        this.batchflag = batchflag;
    }

    
    @Column(name="SERIALNUMBERTRACKINGFLAG", length=1)
    public String getSerialnumbertrackingflag() {
        return this.serialnumbertrackingflag;
    }
    
    public void setSerialnumbertrackingflag(String serialnumbertrackingflag) {
        this.serialnumbertrackingflag = serialnumbertrackingflag;
    }

    
    @Column(name="WAREHOUSE", length=10)
    public String getWarehouse() {
        return this.warehouse;
    }
    
    public void setWarehouse(String warehouse) {
        this.warehouse = warehouse;
    }

    
    @Column(name="SHIPMENTMARKING", length=30)
    public String getShipmentmarking() {
        return this.shipmentmarking;
    }
    
    public void setShipmentmarking(String shipmentmarking) {
        this.shipmentmarking = shipmentmarking;
    }

    
    @Column(name="TRANSITDELIVERYFLAG", length=1)
    public String getTransitdeliveryflag() {
        return this.transitdeliveryflag;
    }
    
    public void setTransitdeliveryflag(String transitdeliveryflag) {
        this.transitdeliveryflag = transitdeliveryflag;
    }

    
    @Column(name="DIRECTDELIVERYFLAG", length=1)
    public String getDirectdeliveryflag() {
        return this.directdeliveryflag;
    }
    
    public void setDirectdeliveryflag(String directdeliveryflag) {
        this.directdeliveryflag = directdeliveryflag;
    }

    
    @Column(name="DISPATCHNOTESUPPLIER", length=30)
    public String getDispatchnotesupplier() {
        return this.dispatchnotesupplier;
    }
    
    public void setDispatchnotesupplier(String dispatchnotesupplier) {
        this.dispatchnotesupplier = dispatchnotesupplier;
    }

    
    @Column(name="SUPPLIERITEMDESC", length=50)
    public String getSupplieritemdesc() {
        return this.supplieritemdesc;
    }
    
    public void setSupplieritemdesc(String supplieritemdesc) {
        this.supplieritemdesc = supplieritemdesc;
    }

    
    @Column(name="GROSSWEIGHT", precision=11, scale=5)
    public BigDecimal getGrossweight() {
        return this.grossweight;
    }
    
    public void setGrossweight(BigDecimal grossweight) {
        this.grossweight = grossweight;
    }

    
    @Column(name="NETWEIGHT", precision=11, scale=5)
    public BigDecimal getNetweight() {
        return this.netweight;
    }
    
    public void setNetweight(BigDecimal netweight) {
        this.netweight = netweight;
    }

    
    @Column(name="GROSSVOLUME", precision=11, scale=5)
    public BigDecimal getGrossvolume() {
        return this.grossvolume;
    }
    
    public void setGrossvolume(BigDecimal grossvolume) {
        this.grossvolume = grossvolume;
    }

    
    @Column(name="NETVOLUME", precision=11, scale=5)
    public BigDecimal getNetvolume() {
        return this.netvolume;
    }
    
    public void setNetvolume(BigDecimal netvolume) {
        this.netvolume = netvolume;
    }

    
    @Column(name="PARTIALDELIVERYFLAG", length=1)
    public String getPartialdeliveryflag() {
        return this.partialdeliveryflag;
    }
    
    public void setPartialdeliveryflag(String partialdeliveryflag) {
        this.partialdeliveryflag = partialdeliveryflag;
    }

    
    @Column(name="DELIVERYCOMPLETEDFLAG", length=1)
    public String getDeliverycompletedflag() {
        return this.deliverycompletedflag;
    }
    
    public void setDeliverycompletedflag(String deliverycompletedflag) {
        this.deliverycompletedflag = deliverycompletedflag;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CONFIRMEDDELIVERYDATE", length=26)
    public Date getConfirmeddeliverydate() {
        return this.confirmeddeliverydate;
    }
    
    public void setConfirmeddeliverydate(Date confirmeddeliverydate) {
        this.confirmeddeliverydate = confirmeddeliverydate;
    }

    
    @Column(name="DELANNLIN_SPLIT", length=1)
    public String getDelannlinSplit() {
        return this.delannlinSplit;
    }
    
    public void setDelannlinSplit(String delannlinSplit) {
        this.delannlinSplit = delannlinSplit;
    }

    
    @Column(name="PROGRAMNAME", length=10)
    public String getProgramname() {
        return this.programname;
    }
    
    public void setProgramname(String programname) {
        this.programname = programname;
    }

    
    @Column(name="FILENAME", length=10)
    public String getFilename() {
        return this.filename;
    }
    
    public void setFilename(String filename) {
        this.filename = filename;
    }

    
    @Column(name="PROCESSINGFLAG1", length=1)
    public String getProcessingflag1() {
        return this.processingflag1;
    }
    
    public void setProcessingflag1(String processingflag1) {
        this.processingflag1 = processingflag1;
    }

    
    @Column(name="PROCESSINGFLAG2", length=1)
    public String getProcessingflag2() {
        return this.processingflag2;
    }
    
    public void setProcessingflag2(String processingflag2) {
        this.processingflag2 = processingflag2;
    }

    
    @Column(name="PROCESSINGFLAG3", length=1)
    public String getProcessingflag3() {
        return this.processingflag3;
    }
    
    public void setProcessingflag3(String processingflag3) {
        this.processingflag3 = processingflag3;
    }

    
    @Column(name="PROCESSINGFLAG4", length=1)
    public String getProcessingflag4() {
        return this.processingflag4;
    }
    
    public void setProcessingflag4(String processingflag4) {
        this.processingflag4 = processingflag4;
    }

    
    @Column(name="PROCESSINGFLAG5", length=1)
    public String getProcessingflag5() {
        return this.processingflag5;
    }
    
    public void setProcessingflag5(String processingflag5) {
        this.processingflag5 = processingflag5;
    }

    
    @Column(name="PROCESSINGFLAG6", length=1)
    public String getProcessingflag6() {
        return this.processingflag6;
    }
    
    public void setProcessingflag6(String processingflag6) {
        this.processingflag6 = processingflag6;
    }

    
    @Column(name="PROCESSINGFLAG7", length=1)
    public String getProcessingflag7() {
        return this.processingflag7;
    }
    
    public void setProcessingflag7(String processingflag7) {
        this.processingflag7 = processingflag7;
    }

    
    @Column(name="PROCESSINGFLAG8", length=1)
    public String getProcessingflag8() {
        return this.processingflag8;
    }
    
    public void setProcessingflag8(String processingflag8) {
        this.processingflag8 = processingflag8;
    }

    
    @Column(name="PROCESSINGFLAG9", length=1)
    public String getProcessingflag9() {
        return this.processingflag9;
    }
    
    public void setProcessingflag9(String processingflag9) {
        this.processingflag9 = processingflag9;
    }

    
    @Column(name="PROCESSINGFLAG10", length=1)
    public String getProcessingflag10() {
        return this.processingflag10;
    }
    
    public void setProcessingflag10(String processingflag10) {
        this.processingflag10 = processingflag10;
    }

    
    @Column(name="OUTBOUNDIGNORE", nullable=false, length=1)
    public String getOutboundignore() {
        return this.outboundignore;
    }
    
    public void setOutboundignore(String outboundignore) {
        this.outboundignore = outboundignore;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="RECORDLASTCHANGETIME", length=26)
    public Date getRecordlastchangetime() {
        return this.recordlastchangetime;
    }
    
    public void setRecordlastchangetime(Date recordlastchangetime) {
        this.recordlastchangetime = recordlastchangetime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="RECORDCREATIONTIME", nullable=false, length=26)
    public Date getRecordcreationtime() {
        return this.recordcreationtime;
    }
    
    public void setRecordcreationtime(Date recordcreationtime) {
        this.recordcreationtime = recordcreationtime;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="grelin")
    public Set<Grelinbtc> getGrelinbtcs() {
        return this.grelinbtcs;
    }
    
    public void setGrelinbtcs(Set<Grelinbtc> grelinbtcs) {
        this.grelinbtcs = grelinbtcs;
    }




}


