package com.galexis.allog2mysql.deleteme;
// Generated Sep 6, 2013 9:37:59 AM by Hibernate Tools 3.6.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Holidaycal generated by hbm2java
 */
@Entity
@Table(name="HOLIDAYCAL"
    ,schema="INTEGAP"
    ,catalog="CHGALE11RDB"
)
public class Holidaycal  implements java.io.Serializable {


     private long pk;
     private Long contrdefpk;
     private String description;
     private Date date;
     private String userlastchange;
     private Date recordlastchangetime;
     private Date recordcreationtime;

    public Holidaycal() {
    }

	
    public Holidaycal(long pk, String description, Date date, String userlastchange, Date recordcreationtime) {
        this.pk = pk;
        this.description = description;
        this.date = date;
        this.userlastchange = userlastchange;
        this.recordcreationtime = recordcreationtime;
    }
    public Holidaycal(long pk, Long contrdefpk, String description, Date date, String userlastchange, Date recordlastchangetime, Date recordcreationtime) {
       this.pk = pk;
       this.contrdefpk = contrdefpk;
       this.description = description;
       this.date = date;
       this.userlastchange = userlastchange;
       this.recordlastchangetime = recordlastchangetime;
       this.recordcreationtime = recordcreationtime;
    }
   
     @Id 

    
    @Column(name="PK", unique=true, nullable=false, precision=12, scale=0)
    public long getPk() {
        return this.pk;
    }
    
    public void setPk(long pk) {
        this.pk = pk;
    }

    
    @Column(name="CONTRDEFPK", precision=12, scale=0)
    public Long getContrdefpk() {
        return this.contrdefpk;
    }
    
    public void setContrdefpk(Long contrdefpk) {
        this.contrdefpk = contrdefpk;
    }

    
    @Column(name="DESCRIPTION", nullable=false, length=100)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATE", nullable=false, length=10)
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }

    
    @Column(name="USERLASTCHANGE", nullable=false, length=20)
    public String getUserlastchange() {
        return this.userlastchange;
    }
    
    public void setUserlastchange(String userlastchange) {
        this.userlastchange = userlastchange;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="RECORDLASTCHANGETIME", length=26)
    public Date getRecordlastchangetime() {
        return this.recordlastchangetime;
    }
    
    public void setRecordlastchangetime(Date recordlastchangetime) {
        this.recordlastchangetime = recordlastchangetime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="RECORDCREATIONTIME", nullable=false, length=26)
    public Date getRecordcreationtime() {
        return this.recordcreationtime;
    }
    
    public void setRecordcreationtime(Date recordcreationtime) {
        this.recordcreationtime = recordcreationtime;
    }




}


