package com.galexis.allog2mysql.deleteme;
// Generated Sep 6, 2013 9:37:59 AM by Hibernate Tools 3.6.0


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Identnrf generated by hbm2java
 */
@Entity
@Table(name="IDENTNRF"
    ,schema="INTEGAP"
    ,catalog="CHGALE11RDB"
    , uniqueConstraints = {@UniqueConstraint(columnNames="PK"), @UniqueConstraint(columnNames="FILENAME")} 
)
public class Identnrf  implements java.io.Serializable {


     private IdentnrfId id;

    public Identnrf() {
    }

    public Identnrf(IdentnrfId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="pk", column=@Column(name="PK", unique=true, nullable=false, precision=12, scale=0) ), 
        @AttributeOverride(name="filename", column=@Column(name="FILENAME", unique=true, nullable=false, length=50) ), 
        @AttributeOverride(name="lastidentifier", column=@Column(name="LASTIDENTIFIER", nullable=false, precision=12, scale=0) ), 
        @AttributeOverride(name="recordlastchangetime", column=@Column(name="RECORDLASTCHANGETIME", nullable=false, length=26) ) } )
    public IdentnrfId getId() {
        return this.id;
    }
    
    public void setId(IdentnrfId id) {
        this.id = id;
    }




}


