package com.galexis.allog2mysql.deleteme;
// Generated Sep 6, 2013 9:37:59 AM by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Invhdr generated by hbm2java
 */
@Entity
@Table(name="INVHDR"
    ,schema="INTEGAP"
    ,catalog="CHGALE11RDB"
)
public class Invhdr  implements java.io.Serializable {


     private long pk;
     private Contrdef contrdef;
     private Bizparaddr bizparaddrByBizparaddrpkInvoice;
     private Bizparaddr bizparaddrByBizparaddrpkOrder;
     private Timedate timedateByIpTimedatepkReporting;
     private Bizparaddr bizparaddrByBizparaddrpkDebtor;
     private Delhdr delhdr;
     private Timedate timedateByTimedatepk;
     private Bizparaddr bizparaddrByBizparaddrpkDelivery;
     private long invoicenr;
     private boolean invoicetype;
     private Date invoicedate;
     private short invoiceyear;
     private String salesorganisation;
     private String salesorganisationdesc;
     private Long salesordernr;
     private String salesordertype;
     private Date salesorderdate;
     private String deliverynr;
     private String debtorcustomercontractor;
     private String contractorsalesorganisation;
     private String contractordivision;
     private String primarycurrency;
     private BigDecimal discountbase;
     private BigDecimal orderlinestotal;
     private BigDecimal ordertotal;
     private BigDecimal invoiceamountexcludingvat;
     private BigDecimal vatamount;
     private BigDecimal invoiceamountincludingvat;
     private BigDecimal invoiceadjustmentamount;
     private BigDecimal invoicediscountamount;
     private BigDecimal invoicefreightamount;
     private String termsofpaymentcode;
     private String termsofpaymentdesc;
     private Date duedate;
     private Short termsofpaymentcreditdays;
     private String mergeinvoicecode;
     private String orderSourceCode;
     private String withmovement;
     private String vathandlingcode1;
     private BigDecimal vathandlingcodepercentage1;
     private BigDecimal vatamount1;
     private BigDecimal vatbaseamount1;
     private String vathandlingcode2;
     private BigDecimal vathandlingcodepercentage2;
     private BigDecimal vatamount2;
     private BigDecimal vatbaseamount2;
     private String vathandlingcode3;
     private BigDecimal vathandlingcodepercentage3;
     private BigDecimal vatamount3;
     private BigDecimal vatbaseamount3;
     private String vathandlingcode4;
     private BigDecimal vathandlingcodepercentage4;
     private BigDecimal vatamount4;
     private BigDecimal vatbaseamount4;
     private Integer ipSalesordertype;
     private Integer ipInvoicetype;
     private Character ipIssaleswithmovement;
     private Character ipIsdebit;
     private String programname;
     private String filename;
     private String processingflag1;
     private String processingflag2;
     private String processingflag3;
     private String processingflag4;
     private String processingflag5;
     private String processingflag6;
     private String processingflag7;
     private String processingflag8;
     private String processingflag9;
     private String processingflag10;
     private String backendreleased;
     private String outboundignore;
     private String transactionid;
     private String recordprocessedflag;
     private Date recordprocessingtime;
     private Date recordlastchangetime;
     private Date recordcreationtime;
     private Set<Invlinbtc> invlinbtcs = new HashSet<Invlinbtc>(0);
     private Set<Invlin> invlins = new HashSet<Invlin>(0);

    public Invhdr() {
    }

	
    public Invhdr(long pk, Contrdef contrdef, Bizparaddr bizparaddrByBizparaddrpkOrder, long invoicenr, boolean invoicetype, Date invoicedate, short invoiceyear, String backendreleased, String outboundignore, String recordprocessedflag, Date recordcreationtime) {
        this.pk = pk;
        this.contrdef = contrdef;
        this.bizparaddrByBizparaddrpkOrder = bizparaddrByBizparaddrpkOrder;
        this.invoicenr = invoicenr;
        this.invoicetype = invoicetype;
        this.invoicedate = invoicedate;
        this.invoiceyear = invoiceyear;
        this.backendreleased = backendreleased;
        this.outboundignore = outboundignore;
        this.recordprocessedflag = recordprocessedflag;
        this.recordcreationtime = recordcreationtime;
    }
    public Invhdr(long pk, Contrdef contrdef, Bizparaddr bizparaddrByBizparaddrpkInvoice, Bizparaddr bizparaddrByBizparaddrpkOrder, Timedate timedateByIpTimedatepkReporting, Bizparaddr bizparaddrByBizparaddrpkDebtor, Delhdr delhdr, Timedate timedateByTimedatepk, Bizparaddr bizparaddrByBizparaddrpkDelivery, long invoicenr, boolean invoicetype, Date invoicedate, short invoiceyear, String salesorganisation, String salesorganisationdesc, Long salesordernr, String salesordertype, Date salesorderdate, String deliverynr, String debtorcustomercontractor, String contractorsalesorganisation, String contractordivision, String primarycurrency, BigDecimal discountbase, BigDecimal orderlinestotal, BigDecimal ordertotal, BigDecimal invoiceamountexcludingvat, BigDecimal vatamount, BigDecimal invoiceamountincludingvat, BigDecimal invoiceadjustmentamount, BigDecimal invoicediscountamount, BigDecimal invoicefreightamount, String termsofpaymentcode, String termsofpaymentdesc, Date duedate, Short termsofpaymentcreditdays, String mergeinvoicecode, String orderSourceCode, String withmovement, String vathandlingcode1, BigDecimal vathandlingcodepercentage1, BigDecimal vatamount1, BigDecimal vatbaseamount1, String vathandlingcode2, BigDecimal vathandlingcodepercentage2, BigDecimal vatamount2, BigDecimal vatbaseamount2, String vathandlingcode3, BigDecimal vathandlingcodepercentage3, BigDecimal vatamount3, BigDecimal vatbaseamount3, String vathandlingcode4, BigDecimal vathandlingcodepercentage4, BigDecimal vatamount4, BigDecimal vatbaseamount4, Integer ipSalesordertype, Integer ipInvoicetype, Character ipIssaleswithmovement, Character ipIsdebit, String programname, String filename, String processingflag1, String processingflag2, String processingflag3, String processingflag4, String processingflag5, String processingflag6, String processingflag7, String processingflag8, String processingflag9, String processingflag10, String backendreleased, String outboundignore, String transactionid, String recordprocessedflag, Date recordprocessingtime, Date recordlastchangetime, Date recordcreationtime, Set<Invlinbtc> invlinbtcs, Set<Invlin> invlins) {
       this.pk = pk;
       this.contrdef = contrdef;
       this.bizparaddrByBizparaddrpkInvoice = bizparaddrByBizparaddrpkInvoice;
       this.bizparaddrByBizparaddrpkOrder = bizparaddrByBizparaddrpkOrder;
       this.timedateByIpTimedatepkReporting = timedateByIpTimedatepkReporting;
       this.bizparaddrByBizparaddrpkDebtor = bizparaddrByBizparaddrpkDebtor;
       this.delhdr = delhdr;
       this.timedateByTimedatepk = timedateByTimedatepk;
       this.bizparaddrByBizparaddrpkDelivery = bizparaddrByBizparaddrpkDelivery;
       this.invoicenr = invoicenr;
       this.invoicetype = invoicetype;
       this.invoicedate = invoicedate;
       this.invoiceyear = invoiceyear;
       this.salesorganisation = salesorganisation;
       this.salesorganisationdesc = salesorganisationdesc;
       this.salesordernr = salesordernr;
       this.salesordertype = salesordertype;
       this.salesorderdate = salesorderdate;
       this.deliverynr = deliverynr;
       this.debtorcustomercontractor = debtorcustomercontractor;
       this.contractorsalesorganisation = contractorsalesorganisation;
       this.contractordivision = contractordivision;
       this.primarycurrency = primarycurrency;
       this.discountbase = discountbase;
       this.orderlinestotal = orderlinestotal;
       this.ordertotal = ordertotal;
       this.invoiceamountexcludingvat = invoiceamountexcludingvat;
       this.vatamount = vatamount;
       this.invoiceamountincludingvat = invoiceamountincludingvat;
       this.invoiceadjustmentamount = invoiceadjustmentamount;
       this.invoicediscountamount = invoicediscountamount;
       this.invoicefreightamount = invoicefreightamount;
       this.termsofpaymentcode = termsofpaymentcode;
       this.termsofpaymentdesc = termsofpaymentdesc;
       this.duedate = duedate;
       this.termsofpaymentcreditdays = termsofpaymentcreditdays;
       this.mergeinvoicecode = mergeinvoicecode;
       this.orderSourceCode = orderSourceCode;
       this.withmovement = withmovement;
       this.vathandlingcode1 = vathandlingcode1;
       this.vathandlingcodepercentage1 = vathandlingcodepercentage1;
       this.vatamount1 = vatamount1;
       this.vatbaseamount1 = vatbaseamount1;
       this.vathandlingcode2 = vathandlingcode2;
       this.vathandlingcodepercentage2 = vathandlingcodepercentage2;
       this.vatamount2 = vatamount2;
       this.vatbaseamount2 = vatbaseamount2;
       this.vathandlingcode3 = vathandlingcode3;
       this.vathandlingcodepercentage3 = vathandlingcodepercentage3;
       this.vatamount3 = vatamount3;
       this.vatbaseamount3 = vatbaseamount3;
       this.vathandlingcode4 = vathandlingcode4;
       this.vathandlingcodepercentage4 = vathandlingcodepercentage4;
       this.vatamount4 = vatamount4;
       this.vatbaseamount4 = vatbaseamount4;
       this.ipSalesordertype = ipSalesordertype;
       this.ipInvoicetype = ipInvoicetype;
       this.ipIssaleswithmovement = ipIssaleswithmovement;
       this.ipIsdebit = ipIsdebit;
       this.programname = programname;
       this.filename = filename;
       this.processingflag1 = processingflag1;
       this.processingflag2 = processingflag2;
       this.processingflag3 = processingflag3;
       this.processingflag4 = processingflag4;
       this.processingflag5 = processingflag5;
       this.processingflag6 = processingflag6;
       this.processingflag7 = processingflag7;
       this.processingflag8 = processingflag8;
       this.processingflag9 = processingflag9;
       this.processingflag10 = processingflag10;
       this.backendreleased = backendreleased;
       this.outboundignore = outboundignore;
       this.transactionid = transactionid;
       this.recordprocessedflag = recordprocessedflag;
       this.recordprocessingtime = recordprocessingtime;
       this.recordlastchangetime = recordlastchangetime;
       this.recordcreationtime = recordcreationtime;
       this.invlinbtcs = invlinbtcs;
       this.invlins = invlins;
    }
   
     @Id 

    
    @Column(name="PK", unique=true, nullable=false, precision=12, scale=0)
    public long getPk() {
        return this.pk;
    }
    
    public void setPk(long pk) {
        this.pk = pk;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CONTRDEFPK", nullable=false)
    public Contrdef getContrdef() {
        return this.contrdef;
    }
    
    public void setContrdef(Contrdef contrdef) {
        this.contrdef = contrdef;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="BIZPARADDRPK_INVOICE")
    public Bizparaddr getBizparaddrByBizparaddrpkInvoice() {
        return this.bizparaddrByBizparaddrpkInvoice;
    }
    
    public void setBizparaddrByBizparaddrpkInvoice(Bizparaddr bizparaddrByBizparaddrpkInvoice) {
        this.bizparaddrByBizparaddrpkInvoice = bizparaddrByBizparaddrpkInvoice;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="BIZPARADDRPK_ORDER", nullable=false)
    public Bizparaddr getBizparaddrByBizparaddrpkOrder() {
        return this.bizparaddrByBizparaddrpkOrder;
    }
    
    public void setBizparaddrByBizparaddrpkOrder(Bizparaddr bizparaddrByBizparaddrpkOrder) {
        this.bizparaddrByBizparaddrpkOrder = bizparaddrByBizparaddrpkOrder;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IP_TIMEDATEPK_REPORTING")
    public Timedate getTimedateByIpTimedatepkReporting() {
        return this.timedateByIpTimedatepkReporting;
    }
    
    public void setTimedateByIpTimedatepkReporting(Timedate timedateByIpTimedatepkReporting) {
        this.timedateByIpTimedatepkReporting = timedateByIpTimedatepkReporting;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="BIZPARADDRPK_DEBTOR")
    public Bizparaddr getBizparaddrByBizparaddrpkDebtor() {
        return this.bizparaddrByBizparaddrpkDebtor;
    }
    
    public void setBizparaddrByBizparaddrpkDebtor(Bizparaddr bizparaddrByBizparaddrpkDebtor) {
        this.bizparaddrByBizparaddrpkDebtor = bizparaddrByBizparaddrpkDebtor;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="DELHDRPK")
    public Delhdr getDelhdr() {
        return this.delhdr;
    }
    
    public void setDelhdr(Delhdr delhdr) {
        this.delhdr = delhdr;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="TIMEDATEPK")
    public Timedate getTimedateByTimedatepk() {
        return this.timedateByTimedatepk;
    }
    
    public void setTimedateByTimedatepk(Timedate timedateByTimedatepk) {
        this.timedateByTimedatepk = timedateByTimedatepk;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="BIZPARADDRPK_DELIVERY")
    public Bizparaddr getBizparaddrByBizparaddrpkDelivery() {
        return this.bizparaddrByBizparaddrpkDelivery;
    }
    
    public void setBizparaddrByBizparaddrpkDelivery(Bizparaddr bizparaddrByBizparaddrpkDelivery) {
        this.bizparaddrByBizparaddrpkDelivery = bizparaddrByBizparaddrpkDelivery;
    }

    
    @Column(name="INVOICENR", nullable=false, precision=12, scale=0)
    public long getInvoicenr() {
        return this.invoicenr;
    }
    
    public void setInvoicenr(long invoicenr) {
        this.invoicenr = invoicenr;
    }

    
    @Column(name="INVOICETYPE", nullable=false, precision=1, scale=0)
    public boolean isInvoicetype() {
        return this.invoicetype;
    }
    
    public void setInvoicetype(boolean invoicetype) {
        this.invoicetype = invoicetype;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="INVOICEDATE", nullable=false, length=26)
    public Date getInvoicedate() {
        return this.invoicedate;
    }
    
    public void setInvoicedate(Date invoicedate) {
        this.invoicedate = invoicedate;
    }

    
    @Column(name="INVOICEYEAR", nullable=false, precision=4, scale=0)
    public short getInvoiceyear() {
        return this.invoiceyear;
    }
    
    public void setInvoiceyear(short invoiceyear) {
        this.invoiceyear = invoiceyear;
    }

    
    @Column(name="SALESORGANISATION", length=30)
    public String getSalesorganisation() {
        return this.salesorganisation;
    }
    
    public void setSalesorganisation(String salesorganisation) {
        this.salesorganisation = salesorganisation;
    }

    
    @Column(name="SALESORGANISATIONDESC", length=50)
    public String getSalesorganisationdesc() {
        return this.salesorganisationdesc;
    }
    
    public void setSalesorganisationdesc(String salesorganisationdesc) {
        this.salesorganisationdesc = salesorganisationdesc;
    }

    
    @Column(name="SALESORDERNR", precision=12, scale=0)
    public Long getSalesordernr() {
        return this.salesordernr;
    }
    
    public void setSalesordernr(Long salesordernr) {
        this.salesordernr = salesordernr;
    }

    
    @Column(name="SALESORDERTYPE", length=2)
    public String getSalesordertype() {
        return this.salesordertype;
    }
    
    public void setSalesordertype(String salesordertype) {
        this.salesordertype = salesordertype;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="SALESORDERDATE", length=26)
    public Date getSalesorderdate() {
        return this.salesorderdate;
    }
    
    public void setSalesorderdate(Date salesorderdate) {
        this.salesorderdate = salesorderdate;
    }

    
    @Column(name="DELIVERYNR", length=35)
    public String getDeliverynr() {
        return this.deliverynr;
    }
    
    public void setDeliverynr(String deliverynr) {
        this.deliverynr = deliverynr;
    }

    
    @Column(name="DEBTORCUSTOMERCONTRACTOR", length=30)
    public String getDebtorcustomercontractor() {
        return this.debtorcustomercontractor;
    }
    
    public void setDebtorcustomercontractor(String debtorcustomercontractor) {
        this.debtorcustomercontractor = debtorcustomercontractor;
    }

    
    @Column(name="CONTRACTORSALESORGANISATION", length=20)
    public String getContractorsalesorganisation() {
        return this.contractorsalesorganisation;
    }
    
    public void setContractorsalesorganisation(String contractorsalesorganisation) {
        this.contractorsalesorganisation = contractorsalesorganisation;
    }

    
    @Column(name="CONTRACTORDIVISION", length=20)
    public String getContractordivision() {
        return this.contractordivision;
    }
    
    public void setContractordivision(String contractordivision) {
        this.contractordivision = contractordivision;
    }

    
    @Column(name="PRIMARYCURRENCY", length=4)
    public String getPrimarycurrency() {
        return this.primarycurrency;
    }
    
    public void setPrimarycurrency(String primarycurrency) {
        this.primarycurrency = primarycurrency;
    }

    
    @Column(name="DISCOUNTBASE", precision=17, scale=4)
    public BigDecimal getDiscountbase() {
        return this.discountbase;
    }
    
    public void setDiscountbase(BigDecimal discountbase) {
        this.discountbase = discountbase;
    }

    
    @Column(name="ORDERLINESTOTAL", precision=17, scale=4)
    public BigDecimal getOrderlinestotal() {
        return this.orderlinestotal;
    }
    
    public void setOrderlinestotal(BigDecimal orderlinestotal) {
        this.orderlinestotal = orderlinestotal;
    }

    
    @Column(name="ORDERTOTAL", precision=17, scale=4)
    public BigDecimal getOrdertotal() {
        return this.ordertotal;
    }
    
    public void setOrdertotal(BigDecimal ordertotal) {
        this.ordertotal = ordertotal;
    }

    
    @Column(name="INVOICEAMOUNTEXCLUDINGVAT", precision=17, scale=4)
    public BigDecimal getInvoiceamountexcludingvat() {
        return this.invoiceamountexcludingvat;
    }
    
    public void setInvoiceamountexcludingvat(BigDecimal invoiceamountexcludingvat) {
        this.invoiceamountexcludingvat = invoiceamountexcludingvat;
    }

    
    @Column(name="VATAMOUNT", precision=17, scale=4)
    public BigDecimal getVatamount() {
        return this.vatamount;
    }
    
    public void setVatamount(BigDecimal vatamount) {
        this.vatamount = vatamount;
    }

    
    @Column(name="INVOICEAMOUNTINCLUDINGVAT", precision=17, scale=4)
    public BigDecimal getInvoiceamountincludingvat() {
        return this.invoiceamountincludingvat;
    }
    
    public void setInvoiceamountincludingvat(BigDecimal invoiceamountincludingvat) {
        this.invoiceamountincludingvat = invoiceamountincludingvat;
    }

    
    @Column(name="INVOICEADJUSTMENTAMOUNT", precision=17, scale=4)
    public BigDecimal getInvoiceadjustmentamount() {
        return this.invoiceadjustmentamount;
    }
    
    public void setInvoiceadjustmentamount(BigDecimal invoiceadjustmentamount) {
        this.invoiceadjustmentamount = invoiceadjustmentamount;
    }

    
    @Column(name="INVOICEDISCOUNTAMOUNT", precision=17, scale=4)
    public BigDecimal getInvoicediscountamount() {
        return this.invoicediscountamount;
    }
    
    public void setInvoicediscountamount(BigDecimal invoicediscountamount) {
        this.invoicediscountamount = invoicediscountamount;
    }

    
    @Column(name="INVOICEFREIGHTAMOUNT", precision=17, scale=4)
    public BigDecimal getInvoicefreightamount() {
        return this.invoicefreightamount;
    }
    
    public void setInvoicefreightamount(BigDecimal invoicefreightamount) {
        this.invoicefreightamount = invoicefreightamount;
    }

    
    @Column(name="TERMSOFPAYMENTCODE", length=3)
    public String getTermsofpaymentcode() {
        return this.termsofpaymentcode;
    }
    
    public void setTermsofpaymentcode(String termsofpaymentcode) {
        this.termsofpaymentcode = termsofpaymentcode;
    }

    
    @Column(name="TERMSOFPAYMENTDESC", length=50)
    public String getTermsofpaymentdesc() {
        return this.termsofpaymentdesc;
    }
    
    public void setTermsofpaymentdesc(String termsofpaymentdesc) {
        this.termsofpaymentdesc = termsofpaymentdesc;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="DUEDATE", length=26)
    public Date getDuedate() {
        return this.duedate;
    }
    
    public void setDuedate(Date duedate) {
        this.duedate = duedate;
    }

    
    @Column(name="TERMSOFPAYMENTCREDITDAYS", precision=3, scale=0)
    public Short getTermsofpaymentcreditdays() {
        return this.termsofpaymentcreditdays;
    }
    
    public void setTermsofpaymentcreditdays(Short termsofpaymentcreditdays) {
        this.termsofpaymentcreditdays = termsofpaymentcreditdays;
    }

    
    @Column(name="MERGEINVOICECODE", length=1)
    public String getMergeinvoicecode() {
        return this.mergeinvoicecode;
    }
    
    public void setMergeinvoicecode(String mergeinvoicecode) {
        this.mergeinvoicecode = mergeinvoicecode;
    }

    
    @Column(name="ORDER_SOURCE_CODE", length=20)
    public String getOrderSourceCode() {
        return this.orderSourceCode;
    }
    
    public void setOrderSourceCode(String orderSourceCode) {
        this.orderSourceCode = orderSourceCode;
    }

    
    @Column(name="WITHMOVEMENT", length=1)
    public String getWithmovement() {
        return this.withmovement;
    }
    
    public void setWithmovement(String withmovement) {
        this.withmovement = withmovement;
    }

    
    @Column(name="VATHANDLINGCODE1", length=4)
    public String getVathandlingcode1() {
        return this.vathandlingcode1;
    }
    
    public void setVathandlingcode1(String vathandlingcode1) {
        this.vathandlingcode1 = vathandlingcode1;
    }

    
    @Column(name="VATHANDLINGCODEPERCENTAGE1", precision=5)
    public BigDecimal getVathandlingcodepercentage1() {
        return this.vathandlingcodepercentage1;
    }
    
    public void setVathandlingcodepercentage1(BigDecimal vathandlingcodepercentage1) {
        this.vathandlingcodepercentage1 = vathandlingcodepercentage1;
    }

    
    @Column(name="VATAMOUNT1", precision=17)
    public BigDecimal getVatamount1() {
        return this.vatamount1;
    }
    
    public void setVatamount1(BigDecimal vatamount1) {
        this.vatamount1 = vatamount1;
    }

    
    @Column(name="VATBASEAMOUNT1", precision=17, scale=4)
    public BigDecimal getVatbaseamount1() {
        return this.vatbaseamount1;
    }
    
    public void setVatbaseamount1(BigDecimal vatbaseamount1) {
        this.vatbaseamount1 = vatbaseamount1;
    }

    
    @Column(name="VATHANDLINGCODE2", length=4)
    public String getVathandlingcode2() {
        return this.vathandlingcode2;
    }
    
    public void setVathandlingcode2(String vathandlingcode2) {
        this.vathandlingcode2 = vathandlingcode2;
    }

    
    @Column(name="VATHANDLINGCODEPERCENTAGE2", precision=5)
    public BigDecimal getVathandlingcodepercentage2() {
        return this.vathandlingcodepercentage2;
    }
    
    public void setVathandlingcodepercentage2(BigDecimal vathandlingcodepercentage2) {
        this.vathandlingcodepercentage2 = vathandlingcodepercentage2;
    }

    
    @Column(name="VATAMOUNT2", precision=17)
    public BigDecimal getVatamount2() {
        return this.vatamount2;
    }
    
    public void setVatamount2(BigDecimal vatamount2) {
        this.vatamount2 = vatamount2;
    }

    
    @Column(name="VATBASEAMOUNT2", precision=17, scale=4)
    public BigDecimal getVatbaseamount2() {
        return this.vatbaseamount2;
    }
    
    public void setVatbaseamount2(BigDecimal vatbaseamount2) {
        this.vatbaseamount2 = vatbaseamount2;
    }

    
    @Column(name="VATHANDLINGCODE3", length=4)
    public String getVathandlingcode3() {
        return this.vathandlingcode3;
    }
    
    public void setVathandlingcode3(String vathandlingcode3) {
        this.vathandlingcode3 = vathandlingcode3;
    }

    
    @Column(name="VATHANDLINGCODEPERCENTAGE3", precision=5)
    public BigDecimal getVathandlingcodepercentage3() {
        return this.vathandlingcodepercentage3;
    }
    
    public void setVathandlingcodepercentage3(BigDecimal vathandlingcodepercentage3) {
        this.vathandlingcodepercentage3 = vathandlingcodepercentage3;
    }

    
    @Column(name="VATAMOUNT3", precision=17)
    public BigDecimal getVatamount3() {
        return this.vatamount3;
    }
    
    public void setVatamount3(BigDecimal vatamount3) {
        this.vatamount3 = vatamount3;
    }

    
    @Column(name="VATBASEAMOUNT3", precision=17, scale=4)
    public BigDecimal getVatbaseamount3() {
        return this.vatbaseamount3;
    }
    
    public void setVatbaseamount3(BigDecimal vatbaseamount3) {
        this.vatbaseamount3 = vatbaseamount3;
    }

    
    @Column(name="VATHANDLINGCODE4", length=4)
    public String getVathandlingcode4() {
        return this.vathandlingcode4;
    }
    
    public void setVathandlingcode4(String vathandlingcode4) {
        this.vathandlingcode4 = vathandlingcode4;
    }

    
    @Column(name="VATHANDLINGCODEPERCENTAGE4", precision=5)
    public BigDecimal getVathandlingcodepercentage4() {
        return this.vathandlingcodepercentage4;
    }
    
    public void setVathandlingcodepercentage4(BigDecimal vathandlingcodepercentage4) {
        this.vathandlingcodepercentage4 = vathandlingcodepercentage4;
    }

    
    @Column(name="VATAMOUNT4", precision=17)
    public BigDecimal getVatamount4() {
        return this.vatamount4;
    }
    
    public void setVatamount4(BigDecimal vatamount4) {
        this.vatamount4 = vatamount4;
    }

    
    @Column(name="VATBASEAMOUNT4", precision=17, scale=4)
    public BigDecimal getVatbaseamount4() {
        return this.vatbaseamount4;
    }
    
    public void setVatbaseamount4(BigDecimal vatbaseamount4) {
        this.vatbaseamount4 = vatbaseamount4;
    }

    
    @Column(name="IP_SALESORDERTYPE", precision=5, scale=0)
    public Integer getIpSalesordertype() {
        return this.ipSalesordertype;
    }
    
    public void setIpSalesordertype(Integer ipSalesordertype) {
        this.ipSalesordertype = ipSalesordertype;
    }

    
    @Column(name="IP_INVOICETYPE", precision=5, scale=0)
    public Integer getIpInvoicetype() {
        return this.ipInvoicetype;
    }
    
    public void setIpInvoicetype(Integer ipInvoicetype) {
        this.ipInvoicetype = ipInvoicetype;
    }

    
    @Column(name="IP_ISSALESWITHMOVEMENT", length=1)
    public Character getIpIssaleswithmovement() {
        return this.ipIssaleswithmovement;
    }
    
    public void setIpIssaleswithmovement(Character ipIssaleswithmovement) {
        this.ipIssaleswithmovement = ipIssaleswithmovement;
    }

    
    @Column(name="IP_ISDEBIT", length=1)
    public Character getIpIsdebit() {
        return this.ipIsdebit;
    }
    
    public void setIpIsdebit(Character ipIsdebit) {
        this.ipIsdebit = ipIsdebit;
    }

    
    @Column(name="PROGRAMNAME", length=10)
    public String getProgramname() {
        return this.programname;
    }
    
    public void setProgramname(String programname) {
        this.programname = programname;
    }

    
    @Column(name="FILENAME", length=10)
    public String getFilename() {
        return this.filename;
    }
    
    public void setFilename(String filename) {
        this.filename = filename;
    }

    
    @Column(name="PROCESSINGFLAG1", length=1)
    public String getProcessingflag1() {
        return this.processingflag1;
    }
    
    public void setProcessingflag1(String processingflag1) {
        this.processingflag1 = processingflag1;
    }

    
    @Column(name="PROCESSINGFLAG2", length=1)
    public String getProcessingflag2() {
        return this.processingflag2;
    }
    
    public void setProcessingflag2(String processingflag2) {
        this.processingflag2 = processingflag2;
    }

    
    @Column(name="PROCESSINGFLAG3", length=1)
    public String getProcessingflag3() {
        return this.processingflag3;
    }
    
    public void setProcessingflag3(String processingflag3) {
        this.processingflag3 = processingflag3;
    }

    
    @Column(name="PROCESSINGFLAG4", length=1)
    public String getProcessingflag4() {
        return this.processingflag4;
    }
    
    public void setProcessingflag4(String processingflag4) {
        this.processingflag4 = processingflag4;
    }

    
    @Column(name="PROCESSINGFLAG5", length=1)
    public String getProcessingflag5() {
        return this.processingflag5;
    }
    
    public void setProcessingflag5(String processingflag5) {
        this.processingflag5 = processingflag5;
    }

    
    @Column(name="PROCESSINGFLAG6", length=1)
    public String getProcessingflag6() {
        return this.processingflag6;
    }
    
    public void setProcessingflag6(String processingflag6) {
        this.processingflag6 = processingflag6;
    }

    
    @Column(name="PROCESSINGFLAG7", length=1)
    public String getProcessingflag7() {
        return this.processingflag7;
    }
    
    public void setProcessingflag7(String processingflag7) {
        this.processingflag7 = processingflag7;
    }

    
    @Column(name="PROCESSINGFLAG8", length=1)
    public String getProcessingflag8() {
        return this.processingflag8;
    }
    
    public void setProcessingflag8(String processingflag8) {
        this.processingflag8 = processingflag8;
    }

    
    @Column(name="PROCESSINGFLAG9", length=1)
    public String getProcessingflag9() {
        return this.processingflag9;
    }
    
    public void setProcessingflag9(String processingflag9) {
        this.processingflag9 = processingflag9;
    }

    
    @Column(name="PROCESSINGFLAG10", length=1)
    public String getProcessingflag10() {
        return this.processingflag10;
    }
    
    public void setProcessingflag10(String processingflag10) {
        this.processingflag10 = processingflag10;
    }

    
    @Column(name="BACKENDRELEASED", nullable=false, length=1)
    public String getBackendreleased() {
        return this.backendreleased;
    }
    
    public void setBackendreleased(String backendreleased) {
        this.backendreleased = backendreleased;
    }

    
    @Column(name="OUTBOUNDIGNORE", nullable=false, length=1)
    public String getOutboundignore() {
        return this.outboundignore;
    }
    
    public void setOutboundignore(String outboundignore) {
        this.outboundignore = outboundignore;
    }

    
    @Column(name="TRANSACTIONID", length=50)
    public String getTransactionid() {
        return this.transactionid;
    }
    
    public void setTransactionid(String transactionid) {
        this.transactionid = transactionid;
    }

    
    @Column(name="RECORDPROCESSEDFLAG", nullable=false, length=1)
    public String getRecordprocessedflag() {
        return this.recordprocessedflag;
    }
    
    public void setRecordprocessedflag(String recordprocessedflag) {
        this.recordprocessedflag = recordprocessedflag;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="RECORDPROCESSINGTIME", length=26)
    public Date getRecordprocessingtime() {
        return this.recordprocessingtime;
    }
    
    public void setRecordprocessingtime(Date recordprocessingtime) {
        this.recordprocessingtime = recordprocessingtime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="RECORDLASTCHANGETIME", length=26)
    public Date getRecordlastchangetime() {
        return this.recordlastchangetime;
    }
    
    public void setRecordlastchangetime(Date recordlastchangetime) {
        this.recordlastchangetime = recordlastchangetime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="RECORDCREATIONTIME", nullable=false, length=26)
    public Date getRecordcreationtime() {
        return this.recordcreationtime;
    }
    
    public void setRecordcreationtime(Date recordcreationtime) {
        this.recordcreationtime = recordcreationtime;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="invhdr")
    public Set<Invlinbtc> getInvlinbtcs() {
        return this.invlinbtcs;
    }
    
    public void setInvlinbtcs(Set<Invlinbtc> invlinbtcs) {
        this.invlinbtcs = invlinbtcs;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="invhdr")
    public Set<Invlin> getInvlins() {
        return this.invlins;
    }
    
    public void setInvlins(Set<Invlin> invlins) {
        this.invlins = invlins;
    }




}


