package com.galexis.allog2mysql.deleteme;
// Generated Sep 6, 2013 9:37:59 AM by Hibernate Tools 3.6.0


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Invhdri04 generated by hbm2java
 */
@Entity
@Table(name="INVHDRI04"
    ,schema="INTEGAP"
    ,catalog="CHGALE11RDB"
)
public class Invhdri04  implements java.io.Serializable {


     private Invhdri04Id id;

    public Invhdri04() {
    }

    public Invhdri04(Invhdri04Id id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="pk", column=@Column(name="PK", nullable=false, precision=12, scale=0) ), 
        @AttributeOverride(name="contrdefpk", column=@Column(name="CONTRDEFPK", nullable=false, precision=12, scale=0) ), 
        @AttributeOverride(name="invoicenr", column=@Column(name="INVOICENR", nullable=false, precision=12, scale=0) ), 
        @AttributeOverride(name="invoicetype", column=@Column(name="INVOICETYPE", nullable=false, precision=1, scale=0) ), 
        @AttributeOverride(name="invoicedate", column=@Column(name="INVOICEDATE", nullable=false, length=26) ), 
        @AttributeOverride(name="invoiceyear", column=@Column(name="INVOICEYEAR", nullable=false, precision=4, scale=0) ), 
        @AttributeOverride(name="salesorganisation", column=@Column(name="SALESORGANISATION", length=30) ), 
        @AttributeOverride(name="salesorganisationdesc", column=@Column(name="SALESORGANISATIONDESC", length=50) ), 
        @AttributeOverride(name="salesordernr", column=@Column(name="SALESORDERNR", precision=12, scale=0) ), 
        @AttributeOverride(name="salesordertype", column=@Column(name="SALESORDERTYPE", length=2) ), 
        @AttributeOverride(name="salesorderdate", column=@Column(name="SALESORDERDATE", length=26) ), 
        @AttributeOverride(name="delhdrpk", column=@Column(name="DELHDRPK", precision=12, scale=0) ), 
        @AttributeOverride(name="deliverynr", column=@Column(name="DELIVERYNR", length=35) ), 
        @AttributeOverride(name="bizparaddrpkOrder", column=@Column(name="BIZPARADDRPK_ORDER", nullable=false, precision=12, scale=0) ), 
        @AttributeOverride(name="bizparaddrpkInvoice", column=@Column(name="BIZPARADDRPK_INVOICE", precision=12, scale=0) ), 
        @AttributeOverride(name="bizparaddrpkDelivery", column=@Column(name="BIZPARADDRPK_DELIVERY", precision=12, scale=0) ), 
        @AttributeOverride(name="bizparaddrpkDebtor", column=@Column(name="BIZPARADDRPK_DEBTOR", precision=12, scale=0) ), 
        @AttributeOverride(name="debtorcustomercontractor", column=@Column(name="DEBTORCUSTOMERCONTRACTOR", length=30) ), 
        @AttributeOverride(name="contractorsalesorganisation", column=@Column(name="CONTRACTORSALESORGANISATION", length=20) ), 
        @AttributeOverride(name="contractordivision", column=@Column(name="CONTRACTORDIVISION", length=20) ), 
        @AttributeOverride(name="primarycurrency", column=@Column(name="PRIMARYCURRENCY", length=4) ), 
        @AttributeOverride(name="discountbase", column=@Column(name="DISCOUNTBASE", precision=17, scale=4) ), 
        @AttributeOverride(name="orderlinestotal", column=@Column(name="ORDERLINESTOTAL", precision=17, scale=4) ), 
        @AttributeOverride(name="ordertotal", column=@Column(name="ORDERTOTAL", precision=17, scale=4) ), 
        @AttributeOverride(name="invoiceamountexcludingvat", column=@Column(name="INVOICEAMOUNTEXCLUDINGVAT", precision=17, scale=4) ), 
        @AttributeOverride(name="vatamount", column=@Column(name="VATAMOUNT", precision=17, scale=4) ), 
        @AttributeOverride(name="invoiceamountincludingvat", column=@Column(name="INVOICEAMOUNTINCLUDINGVAT", precision=17, scale=4) ), 
        @AttributeOverride(name="invoiceadjustmentamount", column=@Column(name="INVOICEADJUSTMENTAMOUNT", precision=17, scale=4) ), 
        @AttributeOverride(name="invoicediscountamount", column=@Column(name="INVOICEDISCOUNTAMOUNT", precision=17, scale=4) ), 
        @AttributeOverride(name="invoicefreightamount", column=@Column(name="INVOICEFREIGHTAMOUNT", precision=17, scale=4) ), 
        @AttributeOverride(name="termsofpaymentcode", column=@Column(name="TERMSOFPAYMENTCODE", length=3) ), 
        @AttributeOverride(name="termsofpaymentdesc", column=@Column(name="TERMSOFPAYMENTDESC", length=50) ), 
        @AttributeOverride(name="duedate", column=@Column(name="DUEDATE", length=26) ), 
        @AttributeOverride(name="termsofpaymentcreditdays", column=@Column(name="TERMSOFPAYMENTCREDITDAYS", precision=3, scale=0) ), 
        @AttributeOverride(name="mergeinvoicecode", column=@Column(name="MERGEINVOICECODE", length=1) ), 
        @AttributeOverride(name="orderSourceCode", column=@Column(name="ORDER_SOURCE_CODE", length=20) ), 
        @AttributeOverride(name="withmovement", column=@Column(name="WITHMOVEMENT", length=1) ), 
        @AttributeOverride(name="vathandlingcode1", column=@Column(name="VATHANDLINGCODE1", length=4) ), 
        @AttributeOverride(name="vathandlingcodepercentage1", column=@Column(name="VATHANDLINGCODEPERCENTAGE1", precision=5) ), 
        @AttributeOverride(name="vatamount1", column=@Column(name="VATAMOUNT1", precision=17) ), 
        @AttributeOverride(name="vatbaseamount1", column=@Column(name="VATBASEAMOUNT1", precision=17, scale=4) ), 
        @AttributeOverride(name="vathandlingcode2", column=@Column(name="VATHANDLINGCODE2", length=4) ), 
        @AttributeOverride(name="vathandlingcodepercentage2", column=@Column(name="VATHANDLINGCODEPERCENTAGE2", precision=5) ), 
        @AttributeOverride(name="vatamount2", column=@Column(name="VATAMOUNT2", precision=17) ), 
        @AttributeOverride(name="vatbaseamount2", column=@Column(name="VATBASEAMOUNT2", precision=17, scale=4) ), 
        @AttributeOverride(name="vathandlingcode3", column=@Column(name="VATHANDLINGCODE3", length=4) ), 
        @AttributeOverride(name="vathandlingcodepercentage3", column=@Column(name="VATHANDLINGCODEPERCENTAGE3", precision=5) ), 
        @AttributeOverride(name="vatamount3", column=@Column(name="VATAMOUNT3", precision=17) ), 
        @AttributeOverride(name="vatbaseamount3", column=@Column(name="VATBASEAMOUNT3", precision=17, scale=4) ), 
        @AttributeOverride(name="vathandlingcode4", column=@Column(name="VATHANDLINGCODE4", length=4) ), 
        @AttributeOverride(name="vathandlingcodepercentage4", column=@Column(name="VATHANDLINGCODEPERCENTAGE4", precision=5) ), 
        @AttributeOverride(name="vatamount4", column=@Column(name="VATAMOUNT4", precision=17) ), 
        @AttributeOverride(name="vatbaseamount4", column=@Column(name="VATBASEAMOUNT4", precision=17, scale=4) ), 
        @AttributeOverride(name="ipSalesordertype", column=@Column(name="IP_SALESORDERTYPE", precision=5, scale=0) ), 
        @AttributeOverride(name="ipInvoicetype", column=@Column(name="IP_INVOICETYPE", precision=5, scale=0) ), 
        @AttributeOverride(name="ipIssaleswithmovement", column=@Column(name="IP_ISSALESWITHMOVEMENT", length=1) ), 
        @AttributeOverride(name="ipIsdebit", column=@Column(name="IP_ISDEBIT", length=1) ), 
        @AttributeOverride(name="timedatepk", column=@Column(name="TIMEDATEPK", precision=8, scale=0) ), 
        @AttributeOverride(name="ipTimedatepkReporting", column=@Column(name="IP_TIMEDATEPK_REPORTING", precision=8, scale=0) ), 
        @AttributeOverride(name="programname", column=@Column(name="PROGRAMNAME", length=10) ), 
        @AttributeOverride(name="filename", column=@Column(name="FILENAME", length=10) ), 
        @AttributeOverride(name="processingflag1", column=@Column(name="PROCESSINGFLAG1", length=1) ), 
        @AttributeOverride(name="processingflag2", column=@Column(name="PROCESSINGFLAG2", length=1) ), 
        @AttributeOverride(name="processingflag3", column=@Column(name="PROCESSINGFLAG3", length=1) ), 
        @AttributeOverride(name="processingflag4", column=@Column(name="PROCESSINGFLAG4", length=1) ), 
        @AttributeOverride(name="processingflag5", column=@Column(name="PROCESSINGFLAG5", length=1) ), 
        @AttributeOverride(name="processingflag6", column=@Column(name="PROCESSINGFLAG6", length=1) ), 
        @AttributeOverride(name="processingflag7", column=@Column(name="PROCESSINGFLAG7", length=1) ), 
        @AttributeOverride(name="processingflag8", column=@Column(name="PROCESSINGFLAG8", length=1) ), 
        @AttributeOverride(name="processingflag9", column=@Column(name="PROCESSINGFLAG9", length=1) ), 
        @AttributeOverride(name="processingflag10", column=@Column(name="PROCESSINGFLAG10", length=1) ), 
        @AttributeOverride(name="backendreleased", column=@Column(name="BACKENDRELEASED", nullable=false, length=1) ), 
        @AttributeOverride(name="outboundignore", column=@Column(name="OUTBOUNDIGNORE", nullable=false, length=1) ), 
        @AttributeOverride(name="transactionid", column=@Column(name="TRANSACTIONID", length=50) ), 
        @AttributeOverride(name="recordprocessedflag", column=@Column(name="RECORDPROCESSEDFLAG", nullable=false, length=1) ), 
        @AttributeOverride(name="recordprocessingtime", column=@Column(name="RECORDPROCESSINGTIME", length=26) ), 
        @AttributeOverride(name="recordlastchangetime", column=@Column(name="RECORDLASTCHANGETIME", length=26) ), 
        @AttributeOverride(name="recordcreationtime", column=@Column(name="RECORDCREATIONTIME", nullable=false, length=26) ) } )
    public Invhdri04Id getId() {
        return this.id;
    }
    
    public void setId(Invhdri04Id id) {
        this.id = id;
    }




}


