package com.galexis.allog2mysql.deleteme;
// Generated Sep 6, 2013 9:37:59 AM by Hibernate Tools 3.6.0


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Invlini01 generated by hbm2java
 */
@Entity
@Table(name="INVLINI01"
    ,schema="INTEGAP"
    ,catalog="CHGALE11RDB"
)
public class Invlini01  implements java.io.Serializable {


     private Invlini01Id id;

    public Invlini01() {
    }

    public Invlini01(Invlini01Id id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="pk", column=@Column(name="PK", nullable=false, precision=12, scale=0) ), 
        @AttributeOverride(name="invhdrpk", column=@Column(name="INVHDRPK", nullable=false, precision=12, scale=0) ), 
        @AttributeOverride(name="invoiceline", column=@Column(name="INVOICELINE", nullable=false, precision=5, scale=0) ), 
        @AttributeOverride(name="accountingperiod", column=@Column(name="ACCOUNTINGPERIOD", precision=6, scale=0) ), 
        @AttributeOverride(name="salesordernr", column=@Column(name="SALESORDERNR", precision=12, scale=0) ), 
        @AttributeOverride(name="orderline", column=@Column(name="ORDERLINE", precision=5, scale=0) ), 
        @AttributeOverride(name="dellinpk", column=@Column(name="DELLINPK", precision=12, scale=0) ), 
        @AttributeOverride(name="itemmasterpk", column=@Column(name="ITEMMASTERPK", nullable=false, precision=12, scale=0) ), 
        @AttributeOverride(name="itemnr", column=@Column(name="ITEMNR", nullable=false, length=35) ), 
        @AttributeOverride(name="itemnrcontractor", column=@Column(name="ITEMNRCONTRACTOR", length=35) ), 
        @AttributeOverride(name="itemnrcontractor2", column=@Column(name="ITEMNRCONTRACTOR2", length=35) ), 
        @AttributeOverride(name="invoicedqty", column=@Column(name="INVOICEDQTY", precision=15, scale=3) ), 
        @AttributeOverride(name="orderqty", column=@Column(name="ORDERQTY", precision=15, scale=3) ), 
        @AttributeOverride(name="deliveredqty", column=@Column(name="DELIVEREDQTY", precision=15, scale=3) ), 
        @AttributeOverride(name="naturaldiscountqty", column=@Column(name="NATURALDISCOUNTQTY", precision=15, scale=3) ), 
        @AttributeOverride(name="unit", column=@Column(name="UNIT", length=5) ), 
        @AttributeOverride(name="batchcontrolledflag", column=@Column(name="BATCHCONTROLLEDFLAG", length=1) ), 
        @AttributeOverride(name="salesprice", column=@Column(name="SALESPRICE", precision=17, scale=4) ), 
        @AttributeOverride(name="salesamount", column=@Column(name="SALESAMOUNT", precision=17, scale=4) ), 
        @AttributeOverride(name="netprice", column=@Column(name="NETPRICE", precision=17, scale=4) ), 
        @AttributeOverride(name="netsalesvalue", column=@Column(name="NETSALESVALUE", precision=17, scale=4) ), 
        @AttributeOverride(name="orderdiscountpercentage", column=@Column(name="ORDERDISCOUNTPERCENTAGE", precision=5) ), 
        @AttributeOverride(name="freeofchargeflag", column=@Column(name="FREEOFCHARGEFLAG", length=1) ), 
        @AttributeOverride(name="freeofchargereasoncode", column=@Column(name="FREEOFCHARGEREASONCODE", length=2) ), 
        @AttributeOverride(name="itempricecode", column=@Column(name="ITEMPRICECODE", length=3) ), 
        @AttributeOverride(name="itempricecodedesc", column=@Column(name="ITEMPRICECODEDESC", length=50) ), 
        @AttributeOverride(name="salesrepresentative", column=@Column(name="SALESREPRESENTATIVE", length=30) ), 
        @AttributeOverride(name="standardcost", column=@Column(name="STANDARDCOST", precision=17, scale=4) ), 
        @AttributeOverride(name="totalamountexcludingvat", column=@Column(name="TOTALAMOUNTEXCLUDINGVAT", precision=17, scale=4) ), 
        @AttributeOverride(name="totalamountincludingvat", column=@Column(name="TOTALAMOUNTINCLUDINGVAT", precision=17, scale=4) ), 
        @AttributeOverride(name="vatamount", column=@Column(name="VATAMOUNT", precision=17, scale=4) ), 
        @AttributeOverride(name="vathandlingcode", column=@Column(name="VATHANDLINGCODE", length=4) ), 
        @AttributeOverride(name="vathandlingcodedesc", column=@Column(name="VATHANDLINGCODEDESC", length=50) ), 
        @AttributeOverride(name="vathandlingcodepercentage", column=@Column(name="VATHANDLINGCODEPERCENTAGE", precision=5) ), 
        @AttributeOverride(name="vatcodeflag", column=@Column(name="VATCODEFLAG", length=1) ), 
        @AttributeOverride(name="vatincludedinpricesflag", column=@Column(name="VATINCLUDEDINPRICESFLAG", length=1) ), 
        @AttributeOverride(name="validfororderdiscountflag", column=@Column(name="VALIDFORORDERDISCOUNTFLAG", length=1) ), 
        @AttributeOverride(name="generaldiscountkey", column=@Column(name="GENERALDISCOUNTKEY", precision=15, scale=0) ), 
        @AttributeOverride(name="salespricecalculationref", column=@Column(name="SALESPRICECALCULATIONREF", precision=15, scale=0) ), 
        @AttributeOverride(name="linecostvalue", column=@Column(name="LINECOSTVALUE", precision=17, scale=4) ), 
        @AttributeOverride(name="backorderflag", column=@Column(name="BACKORDERFLAG", length=1) ), 
        @AttributeOverride(name="reasoncode", column=@Column(name="REASONCODE", length=3) ), 
        @AttributeOverride(name="reasoncodedesc", column=@Column(name="REASONCODEDESC", length=50) ), 
        @AttributeOverride(name="reforiginalordernr", column=@Column(name="REFORIGINALORDERNR", precision=12, scale=0) ), 
        @AttributeOverride(name="reforiginalorderline", column=@Column(name="REFORIGINALORDERLINE", precision=6, scale=0) ), 
        @AttributeOverride(name="reforiginalinvoicenr", column=@Column(name="REFORIGINALINVOICENR", precision=12, scale=0) ), 
        @AttributeOverride(name="incidentnumber", column=@Column(name="INCIDENTNUMBER", precision=12, scale=0) ), 
        @AttributeOverride(name="incidentline", column=@Column(name="INCIDENTLINE", precision=6, scale=0) ), 
        @AttributeOverride(name="incidentreasoncode", column=@Column(name="INCIDENTREASONCODE", length=5) ), 
        @AttributeOverride(name="orderingpartypurchordnumber", column=@Column(name="ORDERINGPARTYPURCHORDNUMBER", length=35) ), 
        @AttributeOverride(name="orderingpartypurchordline", column=@Column(name="ORDERINGPARTYPURCHORDLINE", length=35) ), 
        @AttributeOverride(name="itemnarcoticcategory", column=@Column(name="ITEMNARCOTICCATEGORY", length=10) ), 
        @AttributeOverride(name="transitdeliveryflag", column=@Column(name="TRANSITDELIVERYFLAG", length=1) ), 
        @AttributeOverride(name="directdeliveryflag", column=@Column(name="DIRECTDELIVERYFLAG", length=1) ), 
        @AttributeOverride(name="itemcompanynumber", column=@Column(name="ITEMCOMPANYNUMBER", precision=3, scale=0) ), 
        @AttributeOverride(name="pricelist", column=@Column(name="PRICELIST", length=5) ), 
        @AttributeOverride(name="pricelistdesc", column=@Column(name="PRICELISTDESC", length=50) ), 
        @AttributeOverride(name="priceaccordingtopricelist", column=@Column(name="PRICEACCORDINGTOPRICELIST", precision=17, scale=4) ), 
        @AttributeOverride(name="priceaccordingtocustpricelist", column=@Column(name="PRICEACCORDINGTOCUSTPRICELIST", precision=17, scale=4) ), 
        @AttributeOverride(name="manuallyenteredprice", column=@Column(name="MANUALLYENTEREDPRICE", precision=17, scale=4) ), 
        @AttributeOverride(name="totaldiscountpercentage", column=@Column(name="TOTALDISCOUNTPERCENTAGE", precision=5) ), 
        @AttributeOverride(name="updatestockonhandflag", column=@Column(name="UPDATESTOCKONHANDFLAG", length=1) ), 
        @AttributeOverride(name="ipFreeofchargereasoncode", column=@Column(name="IP_FREEOFCHARGEREASONCODE", precision=5, scale=0) ), 
        @AttributeOverride(name="ipGroupingcriteria1", column=@Column(name="IP_GROUPINGCRITERIA1") ), 
        @AttributeOverride(name="ipGroupingcriteria2", column=@Column(name="IP_GROUPINGCRITERIA2") ), 
        @AttributeOverride(name="ipGroupingcriteria3", column=@Column(name="IP_GROUPINGCRITERIA3") ), 
        @AttributeOverride(name="ipGroupingcriteria4", column=@Column(name="IP_GROUPINGCRITERIA4") ), 
        @AttributeOverride(name="ipGroupingcriteria5", column=@Column(name="IP_GROUPINGCRITERIA5") ), 
        @AttributeOverride(name="programname", column=@Column(name="PROGRAMNAME", length=10) ), 
        @AttributeOverride(name="filename", column=@Column(name="FILENAME", length=10) ), 
        @AttributeOverride(name="processingflag1", column=@Column(name="PROCESSINGFLAG1", length=1) ), 
        @AttributeOverride(name="processingflag2", column=@Column(name="PROCESSINGFLAG2", length=1) ), 
        @AttributeOverride(name="processingflag3", column=@Column(name="PROCESSINGFLAG3", length=1) ), 
        @AttributeOverride(name="processingflag4", column=@Column(name="PROCESSINGFLAG4", length=1) ), 
        @AttributeOverride(name="processingflag5", column=@Column(name="PROCESSINGFLAG5", length=1) ), 
        @AttributeOverride(name="processingflag6", column=@Column(name="PROCESSINGFLAG6", length=1) ), 
        @AttributeOverride(name="processingflag7", column=@Column(name="PROCESSINGFLAG7", length=1) ), 
        @AttributeOverride(name="processingflag8", column=@Column(name="PROCESSINGFLAG8", length=1) ), 
        @AttributeOverride(name="processingflag9", column=@Column(name="PROCESSINGFLAG9", length=1) ), 
        @AttributeOverride(name="processingflag10", column=@Column(name="PROCESSINGFLAG10", length=1) ), 
        @AttributeOverride(name="outboundignore", column=@Column(name="OUTBOUNDIGNORE", nullable=false, length=1) ), 
        @AttributeOverride(name="recordlastchangetime", column=@Column(name="RECORDLASTCHANGETIME", length=26) ), 
        @AttributeOverride(name="recordcreationtime", column=@Column(name="RECORDCREATIONTIME", nullable=false, length=26) ) } )
    public Invlini01Id getId() {
        return this.id;
    }
    
    public void setId(Invlini01Id id) {
        this.id = id;
    }




}


