package com.galexis.allog2mysql.deleteme;
// Generated Sep 6, 2013 9:37:59 AM by Hibernate Tools 3.6.0


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Invlinbtc generated by hbm2java
 */
@Entity
@Table(name="INVLINBTC"
    ,schema="INTEGAP"
    ,catalog="CHGALE11RDB"
    , uniqueConstraints = @UniqueConstraint(columnNames="PK") 
)
public class Invlinbtc  implements java.io.Serializable {


     private InvlinbtcId id;
     private Invlin invlin;
     private Invhdr invhdr;
     private Dellinbtc dellinbtc;

    public Invlinbtc() {
    }

	
    public Invlinbtc(InvlinbtcId id, Invlin invlin, Invhdr invhdr) {
        this.id = id;
        this.invlin = invlin;
        this.invhdr = invhdr;
    }
    public Invlinbtc(InvlinbtcId id, Invlin invlin, Invhdr invhdr, Dellinbtc dellinbtc) {
       this.id = id;
       this.invlin = invlin;
       this.invhdr = invhdr;
       this.dellinbtc = dellinbtc;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="pk", column=@Column(name="PK", unique=true, nullable=false, precision=12, scale=0) ), 
        @AttributeOverride(name="invlinpk", column=@Column(name="INVLINPK", nullable=false, precision=12, scale=0) ), 
        @AttributeOverride(name="invhdrpk", column=@Column(name="INVHDRPK", nullable=false, precision=12, scale=0) ), 
        @AttributeOverride(name="invoicelineseq", column=@Column(name="INVOICELINESEQ", nullable=false, precision=3, scale=0) ), 
        @AttributeOverride(name="dellinbtcpk", column=@Column(name="DELLINBTCPK", precision=12, scale=0) ), 
        @AttributeOverride(name="contractordeliverylinenr", column=@Column(name="CONTRACTORDELIVERYLINENR", precision=6, scale=0) ), 
        @AttributeOverride(name="itemnrcontractor", column=@Column(name="ITEMNRCONTRACTOR", length=35) ), 
        @AttributeOverride(name="batchqty", column=@Column(name="BATCHQTY", precision=15, scale=3) ), 
        @AttributeOverride(name="naturaldiscountqty", column=@Column(name="NATURALDISCOUNTQTY", precision=15, scale=3) ), 
        @AttributeOverride(name="batchid", column=@Column(name="BATCHID", length=20) ), 
        @AttributeOverride(name="batchexpirydate", column=@Column(name="BATCHEXPIRYDATE", length=26) ), 
        @AttributeOverride(name="batchidcontractor", column=@Column(name="BATCHIDCONTRACTOR", length=20) ), 
        @AttributeOverride(name="serialnr", column=@Column(name="SERIALNR", length=30) ), 
        @AttributeOverride(name="calculatedsalesamount", column=@Column(name="CALCULATEDSALESAMOUNT", precision=17, scale=4) ), 
        @AttributeOverride(name="calcualtednetsalesvalue", column=@Column(name="CALCUALTEDNETSALESVALUE", precision=17, scale=4) ), 
        @AttributeOverride(name="rounddiffsalesamount", column=@Column(name="ROUNDDIFFSALESAMOUNT", precision=17, scale=4) ), 
        @AttributeOverride(name="rounddiffnetsalesvalue", column=@Column(name="ROUNDDIFFNETSALESVALUE", precision=17, scale=4) ), 
        @AttributeOverride(name="programname", column=@Column(name="PROGRAMNAME", length=10) ), 
        @AttributeOverride(name="filename", column=@Column(name="FILENAME", length=10) ), 
        @AttributeOverride(name="processingflag1", column=@Column(name="PROCESSINGFLAG1", length=1) ), 
        @AttributeOverride(name="processingflag2", column=@Column(name="PROCESSINGFLAG2", length=1) ), 
        @AttributeOverride(name="processingflag3", column=@Column(name="PROCESSINGFLAG3", length=1) ), 
        @AttributeOverride(name="processingflag4", column=@Column(name="PROCESSINGFLAG4", length=1) ), 
        @AttributeOverride(name="processingflag5", column=@Column(name="PROCESSINGFLAG5", length=1) ), 
        @AttributeOverride(name="processingflag6", column=@Column(name="PROCESSINGFLAG6", length=1) ), 
        @AttributeOverride(name="processingflag7", column=@Column(name="PROCESSINGFLAG7", length=1) ), 
        @AttributeOverride(name="processingflag8", column=@Column(name="PROCESSINGFLAG8", length=1) ), 
        @AttributeOverride(name="processingflag9", column=@Column(name="PROCESSINGFLAG9", length=1) ), 
        @AttributeOverride(name="processingflag10", column=@Column(name="PROCESSINGFLAG10", length=1) ), 
        @AttributeOverride(name="outboundignore", column=@Column(name="OUTBOUNDIGNORE", nullable=false, length=1) ), 
        @AttributeOverride(name="recordlastchangetime", column=@Column(name="RECORDLASTCHANGETIME", length=26) ), 
        @AttributeOverride(name="recordcreationtime", column=@Column(name="RECORDCREATIONTIME", nullable=false, length=26) ) } )
    public InvlinbtcId getId() {
        return this.id;
    }
    
    public void setId(InvlinbtcId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="INVLINPK", nullable=false, insertable=false, updatable=false)
    public Invlin getInvlin() {
        return this.invlin;
    }
    
    public void setInvlin(Invlin invlin) {
        this.invlin = invlin;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="INVHDRPK", nullable=false, insertable=false, updatable=false)
    public Invhdr getInvhdr() {
        return this.invhdr;
    }
    
    public void setInvhdr(Invhdr invhdr) {
        this.invhdr = invhdr;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="DELLINBTCPK", insertable=false, updatable=false)
    public Dellinbtc getDellinbtc() {
        return this.dellinbtc;
    }
    
    public void setDellinbtc(Dellinbtc dellinbtc) {
        this.dellinbtc = dellinbtc;
    }




}


