package com.galexis.allog2mysql.deleteme;
// Generated Sep 6, 2013 9:37:59 AM by Hibernate Tools 3.6.0


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Invmovmap generated by hbm2java
 */
@Entity
@Table(name="INVMOVMAP"
    ,schema="INTEGAP"
    ,catalog="CHGALE11RDB"
    , uniqueConstraints = @UniqueConstraint(columnNames="PK") 
)
public class Invmovmap  implements java.io.Serializable {


     private InvmovmapId id;

    public Invmovmap() {
    }

    public Invmovmap(InvmovmapId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="pk", column=@Column(name="PK", unique=true, nullable=false, precision=12, scale=0) ), 
        @AttributeOverride(name="invmovmntpk", column=@Column(name="INVMOVMNTPK", nullable=false, precision=12, scale=0) ), 
        @AttributeOverride(name="invmovconpk", column=@Column(name="INVMOVCONPK", precision=12, scale=0) ), 
        @AttributeOverride(name="plantfrom", column=@Column(name="PLANTFROM", length=20) ), 
        @AttributeOverride(name="plantto", column=@Column(name="PLANTTO", length=20) ), 
        @AttributeOverride(name="storagelocationfrom", column=@Column(name="STORAGELOCATIONFROM", length=20) ), 
        @AttributeOverride(name="storagelocationto", column=@Column(name="STORAGELOCATIONTO", length=20) ), 
        @AttributeOverride(name="stockstatusfrom", column=@Column(name="STOCKSTATUSFROM", length=20) ), 
        @AttributeOverride(name="stockstatusto", column=@Column(name="STOCKSTATUSTO", length=20) ), 
        @AttributeOverride(name="movementcode", column=@Column(name="MOVEMENTCODE", length=20) ), 
        @AttributeOverride(name="reasoncode", column=@Column(name="REASONCODE", length=20) ), 
        @AttributeOverride(name="salesorganisation", column=@Column(name="SALESORGANISATION", length=20) ), 
        @AttributeOverride(name="reference", column=@Column(name="REFERENCE", length=50) ), 
        @AttributeOverride(name="programname", column=@Column(name="PROGRAMNAME", length=10) ), 
        @AttributeOverride(name="filename", column=@Column(name="FILENAME", length=10) ), 
        @AttributeOverride(name="processingflag1", column=@Column(name="PROCESSINGFLAG1", length=1) ), 
        @AttributeOverride(name="processingflag2", column=@Column(name="PROCESSINGFLAG2", length=1) ), 
        @AttributeOverride(name="processingflag3", column=@Column(name="PROCESSINGFLAG3", length=1) ), 
        @AttributeOverride(name="processingflag4", column=@Column(name="PROCESSINGFLAG4", length=1) ), 
        @AttributeOverride(name="processingflag5", column=@Column(name="PROCESSINGFLAG5", length=1) ), 
        @AttributeOverride(name="processingflag6", column=@Column(name="PROCESSINGFLAG6", length=1) ), 
        @AttributeOverride(name="processingflag7", column=@Column(name="PROCESSINGFLAG7", length=1) ), 
        @AttributeOverride(name="processingflag8", column=@Column(name="PROCESSINGFLAG8", length=1) ), 
        @AttributeOverride(name="processingflag9", column=@Column(name="PROCESSINGFLAG9", length=1) ), 
        @AttributeOverride(name="processingflag10", column=@Column(name="PROCESSINGFLAG10", length=1) ), 
        @AttributeOverride(name="outboundignore", column=@Column(name="OUTBOUNDIGNORE", nullable=false, length=1) ), 
        @AttributeOverride(name="recordlastchangetime", column=@Column(name="RECORDLASTCHANGETIME", length=26) ), 
        @AttributeOverride(name="recordcreationtime", column=@Column(name="RECORDCREATIONTIME", length=26) ) } )
    public InvmovmapId getId() {
        return this.id;
    }
    
    public void setId(InvmovmapId id) {
        this.id = id;
    }




}


