package com.galexis.allog2mysql.deleteme;
// Generated Sep 6, 2013 9:37:59 AM by Hibernate Tools 3.6.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Invmovcon generated by hbm2java
 */
@Entity
@Table(name="INVMOVCON"
    ,schema="INTEGAP"
    ,catalog="CHGALE11RDB"
)
public class Invmovcon  implements java.io.Serializable {


     private long pk;
     private Contrdef contrdef;
     private String salesorganisation;
     private Integer inventorytransactiontype;
     private String inventoryeventcode;
     private String warehousefrom;
     private String locationzonefrom;
     private String locationidfrom;
     private String locationstatusfrom;
     private String bulkflagfrom;
     private String qcflagfrom;
     private String warehouseto;
     private String locationzoneto;
     private String locationidto;
     private String locationstatusto;
     private String bulkflagto;
     private String qcflagto;
     private String signe;
     private String purchaseordertype;
     private String batchreasoncode;
     private String movementcode;
     private String movementcodeqcrejected;
     private String plantfrom;
     private String storagelocationfrom;
     private String stockstatusfrom;
     private String plantto;
     private String storagelocationto;
     private String stockstatusto;
     private String stockstatusqcrejto;
     private String reasoncodeflag;
     private String reasoncode;
     private String quantitysignecontractor;
     private String interfacename;
     private String referenceflag;
     private String referencekeyfield1;
     private String referencekeyfield2;
     private String notreportedtransactionflag;
     private String reasoncodeAlloga;
     private String exitprocedure;
     private String valueconversiononip;
     private String isactiveflag;
     private Date recordcreationtime;
     private Date recordlastchangetime;
     private String userlastchange;

    public Invmovcon() {
    }

	
    public Invmovcon(long pk, Contrdef contrdef, String isactiveflag, Date recordcreationtime) {
        this.pk = pk;
        this.contrdef = contrdef;
        this.isactiveflag = isactiveflag;
        this.recordcreationtime = recordcreationtime;
    }
    public Invmovcon(long pk, Contrdef contrdef, String salesorganisation, Integer inventorytransactiontype, String inventoryeventcode, String warehousefrom, String locationzonefrom, String locationidfrom, String locationstatusfrom, String bulkflagfrom, String qcflagfrom, String warehouseto, String locationzoneto, String locationidto, String locationstatusto, String bulkflagto, String qcflagto, String signe, String purchaseordertype, String batchreasoncode, String movementcode, String movementcodeqcrejected, String plantfrom, String storagelocationfrom, String stockstatusfrom, String plantto, String storagelocationto, String stockstatusto, String stockstatusqcrejto, String reasoncodeflag, String reasoncode, String quantitysignecontractor, String interfacename, String referenceflag, String referencekeyfield1, String referencekeyfield2, String notreportedtransactionflag, String reasoncodeAlloga, String exitprocedure, String valueconversiononip, String isactiveflag, Date recordcreationtime, Date recordlastchangetime, String userlastchange) {
       this.pk = pk;
       this.contrdef = contrdef;
       this.salesorganisation = salesorganisation;
       this.inventorytransactiontype = inventorytransactiontype;
       this.inventoryeventcode = inventoryeventcode;
       this.warehousefrom = warehousefrom;
       this.locationzonefrom = locationzonefrom;
       this.locationidfrom = locationidfrom;
       this.locationstatusfrom = locationstatusfrom;
       this.bulkflagfrom = bulkflagfrom;
       this.qcflagfrom = qcflagfrom;
       this.warehouseto = warehouseto;
       this.locationzoneto = locationzoneto;
       this.locationidto = locationidto;
       this.locationstatusto = locationstatusto;
       this.bulkflagto = bulkflagto;
       this.qcflagto = qcflagto;
       this.signe = signe;
       this.purchaseordertype = purchaseordertype;
       this.batchreasoncode = batchreasoncode;
       this.movementcode = movementcode;
       this.movementcodeqcrejected = movementcodeqcrejected;
       this.plantfrom = plantfrom;
       this.storagelocationfrom = storagelocationfrom;
       this.stockstatusfrom = stockstatusfrom;
       this.plantto = plantto;
       this.storagelocationto = storagelocationto;
       this.stockstatusto = stockstatusto;
       this.stockstatusqcrejto = stockstatusqcrejto;
       this.reasoncodeflag = reasoncodeflag;
       this.reasoncode = reasoncode;
       this.quantitysignecontractor = quantitysignecontractor;
       this.interfacename = interfacename;
       this.referenceflag = referenceflag;
       this.referencekeyfield1 = referencekeyfield1;
       this.referencekeyfield2 = referencekeyfield2;
       this.notreportedtransactionflag = notreportedtransactionflag;
       this.reasoncodeAlloga = reasoncodeAlloga;
       this.exitprocedure = exitprocedure;
       this.valueconversiononip = valueconversiononip;
       this.isactiveflag = isactiveflag;
       this.recordcreationtime = recordcreationtime;
       this.recordlastchangetime = recordlastchangetime;
       this.userlastchange = userlastchange;
    }
   
     @Id 

    
    @Column(name="PK", unique=true, nullable=false, precision=12, scale=0)
    public long getPk() {
        return this.pk;
    }
    
    public void setPk(long pk) {
        this.pk = pk;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CONTRDEFPK", nullable=false)
    public Contrdef getContrdef() {
        return this.contrdef;
    }
    
    public void setContrdef(Contrdef contrdef) {
        this.contrdef = contrdef;
    }

    
    @Column(name="SALESORGANISATION", length=20)
    public String getSalesorganisation() {
        return this.salesorganisation;
    }
    
    public void setSalesorganisation(String salesorganisation) {
        this.salesorganisation = salesorganisation;
    }

    
    @Column(name="INVENTORYTRANSACTIONTYPE", precision=5, scale=0)
    public Integer getInventorytransactiontype() {
        return this.inventorytransactiontype;
    }
    
    public void setInventorytransactiontype(Integer inventorytransactiontype) {
        this.inventorytransactiontype = inventorytransactiontype;
    }

    
    @Column(name="INVENTORYEVENTCODE", length=4)
    public String getInventoryeventcode() {
        return this.inventoryeventcode;
    }
    
    public void setInventoryeventcode(String inventoryeventcode) {
        this.inventoryeventcode = inventoryeventcode;
    }

    
    @Column(name="WAREHOUSEFROM", length=4)
    public String getWarehousefrom() {
        return this.warehousefrom;
    }
    
    public void setWarehousefrom(String warehousefrom) {
        this.warehousefrom = warehousefrom;
    }

    
    @Column(name="LOCATIONZONEFROM", length=4)
    public String getLocationzonefrom() {
        return this.locationzonefrom;
    }
    
    public void setLocationzonefrom(String locationzonefrom) {
        this.locationzonefrom = locationzonefrom;
    }

    
    @Column(name="LOCATIONIDFROM", length=8)
    public String getLocationidfrom() {
        return this.locationidfrom;
    }
    
    public void setLocationidfrom(String locationidfrom) {
        this.locationidfrom = locationidfrom;
    }

    
    @Column(name="LOCATIONSTATUSFROM", length=4)
    public String getLocationstatusfrom() {
        return this.locationstatusfrom;
    }
    
    public void setLocationstatusfrom(String locationstatusfrom) {
        this.locationstatusfrom = locationstatusfrom;
    }

    
    @Column(name="BULKFLAGFROM", length=1)
    public String getBulkflagfrom() {
        return this.bulkflagfrom;
    }
    
    public void setBulkflagfrom(String bulkflagfrom) {
        this.bulkflagfrom = bulkflagfrom;
    }

    
    @Column(name="QCFLAGFROM", length=1)
    public String getQcflagfrom() {
        return this.qcflagfrom;
    }
    
    public void setQcflagfrom(String qcflagfrom) {
        this.qcflagfrom = qcflagfrom;
    }

    
    @Column(name="WAREHOUSETO", length=4)
    public String getWarehouseto() {
        return this.warehouseto;
    }
    
    public void setWarehouseto(String warehouseto) {
        this.warehouseto = warehouseto;
    }

    
    @Column(name="LOCATIONZONETO", length=4)
    public String getLocationzoneto() {
        return this.locationzoneto;
    }
    
    public void setLocationzoneto(String locationzoneto) {
        this.locationzoneto = locationzoneto;
    }

    
    @Column(name="LOCATIONIDTO", length=8)
    public String getLocationidto() {
        return this.locationidto;
    }
    
    public void setLocationidto(String locationidto) {
        this.locationidto = locationidto;
    }

    
    @Column(name="LOCATIONSTATUSTO", length=4)
    public String getLocationstatusto() {
        return this.locationstatusto;
    }
    
    public void setLocationstatusto(String locationstatusto) {
        this.locationstatusto = locationstatusto;
    }

    
    @Column(name="BULKFLAGTO", length=1)
    public String getBulkflagto() {
        return this.bulkflagto;
    }
    
    public void setBulkflagto(String bulkflagto) {
        this.bulkflagto = bulkflagto;
    }

    
    @Column(name="QCFLAGTO", length=1)
    public String getQcflagto() {
        return this.qcflagto;
    }
    
    public void setQcflagto(String qcflagto) {
        this.qcflagto = qcflagto;
    }

    
    @Column(name="SIGNE", length=1)
    public String getSigne() {
        return this.signe;
    }
    
    public void setSigne(String signe) {
        this.signe = signe;
    }

    
    @Column(name="PURCHASEORDERTYPE", length=10)
    public String getPurchaseordertype() {
        return this.purchaseordertype;
    }
    
    public void setPurchaseordertype(String purchaseordertype) {
        this.purchaseordertype = purchaseordertype;
    }

    
    @Column(name="BATCHREASONCODE", length=5)
    public String getBatchreasoncode() {
        return this.batchreasoncode;
    }
    
    public void setBatchreasoncode(String batchreasoncode) {
        this.batchreasoncode = batchreasoncode;
    }

    
    @Column(name="MOVEMENTCODE", length=20)
    public String getMovementcode() {
        return this.movementcode;
    }
    
    public void setMovementcode(String movementcode) {
        this.movementcode = movementcode;
    }

    
    @Column(name="MOVEMENTCODEQCREJECTED", length=20)
    public String getMovementcodeqcrejected() {
        return this.movementcodeqcrejected;
    }
    
    public void setMovementcodeqcrejected(String movementcodeqcrejected) {
        this.movementcodeqcrejected = movementcodeqcrejected;
    }

    
    @Column(name="PLANTFROM", length=20)
    public String getPlantfrom() {
        return this.plantfrom;
    }
    
    public void setPlantfrom(String plantfrom) {
        this.plantfrom = plantfrom;
    }

    
    @Column(name="STORAGELOCATIONFROM", length=20)
    public String getStoragelocationfrom() {
        return this.storagelocationfrom;
    }
    
    public void setStoragelocationfrom(String storagelocationfrom) {
        this.storagelocationfrom = storagelocationfrom;
    }

    
    @Column(name="STOCKSTATUSFROM", length=20)
    public String getStockstatusfrom() {
        return this.stockstatusfrom;
    }
    
    public void setStockstatusfrom(String stockstatusfrom) {
        this.stockstatusfrom = stockstatusfrom;
    }

    
    @Column(name="PLANTTO", length=20)
    public String getPlantto() {
        return this.plantto;
    }
    
    public void setPlantto(String plantto) {
        this.plantto = plantto;
    }

    
    @Column(name="STORAGELOCATIONTO", length=20)
    public String getStoragelocationto() {
        return this.storagelocationto;
    }
    
    public void setStoragelocationto(String storagelocationto) {
        this.storagelocationto = storagelocationto;
    }

    
    @Column(name="STOCKSTATUSTO", length=20)
    public String getStockstatusto() {
        return this.stockstatusto;
    }
    
    public void setStockstatusto(String stockstatusto) {
        this.stockstatusto = stockstatusto;
    }

    
    @Column(name="STOCKSTATUSQCREJTO", length=20)
    public String getStockstatusqcrejto() {
        return this.stockstatusqcrejto;
    }
    
    public void setStockstatusqcrejto(String stockstatusqcrejto) {
        this.stockstatusqcrejto = stockstatusqcrejto;
    }

    
    @Column(name="REASONCODEFLAG", length=1)
    public String getReasoncodeflag() {
        return this.reasoncodeflag;
    }
    
    public void setReasoncodeflag(String reasoncodeflag) {
        this.reasoncodeflag = reasoncodeflag;
    }

    
    @Column(name="REASONCODE", length=10)
    public String getReasoncode() {
        return this.reasoncode;
    }
    
    public void setReasoncode(String reasoncode) {
        this.reasoncode = reasoncode;
    }

    
    @Column(name="QUANTITYSIGNECONTRACTOR", length=1)
    public String getQuantitysignecontractor() {
        return this.quantitysignecontractor;
    }
    
    public void setQuantitysignecontractor(String quantitysignecontractor) {
        this.quantitysignecontractor = quantitysignecontractor;
    }

    
    @Column(name="INTERFACENAME", length=20)
    public String getInterfacename() {
        return this.interfacename;
    }
    
    public void setInterfacename(String interfacename) {
        this.interfacename = interfacename;
    }

    
    @Column(name="REFERENCEFLAG", length=1)
    public String getReferenceflag() {
        return this.referenceflag;
    }
    
    public void setReferenceflag(String referenceflag) {
        this.referenceflag = referenceflag;
    }

    
    @Column(name="REFERENCEKEYFIELD1", length=30)
    public String getReferencekeyfield1() {
        return this.referencekeyfield1;
    }
    
    public void setReferencekeyfield1(String referencekeyfield1) {
        this.referencekeyfield1 = referencekeyfield1;
    }

    
    @Column(name="REFERENCEKEYFIELD2", length=30)
    public String getReferencekeyfield2() {
        return this.referencekeyfield2;
    }
    
    public void setReferencekeyfield2(String referencekeyfield2) {
        this.referencekeyfield2 = referencekeyfield2;
    }

    
    @Column(name="NOTREPORTEDTRANSACTIONFLAG", length=1)
    public String getNotreportedtransactionflag() {
        return this.notreportedtransactionflag;
    }
    
    public void setNotreportedtransactionflag(String notreportedtransactionflag) {
        this.notreportedtransactionflag = notreportedtransactionflag;
    }

    
    @Column(name="REASONCODE_ALLOGA", length=10)
    public String getReasoncodeAlloga() {
        return this.reasoncodeAlloga;
    }
    
    public void setReasoncodeAlloga(String reasoncodeAlloga) {
        this.reasoncodeAlloga = reasoncodeAlloga;
    }

    
    @Column(name="EXITPROCEDURE", length=30)
    public String getExitprocedure() {
        return this.exitprocedure;
    }
    
    public void setExitprocedure(String exitprocedure) {
        this.exitprocedure = exitprocedure;
    }

    
    @Column(name="VALUECONVERSIONONIP", length=1)
    public String getValueconversiononip() {
        return this.valueconversiononip;
    }
    
    public void setValueconversiononip(String valueconversiononip) {
        this.valueconversiononip = valueconversiononip;
    }

    
    @Column(name="ISACTIVEFLAG", nullable=false, length=1)
    public String getIsactiveflag() {
        return this.isactiveflag;
    }
    
    public void setIsactiveflag(String isactiveflag) {
        this.isactiveflag = isactiveflag;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="RECORDCREATIONTIME", nullable=false, length=26)
    public Date getRecordcreationtime() {
        return this.recordcreationtime;
    }
    
    public void setRecordcreationtime(Date recordcreationtime) {
        this.recordcreationtime = recordcreationtime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="RECORDLASTCHANGETIME", length=26)
    public Date getRecordlastchangetime() {
        return this.recordlastchangetime;
    }
    
    public void setRecordlastchangetime(Date recordlastchangetime) {
        this.recordlastchangetime = recordlastchangetime;
    }

    
    @Column(name="USERLASTCHANGE", length=20)
    public String getUserlastchange() {
        return this.userlastchange;
    }
    
    public void setUserlastchange(String userlastchange) {
        this.userlastchange = userlastchange;
    }




}


