package com.galexis.allog2mysql.deleteme;
// Generated Sep 6, 2013 9:37:59 AM by Hibernate Tools 3.6.0


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Itemjrnent generated by hbm2java
 */
@Entity
@Table(name="ITEMJRNENT"
    ,schema="INTEGAP"
    ,catalog="CHGALE11RDB"
    , uniqueConstraints = @UniqueConstraint(columnNames="PK") 
)
public class Itemjrnent  implements java.io.Serializable {


     private ItemjrnentId id;

    public Itemjrnent() {
    }

    public Itemjrnent(ItemjrnentId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="pk", column=@Column(name="PK", unique=true, nullable=false, precision=12, scale=0) ), 
        @AttributeOverride(name="tablename", column=@Column(name="TABLENAME", nullable=false, length=10) ), 
        @AttributeOverride(name="fieldname", column=@Column(name="FIELDNAME", length=10) ) } )
    public ItemjrnentId getId() {
        return this.id;
    }
    
    public void setId(ItemjrnentId id) {
        this.id = id;
    }




}


