package com.galexis.allog2mysql.deleteme;
// Generated Sep 6, 2013 9:37:59 AM by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Itemmaster generated by hbm2java
 */
@Entity
@Table(name="ITEMMASTER"
    ,schema="INTEGAP"
    ,catalog="CHGALE11RDB"
)
public class Itemmaster  implements java.io.Serializable {


     private long pk;
     private String itemnr;
     private String itemnrcontractor;
     private String ean;
     private String pharmacode;
     private String description;
     private String descriptionfrench;
     private String productgroup;
     private String productgroupdesc;
     private String itemfamily;
     private String itemsubfamily;
     private String supplieritemgroup;
     private String mainsupplier;
     private String mainsuppliername;
     private String secondsupplier;
     private String manufacturer;
     private String manufacturername;
     private String replecemntitem;
     private Integer bookkeepingnr;
     private String bookkeepingnrdesc;
     private String salesorganisation;
     private String salesorganisationdesc;
     private BigDecimal standardcost;
     private BigDecimal legalsecuritystock;
     private BigDecimal minimumstock;
     private Short batchsecuritydays;
     private String category1;
     private String category2;
     private String category3;
     private String category4;
     private String category5;
     private String category6;
     private String discountgroup;
     private String pricegroup;
     private String family;
     private String sector;
     private String commissiongroup;
     private String statuscode;
     private String fictitiousflag;
     private String handlingstatuscode;
     private String pickingcode;
     private String pickingcategory;
     private String vathandlingcode;
     private BigDecimal vatpercentage;
     private String swissmediccode;
     private String vignetteflag;
     private String goodstype;
     private String manneroftransportcode;
     private String prescriptionflag;
     private BigDecimal publicprice;
     private BigDecimal doctorsprice;
     private BigDecimal selfdispensingdoctorsprice;
     private BigDecimal pharmacyprice;
     private BigDecimal hospitalprice;
     private BigDecimal exfactoryprice;
     private BigDecimal baseprice;
     private BigDecimal sampleqty;
     private BigDecimal palletqty;
     private BigDecimal cartonqty;
     private String backlogflag;
     private String locationgroup;
     private BigDecimal grossweight;
     private BigDecimal netweight;
     private BigDecimal grossvolume;
     private BigDecimal netvolume;
     private BigDecimal length;
     private BigDecimal height;
     private BigDecimal width;
     private String batchcontrolledflag;
     private String contbatchcontrolledflag;
     private String serialnumbertrackingflag;
     private String narcoticcategory;
     private String eshopprovideflag;
     private String clinicalstudyflag;
     private String cooleditemflag;
     private String qcsamplingflag;
     private String qcsamplebacktowhsflag;
     private String narcoticflag;
     private String hazardoushandlingcode;
     private String hazardousgoodflag;
     private String medtechitem;
     private String electronicorderpermitted;
     private String itemnrcontractor2;
     private String itemnrcontractor3;
     private Date validfrom;
     private Date validto;
     private String outboundignore;
     private String reportignore;
     private String brand;
     private String migelcode;
     private String atccode;
     private String imsotccode;
     private String healthinsuranceaccepted;
     private String fragileflag;
     private String flammableflag;
     private String antibioticsflag;
     private String serumflag;
     private String specialaffairsflag;
     private String processingflag1;
     private String processingflag2;
     private String processingflag3;
     private String processingflag4;
     private String processingflag5;
     private String processingflag6;
     private String processingflag7;
     private String processingflag8;
     private String processingflag9;
     private String processingflag10;
     private String transactionid;
     private String recordprocessedflag;
     private Date recordprocessingtime;
     private Date recordlastchangetime;
     private Date recordcreationtime;
     private String sortdescde;
     private String sortdescfr;
     private String responsible;
     private String planer;
     private String rating;
     private String bewirtschaftungDisplay;
     private Set<Invlin> invlins = new HashSet<Invlin>(0);
     private Set<Custopolin> custopolins = new HashSet<Custopolin>(0);
     private Set<Retlin> retlins = new HashSet<Retlin>(0);
     private Set<Stockrclop> stockrclops = new HashSet<Stockrclop>(0);
     private Set<Itembtcm> itembtcms = new HashSet<Itembtcm>(0);
     private Set<Stockrcbtc> stockrcbtcs = new HashSet<Stockrcbtc>(0);
     private Set<Stockrebtc> stockrebtcs = new HashSet<Stockrebtc>(0);
     private Set<Psilincnf> psilincnfs = new HashSet<Psilincnf>(0);
     private Set<Invmovmnt> invmovmnts = new HashSet<Invmovmnt>(0);
     private Set<Dellin> dellins = new HashSet<Dellin>(0);
     private Set<Grelin> grelins = new HashSet<Grelin>(0);

    public Itemmaster() {
    }

	
    public Itemmaster(long pk, String itemnr, Date validfrom, Date recordcreationtime, String sortdescde, String sortdescfr, String responsible, String planer, String rating, String bewirtschaftungDisplay) {
        this.pk = pk;
        this.itemnr = itemnr;
        this.validfrom = validfrom;
        this.recordcreationtime = recordcreationtime;
        this.sortdescde = sortdescde;
        this.sortdescfr = sortdescfr;
        this.responsible = responsible;
        this.planer = planer;
        this.rating = rating;
        this.bewirtschaftungDisplay = bewirtschaftungDisplay;
    }
    public Itemmaster(long pk, String itemnr, String itemnrcontractor, String ean, String pharmacode, String description, String descriptionfrench, String productgroup, String productgroupdesc, String itemfamily, String itemsubfamily, String supplieritemgroup, String mainsupplier, String mainsuppliername, String secondsupplier, String manufacturer, String manufacturername, String replecemntitem, Integer bookkeepingnr, String bookkeepingnrdesc, String salesorganisation, String salesorganisationdesc, BigDecimal standardcost, BigDecimal legalsecuritystock, BigDecimal minimumstock, Short batchsecuritydays, String category1, String category2, String category3, String category4, String category5, String category6, String discountgroup, String pricegroup, String family, String sector, String commissiongroup, String statuscode, String fictitiousflag, String handlingstatuscode, String pickingcode, String pickingcategory, String vathandlingcode, BigDecimal vatpercentage, String swissmediccode, String vignetteflag, String goodstype, String manneroftransportcode, String prescriptionflag, BigDecimal publicprice, BigDecimal doctorsprice, BigDecimal selfdispensingdoctorsprice, BigDecimal pharmacyprice, BigDecimal hospitalprice, BigDecimal exfactoryprice, BigDecimal baseprice, BigDecimal sampleqty, BigDecimal palletqty, BigDecimal cartonqty, String backlogflag, String locationgroup, BigDecimal grossweight, BigDecimal netweight, BigDecimal grossvolume, BigDecimal netvolume, BigDecimal length, BigDecimal height, BigDecimal width, String batchcontrolledflag, String contbatchcontrolledflag, String serialnumbertrackingflag, String narcoticcategory, String eshopprovideflag, String clinicalstudyflag, String cooleditemflag, String qcsamplingflag, String qcsamplebacktowhsflag, String narcoticflag, String hazardoushandlingcode, String hazardousgoodflag, String medtechitem, String electronicorderpermitted, String itemnrcontractor2, String itemnrcontractor3, Date validfrom, Date validto, String outboundignore, String reportignore, String brand, String migelcode, String atccode, String imsotccode, String healthinsuranceaccepted, String fragileflag, String flammableflag, String antibioticsflag, String serumflag, String specialaffairsflag, String processingflag1, String processingflag2, String processingflag3, String processingflag4, String processingflag5, String processingflag6, String processingflag7, String processingflag8, String processingflag9, String processingflag10, String transactionid, String recordprocessedflag, Date recordprocessingtime, Date recordlastchangetime, Date recordcreationtime, String sortdescde, String sortdescfr, String responsible, String planer, String rating, String bewirtschaftungDisplay, Set<Invlin> invlins, Set<Custopolin> custopolins, Set<Retlin> retlins, Set<Stockrclop> stockrclops, Set<Itembtcm> itembtcms, Set<Stockrcbtc> stockrcbtcs, Set<Stockrebtc> stockrebtcs, Set<Psilincnf> psilincnfs, Set<Invmovmnt> invmovmnts, Set<Dellin> dellins, Set<Grelin> grelins) {
       this.pk = pk;
       this.itemnr = itemnr;
       this.itemnrcontractor = itemnrcontractor;
       this.ean = ean;
       this.pharmacode = pharmacode;
       this.description = description;
       this.descriptionfrench = descriptionfrench;
       this.productgroup = productgroup;
       this.productgroupdesc = productgroupdesc;
       this.itemfamily = itemfamily;
       this.itemsubfamily = itemsubfamily;
       this.supplieritemgroup = supplieritemgroup;
       this.mainsupplier = mainsupplier;
       this.mainsuppliername = mainsuppliername;
       this.secondsupplier = secondsupplier;
       this.manufacturer = manufacturer;
       this.manufacturername = manufacturername;
       this.replecemntitem = replecemntitem;
       this.bookkeepingnr = bookkeepingnr;
       this.bookkeepingnrdesc = bookkeepingnrdesc;
       this.salesorganisation = salesorganisation;
       this.salesorganisationdesc = salesorganisationdesc;
       this.standardcost = standardcost;
       this.legalsecuritystock = legalsecuritystock;
       this.minimumstock = minimumstock;
       this.batchsecuritydays = batchsecuritydays;
       this.category1 = category1;
       this.category2 = category2;
       this.category3 = category3;
       this.category4 = category4;
       this.category5 = category5;
       this.category6 = category6;
       this.discountgroup = discountgroup;
       this.pricegroup = pricegroup;
       this.family = family;
       this.sector = sector;
       this.commissiongroup = commissiongroup;
       this.statuscode = statuscode;
       this.fictitiousflag = fictitiousflag;
       this.handlingstatuscode = handlingstatuscode;
       this.pickingcode = pickingcode;
       this.pickingcategory = pickingcategory;
       this.vathandlingcode = vathandlingcode;
       this.vatpercentage = vatpercentage;
       this.swissmediccode = swissmediccode;
       this.vignetteflag = vignetteflag;
       this.goodstype = goodstype;
       this.manneroftransportcode = manneroftransportcode;
       this.prescriptionflag = prescriptionflag;
       this.publicprice = publicprice;
       this.doctorsprice = doctorsprice;
       this.selfdispensingdoctorsprice = selfdispensingdoctorsprice;
       this.pharmacyprice = pharmacyprice;
       this.hospitalprice = hospitalprice;
       this.exfactoryprice = exfactoryprice;
       this.baseprice = baseprice;
       this.sampleqty = sampleqty;
       this.palletqty = palletqty;
       this.cartonqty = cartonqty;
       this.backlogflag = backlogflag;
       this.locationgroup = locationgroup;
       this.grossweight = grossweight;
       this.netweight = netweight;
       this.grossvolume = grossvolume;
       this.netvolume = netvolume;
       this.length = length;
       this.height = height;
       this.width = width;
       this.batchcontrolledflag = batchcontrolledflag;
       this.contbatchcontrolledflag = contbatchcontrolledflag;
       this.serialnumbertrackingflag = serialnumbertrackingflag;
       this.narcoticcategory = narcoticcategory;
       this.eshopprovideflag = eshopprovideflag;
       this.clinicalstudyflag = clinicalstudyflag;
       this.cooleditemflag = cooleditemflag;
       this.qcsamplingflag = qcsamplingflag;
       this.qcsamplebacktowhsflag = qcsamplebacktowhsflag;
       this.narcoticflag = narcoticflag;
       this.hazardoushandlingcode = hazardoushandlingcode;
       this.hazardousgoodflag = hazardousgoodflag;
       this.medtechitem = medtechitem;
       this.electronicorderpermitted = electronicorderpermitted;
       this.itemnrcontractor2 = itemnrcontractor2;
       this.itemnrcontractor3 = itemnrcontractor3;
       this.validfrom = validfrom;
       this.validto = validto;
       this.outboundignore = outboundignore;
       this.reportignore = reportignore;
       this.brand = brand;
       this.migelcode = migelcode;
       this.atccode = atccode;
       this.imsotccode = imsotccode;
       this.healthinsuranceaccepted = healthinsuranceaccepted;
       this.fragileflag = fragileflag;
       this.flammableflag = flammableflag;
       this.antibioticsflag = antibioticsflag;
       this.serumflag = serumflag;
       this.specialaffairsflag = specialaffairsflag;
       this.processingflag1 = processingflag1;
       this.processingflag2 = processingflag2;
       this.processingflag3 = processingflag3;
       this.processingflag4 = processingflag4;
       this.processingflag5 = processingflag5;
       this.processingflag6 = processingflag6;
       this.processingflag7 = processingflag7;
       this.processingflag8 = processingflag8;
       this.processingflag9 = processingflag9;
       this.processingflag10 = processingflag10;
       this.transactionid = transactionid;
       this.recordprocessedflag = recordprocessedflag;
       this.recordprocessingtime = recordprocessingtime;
       this.recordlastchangetime = recordlastchangetime;
       this.recordcreationtime = recordcreationtime;
       this.sortdescde = sortdescde;
       this.sortdescfr = sortdescfr;
       this.responsible = responsible;
       this.planer = planer;
       this.rating = rating;
       this.bewirtschaftungDisplay = bewirtschaftungDisplay;
       this.invlins = invlins;
       this.custopolins = custopolins;
       this.retlins = retlins;
       this.stockrclops = stockrclops;
       this.itembtcms = itembtcms;
       this.stockrcbtcs = stockrcbtcs;
       this.stockrebtcs = stockrebtcs;
       this.psilincnfs = psilincnfs;
       this.invmovmnts = invmovmnts;
       this.dellins = dellins;
       this.grelins = grelins;
    }
   
     @Id 

    
    @Column(name="PK", unique=true, nullable=false, precision=12, scale=0)
    public long getPk() {
        return this.pk;
    }
    
    public void setPk(long pk) {
        this.pk = pk;
    }

    
    @Column(name="ITEMNR", nullable=false, length=35)
    public String getItemnr() {
        return this.itemnr;
    }
    
    public void setItemnr(String itemnr) {
        this.itemnr = itemnr;
    }

    
    @Column(name="ITEMNRCONTRACTOR", length=35)
    public String getItemnrcontractor() {
        return this.itemnrcontractor;
    }
    
    public void setItemnrcontractor(String itemnrcontractor) {
        this.itemnrcontractor = itemnrcontractor;
    }

    
    @Column(name="EAN", length=35)
    public String getEan() {
        return this.ean;
    }
    
    public void setEan(String ean) {
        this.ean = ean;
    }

    
    @Column(name="PHARMACODE", length=35)
    public String getPharmacode() {
        return this.pharmacode;
    }
    
    public void setPharmacode(String pharmacode) {
        this.pharmacode = pharmacode;
    }

    
    @Column(name="DESCRIPTION", length=50)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="DESCRIPTIONFRENCH", length=50)
    public String getDescriptionfrench() {
        return this.descriptionfrench;
    }
    
    public void setDescriptionfrench(String descriptionfrench) {
        this.descriptionfrench = descriptionfrench;
    }

    
    @Column(name="PRODUCTGROUP", length=5)
    public String getProductgroup() {
        return this.productgroup;
    }
    
    public void setProductgroup(String productgroup) {
        this.productgroup = productgroup;
    }

    
    @Column(name="PRODUCTGROUPDESC", length=50)
    public String getProductgroupdesc() {
        return this.productgroupdesc;
    }
    
    public void setProductgroupdesc(String productgroupdesc) {
        this.productgroupdesc = productgroupdesc;
    }

    
    @Column(name="ITEMFAMILY", length=5)
    public String getItemfamily() {
        return this.itemfamily;
    }
    
    public void setItemfamily(String itemfamily) {
        this.itemfamily = itemfamily;
    }

    
    @Column(name="ITEMSUBFAMILY", length=5)
    public String getItemsubfamily() {
        return this.itemsubfamily;
    }
    
    public void setItemsubfamily(String itemsubfamily) {
        this.itemsubfamily = itemsubfamily;
    }

    
    @Column(name="SUPPLIERITEMGROUP", length=10)
    public String getSupplieritemgroup() {
        return this.supplieritemgroup;
    }
    
    public void setSupplieritemgroup(String supplieritemgroup) {
        this.supplieritemgroup = supplieritemgroup;
    }

    
    @Column(name="MAINSUPPLIER", length=20)
    public String getMainsupplier() {
        return this.mainsupplier;
    }
    
    public void setMainsupplier(String mainsupplier) {
        this.mainsupplier = mainsupplier;
    }

    
    @Column(name="MAINSUPPLIERNAME", length=50)
    public String getMainsuppliername() {
        return this.mainsuppliername;
    }
    
    public void setMainsuppliername(String mainsuppliername) {
        this.mainsuppliername = mainsuppliername;
    }

    
    @Column(name="SECONDSUPPLIER", length=20)
    public String getSecondsupplier() {
        return this.secondsupplier;
    }
    
    public void setSecondsupplier(String secondsupplier) {
        this.secondsupplier = secondsupplier;
    }

    
    @Column(name="MANUFACTURER", length=20)
    public String getManufacturer() {
        return this.manufacturer;
    }
    
    public void setManufacturer(String manufacturer) {
        this.manufacturer = manufacturer;
    }

    
    @Column(name="MANUFACTURERNAME", length=50)
    public String getManufacturername() {
        return this.manufacturername;
    }
    
    public void setManufacturername(String manufacturername) {
        this.manufacturername = manufacturername;
    }

    
    @Column(name="REPLECEMNTITEM", length=35)
    public String getReplecemntitem() {
        return this.replecemntitem;
    }
    
    public void setReplecemntitem(String replecemntitem) {
        this.replecemntitem = replecemntitem;
    }

    
    @Column(name="BOOKKEEPINGNR", precision=9, scale=0)
    public Integer getBookkeepingnr() {
        return this.bookkeepingnr;
    }
    
    public void setBookkeepingnr(Integer bookkeepingnr) {
        this.bookkeepingnr = bookkeepingnr;
    }

    
    @Column(name="BOOKKEEPINGNRDESC", length=50)
    public String getBookkeepingnrdesc() {
        return this.bookkeepingnrdesc;
    }
    
    public void setBookkeepingnrdesc(String bookkeepingnrdesc) {
        this.bookkeepingnrdesc = bookkeepingnrdesc;
    }

    
    @Column(name="SALESORGANISATION", length=30)
    public String getSalesorganisation() {
        return this.salesorganisation;
    }
    
    public void setSalesorganisation(String salesorganisation) {
        this.salesorganisation = salesorganisation;
    }

    
    @Column(name="SALESORGANISATIONDESC", length=50)
    public String getSalesorganisationdesc() {
        return this.salesorganisationdesc;
    }
    
    public void setSalesorganisationdesc(String salesorganisationdesc) {
        this.salesorganisationdesc = salesorganisationdesc;
    }

    
    @Column(name="STANDARDCOST", precision=17, scale=4)
    public BigDecimal getStandardcost() {
        return this.standardcost;
    }
    
    public void setStandardcost(BigDecimal standardcost) {
        this.standardcost = standardcost;
    }

    
    @Column(name="LEGALSECURITYSTOCK", precision=15, scale=3)
    public BigDecimal getLegalsecuritystock() {
        return this.legalsecuritystock;
    }
    
    public void setLegalsecuritystock(BigDecimal legalsecuritystock) {
        this.legalsecuritystock = legalsecuritystock;
    }

    
    @Column(name="MINIMUMSTOCK", precision=15, scale=3)
    public BigDecimal getMinimumstock() {
        return this.minimumstock;
    }
    
    public void setMinimumstock(BigDecimal minimumstock) {
        this.minimumstock = minimumstock;
    }

    
    @Column(name="BATCHSECURITYDAYS", precision=4, scale=0)
    public Short getBatchsecuritydays() {
        return this.batchsecuritydays;
    }
    
    public void setBatchsecuritydays(Short batchsecuritydays) {
        this.batchsecuritydays = batchsecuritydays;
    }

    
    @Column(name="CATEGORY1", length=10)
    public String getCategory1() {
        return this.category1;
    }
    
    public void setCategory1(String category1) {
        this.category1 = category1;
    }

    
    @Column(name="CATEGORY2", length=10)
    public String getCategory2() {
        return this.category2;
    }
    
    public void setCategory2(String category2) {
        this.category2 = category2;
    }

    
    @Column(name="CATEGORY3", length=10)
    public String getCategory3() {
        return this.category3;
    }
    
    public void setCategory3(String category3) {
        this.category3 = category3;
    }

    
    @Column(name="CATEGORY4", length=10)
    public String getCategory4() {
        return this.category4;
    }
    
    public void setCategory4(String category4) {
        this.category4 = category4;
    }

    
    @Column(name="CATEGORY5", length=10)
    public String getCategory5() {
        return this.category5;
    }
    
    public void setCategory5(String category5) {
        this.category5 = category5;
    }

    
    @Column(name="CATEGORY6", length=10)
    public String getCategory6() {
        return this.category6;
    }
    
    public void setCategory6(String category6) {
        this.category6 = category6;
    }

    
    @Column(name="DISCOUNTGROUP", length=10)
    public String getDiscountgroup() {
        return this.discountgroup;
    }
    
    public void setDiscountgroup(String discountgroup) {
        this.discountgroup = discountgroup;
    }

    
    @Column(name="PRICEGROUP", length=10)
    public String getPricegroup() {
        return this.pricegroup;
    }
    
    public void setPricegroup(String pricegroup) {
        this.pricegroup = pricegroup;
    }

    
    @Column(name="FAMILY", length=10)
    public String getFamily() {
        return this.family;
    }
    
    public void setFamily(String family) {
        this.family = family;
    }

    
    @Column(name="SECTOR", length=10)
    public String getSector() {
        return this.sector;
    }
    
    public void setSector(String sector) {
        this.sector = sector;
    }

    
    @Column(name="COMMISSIONGROUP", length=10)
    public String getCommissiongroup() {
        return this.commissiongroup;
    }
    
    public void setCommissiongroup(String commissiongroup) {
        this.commissiongroup = commissiongroup;
    }

    
    @Column(name="STATUSCODE", length=10)
    public String getStatuscode() {
        return this.statuscode;
    }
    
    public void setStatuscode(String statuscode) {
        this.statuscode = statuscode;
    }

    
    @Column(name="FICTITIOUSFLAG", length=1)
    public String getFictitiousflag() {
        return this.fictitiousflag;
    }
    
    public void setFictitiousflag(String fictitiousflag) {
        this.fictitiousflag = fictitiousflag;
    }

    
    @Column(name="HANDLINGSTATUSCODE", length=10)
    public String getHandlingstatuscode() {
        return this.handlingstatuscode;
    }
    
    public void setHandlingstatuscode(String handlingstatuscode) {
        this.handlingstatuscode = handlingstatuscode;
    }

    
    @Column(name="PICKINGCODE", length=10)
    public String getPickingcode() {
        return this.pickingcode;
    }
    
    public void setPickingcode(String pickingcode) {
        this.pickingcode = pickingcode;
    }

    
    @Column(name="PICKINGCATEGORY", length=10)
    public String getPickingcategory() {
        return this.pickingcategory;
    }
    
    public void setPickingcategory(String pickingcategory) {
        this.pickingcategory = pickingcategory;
    }

    
    @Column(name="VATHANDLINGCODE", length=4)
    public String getVathandlingcode() {
        return this.vathandlingcode;
    }
    
    public void setVathandlingcode(String vathandlingcode) {
        this.vathandlingcode = vathandlingcode;
    }

    
    @Column(name="VATPERCENTAGE", precision=4)
    public BigDecimal getVatpercentage() {
        return this.vatpercentage;
    }
    
    public void setVatpercentage(BigDecimal vatpercentage) {
        this.vatpercentage = vatpercentage;
    }

    
    @Column(name="SWISSMEDICCODE", length=10)
    public String getSwissmediccode() {
        return this.swissmediccode;
    }
    
    public void setSwissmediccode(String swissmediccode) {
        this.swissmediccode = swissmediccode;
    }

    
    @Column(name="VIGNETTEFLAG", length=1)
    public String getVignetteflag() {
        return this.vignetteflag;
    }
    
    public void setVignetteflag(String vignetteflag) {
        this.vignetteflag = vignetteflag;
    }

    
    @Column(name="GOODSTYPE", length=10)
    public String getGoodstype() {
        return this.goodstype;
    }
    
    public void setGoodstype(String goodstype) {
        this.goodstype = goodstype;
    }

    
    @Column(name="MANNEROFTRANSPORTCODE", length=10)
    public String getManneroftransportcode() {
        return this.manneroftransportcode;
    }
    
    public void setManneroftransportcode(String manneroftransportcode) {
        this.manneroftransportcode = manneroftransportcode;
    }

    
    @Column(name="PRESCRIPTIONFLAG", length=1)
    public String getPrescriptionflag() {
        return this.prescriptionflag;
    }
    
    public void setPrescriptionflag(String prescriptionflag) {
        this.prescriptionflag = prescriptionflag;
    }

    
    @Column(name="PUBLICPRICE", precision=17, scale=4)
    public BigDecimal getPublicprice() {
        return this.publicprice;
    }
    
    public void setPublicprice(BigDecimal publicprice) {
        this.publicprice = publicprice;
    }

    
    @Column(name="DOCTORSPRICE", precision=17, scale=4)
    public BigDecimal getDoctorsprice() {
        return this.doctorsprice;
    }
    
    public void setDoctorsprice(BigDecimal doctorsprice) {
        this.doctorsprice = doctorsprice;
    }

    
    @Column(name="SELFDISPENSINGDOCTORSPRICE", precision=17, scale=4)
    public BigDecimal getSelfdispensingdoctorsprice() {
        return this.selfdispensingdoctorsprice;
    }
    
    public void setSelfdispensingdoctorsprice(BigDecimal selfdispensingdoctorsprice) {
        this.selfdispensingdoctorsprice = selfdispensingdoctorsprice;
    }

    
    @Column(name="PHARMACYPRICE", precision=17, scale=4)
    public BigDecimal getPharmacyprice() {
        return this.pharmacyprice;
    }
    
    public void setPharmacyprice(BigDecimal pharmacyprice) {
        this.pharmacyprice = pharmacyprice;
    }

    
    @Column(name="HOSPITALPRICE", precision=17, scale=4)
    public BigDecimal getHospitalprice() {
        return this.hospitalprice;
    }
    
    public void setHospitalprice(BigDecimal hospitalprice) {
        this.hospitalprice = hospitalprice;
    }

    
    @Column(name="EXFACTORYPRICE", precision=17, scale=4)
    public BigDecimal getExfactoryprice() {
        return this.exfactoryprice;
    }
    
    public void setExfactoryprice(BigDecimal exfactoryprice) {
        this.exfactoryprice = exfactoryprice;
    }

    
    @Column(name="BASEPRICE", precision=17, scale=4)
    public BigDecimal getBaseprice() {
        return this.baseprice;
    }
    
    public void setBaseprice(BigDecimal baseprice) {
        this.baseprice = baseprice;
    }

    
    @Column(name="SAMPLEQTY", precision=15, scale=3)
    public BigDecimal getSampleqty() {
        return this.sampleqty;
    }
    
    public void setSampleqty(BigDecimal sampleqty) {
        this.sampleqty = sampleqty;
    }

    
    @Column(name="PALLETQTY", precision=15, scale=3)
    public BigDecimal getPalletqty() {
        return this.palletqty;
    }
    
    public void setPalletqty(BigDecimal palletqty) {
        this.palletqty = palletqty;
    }

    
    @Column(name="CARTONQTY", precision=15, scale=3)
    public BigDecimal getCartonqty() {
        return this.cartonqty;
    }
    
    public void setCartonqty(BigDecimal cartonqty) {
        this.cartonqty = cartonqty;
    }

    
    @Column(name="BACKLOGFLAG", length=1)
    public String getBacklogflag() {
        return this.backlogflag;
    }
    
    public void setBacklogflag(String backlogflag) {
        this.backlogflag = backlogflag;
    }

    
    @Column(name="LOCATIONGROUP", length=10)
    public String getLocationgroup() {
        return this.locationgroup;
    }
    
    public void setLocationgroup(String locationgroup) {
        this.locationgroup = locationgroup;
    }

    
    @Column(name="GROSSWEIGHT", precision=11, scale=5)
    public BigDecimal getGrossweight() {
        return this.grossweight;
    }
    
    public void setGrossweight(BigDecimal grossweight) {
        this.grossweight = grossweight;
    }

    
    @Column(name="NETWEIGHT", precision=11, scale=5)
    public BigDecimal getNetweight() {
        return this.netweight;
    }
    
    public void setNetweight(BigDecimal netweight) {
        this.netweight = netweight;
    }

    
    @Column(name="GROSSVOLUME", precision=11, scale=5)
    public BigDecimal getGrossvolume() {
        return this.grossvolume;
    }
    
    public void setGrossvolume(BigDecimal grossvolume) {
        this.grossvolume = grossvolume;
    }

    
    @Column(name="NETVOLUME", precision=11, scale=5)
    public BigDecimal getNetvolume() {
        return this.netvolume;
    }
    
    public void setNetvolume(BigDecimal netvolume) {
        this.netvolume = netvolume;
    }

    
    @Column(name="LENGTH", precision=9, scale=3)
    public BigDecimal getLength() {
        return this.length;
    }
    
    public void setLength(BigDecimal length) {
        this.length = length;
    }

    
    @Column(name="HEIGHT", precision=9, scale=3)
    public BigDecimal getHeight() {
        return this.height;
    }
    
    public void setHeight(BigDecimal height) {
        this.height = height;
    }

    
    @Column(name="WIDTH", precision=9, scale=3)
    public BigDecimal getWidth() {
        return this.width;
    }
    
    public void setWidth(BigDecimal width) {
        this.width = width;
    }

    
    @Column(name="BATCHCONTROLLEDFLAG", length=1)
    public String getBatchcontrolledflag() {
        return this.batchcontrolledflag;
    }
    
    public void setBatchcontrolledflag(String batchcontrolledflag) {
        this.batchcontrolledflag = batchcontrolledflag;
    }

    
    @Column(name="CONTBATCHCONTROLLEDFLAG", length=1)
    public String getContbatchcontrolledflag() {
        return this.contbatchcontrolledflag;
    }
    
    public void setContbatchcontrolledflag(String contbatchcontrolledflag) {
        this.contbatchcontrolledflag = contbatchcontrolledflag;
    }

    
    @Column(name="SERIALNUMBERTRACKINGFLAG", length=1)
    public String getSerialnumbertrackingflag() {
        return this.serialnumbertrackingflag;
    }
    
    public void setSerialnumbertrackingflag(String serialnumbertrackingflag) {
        this.serialnumbertrackingflag = serialnumbertrackingflag;
    }

    
    @Column(name="NARCOTICCATEGORY", length=10)
    public String getNarcoticcategory() {
        return this.narcoticcategory;
    }
    
    public void setNarcoticcategory(String narcoticcategory) {
        this.narcoticcategory = narcoticcategory;
    }

    
    @Column(name="ESHOPPROVIDEFLAG", length=1)
    public String getEshopprovideflag() {
        return this.eshopprovideflag;
    }
    
    public void setEshopprovideflag(String eshopprovideflag) {
        this.eshopprovideflag = eshopprovideflag;
    }

    
    @Column(name="CLINICALSTUDYFLAG", length=1)
    public String getClinicalstudyflag() {
        return this.clinicalstudyflag;
    }
    
    public void setClinicalstudyflag(String clinicalstudyflag) {
        this.clinicalstudyflag = clinicalstudyflag;
    }

    
    @Column(name="COOLEDITEMFLAG", length=1)
    public String getCooleditemflag() {
        return this.cooleditemflag;
    }
    
    public void setCooleditemflag(String cooleditemflag) {
        this.cooleditemflag = cooleditemflag;
    }

    
    @Column(name="QCSAMPLINGFLAG", length=1)
    public String getQcsamplingflag() {
        return this.qcsamplingflag;
    }
    
    public void setQcsamplingflag(String qcsamplingflag) {
        this.qcsamplingflag = qcsamplingflag;
    }

    
    @Column(name="QCSAMPLEBACKTOWHSFLAG", length=1)
    public String getQcsamplebacktowhsflag() {
        return this.qcsamplebacktowhsflag;
    }
    
    public void setQcsamplebacktowhsflag(String qcsamplebacktowhsflag) {
        this.qcsamplebacktowhsflag = qcsamplebacktowhsflag;
    }

    
    @Column(name="NARCOTICFLAG", length=1)
    public String getNarcoticflag() {
        return this.narcoticflag;
    }
    
    public void setNarcoticflag(String narcoticflag) {
        this.narcoticflag = narcoticflag;
    }

    
    @Column(name="HAZARDOUSHANDLINGCODE", length=5)
    public String getHazardoushandlingcode() {
        return this.hazardoushandlingcode;
    }
    
    public void setHazardoushandlingcode(String hazardoushandlingcode) {
        this.hazardoushandlingcode = hazardoushandlingcode;
    }

    
    @Column(name="HAZARDOUSGOODFLAG", length=1)
    public String getHazardousgoodflag() {
        return this.hazardousgoodflag;
    }
    
    public void setHazardousgoodflag(String hazardousgoodflag) {
        this.hazardousgoodflag = hazardousgoodflag;
    }

    
    @Column(name="MEDTECHITEM", length=1)
    public String getMedtechitem() {
        return this.medtechitem;
    }
    
    public void setMedtechitem(String medtechitem) {
        this.medtechitem = medtechitem;
    }

    
    @Column(name="ELECTRONICORDERPERMITTED", length=1)
    public String getElectronicorderpermitted() {
        return this.electronicorderpermitted;
    }
    
    public void setElectronicorderpermitted(String electronicorderpermitted) {
        this.electronicorderpermitted = electronicorderpermitted;
    }

    
    @Column(name="ITEMNRCONTRACTOR2", length=35)
    public String getItemnrcontractor2() {
        return this.itemnrcontractor2;
    }
    
    public void setItemnrcontractor2(String itemnrcontractor2) {
        this.itemnrcontractor2 = itemnrcontractor2;
    }

    
    @Column(name="ITEMNRCONTRACTOR3", length=35)
    public String getItemnrcontractor3() {
        return this.itemnrcontractor3;
    }
    
    public void setItemnrcontractor3(String itemnrcontractor3) {
        this.itemnrcontractor3 = itemnrcontractor3;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="VALIDFROM", nullable=false, length=26)
    public Date getValidfrom() {
        return this.validfrom;
    }
    
    public void setValidfrom(Date validfrom) {
        this.validfrom = validfrom;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="VALIDTO", length=26)
    public Date getValidto() {
        return this.validto;
    }
    
    public void setValidto(Date validto) {
        this.validto = validto;
    }

    
    @Column(name="OUTBOUNDIGNORE", length=1)
    public String getOutboundignore() {
        return this.outboundignore;
    }
    
    public void setOutboundignore(String outboundignore) {
        this.outboundignore = outboundignore;
    }

    
    @Column(name="REPORTIGNORE", length=1)
    public String getReportignore() {
        return this.reportignore;
    }
    
    public void setReportignore(String reportignore) {
        this.reportignore = reportignore;
    }

    
    @Column(name="BRAND", length=50)
    public String getBrand() {
        return this.brand;
    }
    
    public void setBrand(String brand) {
        this.brand = brand;
    }

    
    @Column(name="MIGELCODE", length=20)
    public String getMigelcode() {
        return this.migelcode;
    }
    
    public void setMigelcode(String migelcode) {
        this.migelcode = migelcode;
    }

    
    @Column(name="ATCCODE", length=10)
    public String getAtccode() {
        return this.atccode;
    }
    
    public void setAtccode(String atccode) {
        this.atccode = atccode;
    }

    
    @Column(name="IMSOTCCODE", length=10)
    public String getImsotccode() {
        return this.imsotccode;
    }
    
    public void setImsotccode(String imsotccode) {
        this.imsotccode = imsotccode;
    }

    
    @Column(name="HEALTHINSURANCEACCEPTED", length=1)
    public String getHealthinsuranceaccepted() {
        return this.healthinsuranceaccepted;
    }
    
    public void setHealthinsuranceaccepted(String healthinsuranceaccepted) {
        this.healthinsuranceaccepted = healthinsuranceaccepted;
    }

    
    @Column(name="FRAGILEFLAG", length=1)
    public String getFragileflag() {
        return this.fragileflag;
    }
    
    public void setFragileflag(String fragileflag) {
        this.fragileflag = fragileflag;
    }

    
    @Column(name="FLAMMABLEFLAG", length=1)
    public String getFlammableflag() {
        return this.flammableflag;
    }
    
    public void setFlammableflag(String flammableflag) {
        this.flammableflag = flammableflag;
    }

    
    @Column(name="ANTIBIOTICSFLAG", length=1)
    public String getAntibioticsflag() {
        return this.antibioticsflag;
    }
    
    public void setAntibioticsflag(String antibioticsflag) {
        this.antibioticsflag = antibioticsflag;
    }

    
    @Column(name="SERUMFLAG", length=1)
    public String getSerumflag() {
        return this.serumflag;
    }
    
    public void setSerumflag(String serumflag) {
        this.serumflag = serumflag;
    }

    
    @Column(name="SPECIALAFFAIRSFLAG", length=1)
    public String getSpecialaffairsflag() {
        return this.specialaffairsflag;
    }
    
    public void setSpecialaffairsflag(String specialaffairsflag) {
        this.specialaffairsflag = specialaffairsflag;
    }

    
    @Column(name="PROCESSINGFLAG1", length=1)
    public String getProcessingflag1() {
        return this.processingflag1;
    }
    
    public void setProcessingflag1(String processingflag1) {
        this.processingflag1 = processingflag1;
    }

    
    @Column(name="PROCESSINGFLAG2", length=1)
    public String getProcessingflag2() {
        return this.processingflag2;
    }
    
    public void setProcessingflag2(String processingflag2) {
        this.processingflag2 = processingflag2;
    }

    
    @Column(name="PROCESSINGFLAG3", length=1)
    public String getProcessingflag3() {
        return this.processingflag3;
    }
    
    public void setProcessingflag3(String processingflag3) {
        this.processingflag3 = processingflag3;
    }

    
    @Column(name="PROCESSINGFLAG4", length=1)
    public String getProcessingflag4() {
        return this.processingflag4;
    }
    
    public void setProcessingflag4(String processingflag4) {
        this.processingflag4 = processingflag4;
    }

    
    @Column(name="PROCESSINGFLAG5", length=1)
    public String getProcessingflag5() {
        return this.processingflag5;
    }
    
    public void setProcessingflag5(String processingflag5) {
        this.processingflag5 = processingflag5;
    }

    
    @Column(name="PROCESSINGFLAG6", length=1)
    public String getProcessingflag6() {
        return this.processingflag6;
    }
    
    public void setProcessingflag6(String processingflag6) {
        this.processingflag6 = processingflag6;
    }

    
    @Column(name="PROCESSINGFLAG7", length=1)
    public String getProcessingflag7() {
        return this.processingflag7;
    }
    
    public void setProcessingflag7(String processingflag7) {
        this.processingflag7 = processingflag7;
    }

    
    @Column(name="PROCESSINGFLAG8", length=1)
    public String getProcessingflag8() {
        return this.processingflag8;
    }
    
    public void setProcessingflag8(String processingflag8) {
        this.processingflag8 = processingflag8;
    }

    
    @Column(name="PROCESSINGFLAG9", length=1)
    public String getProcessingflag9() {
        return this.processingflag9;
    }
    
    public void setProcessingflag9(String processingflag9) {
        this.processingflag9 = processingflag9;
    }

    
    @Column(name="PROCESSINGFLAG10", length=1)
    public String getProcessingflag10() {
        return this.processingflag10;
    }
    
    public void setProcessingflag10(String processingflag10) {
        this.processingflag10 = processingflag10;
    }

    
    @Column(name="TRANSACTIONID", length=50)
    public String getTransactionid() {
        return this.transactionid;
    }
    
    public void setTransactionid(String transactionid) {
        this.transactionid = transactionid;
    }

    
    @Column(name="RECORDPROCESSEDFLAG", length=1)
    public String getRecordprocessedflag() {
        return this.recordprocessedflag;
    }
    
    public void setRecordprocessedflag(String recordprocessedflag) {
        this.recordprocessedflag = recordprocessedflag;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="RECORDPROCESSINGTIME", length=26)
    public Date getRecordprocessingtime() {
        return this.recordprocessingtime;
    }
    
    public void setRecordprocessingtime(Date recordprocessingtime) {
        this.recordprocessingtime = recordprocessingtime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="RECORDLASTCHANGETIME", length=26)
    public Date getRecordlastchangetime() {
        return this.recordlastchangetime;
    }
    
    public void setRecordlastchangetime(Date recordlastchangetime) {
        this.recordlastchangetime = recordlastchangetime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="RECORDCREATIONTIME", nullable=false, length=26)
    public Date getRecordcreationtime() {
        return this.recordcreationtime;
    }
    
    public void setRecordcreationtime(Date recordcreationtime) {
        this.recordcreationtime = recordcreationtime;
    }

    
    @Column(name="SORTDESCDE", nullable=false, length=150)
    public String getSortdescde() {
        return this.sortdescde;
    }
    
    public void setSortdescde(String sortdescde) {
        this.sortdescde = sortdescde;
    }

    
    @Column(name="SORTDESCFR", nullable=false, length=150)
    public String getSortdescfr() {
        return this.sortdescfr;
    }
    
    public void setSortdescfr(String sortdescfr) {
        this.sortdescfr = sortdescfr;
    }

    
    @Column(name="RESPONSIBLE", nullable=false, length=10)
    public String getResponsible() {
        return this.responsible;
    }
    
    public void setResponsible(String responsible) {
        this.responsible = responsible;
    }

    
    @Column(name="PLANER", nullable=false, length=10)
    public String getPlaner() {
        return this.planer;
    }
    
    public void setPlaner(String planer) {
        this.planer = planer;
    }

    
    @Column(name="RATING", nullable=false, length=3)
    public String getRating() {
        return this.rating;
    }
    
    public void setRating(String rating) {
        this.rating = rating;
    }

    
    @Column(name="BEWIRTSCHAFTUNG_DISPLAY", nullable=false, length=2)
    public String getBewirtschaftungDisplay() {
        return this.bewirtschaftungDisplay;
    }
    
    public void setBewirtschaftungDisplay(String bewirtschaftungDisplay) {
        this.bewirtschaftungDisplay = bewirtschaftungDisplay;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="itemmaster")
    public Set<Invlin> getInvlins() {
        return this.invlins;
    }
    
    public void setInvlins(Set<Invlin> invlins) {
        this.invlins = invlins;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="itemmaster")
    public Set<Custopolin> getCustopolins() {
        return this.custopolins;
    }
    
    public void setCustopolins(Set<Custopolin> custopolins) {
        this.custopolins = custopolins;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="itemmaster")
    public Set<Retlin> getRetlins() {
        return this.retlins;
    }
    
    public void setRetlins(Set<Retlin> retlins) {
        this.retlins = retlins;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="itemmaster")
    public Set<Stockrclop> getStockrclops() {
        return this.stockrclops;
    }
    
    public void setStockrclops(Set<Stockrclop> stockrclops) {
        this.stockrclops = stockrclops;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="itemmaster")
    public Set<Itembtcm> getItembtcms() {
        return this.itembtcms;
    }
    
    public void setItembtcms(Set<Itembtcm> itembtcms) {
        this.itembtcms = itembtcms;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="itemmaster")
    public Set<Stockrcbtc> getStockrcbtcs() {
        return this.stockrcbtcs;
    }
    
    public void setStockrcbtcs(Set<Stockrcbtc> stockrcbtcs) {
        this.stockrcbtcs = stockrcbtcs;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="itemmaster")
    public Set<Stockrebtc> getStockrebtcs() {
        return this.stockrebtcs;
    }
    
    public void setStockrebtcs(Set<Stockrebtc> stockrebtcs) {
        this.stockrebtcs = stockrebtcs;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="itemmaster")
    public Set<Psilincnf> getPsilincnfs() {
        return this.psilincnfs;
    }
    
    public void setPsilincnfs(Set<Psilincnf> psilincnfs) {
        this.psilincnfs = psilincnfs;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="itemmaster")
    public Set<Invmovmnt> getInvmovmnts() {
        return this.invmovmnts;
    }
    
    public void setInvmovmnts(Set<Invmovmnt> invmovmnts) {
        this.invmovmnts = invmovmnts;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="itemmaster")
    public Set<Dellin> getDellins() {
        return this.dellins;
    }
    
    public void setDellins(Set<Dellin> dellins) {
        this.dellins = dellins;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="itemmaster")
    public Set<Grelin> getGrelins() {
        return this.grelins;
    }
    
    public void setGrelins(Set<Grelin> grelins) {
        this.grelins = grelins;
    }




}


