package com.galexis.allog2mysql.deleteme;
// Generated Sep 6, 2013 9:37:59 AM by Hibernate Tools 3.6.0


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Qddssrc generated by hbm2java
 */
@Entity
@Table(name="QDDSSRC"
    ,schema="INTEGAP"
    ,catalog="CHGALE11RDB"
)
public class Qddssrc  implements java.io.Serializable {


     private QddssrcId id;

    public Qddssrc() {
    }

    public Qddssrc(QddssrcId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="srcseq", column=@Column(name="SRCSEQ", nullable=false, precision=6) ), 
        @AttributeOverride(name="srcdat", column=@Column(name="SRCDAT", nullable=false, precision=6, scale=0) ), 
        @AttributeOverride(name="srcdta", column=@Column(name="SRCDTA", nullable=false, length=80) ) } )
    public QddssrcId getId() {
        return this.id;
    }
    
    public void setId(QddssrcId id) {
        this.id = id;
    }




}


