package com.galexis.allog2mysql.deleteme;
// Generated Sep 6, 2013 9:37:59 AM by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * QddssrcId generated by hbm2java
 */
@Embeddable
public class QddssrcId  implements java.io.Serializable {


     private BigDecimal srcseq;
     private int srcdat;
     private String srcdta;

    public QddssrcId() {
    }

    public QddssrcId(BigDecimal srcseq, int srcdat, String srcdta) {
       this.srcseq = srcseq;
       this.srcdat = srcdat;
       this.srcdta = srcdta;
    }
   


    @Column(name="SRCSEQ", nullable=false, precision=6)
    public BigDecimal getSrcseq() {
        return this.srcseq;
    }
    
    public void setSrcseq(BigDecimal srcseq) {
        this.srcseq = srcseq;
    }


    @Column(name="SRCDAT", nullable=false, precision=6, scale=0)
    public int getSrcdat() {
        return this.srcdat;
    }
    
    public void setSrcdat(int srcdat) {
        this.srcdat = srcdat;
    }


    @Column(name="SRCDTA", nullable=false, length=80)
    public String getSrcdta() {
        return this.srcdta;
    }
    
    public void setSrcdta(String srcdta) {
        this.srcdta = srcdta;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof QddssrcId) ) return false;
		 QddssrcId castOther = ( QddssrcId ) other; 
         
		 return ( (this.getSrcseq()==castOther.getSrcseq()) || ( this.getSrcseq()!=null && castOther.getSrcseq()!=null && this.getSrcseq().equals(castOther.getSrcseq()) ) )
 && (this.getSrcdat()==castOther.getSrcdat())
 && ( (this.getSrcdta()==castOther.getSrcdta()) || ( this.getSrcdta()!=null && castOther.getSrcdta()!=null && this.getSrcdta().equals(castOther.getSrcdta()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getSrcseq() == null ? 0 : this.getSrcseq().hashCode() );
         result = 37 * result + this.getSrcdat();
         result = 37 * result + ( getSrcdta() == null ? 0 : this.getSrcdta().hashCode() );
         return result;
   }   


}


