package com.galexis.allog2mysql.deleteme;
// Generated Sep 6, 2013 9:37:59 AM by Hibernate Tools 3.6.0


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Rethdri01 generated by hbm2java
 */
@Entity
@Table(name="RETHDRI01"
    ,schema="INTEGAP"
    ,catalog="CHGALE11RDB"
)
public class Rethdri01  implements java.io.Serializable {


     private Rethdri01Id id;

    public Rethdri01() {
    }

    public Rethdri01(Rethdri01Id id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="pk", column=@Column(name="PK", nullable=false, precision=12, scale=0) ), 
        @AttributeOverride(name="contrdefpk", column=@Column(name="CONTRDEFPK", nullable=false, precision=12, scale=0) ), 
        @AttributeOverride(name="incidentnr", column=@Column(name="INCIDENTNR", nullable=false, precision=12, scale=0) ), 
        @AttributeOverride(name="incidentdate", column=@Column(name="INCIDENTDATE", nullable=false, length=26) ), 
        @AttributeOverride(name="salesorganisation", column=@Column(name="SALESORGANISATION", length=30) ), 
        @AttributeOverride(name="salesorganisationdesc", column=@Column(name="SALESORGANISATIONDESC", length=50) ), 
        @AttributeOverride(name="principlereferencenr", column=@Column(name="PRINCIPLEREFERENCENR", length=35) ), 
        @AttributeOverride(name="bizparaddrpk", column=@Column(name="BIZPARADDRPK", nullable=false, precision=12, scale=0) ), 
        @AttributeOverride(name="customercontractor", column=@Column(name="CUSTOMERCONTRACTOR", length=30) ), 
        @AttributeOverride(name="problemcode", column=@Column(name="PROBLEMCODE", length=10) ), 
        @AttributeOverride(name="resolutioncode", column=@Column(name="RESOLUTIONCODE", length=10) ), 
        @AttributeOverride(name="handler", column=@Column(name="HANDLER", length=10) ), 
        @AttributeOverride(name="customerreturndate", column=@Column(name="CUSTOMERRETURNDATE", length=26) ), 
        @AttributeOverride(name="customerreference", column=@Column(name="CUSTOMERREFERENCE", length=30) ), 
        @AttributeOverride(name="typeofreference", column=@Column(name="TYPEOFREFERENCE", length=1) ), 
        @AttributeOverride(name="referencenr", column=@Column(name="REFERENCENR", precision=12, scale=0) ), 
        @AttributeOverride(name="timedatepk", column=@Column(name="TIMEDATEPK", precision=8, scale=0) ), 
        @AttributeOverride(name="ipTimedatepkReporting", column=@Column(name="IP_TIMEDATEPK_REPORTING", precision=8, scale=0) ), 
        @AttributeOverride(name="programname", column=@Column(name="PROGRAMNAME", length=10) ), 
        @AttributeOverride(name="filename", column=@Column(name="FILENAME", length=10) ), 
        @AttributeOverride(name="processingflag1", column=@Column(name="PROCESSINGFLAG1", length=1) ), 
        @AttributeOverride(name="processingflag2", column=@Column(name="PROCESSINGFLAG2", length=1) ), 
        @AttributeOverride(name="processingflag3", column=@Column(name="PROCESSINGFLAG3", length=1) ), 
        @AttributeOverride(name="processingflag4", column=@Column(name="PROCESSINGFLAG4", length=1) ), 
        @AttributeOverride(name="processingflag5", column=@Column(name="PROCESSINGFLAG5", length=1) ), 
        @AttributeOverride(name="processingflag6", column=@Column(name="PROCESSINGFLAG6", length=1) ), 
        @AttributeOverride(name="processingflag7", column=@Column(name="PROCESSINGFLAG7", length=1) ), 
        @AttributeOverride(name="processingflag8", column=@Column(name="PROCESSINGFLAG8", length=1) ), 
        @AttributeOverride(name="processingflag9", column=@Column(name="PROCESSINGFLAG9", length=1) ), 
        @AttributeOverride(name="processingflag10", column=@Column(name="PROCESSINGFLAG10", length=1) ), 
        @AttributeOverride(name="backendreleased", column=@Column(name="BACKENDRELEASED", nullable=false, length=1) ), 
        @AttributeOverride(name="outboundignore", column=@Column(name="OUTBOUNDIGNORE", nullable=false, length=1) ), 
        @AttributeOverride(name="transactionid", column=@Column(name="TRANSACTIONID", length=50) ), 
        @AttributeOverride(name="recordprocessedflag", column=@Column(name="RECORDPROCESSEDFLAG", nullable=false, length=1) ), 
        @AttributeOverride(name="recordprocessingtime", column=@Column(name="RECORDPROCESSINGTIME", length=26) ), 
        @AttributeOverride(name="recordlastchangetime", column=@Column(name="RECORDLASTCHANGETIME", length=26) ), 
        @AttributeOverride(name="recordcreationtime", column=@Column(name="RECORDCREATIONTIME", nullable=false, length=26) ) } )
    public Rethdri01Id getId() {
        return this.id;
    }
    
    public void setId(Rethdri01Id id) {
        this.id = id;
    }




}


