package com.galexis.allog2mysql.deleteme;
// Generated Sep 6, 2013 9:37:59 AM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Rethdr generated by hbm2java
 */
@Entity
@Table(name="RETHDR"
    ,schema="INTEGAP"
    ,catalog="CHGALE11RDB"
)
public class Rethdr  implements java.io.Serializable {


     private long pk;
     private Contrdef contrdef;
     private Bizparaddr bizparaddr;
     private Timedate timedateByIpTimedatepkReporting;
     private Timedate timedateByTimedatepk;
     private long incidentnr;
     private Date incidentdate;
     private String salesorganisation;
     private String salesorganisationdesc;
     private String principlereferencenr;
     private String customercontractor;
     private String problemcode;
     private String resolutioncode;
     private String handler;
     private Date customerreturndate;
     private String customerreference;
     private String typeofreference;
     private Long referencenr;
     private String programname;
     private String filename;
     private String processingflag1;
     private String processingflag2;
     private String processingflag3;
     private String processingflag4;
     private String processingflag5;
     private String processingflag6;
     private String processingflag7;
     private String processingflag8;
     private String processingflag9;
     private String processingflag10;
     private String backendreleased;
     private String outboundignore;
     private String transactionid;
     private String recordprocessedflag;
     private Date recordprocessingtime;
     private Date recordlastchangetime;
     private Date recordcreationtime;
     private Set<Retlin> retlins = new HashSet<Retlin>(0);
     private Set<Retlinbtc> retlinbtcs = new HashSet<Retlinbtc>(0);

    public Rethdr() {
    }

	
    public Rethdr(long pk, Contrdef contrdef, Bizparaddr bizparaddr, long incidentnr, Date incidentdate, String backendreleased, String outboundignore, String recordprocessedflag, Date recordcreationtime) {
        this.pk = pk;
        this.contrdef = contrdef;
        this.bizparaddr = bizparaddr;
        this.incidentnr = incidentnr;
        this.incidentdate = incidentdate;
        this.backendreleased = backendreleased;
        this.outboundignore = outboundignore;
        this.recordprocessedflag = recordprocessedflag;
        this.recordcreationtime = recordcreationtime;
    }
    public Rethdr(long pk, Contrdef contrdef, Bizparaddr bizparaddr, Timedate timedateByIpTimedatepkReporting, Timedate timedateByTimedatepk, long incidentnr, Date incidentdate, String salesorganisation, String salesorganisationdesc, String principlereferencenr, String customercontractor, String problemcode, String resolutioncode, String handler, Date customerreturndate, String customerreference, String typeofreference, Long referencenr, String programname, String filename, String processingflag1, String processingflag2, String processingflag3, String processingflag4, String processingflag5, String processingflag6, String processingflag7, String processingflag8, String processingflag9, String processingflag10, String backendreleased, String outboundignore, String transactionid, String recordprocessedflag, Date recordprocessingtime, Date recordlastchangetime, Date recordcreationtime, Set<Retlin> retlins, Set<Retlinbtc> retlinbtcs) {
       this.pk = pk;
       this.contrdef = contrdef;
       this.bizparaddr = bizparaddr;
       this.timedateByIpTimedatepkReporting = timedateByIpTimedatepkReporting;
       this.timedateByTimedatepk = timedateByTimedatepk;
       this.incidentnr = incidentnr;
       this.incidentdate = incidentdate;
       this.salesorganisation = salesorganisation;
       this.salesorganisationdesc = salesorganisationdesc;
       this.principlereferencenr = principlereferencenr;
       this.customercontractor = customercontractor;
       this.problemcode = problemcode;
       this.resolutioncode = resolutioncode;
       this.handler = handler;
       this.customerreturndate = customerreturndate;
       this.customerreference = customerreference;
       this.typeofreference = typeofreference;
       this.referencenr = referencenr;
       this.programname = programname;
       this.filename = filename;
       this.processingflag1 = processingflag1;
       this.processingflag2 = processingflag2;
       this.processingflag3 = processingflag3;
       this.processingflag4 = processingflag4;
       this.processingflag5 = processingflag5;
       this.processingflag6 = processingflag6;
       this.processingflag7 = processingflag7;
       this.processingflag8 = processingflag8;
       this.processingflag9 = processingflag9;
       this.processingflag10 = processingflag10;
       this.backendreleased = backendreleased;
       this.outboundignore = outboundignore;
       this.transactionid = transactionid;
       this.recordprocessedflag = recordprocessedflag;
       this.recordprocessingtime = recordprocessingtime;
       this.recordlastchangetime = recordlastchangetime;
       this.recordcreationtime = recordcreationtime;
       this.retlins = retlins;
       this.retlinbtcs = retlinbtcs;
    }
   
     @Id 

    
    @Column(name="PK", unique=true, nullable=false, precision=12, scale=0)
    public long getPk() {
        return this.pk;
    }
    
    public void setPk(long pk) {
        this.pk = pk;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CONTRDEFPK", nullable=false)
    public Contrdef getContrdef() {
        return this.contrdef;
    }
    
    public void setContrdef(Contrdef contrdef) {
        this.contrdef = contrdef;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="BIZPARADDRPK", nullable=false)
    public Bizparaddr getBizparaddr() {
        return this.bizparaddr;
    }
    
    public void setBizparaddr(Bizparaddr bizparaddr) {
        this.bizparaddr = bizparaddr;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IP_TIMEDATEPK_REPORTING")
    public Timedate getTimedateByIpTimedatepkReporting() {
        return this.timedateByIpTimedatepkReporting;
    }
    
    public void setTimedateByIpTimedatepkReporting(Timedate timedateByIpTimedatepkReporting) {
        this.timedateByIpTimedatepkReporting = timedateByIpTimedatepkReporting;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="TIMEDATEPK")
    public Timedate getTimedateByTimedatepk() {
        return this.timedateByTimedatepk;
    }
    
    public void setTimedateByTimedatepk(Timedate timedateByTimedatepk) {
        this.timedateByTimedatepk = timedateByTimedatepk;
    }

    
    @Column(name="INCIDENTNR", nullable=false, precision=12, scale=0)
    public long getIncidentnr() {
        return this.incidentnr;
    }
    
    public void setIncidentnr(long incidentnr) {
        this.incidentnr = incidentnr;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="INCIDENTDATE", nullable=false, length=26)
    public Date getIncidentdate() {
        return this.incidentdate;
    }
    
    public void setIncidentdate(Date incidentdate) {
        this.incidentdate = incidentdate;
    }

    
    @Column(name="SALESORGANISATION", length=30)
    public String getSalesorganisation() {
        return this.salesorganisation;
    }
    
    public void setSalesorganisation(String salesorganisation) {
        this.salesorganisation = salesorganisation;
    }

    
    @Column(name="SALESORGANISATIONDESC", length=50)
    public String getSalesorganisationdesc() {
        return this.salesorganisationdesc;
    }
    
    public void setSalesorganisationdesc(String salesorganisationdesc) {
        this.salesorganisationdesc = salesorganisationdesc;
    }

    
    @Column(name="PRINCIPLEREFERENCENR", length=35)
    public String getPrinciplereferencenr() {
        return this.principlereferencenr;
    }
    
    public void setPrinciplereferencenr(String principlereferencenr) {
        this.principlereferencenr = principlereferencenr;
    }

    
    @Column(name="CUSTOMERCONTRACTOR", length=30)
    public String getCustomercontractor() {
        return this.customercontractor;
    }
    
    public void setCustomercontractor(String customercontractor) {
        this.customercontractor = customercontractor;
    }

    
    @Column(name="PROBLEMCODE", length=10)
    public String getProblemcode() {
        return this.problemcode;
    }
    
    public void setProblemcode(String problemcode) {
        this.problemcode = problemcode;
    }

    
    @Column(name="RESOLUTIONCODE", length=10)
    public String getResolutioncode() {
        return this.resolutioncode;
    }
    
    public void setResolutioncode(String resolutioncode) {
        this.resolutioncode = resolutioncode;
    }

    
    @Column(name="HANDLER", length=10)
    public String getHandler() {
        return this.handler;
    }
    
    public void setHandler(String handler) {
        this.handler = handler;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CUSTOMERRETURNDATE", length=26)
    public Date getCustomerreturndate() {
        return this.customerreturndate;
    }
    
    public void setCustomerreturndate(Date customerreturndate) {
        this.customerreturndate = customerreturndate;
    }

    
    @Column(name="CUSTOMERREFERENCE", length=30)
    public String getCustomerreference() {
        return this.customerreference;
    }
    
    public void setCustomerreference(String customerreference) {
        this.customerreference = customerreference;
    }

    
    @Column(name="TYPEOFREFERENCE", length=1)
    public String getTypeofreference() {
        return this.typeofreference;
    }
    
    public void setTypeofreference(String typeofreference) {
        this.typeofreference = typeofreference;
    }

    
    @Column(name="REFERENCENR", precision=12, scale=0)
    public Long getReferencenr() {
        return this.referencenr;
    }
    
    public void setReferencenr(Long referencenr) {
        this.referencenr = referencenr;
    }

    
    @Column(name="PROGRAMNAME", length=10)
    public String getProgramname() {
        return this.programname;
    }
    
    public void setProgramname(String programname) {
        this.programname = programname;
    }

    
    @Column(name="FILENAME", length=10)
    public String getFilename() {
        return this.filename;
    }
    
    public void setFilename(String filename) {
        this.filename = filename;
    }

    
    @Column(name="PROCESSINGFLAG1", length=1)
    public String getProcessingflag1() {
        return this.processingflag1;
    }
    
    public void setProcessingflag1(String processingflag1) {
        this.processingflag1 = processingflag1;
    }

    
    @Column(name="PROCESSINGFLAG2", length=1)
    public String getProcessingflag2() {
        return this.processingflag2;
    }
    
    public void setProcessingflag2(String processingflag2) {
        this.processingflag2 = processingflag2;
    }

    
    @Column(name="PROCESSINGFLAG3", length=1)
    public String getProcessingflag3() {
        return this.processingflag3;
    }
    
    public void setProcessingflag3(String processingflag3) {
        this.processingflag3 = processingflag3;
    }

    
    @Column(name="PROCESSINGFLAG4", length=1)
    public String getProcessingflag4() {
        return this.processingflag4;
    }
    
    public void setProcessingflag4(String processingflag4) {
        this.processingflag4 = processingflag4;
    }

    
    @Column(name="PROCESSINGFLAG5", length=1)
    public String getProcessingflag5() {
        return this.processingflag5;
    }
    
    public void setProcessingflag5(String processingflag5) {
        this.processingflag5 = processingflag5;
    }

    
    @Column(name="PROCESSINGFLAG6", length=1)
    public String getProcessingflag6() {
        return this.processingflag6;
    }
    
    public void setProcessingflag6(String processingflag6) {
        this.processingflag6 = processingflag6;
    }

    
    @Column(name="PROCESSINGFLAG7", length=1)
    public String getProcessingflag7() {
        return this.processingflag7;
    }
    
    public void setProcessingflag7(String processingflag7) {
        this.processingflag7 = processingflag7;
    }

    
    @Column(name="PROCESSINGFLAG8", length=1)
    public String getProcessingflag8() {
        return this.processingflag8;
    }
    
    public void setProcessingflag8(String processingflag8) {
        this.processingflag8 = processingflag8;
    }

    
    @Column(name="PROCESSINGFLAG9", length=1)
    public String getProcessingflag9() {
        return this.processingflag9;
    }
    
    public void setProcessingflag9(String processingflag9) {
        this.processingflag9 = processingflag9;
    }

    
    @Column(name="PROCESSINGFLAG10", length=1)
    public String getProcessingflag10() {
        return this.processingflag10;
    }
    
    public void setProcessingflag10(String processingflag10) {
        this.processingflag10 = processingflag10;
    }

    
    @Column(name="BACKENDRELEASED", nullable=false, length=1)
    public String getBackendreleased() {
        return this.backendreleased;
    }
    
    public void setBackendreleased(String backendreleased) {
        this.backendreleased = backendreleased;
    }

    
    @Column(name="OUTBOUNDIGNORE", nullable=false, length=1)
    public String getOutboundignore() {
        return this.outboundignore;
    }
    
    public void setOutboundignore(String outboundignore) {
        this.outboundignore = outboundignore;
    }

    
    @Column(name="TRANSACTIONID", length=50)
    public String getTransactionid() {
        return this.transactionid;
    }
    
    public void setTransactionid(String transactionid) {
        this.transactionid = transactionid;
    }

    
    @Column(name="RECORDPROCESSEDFLAG", nullable=false, length=1)
    public String getRecordprocessedflag() {
        return this.recordprocessedflag;
    }
    
    public void setRecordprocessedflag(String recordprocessedflag) {
        this.recordprocessedflag = recordprocessedflag;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="RECORDPROCESSINGTIME", length=26)
    public Date getRecordprocessingtime() {
        return this.recordprocessingtime;
    }
    
    public void setRecordprocessingtime(Date recordprocessingtime) {
        this.recordprocessingtime = recordprocessingtime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="RECORDLASTCHANGETIME", length=26)
    public Date getRecordlastchangetime() {
        return this.recordlastchangetime;
    }
    
    public void setRecordlastchangetime(Date recordlastchangetime) {
        this.recordlastchangetime = recordlastchangetime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="RECORDCREATIONTIME", nullable=false, length=26)
    public Date getRecordcreationtime() {
        return this.recordcreationtime;
    }
    
    public void setRecordcreationtime(Date recordcreationtime) {
        this.recordcreationtime = recordcreationtime;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="rethdr")
    public Set<Retlin> getRetlins() {
        return this.retlins;
    }
    
    public void setRetlins(Set<Retlin> retlins) {
        this.retlins = retlins;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="rethdr")
    public Set<Retlinbtc> getRetlinbtcs() {
        return this.retlinbtcs;
    }
    
    public void setRetlinbtcs(Set<Retlinbtc> retlinbtcs) {
        this.retlinbtcs = retlinbtcs;
    }




}


