package com.galexis.allog2mysql.deleteme;
// Generated Sep 6, 2013 9:37:59 AM by Hibernate Tools 3.6.0


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Retlinbi01 generated by hbm2java
 */
@Entity
@Table(name="RETLINBI01"
    ,schema="INTEGAP"
    ,catalog="CHGALE11RDB"
)
public class Retlinbi01  implements java.io.Serializable {


     private Retlinbi01Id id;

    public Retlinbi01() {
    }

    public Retlinbi01(Retlinbi01Id id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="pk", column=@Column(name="PK", nullable=false, precision=12, scale=0) ), 
        @AttributeOverride(name="retlinpk", column=@Column(name="RETLINPK", nullable=false, precision=12, scale=0) ), 
        @AttributeOverride(name="rethdrpk", column=@Column(name="RETHDRPK", nullable=false, precision=12, scale=0) ), 
        @AttributeOverride(name="incidentlineseq", column=@Column(name="INCIDENTLINESEQ", nullable=false, precision=3, scale=0) ), 
        @AttributeOverride(name="itemnrcontractor", column=@Column(name="ITEMNRCONTRACTOR", length=35) ), 
        @AttributeOverride(name="batchqty", column=@Column(name="BATCHQTY", precision=15, scale=3) ), 
        @AttributeOverride(name="approvedqty", column=@Column(name="APPROVEDQTY", precision=15, scale=3) ), 
        @AttributeOverride(name="rejectedqty", column=@Column(name="REJECTEDQTY", precision=15, scale=3) ), 
        @AttributeOverride(name="batchid", column=@Column(name="BATCHID", length=20) ), 
        @AttributeOverride(name="batchexpirydate", column=@Column(name="BATCHEXPIRYDATE", length=26) ), 
        @AttributeOverride(name="serialnr", column=@Column(name="SERIALNR", length=30) ), 
        @AttributeOverride(name="batchidcontractor", column=@Column(name="BATCHIDCONTRACTOR", length=20) ), 
        @AttributeOverride(name="batchrecallnr", column=@Column(name="BATCHRECALLNR", precision=12, scale=0) ), 
        @AttributeOverride(name="whs", column=@Column(name="WHS", length=10) ), 
        @AttributeOverride(name="zone", column=@Column(name="ZONE", length=10) ), 
        @AttributeOverride(name="location", column=@Column(name="LOCATION", length=10) ), 
        @AttributeOverride(name="stockstatus", column=@Column(name="STOCKSTATUS", length=10) ), 
        @AttributeOverride(name="qualitycontrolflag", column=@Column(name="QUALITYCONTROLFLAG", length=1) ), 
        @AttributeOverride(name="ipWarehouse", column=@Column(name="IP_WAREHOUSE", precision=5, scale=0) ), 
        @AttributeOverride(name="ipLocationzone", column=@Column(name="IP_LOCATIONZONE", precision=5, scale=0) ), 
        @AttributeOverride(name="ipStockcategory", column=@Column(name="IP_STOCKCATEGORY", precision=5, scale=0) ), 
        @AttributeOverride(name="programname", column=@Column(name="PROGRAMNAME", length=10) ), 
        @AttributeOverride(name="filename", column=@Column(name="FILENAME", length=10) ), 
        @AttributeOverride(name="processingflag1", column=@Column(name="PROCESSINGFLAG1", length=1) ), 
        @AttributeOverride(name="processingflag2", column=@Column(name="PROCESSINGFLAG2", length=1) ), 
        @AttributeOverride(name="processingflag3", column=@Column(name="PROCESSINGFLAG3", length=1) ), 
        @AttributeOverride(name="processingflag4", column=@Column(name="PROCESSINGFLAG4", length=1) ), 
        @AttributeOverride(name="processingflag5", column=@Column(name="PROCESSINGFLAG5", length=1) ), 
        @AttributeOverride(name="processingflag6", column=@Column(name="PROCESSINGFLAG6", length=1) ), 
        @AttributeOverride(name="processingflag7", column=@Column(name="PROCESSINGFLAG7", length=1) ), 
        @AttributeOverride(name="processingflag8", column=@Column(name="PROCESSINGFLAG8", length=1) ), 
        @AttributeOverride(name="processingflag9", column=@Column(name="PROCESSINGFLAG9", length=1) ), 
        @AttributeOverride(name="processingflag10", column=@Column(name="PROCESSINGFLAG10", length=1) ), 
        @AttributeOverride(name="outboundignore", column=@Column(name="OUTBOUNDIGNORE", nullable=false, length=1) ), 
        @AttributeOverride(name="recordlastchangetime", column=@Column(name="RECORDLASTCHANGETIME", length=26) ), 
        @AttributeOverride(name="recordcreationtime", column=@Column(name="RECORDCREATIONTIME", nullable=false, length=26) ) } )
    public Retlinbi01Id getId() {
        return this.id;
    }
    
    public void setId(Retlinbi01Id id) {
        this.id = id;
    }




}


