package com.galexis.allog2mysql.deleteme;
// Generated Sep 6, 2013 9:37:59 AM by Hibernate Tools 3.6.0


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Retlinbtc generated by hbm2java
 */
@Entity
@Table(name="RETLINBTC"
    ,schema="INTEGAP"
    ,catalog="CHGALE11RDB"
    , uniqueConstraints = @UniqueConstraint(columnNames="PK") 
)
public class Retlinbtc  implements java.io.Serializable {


     private RetlinbtcId id;
     private Retlin retlin;
     private Rethdr rethdr;

    public Retlinbtc() {
    }

    public Retlinbtc(RetlinbtcId id, Retlin retlin, Rethdr rethdr) {
       this.id = id;
       this.retlin = retlin;
       this.rethdr = rethdr;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="pk", column=@Column(name="PK", unique=true, nullable=false, precision=12, scale=0) ), 
        @AttributeOverride(name="retlinpk", column=@Column(name="RETLINPK", nullable=false, precision=12, scale=0) ), 
        @AttributeOverride(name="rethdrpk", column=@Column(name="RETHDRPK", nullable=false, precision=12, scale=0) ), 
        @AttributeOverride(name="incidentlineseq", column=@Column(name="INCIDENTLINESEQ", nullable=false, precision=3, scale=0) ), 
        @AttributeOverride(name="itemnrcontractor", column=@Column(name="ITEMNRCONTRACTOR", length=35) ), 
        @AttributeOverride(name="batchqty", column=@Column(name="BATCHQTY", precision=15, scale=3) ), 
        @AttributeOverride(name="approvedqty", column=@Column(name="APPROVEDQTY", precision=15, scale=3) ), 
        @AttributeOverride(name="rejectedqty", column=@Column(name="REJECTEDQTY", precision=15, scale=3) ), 
        @AttributeOverride(name="batchid", column=@Column(name="BATCHID", length=20) ), 
        @AttributeOverride(name="batchexpirydate", column=@Column(name="BATCHEXPIRYDATE", length=26) ), 
        @AttributeOverride(name="serialnr", column=@Column(name="SERIALNR", length=30) ), 
        @AttributeOverride(name="batchidcontractor", column=@Column(name="BATCHIDCONTRACTOR", length=20) ), 
        @AttributeOverride(name="batchrecallnr", column=@Column(name="BATCHRECALLNR", precision=12, scale=0) ), 
        @AttributeOverride(name="whs", column=@Column(name="WHS", length=10) ), 
        @AttributeOverride(name="zone", column=@Column(name="ZONE", length=10) ), 
        @AttributeOverride(name="location", column=@Column(name="LOCATION", length=10) ), 
        @AttributeOverride(name="stockstatus", column=@Column(name="STOCKSTATUS", length=10) ), 
        @AttributeOverride(name="qualitycontrolflag", column=@Column(name="QUALITYCONTROLFLAG", length=1) ), 
        @AttributeOverride(name="ipWarehouse", column=@Column(name="IP_WAREHOUSE", precision=5, scale=0) ), 
        @AttributeOverride(name="ipLocationzone", column=@Column(name="IP_LOCATIONZONE", precision=5, scale=0) ), 
        @AttributeOverride(name="ipStockcategory", column=@Column(name="IP_STOCKCATEGORY", precision=5, scale=0) ), 
        @AttributeOverride(name="programname", column=@Column(name="PROGRAMNAME", length=10) ), 
        @AttributeOverride(name="filename", column=@Column(name="FILENAME", length=10) ), 
        @AttributeOverride(name="processingflag1", column=@Column(name="PROCESSINGFLAG1", length=1) ), 
        @AttributeOverride(name="processingflag2", column=@Column(name="PROCESSINGFLAG2", length=1) ), 
        @AttributeOverride(name="processingflag3", column=@Column(name="PROCESSINGFLAG3", length=1) ), 
        @AttributeOverride(name="processingflag4", column=@Column(name="PROCESSINGFLAG4", length=1) ), 
        @AttributeOverride(name="processingflag5", column=@Column(name="PROCESSINGFLAG5", length=1) ), 
        @AttributeOverride(name="processingflag6", column=@Column(name="PROCESSINGFLAG6", length=1) ), 
        @AttributeOverride(name="processingflag7", column=@Column(name="PROCESSINGFLAG7", length=1) ), 
        @AttributeOverride(name="processingflag8", column=@Column(name="PROCESSINGFLAG8", length=1) ), 
        @AttributeOverride(name="processingflag9", column=@Column(name="PROCESSINGFLAG9", length=1) ), 
        @AttributeOverride(name="processingflag10", column=@Column(name="PROCESSINGFLAG10", length=1) ), 
        @AttributeOverride(name="outboundignore", column=@Column(name="OUTBOUNDIGNORE", nullable=false, length=1) ), 
        @AttributeOverride(name="recordlastchangetime", column=@Column(name="RECORDLASTCHANGETIME", length=26) ), 
        @AttributeOverride(name="recordcreationtime", column=@Column(name="RECORDCREATIONTIME", nullable=false, length=26) ) } )
    public RetlinbtcId getId() {
        return this.id;
    }
    
    public void setId(RetlinbtcId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="RETLINPK", nullable=false, insertable=false, updatable=false)
    public Retlin getRetlin() {
        return this.retlin;
    }
    
    public void setRetlin(Retlin retlin) {
        this.retlin = retlin;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="RETHDRPK", nullable=false, insertable=false, updatable=false)
    public Rethdr getRethdr() {
        return this.rethdr;
    }
    
    public void setRethdr(Rethdr rethdr) {
        this.rethdr = rethdr;
    }




}


