package com.galexis.allog2mysql.deleteme;
// Generated Sep 6, 2013 9:37:59 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Version;

/**
 * Selmsgtdef generated by hbm2java
 */
@Entity
@Table(name="SELMSGTDEF"
    ,schema="INTEGAP"
    ,catalog="CHGALE11RDB"
)
public class Selmsgtdef  implements java.io.Serializable {


     private long pk;
     private String version;
     private Jobdef jobdef;
     private String name;
     private short sequence;
     private Set<Selstcelem> selstcelems = new HashSet<Selstcelem>(0);

    public Selmsgtdef() {
    }

	
    public Selmsgtdef(long pk, Jobdef jobdef, String name, short sequence) {
        this.pk = pk;
        this.jobdef = jobdef;
        this.name = name;
        this.sequence = sequence;
    }
    public Selmsgtdef(long pk, Jobdef jobdef, String name, short sequence, Set<Selstcelem> selstcelems) {
       this.pk = pk;
       this.jobdef = jobdef;
       this.name = name;
       this.sequence = sequence;
       this.selstcelems = selstcelems;
    }
   
     @Id 

    
    @Column(name="PK", unique=true, nullable=false, precision=12, scale=0)
    public long getPk() {
        return this.pk;
    }
    
    public void setPk(long pk) {
        this.pk = pk;
    }

    @Version
    @Column(name="VERSION", nullable=false, length=8)
    public String getVersion() {
        return this.version;
    }
    
    public void setVersion(String version) {
        this.version = version;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="JOBDEFPK", nullable=false)
    public Jobdef getJobdef() {
        return this.jobdef;
    }
    
    public void setJobdef(Jobdef jobdef) {
        this.jobdef = jobdef;
    }

    
    @Column(name="NAME", nullable=false)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="SEQUENCE", nullable=false, precision=4, scale=0)
    public short getSequence() {
        return this.sequence;
    }
    
    public void setSequence(short sequence) {
        this.sequence = sequence;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="selmsgtdef")
    public Set<Selstcelem> getSelstcelems() {
        return this.selstcelems;
    }
    
    public void setSelstcelems(Set<Selstcelem> selstcelems) {
        this.selstcelems = selstcelems;
    }




}


