package com.galexis.allog2mysql.deleteme;
// Generated Sep 6, 2013 9:37:59 AM by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Selstcattr generated by hbm2java
 */
@Entity
@Table(name="SELSTCATTR"
    ,schema="INTEGAP"
    ,catalog="CHGALE11RDB"
)
public class Selstcattr  implements java.io.Serializable {


     private long pk;
     private Selstcelem selstcelem;
     private String name;
     private String value;

    public Selstcattr() {
    }

	
    public Selstcattr(long pk, String name, String value) {
        this.pk = pk;
        this.name = name;
        this.value = value;
    }
    public Selstcattr(long pk, Selstcelem selstcelem, String name, String value) {
       this.pk = pk;
       this.selstcelem = selstcelem;
       this.name = name;
       this.value = value;
    }
   
     @Id 

    
    @Column(name="PK", unique=true, nullable=false, precision=12, scale=0)
    public long getPk() {
        return this.pk;
    }
    
    public void setPk(long pk) {
        this.pk = pk;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="SELSTCELEMPK")
    public Selstcelem getSelstcelem() {
        return this.selstcelem;
    }
    
    public void setSelstcelem(Selstcelem selstcelem) {
        this.selstcelem = selstcelem;
    }

    
    @Column(name="NAME", nullable=false)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="VALUE", nullable=false, length=2048)
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }




}


