package com.galexis.allog2mysql.deleteme;
// Generated Sep 6, 2013 9:37:59 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Version;

/**
 * Selstcelem generated by hbm2java
 */
@Entity
@Table(name="SELSTCELEM"
    ,schema="INTEGAP"
    ,catalog="CHGALE11RDB"
)
public class Selstcelem  implements java.io.Serializable {


     private long pk;
     private String version;
     private Selstcelem selstcelem;
     private Selmsgtdef selmsgtdef;
     private String name;
     private String token;
     private String value;
     private Set<Jobdef> jobdefs = new HashSet<Jobdef>(0);
     private Set<Selstcattr> selstcattrs = new HashSet<Selstcattr>(0);
     private Set<Selstcelem> selstcelems = new HashSet<Selstcelem>(0);

    public Selstcelem() {
    }

	
    public Selstcelem(long pk, String name, String token, String value) {
        this.pk = pk;
        this.name = name;
        this.token = token;
        this.value = value;
    }
    public Selstcelem(long pk, Selstcelem selstcelem, Selmsgtdef selmsgtdef, String name, String token, String value, Set<Jobdef> jobdefs, Set<Selstcattr> selstcattrs, Set<Selstcelem> selstcelems) {
       this.pk = pk;
       this.selstcelem = selstcelem;
       this.selmsgtdef = selmsgtdef;
       this.name = name;
       this.token = token;
       this.value = value;
       this.jobdefs = jobdefs;
       this.selstcattrs = selstcattrs;
       this.selstcelems = selstcelems;
    }
   
     @Id 

    
    @Column(name="PK", unique=true, nullable=false, precision=12, scale=0)
    public long getPk() {
        return this.pk;
    }
    
    public void setPk(long pk) {
        this.pk = pk;
    }

    @Version
    @Column(name="VERSION", nullable=false, length=8)
    public String getVersion() {
        return this.version;
    }
    
    public void setVersion(String version) {
        this.version = version;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="SELSTCELEMPK")
    public Selstcelem getSelstcelem() {
        return this.selstcelem;
    }
    
    public void setSelstcelem(Selstcelem selstcelem) {
        this.selstcelem = selstcelem;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="SELMSGTDEFPK")
    public Selmsgtdef getSelmsgtdef() {
        return this.selmsgtdef;
    }
    
    public void setSelmsgtdef(Selmsgtdef selmsgtdef) {
        this.selmsgtdef = selmsgtdef;
    }

    
    @Column(name="NAME", nullable=false)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="TOKEN", nullable=false)
    public String getToken() {
        return this.token;
    }
    
    public void setToken(String token) {
        this.token = token;
    }

    
    @Column(name="VALUE", nullable=false, length=2048)
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="selstcelem")
    public Set<Jobdef> getJobdefs() {
        return this.jobdefs;
    }
    
    public void setJobdefs(Set<Jobdef> jobdefs) {
        this.jobdefs = jobdefs;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="selstcelem")
    public Set<Selstcattr> getSelstcattrs() {
        return this.selstcattrs;
    }
    
    public void setSelstcattrs(Set<Selstcattr> selstcattrs) {
        this.selstcattrs = selstcattrs;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="selstcelem")
    public Set<Selstcelem> getSelstcelems() {
        return this.selstcelems;
    }
    
    public void setSelstcelems(Set<Selstcelem> selstcelems) {
        this.selstcelems = selstcelems;
    }




}


