package com.galexis.allog2mysql.deleteme;
// Generated Sep 6, 2013 9:37:59 AM by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Stockrclop generated by hbm2java
 */
@Entity
@Table(name="STOCKRCLOP"
    ,schema="INTEGAP"
    ,catalog="CHGALE11RDB"
)
public class Stockrclop  implements java.io.Serializable {


     private long pk;
     private Contrdef contrdef;
     private Itemmaster itemmaster;
     private Timedate timedateByIpTimedatepkReporting;
     private Stockrcmap stockrcmap;
     private Timedate timedateByTimedatepk;
     private Date extractiondate;
     private String itemnr;
     private String itemnrcontractor;
     private String batchid;
     private Date batchsellbydate;
     private Date batchexpirydate;
     private String batchidcontractor;
     private String whs;
     private String zone;
     private String location;
     private BigDecimal locationqty;
     private BigDecimal reservedforpickqty;
     private String locationstockstatus;
     private String qualitycontrolflag;
     private BigDecimal palletnr;
     private Long nccnr;
     private String stockkeepingunit;
     private String heldbalanceflag;
     private Long stocktakelistnr;
     private Short pickpriority;
     private String locationtype;
     private String locationsize;
     private String locationgroup;
     private String reportingstockstatus;
     private String reasoncodeNcc;
     private String reasoncodedescNcc;
     private String batchreasoncode;
     private String serialnr;
     private Integer ipWarehouse;
     private Integer ipLocationzone;
     private Integer ipStockcategory;
     private String ipIsavailablestock;
     private String ipIsstockonhand;
     private String ipIsdestructionstock;
     private String ipContractorPlant;
     private String ipContractorStoragelocation;
     private String ipContractorStockstatus;
     private Short ipContractorReportcolumn;
     private Integer ipStockkey;
     private String programname;
     private String filename;
     private String processingflag1;
     private String processingflag2;
     private String processingflag3;
     private String processingflag4;
     private String processingflag5;
     private String processingflag6;
     private String processingflag7;
     private String processingflag8;
     private String processingflag9;
     private String processingflag10;
     private String backendreleased;
     private String outboundignore;
     private String transactionid;
     private String recordprocessedflag;
     private Date recordprocessingtime;
     private Date recordlastchangetime;
     private Date recordcreationtime;

    public Stockrclop() {
    }

	
    public Stockrclop(long pk, Contrdef contrdef, Itemmaster itemmaster, Date extractiondate, String itemnr, String backendreleased, String outboundignore, String recordprocessedflag, Date recordcreationtime) {
        this.pk = pk;
        this.contrdef = contrdef;
        this.itemmaster = itemmaster;
        this.extractiondate = extractiondate;
        this.itemnr = itemnr;
        this.backendreleased = backendreleased;
        this.outboundignore = outboundignore;
        this.recordprocessedflag = recordprocessedflag;
        this.recordcreationtime = recordcreationtime;
    }
    public Stockrclop(long pk, Contrdef contrdef, Itemmaster itemmaster, Timedate timedateByIpTimedatepkReporting, Stockrcmap stockrcmap, Timedate timedateByTimedatepk, Date extractiondate, String itemnr, String itemnrcontractor, String batchid, Date batchsellbydate, Date batchexpirydate, String batchidcontractor, String whs, String zone, String location, BigDecimal locationqty, BigDecimal reservedforpickqty, String locationstockstatus, String qualitycontrolflag, BigDecimal palletnr, Long nccnr, String stockkeepingunit, String heldbalanceflag, Long stocktakelistnr, Short pickpriority, String locationtype, String locationsize, String locationgroup, String reportingstockstatus, String reasoncodeNcc, String reasoncodedescNcc, String batchreasoncode, String serialnr, Integer ipWarehouse, Integer ipLocationzone, Integer ipStockcategory, String ipIsavailablestock, String ipIsstockonhand, String ipIsdestructionstock, String ipContractorPlant, String ipContractorStoragelocation, String ipContractorStockstatus, Short ipContractorReportcolumn, Integer ipStockkey, String programname, String filename, String processingflag1, String processingflag2, String processingflag3, String processingflag4, String processingflag5, String processingflag6, String processingflag7, String processingflag8, String processingflag9, String processingflag10, String backendreleased, String outboundignore, String transactionid, String recordprocessedflag, Date recordprocessingtime, Date recordlastchangetime, Date recordcreationtime) {
       this.pk = pk;
       this.contrdef = contrdef;
       this.itemmaster = itemmaster;
       this.timedateByIpTimedatepkReporting = timedateByIpTimedatepkReporting;
       this.stockrcmap = stockrcmap;
       this.timedateByTimedatepk = timedateByTimedatepk;
       this.extractiondate = extractiondate;
       this.itemnr = itemnr;
       this.itemnrcontractor = itemnrcontractor;
       this.batchid = batchid;
       this.batchsellbydate = batchsellbydate;
       this.batchexpirydate = batchexpirydate;
       this.batchidcontractor = batchidcontractor;
       this.whs = whs;
       this.zone = zone;
       this.location = location;
       this.locationqty = locationqty;
       this.reservedforpickqty = reservedforpickqty;
       this.locationstockstatus = locationstockstatus;
       this.qualitycontrolflag = qualitycontrolflag;
       this.palletnr = palletnr;
       this.nccnr = nccnr;
       this.stockkeepingunit = stockkeepingunit;
       this.heldbalanceflag = heldbalanceflag;
       this.stocktakelistnr = stocktakelistnr;
       this.pickpriority = pickpriority;
       this.locationtype = locationtype;
       this.locationsize = locationsize;
       this.locationgroup = locationgroup;
       this.reportingstockstatus = reportingstockstatus;
       this.reasoncodeNcc = reasoncodeNcc;
       this.reasoncodedescNcc = reasoncodedescNcc;
       this.batchreasoncode = batchreasoncode;
       this.serialnr = serialnr;
       this.ipWarehouse = ipWarehouse;
       this.ipLocationzone = ipLocationzone;
       this.ipStockcategory = ipStockcategory;
       this.ipIsavailablestock = ipIsavailablestock;
       this.ipIsstockonhand = ipIsstockonhand;
       this.ipIsdestructionstock = ipIsdestructionstock;
       this.ipContractorPlant = ipContractorPlant;
       this.ipContractorStoragelocation = ipContractorStoragelocation;
       this.ipContractorStockstatus = ipContractorStockstatus;
       this.ipContractorReportcolumn = ipContractorReportcolumn;
       this.ipStockkey = ipStockkey;
       this.programname = programname;
       this.filename = filename;
       this.processingflag1 = processingflag1;
       this.processingflag2 = processingflag2;
       this.processingflag3 = processingflag3;
       this.processingflag4 = processingflag4;
       this.processingflag5 = processingflag5;
       this.processingflag6 = processingflag6;
       this.processingflag7 = processingflag7;
       this.processingflag8 = processingflag8;
       this.processingflag9 = processingflag9;
       this.processingflag10 = processingflag10;
       this.backendreleased = backendreleased;
       this.outboundignore = outboundignore;
       this.transactionid = transactionid;
       this.recordprocessedflag = recordprocessedflag;
       this.recordprocessingtime = recordprocessingtime;
       this.recordlastchangetime = recordlastchangetime;
       this.recordcreationtime = recordcreationtime;
    }
   
     @Id 

    
    @Column(name="PK", unique=true, nullable=false, precision=12, scale=0)
    public long getPk() {
        return this.pk;
    }
    
    public void setPk(long pk) {
        this.pk = pk;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CONTRDEFPK", nullable=false)
    public Contrdef getContrdef() {
        return this.contrdef;
    }
    
    public void setContrdef(Contrdef contrdef) {
        this.contrdef = contrdef;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ITEMMASTERPK", nullable=false)
    public Itemmaster getItemmaster() {
        return this.itemmaster;
    }
    
    public void setItemmaster(Itemmaster itemmaster) {
        this.itemmaster = itemmaster;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IP_TIMEDATEPK_REPORTING")
    public Timedate getTimedateByIpTimedatepkReporting() {
        return this.timedateByIpTimedatepkReporting;
    }
    
    public void setTimedateByIpTimedatepkReporting(Timedate timedateByIpTimedatepkReporting) {
        this.timedateByIpTimedatepkReporting = timedateByIpTimedatepkReporting;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="STOCKRCMAPPK")
    public Stockrcmap getStockrcmap() {
        return this.stockrcmap;
    }
    
    public void setStockrcmap(Stockrcmap stockrcmap) {
        this.stockrcmap = stockrcmap;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="TIMEDATEPK")
    public Timedate getTimedateByTimedatepk() {
        return this.timedateByTimedatepk;
    }
    
    public void setTimedateByTimedatepk(Timedate timedateByTimedatepk) {
        this.timedateByTimedatepk = timedateByTimedatepk;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="EXTRACTIONDATE", nullable=false, length=26)
    public Date getExtractiondate() {
        return this.extractiondate;
    }
    
    public void setExtractiondate(Date extractiondate) {
        this.extractiondate = extractiondate;
    }

    
    @Column(name="ITEMNR", nullable=false, length=35)
    public String getItemnr() {
        return this.itemnr;
    }
    
    public void setItemnr(String itemnr) {
        this.itemnr = itemnr;
    }

    
    @Column(name="ITEMNRCONTRACTOR", length=35)
    public String getItemnrcontractor() {
        return this.itemnrcontractor;
    }
    
    public void setItemnrcontractor(String itemnrcontractor) {
        this.itemnrcontractor = itemnrcontractor;
    }

    
    @Column(name="BATCHID", length=20)
    public String getBatchid() {
        return this.batchid;
    }
    
    public void setBatchid(String batchid) {
        this.batchid = batchid;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="BATCHSELLBYDATE", length=26)
    public Date getBatchsellbydate() {
        return this.batchsellbydate;
    }
    
    public void setBatchsellbydate(Date batchsellbydate) {
        this.batchsellbydate = batchsellbydate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="BATCHEXPIRYDATE", length=26)
    public Date getBatchexpirydate() {
        return this.batchexpirydate;
    }
    
    public void setBatchexpirydate(Date batchexpirydate) {
        this.batchexpirydate = batchexpirydate;
    }

    
    @Column(name="BATCHIDCONTRACTOR", length=20)
    public String getBatchidcontractor() {
        return this.batchidcontractor;
    }
    
    public void setBatchidcontractor(String batchidcontractor) {
        this.batchidcontractor = batchidcontractor;
    }

    
    @Column(name="WHS", length=10)
    public String getWhs() {
        return this.whs;
    }
    
    public void setWhs(String whs) {
        this.whs = whs;
    }

    
    @Column(name="ZONE", length=10)
    public String getZone() {
        return this.zone;
    }
    
    public void setZone(String zone) {
        this.zone = zone;
    }

    
    @Column(name="LOCATION", length=10)
    public String getLocation() {
        return this.location;
    }
    
    public void setLocation(String location) {
        this.location = location;
    }

    
    @Column(name="LOCATIONQTY", precision=15, scale=3)
    public BigDecimal getLocationqty() {
        return this.locationqty;
    }
    
    public void setLocationqty(BigDecimal locationqty) {
        this.locationqty = locationqty;
    }

    
    @Column(name="RESERVEDFORPICKQTY", precision=15, scale=3)
    public BigDecimal getReservedforpickqty() {
        return this.reservedforpickqty;
    }
    
    public void setReservedforpickqty(BigDecimal reservedforpickqty) {
        this.reservedforpickqty = reservedforpickqty;
    }

    
    @Column(name="LOCATIONSTOCKSTATUS", length=10)
    public String getLocationstockstatus() {
        return this.locationstockstatus;
    }
    
    public void setLocationstockstatus(String locationstockstatus) {
        this.locationstockstatus = locationstockstatus;
    }

    
    @Column(name="QUALITYCONTROLFLAG", length=1)
    public String getQualitycontrolflag() {
        return this.qualitycontrolflag;
    }
    
    public void setQualitycontrolflag(String qualitycontrolflag) {
        this.qualitycontrolflag = qualitycontrolflag;
    }

    
    @Column(name="PALLETNR", precision=30, scale=0)
    public BigDecimal getPalletnr() {
        return this.palletnr;
    }
    
    public void setPalletnr(BigDecimal palletnr) {
        this.palletnr = palletnr;
    }

    
    @Column(name="NCCNR", precision=12, scale=0)
    public Long getNccnr() {
        return this.nccnr;
    }
    
    public void setNccnr(Long nccnr) {
        this.nccnr = nccnr;
    }

    
    @Column(name="STOCKKEEPINGUNIT", length=5)
    public String getStockkeepingunit() {
        return this.stockkeepingunit;
    }
    
    public void setStockkeepingunit(String stockkeepingunit) {
        this.stockkeepingunit = stockkeepingunit;
    }

    
    @Column(name="HELDBALANCEFLAG", length=1)
    public String getHeldbalanceflag() {
        return this.heldbalanceflag;
    }
    
    public void setHeldbalanceflag(String heldbalanceflag) {
        this.heldbalanceflag = heldbalanceflag;
    }

    
    @Column(name="STOCKTAKELISTNR", precision=12, scale=0)
    public Long getStocktakelistnr() {
        return this.stocktakelistnr;
    }
    
    public void setStocktakelistnr(Long stocktakelistnr) {
        this.stocktakelistnr = stocktakelistnr;
    }

    
    @Column(name="PICKPRIORITY", precision=3, scale=0)
    public Short getPickpriority() {
        return this.pickpriority;
    }
    
    public void setPickpriority(Short pickpriority) {
        this.pickpriority = pickpriority;
    }

    
    @Column(name="LOCATIONTYPE", length=10)
    public String getLocationtype() {
        return this.locationtype;
    }
    
    public void setLocationtype(String locationtype) {
        this.locationtype = locationtype;
    }

    
    @Column(name="LOCATIONSIZE", length=10)
    public String getLocationsize() {
        return this.locationsize;
    }
    
    public void setLocationsize(String locationsize) {
        this.locationsize = locationsize;
    }

    
    @Column(name="LOCATIONGROUP", length=10)
    public String getLocationgroup() {
        return this.locationgroup;
    }
    
    public void setLocationgroup(String locationgroup) {
        this.locationgroup = locationgroup;
    }

    
    @Column(name="REPORTINGSTOCKSTATUS", length=10)
    public String getReportingstockstatus() {
        return this.reportingstockstatus;
    }
    
    public void setReportingstockstatus(String reportingstockstatus) {
        this.reportingstockstatus = reportingstockstatus;
    }

    
    @Column(name="REASONCODE_NCC", length=3)
    public String getReasoncodeNcc() {
        return this.reasoncodeNcc;
    }
    
    public void setReasoncodeNcc(String reasoncodeNcc) {
        this.reasoncodeNcc = reasoncodeNcc;
    }

    
    @Column(name="REASONCODEDESC_NCC", length=50)
    public String getReasoncodedescNcc() {
        return this.reasoncodedescNcc;
    }
    
    public void setReasoncodedescNcc(String reasoncodedescNcc) {
        this.reasoncodedescNcc = reasoncodedescNcc;
    }

    
    @Column(name="BATCHREASONCODE", length=5)
    public String getBatchreasoncode() {
        return this.batchreasoncode;
    }
    
    public void setBatchreasoncode(String batchreasoncode) {
        this.batchreasoncode = batchreasoncode;
    }

    
    @Column(name="SERIALNR", length=30)
    public String getSerialnr() {
        return this.serialnr;
    }
    
    public void setSerialnr(String serialnr) {
        this.serialnr = serialnr;
    }

    
    @Column(name="IP_WAREHOUSE", precision=5, scale=0)
    public Integer getIpWarehouse() {
        return this.ipWarehouse;
    }
    
    public void setIpWarehouse(Integer ipWarehouse) {
        this.ipWarehouse = ipWarehouse;
    }

    
    @Column(name="IP_LOCATIONZONE", precision=5, scale=0)
    public Integer getIpLocationzone() {
        return this.ipLocationzone;
    }
    
    public void setIpLocationzone(Integer ipLocationzone) {
        this.ipLocationzone = ipLocationzone;
    }

    
    @Column(name="IP_STOCKCATEGORY", precision=5, scale=0)
    public Integer getIpStockcategory() {
        return this.ipStockcategory;
    }
    
    public void setIpStockcategory(Integer ipStockcategory) {
        this.ipStockcategory = ipStockcategory;
    }

    
    @Column(name="IP_ISAVAILABLESTOCK", length=1)
    public String getIpIsavailablestock() {
        return this.ipIsavailablestock;
    }
    
    public void setIpIsavailablestock(String ipIsavailablestock) {
        this.ipIsavailablestock = ipIsavailablestock;
    }

    
    @Column(name="IP_ISSTOCKONHAND", length=1)
    public String getIpIsstockonhand() {
        return this.ipIsstockonhand;
    }
    
    public void setIpIsstockonhand(String ipIsstockonhand) {
        this.ipIsstockonhand = ipIsstockonhand;
    }

    
    @Column(name="IP_ISDESTRUCTIONSTOCK", length=1)
    public String getIpIsdestructionstock() {
        return this.ipIsdestructionstock;
    }
    
    public void setIpIsdestructionstock(String ipIsdestructionstock) {
        this.ipIsdestructionstock = ipIsdestructionstock;
    }

    
    @Column(name="IP_CONTRACTOR_PLANT", length=20)
    public String getIpContractorPlant() {
        return this.ipContractorPlant;
    }
    
    public void setIpContractorPlant(String ipContractorPlant) {
        this.ipContractorPlant = ipContractorPlant;
    }

    
    @Column(name="IP_CONTRACTOR_STORAGELOCATION", length=20)
    public String getIpContractorStoragelocation() {
        return this.ipContractorStoragelocation;
    }
    
    public void setIpContractorStoragelocation(String ipContractorStoragelocation) {
        this.ipContractorStoragelocation = ipContractorStoragelocation;
    }

    
    @Column(name="IP_CONTRACTOR_STOCKSTATUS", length=20)
    public String getIpContractorStockstatus() {
        return this.ipContractorStockstatus;
    }
    
    public void setIpContractorStockstatus(String ipContractorStockstatus) {
        this.ipContractorStockstatus = ipContractorStockstatus;
    }

    
    @Column(name="IP_CONTRACTOR_REPORTCOLUMN", precision=3, scale=0)
    public Short getIpContractorReportcolumn() {
        return this.ipContractorReportcolumn;
    }
    
    public void setIpContractorReportcolumn(Short ipContractorReportcolumn) {
        this.ipContractorReportcolumn = ipContractorReportcolumn;
    }

    
    @Column(name="IP_STOCKKEY", precision=5, scale=0)
    public Integer getIpStockkey() {
        return this.ipStockkey;
    }
    
    public void setIpStockkey(Integer ipStockkey) {
        this.ipStockkey = ipStockkey;
    }

    
    @Column(name="PROGRAMNAME", length=10)
    public String getProgramname() {
        return this.programname;
    }
    
    public void setProgramname(String programname) {
        this.programname = programname;
    }

    
    @Column(name="FILENAME", length=10)
    public String getFilename() {
        return this.filename;
    }
    
    public void setFilename(String filename) {
        this.filename = filename;
    }

    
    @Column(name="PROCESSINGFLAG1", length=1)
    public String getProcessingflag1() {
        return this.processingflag1;
    }
    
    public void setProcessingflag1(String processingflag1) {
        this.processingflag1 = processingflag1;
    }

    
    @Column(name="PROCESSINGFLAG2", length=1)
    public String getProcessingflag2() {
        return this.processingflag2;
    }
    
    public void setProcessingflag2(String processingflag2) {
        this.processingflag2 = processingflag2;
    }

    
    @Column(name="PROCESSINGFLAG3", length=1)
    public String getProcessingflag3() {
        return this.processingflag3;
    }
    
    public void setProcessingflag3(String processingflag3) {
        this.processingflag3 = processingflag3;
    }

    
    @Column(name="PROCESSINGFLAG4", length=1)
    public String getProcessingflag4() {
        return this.processingflag4;
    }
    
    public void setProcessingflag4(String processingflag4) {
        this.processingflag4 = processingflag4;
    }

    
    @Column(name="PROCESSINGFLAG5", length=1)
    public String getProcessingflag5() {
        return this.processingflag5;
    }
    
    public void setProcessingflag5(String processingflag5) {
        this.processingflag5 = processingflag5;
    }

    
    @Column(name="PROCESSINGFLAG6", length=1)
    public String getProcessingflag6() {
        return this.processingflag6;
    }
    
    public void setProcessingflag6(String processingflag6) {
        this.processingflag6 = processingflag6;
    }

    
    @Column(name="PROCESSINGFLAG7", length=1)
    public String getProcessingflag7() {
        return this.processingflag7;
    }
    
    public void setProcessingflag7(String processingflag7) {
        this.processingflag7 = processingflag7;
    }

    
    @Column(name="PROCESSINGFLAG8", length=1)
    public String getProcessingflag8() {
        return this.processingflag8;
    }
    
    public void setProcessingflag8(String processingflag8) {
        this.processingflag8 = processingflag8;
    }

    
    @Column(name="PROCESSINGFLAG9", length=1)
    public String getProcessingflag9() {
        return this.processingflag9;
    }
    
    public void setProcessingflag9(String processingflag9) {
        this.processingflag9 = processingflag9;
    }

    
    @Column(name="PROCESSINGFLAG10", length=1)
    public String getProcessingflag10() {
        return this.processingflag10;
    }
    
    public void setProcessingflag10(String processingflag10) {
        this.processingflag10 = processingflag10;
    }

    
    @Column(name="BACKENDRELEASED", nullable=false, length=1)
    public String getBackendreleased() {
        return this.backendreleased;
    }
    
    public void setBackendreleased(String backendreleased) {
        this.backendreleased = backendreleased;
    }

    
    @Column(name="OUTBOUNDIGNORE", nullable=false, length=1)
    public String getOutboundignore() {
        return this.outboundignore;
    }
    
    public void setOutboundignore(String outboundignore) {
        this.outboundignore = outboundignore;
    }

    
    @Column(name="TRANSACTIONID", length=50)
    public String getTransactionid() {
        return this.transactionid;
    }
    
    public void setTransactionid(String transactionid) {
        this.transactionid = transactionid;
    }

    
    @Column(name="RECORDPROCESSEDFLAG", nullable=false, length=1)
    public String getRecordprocessedflag() {
        return this.recordprocessedflag;
    }
    
    public void setRecordprocessedflag(String recordprocessedflag) {
        this.recordprocessedflag = recordprocessedflag;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="RECORDPROCESSINGTIME", length=26)
    public Date getRecordprocessingtime() {
        return this.recordprocessingtime;
    }
    
    public void setRecordprocessingtime(Date recordprocessingtime) {
        this.recordprocessingtime = recordprocessingtime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="RECORDLASTCHANGETIME", length=26)
    public Date getRecordlastchangetime() {
        return this.recordlastchangetime;
    }
    
    public void setRecordlastchangetime(Date recordlastchangetime) {
        this.recordlastchangetime = recordlastchangetime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="RECORDCREATIONTIME", nullable=false, length=26)
    public Date getRecordcreationtime() {
        return this.recordcreationtime;
    }
    
    public void setRecordcreationtime(Date recordcreationtime) {
        this.recordcreationtime = recordcreationtime;
    }




}


