package com.galexis.allog2mysql.deleteme;
// Generated Sep 6, 2013 9:37:59 AM by Hibernate Tools 3.6.0


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * TaskLock generated by hbm2java
 */
@Entity
@Table(name="TASK_LOCK"
    ,schema="INTEGAP"
    ,catalog="CHGALE11RDB"
    , uniqueConstraints = @UniqueConstraint(columnNames="LOCK_KEY") 
)
public class TaskLock  implements java.io.Serializable {


     private TaskLockId id;

    public TaskLock() {
    }

    public TaskLock(TaskLockId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="lockKey", column=@Column(name="LOCK_KEY", unique=true, nullable=false, length=250) ), 
        @AttributeOverride(name="crTime", column=@Column(name="CR_TIME", nullable=false, length=26) ) } )
    public TaskLockId getId() {
        return this.id;
    }
    
    public void setId(TaskLockId id) {
        this.id = id;
    }




}


