package com.galexis.allog2mysql.deleteme;
// Generated Sep 6, 2013 9:37:59 AM by Hibernate Tools 3.6.0


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Testgre generated by hbm2java
 */
@Entity
@Table(name="TESTGRE"
    ,schema="INTEGAP"
    ,catalog="CHGALE11RDB"
    , uniqueConstraints = @UniqueConstraint(columnNames="PK") 
)
public class Testgre  implements java.io.Serializable {


     private TestgreId id;

    public Testgre() {
    }

    public Testgre(TestgreId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="pk", column=@Column(name="PK", unique=true, nullable=false, precision=12, scale=0) ), 
        @AttributeOverride(name="contrdefpk", column=@Column(name="CONTRDEFPK", nullable=false, precision=12, scale=0) ), 
        @AttributeOverride(name="transnr", column=@Column(name="TRANSNR", nullable=false, precision=12, scale=0) ), 
        @AttributeOverride(name="transseq", column=@Column(name="TRANSSEQ", nullable=false, precision=3, scale=0) ), 
        @AttributeOverride(name="transdate", column=@Column(name="TRANSDATE", nullable=false, length=26) ), 
        @AttributeOverride(name="transbookperiod", column=@Column(name="TRANSBOOKPERIOD", length=20) ), 
        @AttributeOverride(name="recordtype", column=@Column(name="RECORDTYPE", length=30) ), 
        @AttributeOverride(name="transtype", column=@Column(name="TRANSTYPE", precision=5, scale=0) ), 
        @AttributeOverride(name="transtypetext", column=@Column(name="TRANSTYPETEXT", length=50) ), 
        @AttributeOverride(name="eventcode", column=@Column(name="EVENTCODE", length=4) ), 
        @AttributeOverride(name="eventcodetext", column=@Column(name="EVENTCODETEXT", length=50) ), 
        @AttributeOverride(name="itemmasterpk", column=@Column(name="ITEMMASTERPK", precision=12, scale=0) ), 
        @AttributeOverride(name="itemnr", column=@Column(name="ITEMNR", length=35) ), 
        @AttributeOverride(name="itemnrcontractor", column=@Column(name="ITEMNRCONTRACTOR", length=35) ), 
        @AttributeOverride(name="batchid", column=@Column(name="BATCHID", length=20) ), 
        @AttributeOverride(name="batchsellbydate", column=@Column(name="BATCHSELLBYDATE", length=26) ), 
        @AttributeOverride(name="batchexpirydate", column=@Column(name="BATCHEXPIRYDATE", length=26) ), 
        @AttributeOverride(name="batchidcontractor", column=@Column(name="BATCHIDCONTRACTOR", length=20) ), 
        @AttributeOverride(name="serialnr", column=@Column(name="SERIALNR", length=30) ), 
        @AttributeOverride(name="fromwhs", column=@Column(name="FROMWHS", length=10) ), 
        @AttributeOverride(name="fromzone", column=@Column(name="FROMZONE", length=10) ), 
        @AttributeOverride(name="fromlocation", column=@Column(name="FROMLOCATION", length=10) ), 
        @AttributeOverride(name="fromstockstatus", column=@Column(name="FROMSTOCKSTATUS", length=10) ), 
        @AttributeOverride(name="towhs", column=@Column(name="TOWHS", length=10) ), 
        @AttributeOverride(name="tozone", column=@Column(name="TOZONE", length=10) ), 
        @AttributeOverride(name="tolocation", column=@Column(name="TOLOCATION", length=10) ), 
        @AttributeOverride(name="tostockstatus", column=@Column(name="TOSTOCKSTATUS", length=10) ), 
        @AttributeOverride(name="fromqcflag", column=@Column(name="FROMQCFLAG", length=1) ), 
        @AttributeOverride(name="toqcflag", column=@Column(name="TOQCFLAG", length=1) ), 
        @AttributeOverride(name="frompalletid", column=@Column(name="FROMPALLETID", precision=30, scale=0) ), 
        @AttributeOverride(name="topalletid", column=@Column(name="TOPALLETID", precision=30, scale=0) ), 
        @AttributeOverride(name="nccnr", column=@Column(name="NCCNR", precision=12, scale=0) ), 
        @AttributeOverride(name="transqty", column=@Column(name="TRANSQTY", precision=15, scale=3) ), 
        @AttributeOverride(name="stockkeepingunit", column=@Column(name="STOCKKEEPINGUNIT", length=5) ), 
        @AttributeOverride(name="reasoncode", column=@Column(name="REASONCODE", length=3) ), 
        @AttributeOverride(name="reasoncodedesc", column=@Column(name="REASONCODEDESC", length=50) ), 
        @AttributeOverride(name="reasoncodeNcc", column=@Column(name="REASONCODE_NCC", length=3) ), 
        @AttributeOverride(name="reasoncodedescNcc", column=@Column(name="REASONCODEDESC_NCC", length=50) ), 
        @AttributeOverride(name="transtext", column=@Column(name="TRANSTEXT", length=50) ), 
        @AttributeOverride(name="referencetext", column=@Column(name="REFERENCETEXT", length=50) ), 
        @AttributeOverride(name="contractorreference", column=@Column(name="CONTRACTORREFERENCE", length=100) ), 
        @AttributeOverride(name="standardcost", column=@Column(name="STANDARDCOST", precision=17, scale=4) ), 
        @AttributeOverride(name="transvalue", column=@Column(name="TRANSVALUE", precision=17, scale=4) ), 
        @AttributeOverride(name="itrtransnr", column=@Column(name="ITRTRANSNR", precision=12, scale=0) ), 
        @AttributeOverride(name="suggestionnr", column=@Column(name="SUGGESTIONNR", precision=12, scale=0) ), 
        @AttributeOverride(name="suggestionline", column=@Column(name="SUGGESTIONLINE", precision=6, scale=0) ), 
        @AttributeOverride(name="suggestionsubline", column=@Column(name="SUGGESTIONSUBLINE", precision=6, scale=0) ), 
        @AttributeOverride(name="salesordernr", column=@Column(name="SALESORDERNR", precision=12, scale=0) ), 
        @AttributeOverride(name="salesorderline", column=@Column(name="SALESORDERLINE", precision=5, scale=0) ), 
        @AttributeOverride(name="salesordertype", column=@Column(name="SALESORDERTYPE", length=2) ), 
        @AttributeOverride(name="dellinbtcpk", column=@Column(name="DELLINBTCPK", precision=12, scale=0) ), 
        @AttributeOverride(name="purchaseordernr", column=@Column(name="PURCHASEORDERNR", precision=12, scale=0) ), 
        @AttributeOverride(name="purchaseorderline", column=@Column(name="PURCHASEORDERLINE", precision=6, scale=0) ), 
        @AttributeOverride(name="purchaseordertype", column=@Column(name="PURCHASEORDERTYPE", length=2) ), 
        @AttributeOverride(name="grelinbtcpk", column=@Column(name="GRELINBTCPK", precision=12, scale=0) ), 
        @AttributeOverride(name="orderreferencenr", column=@Column(name="ORDERREFERENCENR", precision=12, scale=0) ), 
        @AttributeOverride(name="orderreferenceline", column=@Column(name="ORDERREFERENCELINE", precision=6, scale=0) ), 
        @AttributeOverride(name="incidentnr", column=@Column(name="INCIDENTNR", precision=12, scale=0) ), 
        @AttributeOverride(name="incidentline", column=@Column(name="INCIDENTLINE", precision=6, scale=0) ), 
        @AttributeOverride(name="salesorderpicklistnr", column=@Column(name="SALESORDERPICKLISTNR", precision=12, scale=0) ), 
        @AttributeOverride(name="salesorderpicklistline", column=@Column(name="SALESORDERPICKLISTLINE", precision=6, scale=0) ), 
        @AttributeOverride(name="salesorderpickconsolidationnr", column=@Column(name="SALESORDERPICKCONSOLIDATIONNR", precision=12, scale=0) ), 
        @AttributeOverride(name="salesordershipmentnr", column=@Column(name="SALESORDERSHIPMENTNR", precision=12, scale=0) ), 
        @AttributeOverride(name="pogoodsreceptionnote", column=@Column(name="POGOODSRECEPTIONNOTE", precision=12, scale=0) ), 
        @AttributeOverride(name="pogoodsreceptionnoteline", column=@Column(name="POGOODSRECEPTIONNOTELINE", precision=6, scale=0) ), 
        @AttributeOverride(name="transitdeliveryflag", column=@Column(name="TRANSITDELIVERYFLAG", length=1) ), 
        @AttributeOverride(name="freeofchargeflag", column=@Column(name="FREEOFCHARGEFLAG", length=1) ), 
        @AttributeOverride(name="freeofchargereasoncode", column=@Column(name="FREEOFCHARGEREASONCODE", length=2) ), 
        @AttributeOverride(name="orderSourceCode", column=@Column(name="ORDER_SOURCE_CODE", length=20) ), 
        @AttributeOverride(name="deliveryannouncementnr", column=@Column(name="DELIVERYANNOUNCEMENTNR", length=35) ), 
        @AttributeOverride(name="deliveryannouncementline", column=@Column(name="DELIVERYANNOUNCEMENTLINE", precision=6, scale=0) ), 
        @AttributeOverride(name="usertransstarted", column=@Column(name="USERTRANSSTARTED", length=10) ), 
        @AttributeOverride(name="usertranscompleted", column=@Column(name="USERTRANSCOMPLETED", length=10) ), 
        @AttributeOverride(name="timetransstarted", column=@Column(name="TIMETRANSSTARTED", length=26) ), 
        @AttributeOverride(name="timetranscompleted", column=@Column(name="TIMETRANSCOMPLETED", length=26) ), 
        @AttributeOverride(name="fromreportingkey", column=@Column(name="FROMREPORTINGKEY", length=20) ), 
        @AttributeOverride(name="toreportingkey", column=@Column(name="TOREPORTINGKEY", length=20) ), 
        @AttributeOverride(name="fromreportingstockstatus", column=@Column(name="FROMREPORTINGSTOCKSTATUS", length=10) ), 
        @AttributeOverride(name="toreportingstockstatus", column=@Column(name="TOREPORTINGSTOCKSTATUS", length=10) ), 
        @AttributeOverride(name="stocktakelistnr", column=@Column(name="STOCKTAKELISTNR", precision=12, scale=0) ), 
        @AttributeOverride(name="stocktakelistline", column=@Column(name="STOCKTAKELISTLINE", precision=6, scale=0) ), 
        @AttributeOverride(name="rfbatchid", column=@Column(name="RFBATCHID", precision=9, scale=0) ), 
        @AttributeOverride(name="rfinstructionnr", column=@Column(name="RFINSTRUCTIONNR", precision=17, scale=0) ), 
        @AttributeOverride(name="freetext", column=@Column(name="FREETEXT") ), 
        @AttributeOverride(name="ipTranstype", column=@Column(name="IP_TRANSTYPE", precision=5, scale=0) ), 
        @AttributeOverride(name="ipEventcode", column=@Column(name="IP_EVENTCODE", precision=5, scale=0) ), 
        @AttributeOverride(name="ipFromwarehouse", column=@Column(name="IP_FROMWAREHOUSE", precision=5, scale=0) ), 
        @AttributeOverride(name="ipTowarehouse", column=@Column(name="IP_TOWAREHOUSE", precision=5, scale=0) ), 
        @AttributeOverride(name="ipFromlocationzone", column=@Column(name="IP_FROMLOCATIONZONE", precision=5, scale=0) ), 
        @AttributeOverride(name="ipTolocationzone", column=@Column(name="IP_TOLOCATIONZONE", precision=5, scale=0) ), 
        @AttributeOverride(name="ipFromstockcategory", column=@Column(name="IP_FROMSTOCKCATEGORY", precision=5, scale=0) ), 
        @AttributeOverride(name="ipTostockcategory", column=@Column(name="IP_TOSTOCKCATEGORY", precision=5, scale=0) ), 
        @AttributeOverride(name="ipPurchaseordertype", column=@Column(name="IP_PURCHASEORDERTYPE", precision=5, scale=0) ), 
        @AttributeOverride(name="ipSalesordertype", column=@Column(name="IP_SALESORDERTYPE", precision=5, scale=0) ), 
        @AttributeOverride(name="ipInvoicetype", column=@Column(name="IP_INVOICETYPE", precision=5, scale=0) ), 
        @AttributeOverride(name="ipIsfreeofcharge", column=@Column(name="IP_ISFREEOFCHARGE", length=1) ), 
        @AttributeOverride(name="ipFreeofchargereasoncode", column=@Column(name="IP_FREEOFCHARGEREASONCODE", precision=5, scale=0) ), 
        @AttributeOverride(name="ipTransclas1", column=@Column(name="IP_TRANSCLAS_1", length=10) ), 
        @AttributeOverride(name="ipTransclas2", column=@Column(name="IP_TRANSCLAS_2", length=10) ), 
        @AttributeOverride(name="ipTransclas3", column=@Column(name="IP_TRANSCLAS_3", length=10) ), 
        @AttributeOverride(name="ipIsdebit", column=@Column(name="IP_ISDEBIT", length=1) ), 
        @AttributeOverride(name="ipIssaleswithmovement", column=@Column(name="IP_ISSALESWITHMOVEMENT", length=1) ), 
        @AttributeOverride(name="ipIsstockrelevant", column=@Column(name="IP_ISSTOCKRELEVANT", length=1) ), 
        @AttributeOverride(name="ipMovementcode", column=@Column(name="IP_MOVEMENTCODE", length=20) ), 
        @AttributeOverride(name="ipMovementreason", column=@Column(name="IP_MOVEMENTREASON", length=20) ), 
        @AttributeOverride(name="ipPlantfrom", column=@Column(name="IP_PLANTFROM", length=20) ), 
        @AttributeOverride(name="ipPlantto", column=@Column(name="IP_PLANTTO", length=20) ), 
        @AttributeOverride(name="ipStoragelocationfrom", column=@Column(name="IP_STORAGELOCATIONFROM", length=20) ), 
        @AttributeOverride(name="ipStoragelocationto", column=@Column(name="IP_STORAGELOCATIONTO", length=20) ), 
        @AttributeOverride(name="ipStockstatusfrom", column=@Column(name="IP_STOCKSTATUSFROM", length=20) ), 
        @AttributeOverride(name="ipStockstatusto", column=@Column(name="IP_STOCKSTATUSTO", length=20) ), 
        @AttributeOverride(name="timedatepk", column=@Column(name="TIMEDATEPK", precision=8, scale=0) ), 
        @AttributeOverride(name="ipTimedatepkReporting", column=@Column(name="IP_TIMEDATEPK_REPORTING", precision=8, scale=0) ), 
        @AttributeOverride(name="programname", column=@Column(name="PROGRAMNAME", length=10) ), 
        @AttributeOverride(name="filename", column=@Column(name="FILENAME", length=10) ), 
        @AttributeOverride(name="processingflag1", column=@Column(name="PROCESSINGFLAG1", length=1) ), 
        @AttributeOverride(name="processingflag2", column=@Column(name="PROCESSINGFLAG2", length=1) ), 
        @AttributeOverride(name="processingflag3", column=@Column(name="PROCESSINGFLAG3", length=1) ), 
        @AttributeOverride(name="processingflag4", column=@Column(name="PROCESSINGFLAG4", length=1) ), 
        @AttributeOverride(name="processingflag5", column=@Column(name="PROCESSINGFLAG5", length=1) ), 
        @AttributeOverride(name="processingflag6", column=@Column(name="PROCESSINGFLAG6", length=1) ), 
        @AttributeOverride(name="processingflag7", column=@Column(name="PROCESSINGFLAG7", length=1) ), 
        @AttributeOverride(name="processingflag8", column=@Column(name="PROCESSINGFLAG8", length=1) ), 
        @AttributeOverride(name="processingflag9", column=@Column(name="PROCESSINGFLAG9", length=1) ), 
        @AttributeOverride(name="processingflag10", column=@Column(name="PROCESSINGFLAG10", length=1) ), 
        @AttributeOverride(name="backendreleased", column=@Column(name="BACKENDRELEASED", nullable=false, length=1) ), 
        @AttributeOverride(name="outboundignore", column=@Column(name="OUTBOUNDIGNORE", nullable=false, length=1) ), 
        @AttributeOverride(name="transactionid", column=@Column(name="TRANSACTIONID", length=50) ), 
        @AttributeOverride(name="recordprocessedflag", column=@Column(name="RECORDPROCESSEDFLAG", nullable=false, length=1) ), 
        @AttributeOverride(name="recordprocessingtime", column=@Column(name="RECORDPROCESSINGTIME", length=26) ), 
        @AttributeOverride(name="recordlastchangetime", column=@Column(name="RECORDLASTCHANGETIME", length=26) ), 
        @AttributeOverride(name="recordcreationtime", column=@Column(name="RECORDCREATIONTIME", nullable=false, length=26) ) } )
    public TestgreId getId() {
        return this.id;
    }
    
    public void setId(TestgreId id) {
        this.id = id;
    }




}


