package com.galexis.allog2mysql.deleteme;
// Generated Sep 6, 2013 9:37:59 AM by Hibernate Tools 3.6.0


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Testtable generated by hbm2java
 */
@Entity
@Table(name="TESTTABLE"
    ,schema="INTEGAP"
    ,catalog="CHGALE11RDB"
)
public class Testtable  implements java.io.Serializable {


     private TesttableId id;

    public Testtable() {
    }

    public Testtable(TesttableId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="field1", column=@Column(name="FIELD1") ), 
        @AttributeOverride(name="field2", column=@Column(name="FIELD2") ), 
        @AttributeOverride(name="field3", column=@Column(name="FIELD3") ), 
        @AttributeOverride(name="field4", column=@Column(name="FIELD4") ), 
        @AttributeOverride(name="field5", column=@Column(name="FIELD5") ), 
        @AttributeOverride(name="field6", column=@Column(name="FIELD6") ), 
        @AttributeOverride(name="field7", column=@Column(name="FIELD7") ), 
        @AttributeOverride(name="field8", column=@Column(name="FIELD8") ), 
        @AttributeOverride(name="field9", column=@Column(name="FIELD9") ) } )
    public TesttableId getId() {
        return this.id;
    }
    
    public void setId(TesttableId id) {
        this.id = id;
    }




}


