package com.galexis.allog2mysql.deleteme;
// Generated Sep 6, 2013 9:37:59 AM by Hibernate Tools 3.6.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * Timedati01Id generated by hbm2java
 */
@Embeddable
public class Timedati01Id  implements java.io.Serializable {


     private int pk;
     private Date tddate;
     private short tdyear;
     private byte tdmonth;
     private byte tdday;
     private byte tdweekofyear;
     private String daycode;
     private String daydesc;
     private String monthcode;
     private String monthdesc;
     private String quartercode;
     private String isleapyear;
     private Integer actualperiod;
     private Integer actualperiodlastday;
     private Integer actualperiodfirstday;
     private Integer previousperiod;
     private Integer previousperiodlastday;
     private Integer previousperiodfirstday;
     private Integer previousyearperiod;
     private Integer previyearpreviperiod;
     private Integer prevyearprevperiodlastday;
     private Integer prevyearprevperiodfirstday;

    public Timedati01Id() {
    }

	
    public Timedati01Id(int pk, Date tddate, short tdyear, byte tdmonth, byte tdday, byte tdweekofyear, String daycode, String daydesc, String monthcode, String monthdesc, String quartercode, String isleapyear) {
        this.pk = pk;
        this.tddate = tddate;
        this.tdyear = tdyear;
        this.tdmonth = tdmonth;
        this.tdday = tdday;
        this.tdweekofyear = tdweekofyear;
        this.daycode = daycode;
        this.daydesc = daydesc;
        this.monthcode = monthcode;
        this.monthdesc = monthdesc;
        this.quartercode = quartercode;
        this.isleapyear = isleapyear;
    }
    public Timedati01Id(int pk, Date tddate, short tdyear, byte tdmonth, byte tdday, byte tdweekofyear, String daycode, String daydesc, String monthcode, String monthdesc, String quartercode, String isleapyear, Integer actualperiod, Integer actualperiodlastday, Integer actualperiodfirstday, Integer previousperiod, Integer previousperiodlastday, Integer previousperiodfirstday, Integer previousyearperiod, Integer previyearpreviperiod, Integer prevyearprevperiodlastday, Integer prevyearprevperiodfirstday) {
       this.pk = pk;
       this.tddate = tddate;
       this.tdyear = tdyear;
       this.tdmonth = tdmonth;
       this.tdday = tdday;
       this.tdweekofyear = tdweekofyear;
       this.daycode = daycode;
       this.daydesc = daydesc;
       this.monthcode = monthcode;
       this.monthdesc = monthdesc;
       this.quartercode = quartercode;
       this.isleapyear = isleapyear;
       this.actualperiod = actualperiod;
       this.actualperiodlastday = actualperiodlastday;
       this.actualperiodfirstday = actualperiodfirstday;
       this.previousperiod = previousperiod;
       this.previousperiodlastday = previousperiodlastday;
       this.previousperiodfirstday = previousperiodfirstday;
       this.previousyearperiod = previousyearperiod;
       this.previyearpreviperiod = previyearpreviperiod;
       this.prevyearprevperiodlastday = prevyearprevperiodlastday;
       this.prevyearprevperiodfirstday = prevyearprevperiodfirstday;
    }
   


    @Column(name="PK", nullable=false, precision=8, scale=0)
    public int getPk() {
        return this.pk;
    }
    
    public void setPk(int pk) {
        this.pk = pk;
    }


    @Column(name="TDDATE", nullable=false, length=10)
    public Date getTddate() {
        return this.tddate;
    }
    
    public void setTddate(Date tddate) {
        this.tddate = tddate;
    }


    @Column(name="TDYEAR", nullable=false, precision=4, scale=0)
    public short getTdyear() {
        return this.tdyear;
    }
    
    public void setTdyear(short tdyear) {
        this.tdyear = tdyear;
    }


    @Column(name="TDMONTH", nullable=false, precision=2, scale=0)
    public byte getTdmonth() {
        return this.tdmonth;
    }
    
    public void setTdmonth(byte tdmonth) {
        this.tdmonth = tdmonth;
    }


    @Column(name="TDDAY", nullable=false, precision=2, scale=0)
    public byte getTdday() {
        return this.tdday;
    }
    
    public void setTdday(byte tdday) {
        this.tdday = tdday;
    }


    @Column(name="TDWEEKOFYEAR", nullable=false, precision=2, scale=0)
    public byte getTdweekofyear() {
        return this.tdweekofyear;
    }
    
    public void setTdweekofyear(byte tdweekofyear) {
        this.tdweekofyear = tdweekofyear;
    }


    @Column(name="DAYCODE", nullable=false, length=3)
    public String getDaycode() {
        return this.daycode;
    }
    
    public void setDaycode(String daycode) {
        this.daycode = daycode;
    }


    @Column(name="DAYDESC", nullable=false, length=30)
    public String getDaydesc() {
        return this.daydesc;
    }
    
    public void setDaydesc(String daydesc) {
        this.daydesc = daydesc;
    }


    @Column(name="MONTHCODE", nullable=false, length=3)
    public String getMonthcode() {
        return this.monthcode;
    }
    
    public void setMonthcode(String monthcode) {
        this.monthcode = monthcode;
    }


    @Column(name="MONTHDESC", nullable=false, length=30)
    public String getMonthdesc() {
        return this.monthdesc;
    }
    
    public void setMonthdesc(String monthdesc) {
        this.monthdesc = monthdesc;
    }


    @Column(name="QUARTERCODE", nullable=false, length=2)
    public String getQuartercode() {
        return this.quartercode;
    }
    
    public void setQuartercode(String quartercode) {
        this.quartercode = quartercode;
    }


    @Column(name="ISLEAPYEAR", nullable=false, length=1)
    public String getIsleapyear() {
        return this.isleapyear;
    }
    
    public void setIsleapyear(String isleapyear) {
        this.isleapyear = isleapyear;
    }


    @Column(name="ACTUALPERIOD", precision=6, scale=0)
    public Integer getActualperiod() {
        return this.actualperiod;
    }
    
    public void setActualperiod(Integer actualperiod) {
        this.actualperiod = actualperiod;
    }


    @Column(name="ACTUALPERIODLASTDAY", precision=8, scale=0)
    public Integer getActualperiodlastday() {
        return this.actualperiodlastday;
    }
    
    public void setActualperiodlastday(Integer actualperiodlastday) {
        this.actualperiodlastday = actualperiodlastday;
    }


    @Column(name="ACTUALPERIODFIRSTDAY", precision=8, scale=0)
    public Integer getActualperiodfirstday() {
        return this.actualperiodfirstday;
    }
    
    public void setActualperiodfirstday(Integer actualperiodfirstday) {
        this.actualperiodfirstday = actualperiodfirstday;
    }


    @Column(name="PREVIOUSPERIOD", precision=6, scale=0)
    public Integer getPreviousperiod() {
        return this.previousperiod;
    }
    
    public void setPreviousperiod(Integer previousperiod) {
        this.previousperiod = previousperiod;
    }


    @Column(name="PREVIOUSPERIODLASTDAY", precision=8, scale=0)
    public Integer getPreviousperiodlastday() {
        return this.previousperiodlastday;
    }
    
    public void setPreviousperiodlastday(Integer previousperiodlastday) {
        this.previousperiodlastday = previousperiodlastday;
    }


    @Column(name="PREVIOUSPERIODFIRSTDAY", precision=8, scale=0)
    public Integer getPreviousperiodfirstday() {
        return this.previousperiodfirstday;
    }
    
    public void setPreviousperiodfirstday(Integer previousperiodfirstday) {
        this.previousperiodfirstday = previousperiodfirstday;
    }


    @Column(name="PREVIOUSYEARPERIOD", precision=6, scale=0)
    public Integer getPreviousyearperiod() {
        return this.previousyearperiod;
    }
    
    public void setPreviousyearperiod(Integer previousyearperiod) {
        this.previousyearperiod = previousyearperiod;
    }


    @Column(name="PREVIYEARPREVIPERIOD", precision=6, scale=0)
    public Integer getPreviyearpreviperiod() {
        return this.previyearpreviperiod;
    }
    
    public void setPreviyearpreviperiod(Integer previyearpreviperiod) {
        this.previyearpreviperiod = previyearpreviperiod;
    }


    @Column(name="PREVYEARPREVPERIODLASTDAY", precision=8, scale=0)
    public Integer getPrevyearprevperiodlastday() {
        return this.prevyearprevperiodlastday;
    }
    
    public void setPrevyearprevperiodlastday(Integer prevyearprevperiodlastday) {
        this.prevyearprevperiodlastday = prevyearprevperiodlastday;
    }


    @Column(name="PREVYEARPREVPERIODFIRSTDAY", precision=8, scale=0)
    public Integer getPrevyearprevperiodfirstday() {
        return this.prevyearprevperiodfirstday;
    }
    
    public void setPrevyearprevperiodfirstday(Integer prevyearprevperiodfirstday) {
        this.prevyearprevperiodfirstday = prevyearprevperiodfirstday;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof Timedati01Id) ) return false;
		 Timedati01Id castOther = ( Timedati01Id ) other; 
         
		 return (this.getPk()==castOther.getPk())
 && ( (this.getTddate()==castOther.getTddate()) || ( this.getTddate()!=null && castOther.getTddate()!=null && this.getTddate().equals(castOther.getTddate()) ) )
 && (this.getTdyear()==castOther.getTdyear())
 && (this.getTdmonth()==castOther.getTdmonth())
 && (this.getTdday()==castOther.getTdday())
 && (this.getTdweekofyear()==castOther.getTdweekofyear())
 && ( (this.getDaycode()==castOther.getDaycode()) || ( this.getDaycode()!=null && castOther.getDaycode()!=null && this.getDaycode().equals(castOther.getDaycode()) ) )
 && ( (this.getDaydesc()==castOther.getDaydesc()) || ( this.getDaydesc()!=null && castOther.getDaydesc()!=null && this.getDaydesc().equals(castOther.getDaydesc()) ) )
 && ( (this.getMonthcode()==castOther.getMonthcode()) || ( this.getMonthcode()!=null && castOther.getMonthcode()!=null && this.getMonthcode().equals(castOther.getMonthcode()) ) )
 && ( (this.getMonthdesc()==castOther.getMonthdesc()) || ( this.getMonthdesc()!=null && castOther.getMonthdesc()!=null && this.getMonthdesc().equals(castOther.getMonthdesc()) ) )
 && ( (this.getQuartercode()==castOther.getQuartercode()) || ( this.getQuartercode()!=null && castOther.getQuartercode()!=null && this.getQuartercode().equals(castOther.getQuartercode()) ) )
 && ( (this.getIsleapyear()==castOther.getIsleapyear()) || ( this.getIsleapyear()!=null && castOther.getIsleapyear()!=null && this.getIsleapyear().equals(castOther.getIsleapyear()) ) )
 && ( (this.getActualperiod()==castOther.getActualperiod()) || ( this.getActualperiod()!=null && castOther.getActualperiod()!=null && this.getActualperiod().equals(castOther.getActualperiod()) ) )
 && ( (this.getActualperiodlastday()==castOther.getActualperiodlastday()) || ( this.getActualperiodlastday()!=null && castOther.getActualperiodlastday()!=null && this.getActualperiodlastday().equals(castOther.getActualperiodlastday()) ) )
 && ( (this.getActualperiodfirstday()==castOther.getActualperiodfirstday()) || ( this.getActualperiodfirstday()!=null && castOther.getActualperiodfirstday()!=null && this.getActualperiodfirstday().equals(castOther.getActualperiodfirstday()) ) )
 && ( (this.getPreviousperiod()==castOther.getPreviousperiod()) || ( this.getPreviousperiod()!=null && castOther.getPreviousperiod()!=null && this.getPreviousperiod().equals(castOther.getPreviousperiod()) ) )
 && ( (this.getPreviousperiodlastday()==castOther.getPreviousperiodlastday()) || ( this.getPreviousperiodlastday()!=null && castOther.getPreviousperiodlastday()!=null && this.getPreviousperiodlastday().equals(castOther.getPreviousperiodlastday()) ) )
 && ( (this.getPreviousperiodfirstday()==castOther.getPreviousperiodfirstday()) || ( this.getPreviousperiodfirstday()!=null && castOther.getPreviousperiodfirstday()!=null && this.getPreviousperiodfirstday().equals(castOther.getPreviousperiodfirstday()) ) )
 && ( (this.getPreviousyearperiod()==castOther.getPreviousyearperiod()) || ( this.getPreviousyearperiod()!=null && castOther.getPreviousyearperiod()!=null && this.getPreviousyearperiod().equals(castOther.getPreviousyearperiod()) ) )
 && ( (this.getPreviyearpreviperiod()==castOther.getPreviyearpreviperiod()) || ( this.getPreviyearpreviperiod()!=null && castOther.getPreviyearpreviperiod()!=null && this.getPreviyearpreviperiod().equals(castOther.getPreviyearpreviperiod()) ) )
 && ( (this.getPrevyearprevperiodlastday()==castOther.getPrevyearprevperiodlastday()) || ( this.getPrevyearprevperiodlastday()!=null && castOther.getPrevyearprevperiodlastday()!=null && this.getPrevyearprevperiodlastday().equals(castOther.getPrevyearprevperiodlastday()) ) )
 && ( (this.getPrevyearprevperiodfirstday()==castOther.getPrevyearprevperiodfirstday()) || ( this.getPrevyearprevperiodfirstday()!=null && castOther.getPrevyearprevperiodfirstday()!=null && this.getPrevyearprevperiodfirstday().equals(castOther.getPrevyearprevperiodfirstday()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getPk();
         result = 37 * result + ( getTddate() == null ? 0 : this.getTddate().hashCode() );
         result = 37 * result + this.getTdyear();
         result = 37 * result + this.getTdmonth();
         result = 37 * result + this.getTdday();
         result = 37 * result + this.getTdweekofyear();
         result = 37 * result + ( getDaycode() == null ? 0 : this.getDaycode().hashCode() );
         result = 37 * result + ( getDaydesc() == null ? 0 : this.getDaydesc().hashCode() );
         result = 37 * result + ( getMonthcode() == null ? 0 : this.getMonthcode().hashCode() );
         result = 37 * result + ( getMonthdesc() == null ? 0 : this.getMonthdesc().hashCode() );
         result = 37 * result + ( getQuartercode() == null ? 0 : this.getQuartercode().hashCode() );
         result = 37 * result + ( getIsleapyear() == null ? 0 : this.getIsleapyear().hashCode() );
         result = 37 * result + ( getActualperiod() == null ? 0 : this.getActualperiod().hashCode() );
         result = 37 * result + ( getActualperiodlastday() == null ? 0 : this.getActualperiodlastday().hashCode() );
         result = 37 * result + ( getActualperiodfirstday() == null ? 0 : this.getActualperiodfirstday().hashCode() );
         result = 37 * result + ( getPreviousperiod() == null ? 0 : this.getPreviousperiod().hashCode() );
         result = 37 * result + ( getPreviousperiodlastday() == null ? 0 : this.getPreviousperiodlastday().hashCode() );
         result = 37 * result + ( getPreviousperiodfirstday() == null ? 0 : this.getPreviousperiodfirstday().hashCode() );
         result = 37 * result + ( getPreviousyearperiod() == null ? 0 : this.getPreviousyearperiod().hashCode() );
         result = 37 * result + ( getPreviyearpreviperiod() == null ? 0 : this.getPreviyearpreviperiod().hashCode() );
         result = 37 * result + ( getPrevyearprevperiodlastday() == null ? 0 : this.getPrevyearprevperiodlastday().hashCode() );
         result = 37 * result + ( getPrevyearprevperiodfirstday() == null ? 0 : this.getPrevyearprevperiodfirstday().hashCode() );
         return result;
   }   


}


