package com.galexis.allog2mysql.deleteme;
// Generated Sep 6, 2013 9:37:59 AM by Hibernate Tools 3.6.0


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Timedati03 generated by hbm2java
 */
@Entity
@Table(name="TIMEDATI03"
    ,schema="INTEGAP"
    ,catalog="CHGALE11RDB"
)
public class Timedati03  implements java.io.Serializable {


     private Timedati03Id id;

    public Timedati03() {
    }

    public Timedati03(Timedati03Id id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="pk", column=@Column(name="PK", nullable=false, precision=8, scale=0) ), 
        @AttributeOverride(name="tddate", column=@Column(name="TDDATE", nullable=false, length=10) ), 
        @AttributeOverride(name="tdyear", column=@Column(name="TDYEAR", nullable=false, precision=4, scale=0) ), 
        @AttributeOverride(name="tdmonth", column=@Column(name="TDMONTH", nullable=false, precision=2, scale=0) ), 
        @AttributeOverride(name="tdday", column=@Column(name="TDDAY", nullable=false, precision=2, scale=0) ), 
        @AttributeOverride(name="tdweekofyear", column=@Column(name="TDWEEKOFYEAR", nullable=false, precision=2, scale=0) ), 
        @AttributeOverride(name="daycode", column=@Column(name="DAYCODE", nullable=false, length=3) ), 
        @AttributeOverride(name="daydesc", column=@Column(name="DAYDESC", nullable=false, length=30) ), 
        @AttributeOverride(name="monthcode", column=@Column(name="MONTHCODE", nullable=false, length=3) ), 
        @AttributeOverride(name="monthdesc", column=@Column(name="MONTHDESC", nullable=false, length=30) ), 
        @AttributeOverride(name="quartercode", column=@Column(name="QUARTERCODE", nullable=false, length=2) ), 
        @AttributeOverride(name="isleapyear", column=@Column(name="ISLEAPYEAR", nullable=false, length=1) ), 
        @AttributeOverride(name="actualperiod", column=@Column(name="ACTUALPERIOD", precision=6, scale=0) ), 
        @AttributeOverride(name="actualperiodlastday", column=@Column(name="ACTUALPERIODLASTDAY", precision=8, scale=0) ), 
        @AttributeOverride(name="actualperiodfirstday", column=@Column(name="ACTUALPERIODFIRSTDAY", precision=8, scale=0) ), 
        @AttributeOverride(name="previousperiod", column=@Column(name="PREVIOUSPERIOD", precision=6, scale=0) ), 
        @AttributeOverride(name="previousperiodlastday", column=@Column(name="PREVIOUSPERIODLASTDAY", precision=8, scale=0) ), 
        @AttributeOverride(name="previousperiodfirstday", column=@Column(name="PREVIOUSPERIODFIRSTDAY", precision=8, scale=0) ), 
        @AttributeOverride(name="previousyearperiod", column=@Column(name="PREVIOUSYEARPERIOD", precision=6, scale=0) ), 
        @AttributeOverride(name="previyearpreviperiod", column=@Column(name="PREVIYEARPREVIPERIOD", precision=6, scale=0) ), 
        @AttributeOverride(name="prevyearprevperiodlastday", column=@Column(name="PREVYEARPREVPERIODLASTDAY", precision=8, scale=0) ), 
        @AttributeOverride(name="prevyearprevperiodfirstday", column=@Column(name="PREVYEARPREVPERIODFIRSTDAY", precision=8, scale=0) ) } )
    public Timedati03Id getId() {
        return this.id;
    }
    
    public void setId(Timedati03Id id) {
        this.id = id;
    }




}


