package com.galexis.allog2mysql.deleteme;
// Generated Sep 6, 2013 9:37:59 AM by Hibernate Tools 3.6.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Tourexg generated by hbm2java
 */
@Entity
@Table(name="TOUREXG"
    ,schema="INTEGAP"
    ,catalog="CHGALE11RDB"
)
public class Tourexg  implements java.io.Serializable {


     private long pk;
     private String custglx;
     private String custgln;
     private String dispatchwarehouse;
     private int dispatchdate;
     private int dispatchtime;
     private String tourid;
     private int cutoffdate;
     private int cutofftime;
     private char tourtype;
     private String transactionid;
     private Date recordcreationtime;
     private char recordprocessedflag;
     private Date recordprocessingtime;

    public Tourexg() {
    }

	
    public Tourexg(long pk, String custglx, String custgln, String dispatchwarehouse, int dispatchdate, int dispatchtime, String tourid, int cutoffdate, int cutofftime, char tourtype, String transactionid, Date recordcreationtime, char recordprocessedflag) {
        this.pk = pk;
        this.custglx = custglx;
        this.custgln = custgln;
        this.dispatchwarehouse = dispatchwarehouse;
        this.dispatchdate = dispatchdate;
        this.dispatchtime = dispatchtime;
        this.tourid = tourid;
        this.cutoffdate = cutoffdate;
        this.cutofftime = cutofftime;
        this.tourtype = tourtype;
        this.transactionid = transactionid;
        this.recordcreationtime = recordcreationtime;
        this.recordprocessedflag = recordprocessedflag;
    }
    public Tourexg(long pk, String custglx, String custgln, String dispatchwarehouse, int dispatchdate, int dispatchtime, String tourid, int cutoffdate, int cutofftime, char tourtype, String transactionid, Date recordcreationtime, char recordprocessedflag, Date recordprocessingtime) {
       this.pk = pk;
       this.custglx = custglx;
       this.custgln = custgln;
       this.dispatchwarehouse = dispatchwarehouse;
       this.dispatchdate = dispatchdate;
       this.dispatchtime = dispatchtime;
       this.tourid = tourid;
       this.cutoffdate = cutoffdate;
       this.cutofftime = cutofftime;
       this.tourtype = tourtype;
       this.transactionid = transactionid;
       this.recordcreationtime = recordcreationtime;
       this.recordprocessedflag = recordprocessedflag;
       this.recordprocessingtime = recordprocessingtime;
    }
   
     @Id 

    
    @Column(name="PK", unique=true, nullable=false, precision=12, scale=0)
    public long getPk() {
        return this.pk;
    }
    
    public void setPk(long pk) {
        this.pk = pk;
    }

    
    @Column(name="CUSTGLX", nullable=false, length=11)
    public String getCustglx() {
        return this.custglx;
    }
    
    public void setCustglx(String custglx) {
        this.custglx = custglx;
    }

    
    @Column(name="CUSTGLN", nullable=false, length=13)
    public String getCustgln() {
        return this.custgln;
    }
    
    public void setCustgln(String custgln) {
        this.custgln = custgln;
    }

    
    @Column(name="DISPATCHWAREHOUSE", nullable=false, length=3)
    public String getDispatchwarehouse() {
        return this.dispatchwarehouse;
    }
    
    public void setDispatchwarehouse(String dispatchwarehouse) {
        this.dispatchwarehouse = dispatchwarehouse;
    }

    
    @Column(name="DISPATCHDATE", nullable=false, precision=8, scale=0)
    public int getDispatchdate() {
        return this.dispatchdate;
    }
    
    public void setDispatchdate(int dispatchdate) {
        this.dispatchdate = dispatchdate;
    }

    
    @Column(name="DISPATCHTIME", nullable=false, precision=6, scale=0)
    public int getDispatchtime() {
        return this.dispatchtime;
    }
    
    public void setDispatchtime(int dispatchtime) {
        this.dispatchtime = dispatchtime;
    }

    
    @Column(name="TOURID", nullable=false, length=10)
    public String getTourid() {
        return this.tourid;
    }
    
    public void setTourid(String tourid) {
        this.tourid = tourid;
    }

    
    @Column(name="CUTOFFDATE", nullable=false, precision=8, scale=0)
    public int getCutoffdate() {
        return this.cutoffdate;
    }
    
    public void setCutoffdate(int cutoffdate) {
        this.cutoffdate = cutoffdate;
    }

    
    @Column(name="CUTOFFTIME", nullable=false, precision=6, scale=0)
    public int getCutofftime() {
        return this.cutofftime;
    }
    
    public void setCutofftime(int cutofftime) {
        this.cutofftime = cutofftime;
    }

    
    @Column(name="TOURTYPE", nullable=false, length=1)
    public char getTourtype() {
        return this.tourtype;
    }
    
    public void setTourtype(char tourtype) {
        this.tourtype = tourtype;
    }

    
    @Column(name="TRANSACTIONID", nullable=false, length=50)
    public String getTransactionid() {
        return this.transactionid;
    }
    
    public void setTransactionid(String transactionid) {
        this.transactionid = transactionid;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="RECORDCREATIONTIME", nullable=false, length=26)
    public Date getRecordcreationtime() {
        return this.recordcreationtime;
    }
    
    public void setRecordcreationtime(Date recordcreationtime) {
        this.recordcreationtime = recordcreationtime;
    }

    
    @Column(name="RECORDPROCESSEDFLAG", nullable=false, length=1)
    public char getRecordprocessedflag() {
        return this.recordprocessedflag;
    }
    
    public void setRecordprocessedflag(char recordprocessedflag) {
        this.recordprocessedflag = recordprocessedflag;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="RECORDPROCESSINGTIME", length=26)
    public Date getRecordprocessingtime() {
        return this.recordprocessingtime;
    }
    
    public void setRecordprocessingtime(Date recordprocessingtime) {
        this.recordprocessingtime = recordprocessingtime;
    }




}


