package com.galexis.allog2mysql.deleteme;
// Generated Sep 6, 2013 9:37:59 AM by Hibernate Tools 3.6.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Triggerdef generated by hbm2java
 */
@Entity
@Table(name="TRIGGERDEF"
    ,schema="INTEGAP"
    ,catalog="CHGALE11RDB"
)
public class Triggerdef  implements java.io.Serializable {


     private long pk;
     private Contrdef contrdef;
     private Jobdef jobdef;
     private String triggername;
     private Date starttime;
     private Date endtime;
     private short intervalmin;
     private String startdow;
     private String enddow;
     private String dom;
     private char dayendjob;
     private String phase;
     private Short dayenddelaymin;
     private Short phasedelaymin;
     private Date datefrom;
     private Date dateto;
     private Date lastruntime;
     private Date recordcreationtime;

    public Triggerdef() {
    }

	
    public Triggerdef(long pk, Contrdef contrdef, Jobdef jobdef, String triggername, short intervalmin, char dayendjob, String phase, Date datefrom, Date recordcreationtime) {
        this.pk = pk;
        this.contrdef = contrdef;
        this.jobdef = jobdef;
        this.triggername = triggername;
        this.intervalmin = intervalmin;
        this.dayendjob = dayendjob;
        this.phase = phase;
        this.datefrom = datefrom;
        this.recordcreationtime = recordcreationtime;
    }
    public Triggerdef(long pk, Contrdef contrdef, Jobdef jobdef, String triggername, Date starttime, Date endtime, short intervalmin, String startdow, String enddow, String dom, char dayendjob, String phase, Short dayenddelaymin, Short phasedelaymin, Date datefrom, Date dateto, Date lastruntime, Date recordcreationtime) {
       this.pk = pk;
       this.contrdef = contrdef;
       this.jobdef = jobdef;
       this.triggername = triggername;
       this.starttime = starttime;
       this.endtime = endtime;
       this.intervalmin = intervalmin;
       this.startdow = startdow;
       this.enddow = enddow;
       this.dom = dom;
       this.dayendjob = dayendjob;
       this.phase = phase;
       this.dayenddelaymin = dayenddelaymin;
       this.phasedelaymin = phasedelaymin;
       this.datefrom = datefrom;
       this.dateto = dateto;
       this.lastruntime = lastruntime;
       this.recordcreationtime = recordcreationtime;
    }
   
     @Id 

    
    @Column(name="PK", unique=true, nullable=false, precision=12, scale=0)
    public long getPk() {
        return this.pk;
    }
    
    public void setPk(long pk) {
        this.pk = pk;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CONTRDEFPK", nullable=false)
    public Contrdef getContrdef() {
        return this.contrdef;
    }
    
    public void setContrdef(Contrdef contrdef) {
        this.contrdef = contrdef;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="JOBDEFPK", nullable=false)
    public Jobdef getJobdef() {
        return this.jobdef;
    }
    
    public void setJobdef(Jobdef jobdef) {
        this.jobdef = jobdef;
    }

    
    @Column(name="TRIGGERNAME", nullable=false, length=50)
    public String getTriggername() {
        return this.triggername;
    }
    
    public void setTriggername(String triggername) {
        this.triggername = triggername;
    }

    @Temporal(TemporalType.TIME)
    @Column(name="STARTTIME", length=8)
    public Date getStarttime() {
        return this.starttime;
    }
    
    public void setStarttime(Date starttime) {
        this.starttime = starttime;
    }

    @Temporal(TemporalType.TIME)
    @Column(name="ENDTIME", length=8)
    public Date getEndtime() {
        return this.endtime;
    }
    
    public void setEndtime(Date endtime) {
        this.endtime = endtime;
    }

    
    @Column(name="INTERVALMIN", nullable=false, precision=3, scale=0)
    public short getIntervalmin() {
        return this.intervalmin;
    }
    
    public void setIntervalmin(short intervalmin) {
        this.intervalmin = intervalmin;
    }

    
    @Column(name="STARTDOW", length=3)
    public String getStartdow() {
        return this.startdow;
    }
    
    public void setStartdow(String startdow) {
        this.startdow = startdow;
    }

    
    @Column(name="ENDDOW", length=3)
    public String getEnddow() {
        return this.enddow;
    }
    
    public void setEnddow(String enddow) {
        this.enddow = enddow;
    }

    
    @Column(name="DOM", length=3)
    public String getDom() {
        return this.dom;
    }
    
    public void setDom(String dom) {
        this.dom = dom;
    }

    
    @Column(name="DAYENDJOB", nullable=false, length=1)
    public char getDayendjob() {
        return this.dayendjob;
    }
    
    public void setDayendjob(char dayendjob) {
        this.dayendjob = dayendjob;
    }

    
    @Column(name="PHASE", nullable=false, length=10)
    public String getPhase() {
        return this.phase;
    }
    
    public void setPhase(String phase) {
        this.phase = phase;
    }

    
    @Column(name="DAYENDDELAYMIN", precision=3, scale=0)
    public Short getDayenddelaymin() {
        return this.dayenddelaymin;
    }
    
    public void setDayenddelaymin(Short dayenddelaymin) {
        this.dayenddelaymin = dayenddelaymin;
    }

    
    @Column(name="PHASEDELAYMIN", precision=3, scale=0)
    public Short getPhasedelaymin() {
        return this.phasedelaymin;
    }
    
    public void setPhasedelaymin(Short phasedelaymin) {
        this.phasedelaymin = phasedelaymin;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATEFROM", nullable=false, length=10)
    public Date getDatefrom() {
        return this.datefrom;
    }
    
    public void setDatefrom(Date datefrom) {
        this.datefrom = datefrom;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATETO", length=10)
    public Date getDateto() {
        return this.dateto;
    }
    
    public void setDateto(Date dateto) {
        this.dateto = dateto;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LASTRUNTIME", length=26)
    public Date getLastruntime() {
        return this.lastruntime;
    }
    
    public void setLastruntime(Date lastruntime) {
        this.lastruntime = lastruntime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="RECORDCREATIONTIME", nullable=false, length=26)
    public Date getRecordcreationtime() {
        return this.recordcreationtime;
    }
    
    public void setRecordcreationtime(Date recordcreationtime) {
        this.recordcreationtime = recordcreationtime;
    }




}


