package com.galexis.allog2mysql.deleteme;
// Generated Sep 6, 2013 9:37:59 AM by Hibernate Tools 3.6.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Triggerexc generated by hbm2java
 */
@Entity
@Table(name="TRIGGEREXC"
    ,schema="INTEGAP"
    ,catalog="CHGALE11RDB"
)
public class Triggerexc  implements java.io.Serializable {


     private long pk;
     private Contrdef contrdef;
     private String triggername;
     private Date starttime;
     private Date endtime;
     private short intervalmin;
     private Character dayendjob;
     private String phase;
     private Short dayenddelaymin;
     private Short phasedelaymin;
     private Date exeptiondate;
     private Date considered;
     private Date lastruntime;
     private Date recordcreationtime;

    public Triggerexc() {
    }

	
    public Triggerexc(long pk, String triggername, short intervalmin, String phase, Date exeptiondate, Date recordcreationtime) {
        this.pk = pk;
        this.triggername = triggername;
        this.intervalmin = intervalmin;
        this.phase = phase;
        this.exeptiondate = exeptiondate;
        this.recordcreationtime = recordcreationtime;
    }
    public Triggerexc(long pk, Contrdef contrdef, String triggername, Date starttime, Date endtime, short intervalmin, Character dayendjob, String phase, Short dayenddelaymin, Short phasedelaymin, Date exeptiondate, Date considered, Date lastruntime, Date recordcreationtime) {
       this.pk = pk;
       this.contrdef = contrdef;
       this.triggername = triggername;
       this.starttime = starttime;
       this.endtime = endtime;
       this.intervalmin = intervalmin;
       this.dayendjob = dayendjob;
       this.phase = phase;
       this.dayenddelaymin = dayenddelaymin;
       this.phasedelaymin = phasedelaymin;
       this.exeptiondate = exeptiondate;
       this.considered = considered;
       this.lastruntime = lastruntime;
       this.recordcreationtime = recordcreationtime;
    }
   
     @Id 

    
    @Column(name="PK", unique=true, nullable=false, precision=12, scale=0)
    public long getPk() {
        return this.pk;
    }
    
    public void setPk(long pk) {
        this.pk = pk;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CONTRDEFPK")
    public Contrdef getContrdef() {
        return this.contrdef;
    }
    
    public void setContrdef(Contrdef contrdef) {
        this.contrdef = contrdef;
    }

    
    @Column(name="TRIGGERNAME", nullable=false, length=50)
    public String getTriggername() {
        return this.triggername;
    }
    
    public void setTriggername(String triggername) {
        this.triggername = triggername;
    }

    @Temporal(TemporalType.TIME)
    @Column(name="STARTTIME", length=8)
    public Date getStarttime() {
        return this.starttime;
    }
    
    public void setStarttime(Date starttime) {
        this.starttime = starttime;
    }

    @Temporal(TemporalType.TIME)
    @Column(name="ENDTIME", length=8)
    public Date getEndtime() {
        return this.endtime;
    }
    
    public void setEndtime(Date endtime) {
        this.endtime = endtime;
    }

    
    @Column(name="INTERVALMIN", nullable=false, precision=3, scale=0)
    public short getIntervalmin() {
        return this.intervalmin;
    }
    
    public void setIntervalmin(short intervalmin) {
        this.intervalmin = intervalmin;
    }

    
    @Column(name="DAYENDJOB", length=1)
    public Character getDayendjob() {
        return this.dayendjob;
    }
    
    public void setDayendjob(Character dayendjob) {
        this.dayendjob = dayendjob;
    }

    
    @Column(name="PHASE", nullable=false, length=10)
    public String getPhase() {
        return this.phase;
    }
    
    public void setPhase(String phase) {
        this.phase = phase;
    }

    
    @Column(name="DAYENDDELAYMIN", precision=3, scale=0)
    public Short getDayenddelaymin() {
        return this.dayenddelaymin;
    }
    
    public void setDayenddelaymin(Short dayenddelaymin) {
        this.dayenddelaymin = dayenddelaymin;
    }

    
    @Column(name="PHASEDELAYMIN", precision=3, scale=0)
    public Short getPhasedelaymin() {
        return this.phasedelaymin;
    }
    
    public void setPhasedelaymin(Short phasedelaymin) {
        this.phasedelaymin = phasedelaymin;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="EXEPTIONDATE", nullable=false, length=10)
    public Date getExeptiondate() {
        return this.exeptiondate;
    }
    
    public void setExeptiondate(Date exeptiondate) {
        this.exeptiondate = exeptiondate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CONSIDERED", length=26)
    public Date getConsidered() {
        return this.considered;
    }
    
    public void setConsidered(Date considered) {
        this.considered = considered;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LASTRUNTIME", length=26)
    public Date getLastruntime() {
        return this.lastruntime;
    }
    
    public void setLastruntime(Date lastruntime) {
        this.lastruntime = lastruntime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="RECORDCREATIONTIME", nullable=false, length=26)
    public Date getRecordcreationtime() {
        return this.recordcreationtime;
    }
    
    public void setRecordcreationtime(Date recordcreationtime) {
        this.recordcreationtime = recordcreationtime;
    }




}


