package com.galexis.allog2mysql.deleteme;
// Generated Sep 6, 2013 9:37:59 AM by Hibernate Tools 3.6.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Trpordinfo generated by hbm2java
 */
@Entity
@Table(name="TRPORDINFO"
    ,schema="INTEGAP"
    ,catalog="CHGALE11RDB"
)
public class Trpordinfo  implements java.io.Serializable {


     private long pk;
     private long carrierContrdefpk;
     private String transportordernumber;
     private String recipientidentification;
     private Date deliverytime;
     private Integer timedatepk;
     private Integer ipTimedatepkReporting;
     private String transactionid;
     private String processingflag1;
     private String processingflag2;
     private String processingflag3;
     private String processingflag4;
     private String processingflag5;
     private String processingflag6;
     private String processingflag7;
     private String processingflag8;
     private String processingflag9;
     private String processingflag10;
     private Date recordcreationtime;

    public Trpordinfo() {
    }

	
    public Trpordinfo(long pk, long carrierContrdefpk, String transportordernumber, String recipientidentification, Date deliverytime, Date recordcreationtime) {
        this.pk = pk;
        this.carrierContrdefpk = carrierContrdefpk;
        this.transportordernumber = transportordernumber;
        this.recipientidentification = recipientidentification;
        this.deliverytime = deliverytime;
        this.recordcreationtime = recordcreationtime;
    }
    public Trpordinfo(long pk, long carrierContrdefpk, String transportordernumber, String recipientidentification, Date deliverytime, Integer timedatepk, Integer ipTimedatepkReporting, String transactionid, String processingflag1, String processingflag2, String processingflag3, String processingflag4, String processingflag5, String processingflag6, String processingflag7, String processingflag8, String processingflag9, String processingflag10, Date recordcreationtime) {
       this.pk = pk;
       this.carrierContrdefpk = carrierContrdefpk;
       this.transportordernumber = transportordernumber;
       this.recipientidentification = recipientidentification;
       this.deliverytime = deliverytime;
       this.timedatepk = timedatepk;
       this.ipTimedatepkReporting = ipTimedatepkReporting;
       this.transactionid = transactionid;
       this.processingflag1 = processingflag1;
       this.processingflag2 = processingflag2;
       this.processingflag3 = processingflag3;
       this.processingflag4 = processingflag4;
       this.processingflag5 = processingflag5;
       this.processingflag6 = processingflag6;
       this.processingflag7 = processingflag7;
       this.processingflag8 = processingflag8;
       this.processingflag9 = processingflag9;
       this.processingflag10 = processingflag10;
       this.recordcreationtime = recordcreationtime;
    }
   
     @Id 

    
    @Column(name="PK", unique=true, nullable=false, precision=12, scale=0)
    public long getPk() {
        return this.pk;
    }
    
    public void setPk(long pk) {
        this.pk = pk;
    }

    
    @Column(name="CARRIER_CONTRDEFPK", nullable=false, precision=12, scale=0)
    public long getCarrierContrdefpk() {
        return this.carrierContrdefpk;
    }
    
    public void setCarrierContrdefpk(long carrierContrdefpk) {
        this.carrierContrdefpk = carrierContrdefpk;
    }

    
    @Column(name="TRANSPORTORDERNUMBER", nullable=false, length=40)
    public String getTransportordernumber() {
        return this.transportordernumber;
    }
    
    public void setTransportordernumber(String transportordernumber) {
        this.transportordernumber = transportordernumber;
    }

    
    @Column(name="RECIPIENTIDENTIFICATION", nullable=false, length=40)
    public String getRecipientidentification() {
        return this.recipientidentification;
    }
    
    public void setRecipientidentification(String recipientidentification) {
        this.recipientidentification = recipientidentification;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="DELIVERYTIME", nullable=false, length=26)
    public Date getDeliverytime() {
        return this.deliverytime;
    }
    
    public void setDeliverytime(Date deliverytime) {
        this.deliverytime = deliverytime;
    }

    
    @Column(name="TIMEDATEPK", precision=8, scale=0)
    public Integer getTimedatepk() {
        return this.timedatepk;
    }
    
    public void setTimedatepk(Integer timedatepk) {
        this.timedatepk = timedatepk;
    }

    
    @Column(name="IP_TIMEDATEPK_REPORTING", precision=8, scale=0)
    public Integer getIpTimedatepkReporting() {
        return this.ipTimedatepkReporting;
    }
    
    public void setIpTimedatepkReporting(Integer ipTimedatepkReporting) {
        this.ipTimedatepkReporting = ipTimedatepkReporting;
    }

    
    @Column(name="TRANSACTIONID", length=50)
    public String getTransactionid() {
        return this.transactionid;
    }
    
    public void setTransactionid(String transactionid) {
        this.transactionid = transactionid;
    }

    
    @Column(name="PROCESSINGFLAG1", length=1)
    public String getProcessingflag1() {
        return this.processingflag1;
    }
    
    public void setProcessingflag1(String processingflag1) {
        this.processingflag1 = processingflag1;
    }

    
    @Column(name="PROCESSINGFLAG2", length=1)
    public String getProcessingflag2() {
        return this.processingflag2;
    }
    
    public void setProcessingflag2(String processingflag2) {
        this.processingflag2 = processingflag2;
    }

    
    @Column(name="PROCESSINGFLAG3", length=1)
    public String getProcessingflag3() {
        return this.processingflag3;
    }
    
    public void setProcessingflag3(String processingflag3) {
        this.processingflag3 = processingflag3;
    }

    
    @Column(name="PROCESSINGFLAG4", length=1)
    public String getProcessingflag4() {
        return this.processingflag4;
    }
    
    public void setProcessingflag4(String processingflag4) {
        this.processingflag4 = processingflag4;
    }

    
    @Column(name="PROCESSINGFLAG5", length=1)
    public String getProcessingflag5() {
        return this.processingflag5;
    }
    
    public void setProcessingflag5(String processingflag5) {
        this.processingflag5 = processingflag5;
    }

    
    @Column(name="PROCESSINGFLAG6", length=1)
    public String getProcessingflag6() {
        return this.processingflag6;
    }
    
    public void setProcessingflag6(String processingflag6) {
        this.processingflag6 = processingflag6;
    }

    
    @Column(name="PROCESSINGFLAG7", length=1)
    public String getProcessingflag7() {
        return this.processingflag7;
    }
    
    public void setProcessingflag7(String processingflag7) {
        this.processingflag7 = processingflag7;
    }

    
    @Column(name="PROCESSINGFLAG8", length=1)
    public String getProcessingflag8() {
        return this.processingflag8;
    }
    
    public void setProcessingflag8(String processingflag8) {
        this.processingflag8 = processingflag8;
    }

    
    @Column(name="PROCESSINGFLAG9", length=1)
    public String getProcessingflag9() {
        return this.processingflag9;
    }
    
    public void setProcessingflag9(String processingflag9) {
        this.processingflag9 = processingflag9;
    }

    
    @Column(name="PROCESSINGFLAG10", length=1)
    public String getProcessingflag10() {
        return this.processingflag10;
    }
    
    public void setProcessingflag10(String processingflag10) {
        this.processingflag10 = processingflag10;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="RECORDCREATIONTIME", nullable=false, length=26)
    public Date getRecordcreationtime() {
        return this.recordcreationtime;
    }
    
    public void setRecordcreationtime(Date recordcreationtime) {
        this.recordcreationtime = recordcreationtime;
    }




}


