-- 18.3.2013
ALTER TABLE GRELIN ADD DELANNLIN_SPLIT VARCHAR(1) DEFAULT ' ' AFTER CONFIRMEDDELIVERYDATE;
ALTER TABLE INVMOVMNT ADD IP_INVMOVMNTKEY DECIMAL(8,0) DEFAULT '0.0' AFTER IP_TIMEDATEPK_REPORTING;
ALTER TABLE STOCKRCLOP ADD IP_STOCKKEY DECIMAL(5, 0) DEFAULT '0.0' AFTER IP_CONTRACTOR_REPORTCOLUMN;
ALTER TABLE ITEMMASTER ADD RESPONSIBLE CHAR(10) NOT NULL DEFAULT '          ' AFTER SORTDESCFR;
ALTER TABLE ITEMMASTER ADD PLANER CHAR(10) NOT NULL DEFAULT '          ' AFTER RESPONSIBLE;
ALTER TABLE ITEMMASTER ADD RATING CHAR(3) NOT NULL DEFAULT '   ' AFTER PLANER;
ALTER TABLE ITEMMASTER ADD BEWIRTSCHAFTUNG_DISPLAY CHAR(1) NOT NULL DEFAULT ' ' AFTER RATING;